### ISSUE TITLE
[feature request]: Add ability to set license to how-tos

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/community-platform#1000]
**Is your feature request related to a problem? Please describe.**
It's not entirely clear what terms the writer of a how-to is allowing for the content to be used for (exclusions on commercial use etc.). It would be nice to have a feature on the how-tos to add a license for the tutorial they are writing. For example CC-BY or CC-BY-SA or MIT or another from a dropdown field like on GitHub. 

**Describe the solution you'd like**
Two additional dropdowns when editing a how-to one for the license of the text of the how-to and one for any additional files which were added. This is because the text may want to be set to a different license to any blueprints, 2D design files or 3D models.

Any pre-existing how-tos should probably say "no-license yet chosen" or the like and if possible to prompt-them when the feature is set to live.

**Describe alternatives you've considered**
Could also have a "wizard" that helps how-to writers to pick the license that is best for what they want people to be doing with the content of the tutorial and additional files. But for a minimum viable product dropdowns would. Examples of a wizard question would be 

"Do you wish to be allowed other people to use the content for commercial use?"

It can then narrow down the options of the licenses that the user can choose at the end.

**Additional context**
GitHub has a similar feature but for code when creating a repository. Would probably be best to choose the common variations of the creative commons licenses as a start & some which are more relevant to hardware-based projects.

**Comment by BenGamma** [comment]
@darigovresearch thanks for pointing out, and congrats for the issue number #1000 :grin: 

It's a good point and I understand it may not be clear enough when you create a how-to. As far as I know, a how-to is under the same license as all the precious plastic content. I'm not sure what the license is now, @davehakkens may have a hint on this one
?
@davehakkens any thoughts on this ?

**Comment by davehakkens** [comment]
yeh good point. However it is something we need to dive a bit deeper into to see whats the best approuch for us
I'll put it on the list for our next big meeting

**Comment by davehakkens** [comment]
Not on the roadmap for now. Closing the issue

**Comment by Thatoo** [comment]
It would be a nice feature to be able to choose easily the licence for everything single publication.

Speaking about licence, why did you choose MIT licence (instead of AGPL-3.0 license for example)?
