### ISSUE TITLE
[feature request] Render SVGs inline

### ISSUE THREAD

**Issue by tudi2d** [ONEARMY/community-platform#1003]
**Is your feature request related to a problem? Please describe.**
There are different solutions for using Icons. Mostly custom Icons are used but additionally `react-icons` is used. All SVG Icons are loaded into `Image` components as src. This is not optimal. SVG could be easily directly rendered into the DOM.

**Describe the solution you'd like**
It would be nice to restart an attempt to unify the way Icons are imported (see src/components/Icons) and render them inline using [SVGR](https://github.com/gregberge/svgr).

**Describe alternatives you've considered**
Alternative would be staying by this implementation.
**Additional:**
Rendering in images can be useful for preventing script injections - this is should not possible in the community platform as users don´t upload icons as svgs at all.
- https://github.com/Shopify/polaris-react/blob/master/src/components/Icon/Icon.tsx

**Comment by kfern** [comment]
Hi @tudi2d 

We have more than 100 icons on the map page and this feature will add performance issues; we will have a larger html page (all images will be embedded) and this images cannot be cached by a browser.

Also, as we can see at https://stackoverflow.com/a/23779501/3623553 
"when loading multiple times the same image, if it is declared inline, the browser performs a request for each image (I suppose it base64-decodes it one time per image), whereas in the other scenario, the image is requested once per document"

What do you think? Do we need to do a real performance test?

**Comment by thisislawatts** [comment]
@kfern some additional context [here](https://github.com/ONEARMY/community-platform/issues/1257), as we are already experiencing performance issues on our Map page.
