### ISSUE TITLE
[bug] no pin cluster when multiple pin type on the same location

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#1006]
**Describe the bug**
The map pin clusters is not working correctly when at the same location, there is multiple pin type.
The pins of different type are over each others. The last one added hides the previous one which affects a lot the visibility of the previously added.

**To Reproduce**

1. Go to the map and check for example the area of mexico city or florida. 

**Expected behavior**
A cluster should be created independently of the pin type, and not only for pins of the same type.

**Screenshots**
![Screenshot from 2020-08-05 17-18-38](https://user-images.githubusercontent.com/4993215/89437711-d2563d00-d73f-11ea-8e36-b8b27fda2cde.png)
![Screenshot from 2020-08-05 17-18-23](https://user-images.githubusercontent.com/4993215/89437721-d5512d80-d73f-11ea-8cc6-91df057113f2.png)

**Comment by tudi2d** [comment]
Hey @BenGamma - I would like to work on this 🙂

**Comment by BenGamma** [comment]
Hello @tudi2d ! Yes no problem go ahead

**Comment by tudi2d** [comment]
@BenGamma Quick solution - all pins are clustered together. I only tested this with the data available for development.

When looking at the live version my guess is that there will be way more clustering, which will look cleaner, but also maybe less impressive and interesting. If the clustering is to harsh it can be adjusted afterwards using the `maxClusterRadius`. 

![wriaRXe4mx](https://user-images.githubusercontent.com/8904624/90072038-fba23a80-dcf6-11ea-91e6-4efb2731b96c.gif)
