### ISSUE TITLE
[bug] community-platform down/ not reachable

### ISSUE THREAD

**Issue by tudi2d** [ONEARMY/community-platform#1011]
**Describe the bug**
The community platform is not reachable, because of a broken firebase config/ broken deployment. Seems like the last deployment caused this.

**To Reproduce**

1. Visit the community platform

**Expected behavior**

Community platform should work.

**Screenshots**
![Screenshot_20200824-114533~2.png](https://user-images.githubusercontent.com/8904624/91030513-92c49780-e5ff-11ea-8084-92d5cc5edf6c.png)

**Comment by tudi2d** [comment]
@chrismclarke @BenGamma Kind of urgent, as no one can use the community platform right now. I think this should be easy to fix. People in the Discord were mentioning, that the academy is not working.

**Comment by davehakkens** [comment]
thanks for letting us know.
Not sure where this goes wrong. limited webskills here and dont know where @BenGamma is.atm.
You have suggestions @tudi2d?

**Comment by tudi2d** [comment]
I don´t know what exactly the issue is with firebase. I created a pull request to revert the last PR on production called "Fix deploys". If that does not work i would just revert production again to #996, which was the last, bigger release. 

My suggestion is to just revert and wait for @BenGamma to fix the deployment as it seems it was his intention to do so anyways. This way an older version of the website will be running, but at least people can use it in the mean time 👍 :)

**Comment by tudi2d** [comment]
This did not really fix it for me... I will create a PR for reverting to the last production release..

**Comment by davehakkens** [comment]
yeh same here. still offline.
We have a dev site. But for some reason that does still work
https://dev.onearmy.world/how-to

**Comment by tudi2d** [comment]
Yeah. Seems like the dev site runs the latest master branch. The live version is running the latest production branch. There are also separate deployment scripts for both versions.

**Comment by catx23** [comment]
it's off since Friday or so, more or less the time when the kamp site was deployed or so. the forum was also affected which points rather to some messed up DNS settings as well. The dev site how is working because it's using another dns but also the test database.
good luck

**Comment by catx23** [comment]
btw. the there are plenty of build errors when building this outside of the CI, took me almost a day to fix, mostly typescript errors but also the main build command "npm build" won't work since somebody place env settings in there CI=false (which was fixed recently by ben again). good luck.

**Comment by tudi2d** [comment]
Mhh. Tried all the builds locally before creating the PR´s and they were working for me 😕

Nevertheless I would suggest jumping back to v1.2.0 now, as it was the last production build which did not fail in Travis CI and then continue finding the error.

**Comment by catx23** [comment]
@tudi2d ,
I don't know the CI env.... here however - on clean setups (lnx and windows, Node 10.20.1 ) ```npm build``` fails because of 

1. CI=false in the npm script ( I removed it)
2. several typing errors regarding untyped HTML attributes - I fixed the typings but hardcoded/directly. Possibly there is a mismatch or non updated dep.
3. webpack error (had to explicit install the right version) - still ugly

I can imagine this will happen in the CI as well. Evtl. you can bypass the CI for now and just fix those errors. Evtl. your provider changed environments. However, one thing is for sure that the devs didn't run build tests locally since quite a while - I also couldn't find when they actually broke it ... just needed to move on :-)
