### ISSUE TITLE
Change App Manifest short name

### ISSUE THREAD

**Issue by teja8792** [ONEARMY/community-platform#1038]
Need to change the app name in manifest file

[Manifest](https://github.com/ONEARMY/community-platform/blob/1964eef9b4dd6a767792ab11e9ab8f0eac723acb/public/manifest.json#L2)

**Comment by davehakkens** [comment]
why is this an issue?

**Comment by BenGamma** [comment]
No biggy but it can be used if you put the website in your fav or create a shortcut on desktop for example.
I updated the name, thanks for pointing out @teja8792
