### ISSUE TITLE
Arrow is pointing in the wrong direction :)

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1042]
**Describe the bug**
The arrow next to the back button on the how-to is pointing in the wrong direction. 

**To Reproduce**
https://community.preciousplastic.com/how-to/trouble-shooting-injection-moulding

**Screenshots**
<img width="410" alt="Screenshot 2020-09-16 at 17 27 10" src="https://user-images.githubusercontent.com/17761877/93358626-03975200-f842-11ea-8d98-444e420dbc21.png">

**Comment by tudi2d** [comment]
I would like to fix it, as I likely have caused this one 😄 Seems to be an issue with supported browser features - what kind of browser & environment are you using?

**Comment by mattia-io** [comment]
Thanks!
I am on the latest chrome.

**Comment by mattia-io** [comment]
Also as you're at it, I am not sure if it is related, but on mobile there are also some issues. 
![screenshot_20200918-085841](https://user-images.githubusercontent.com/17761877/93566295-1a968b00-f98d-11ea-9d51-c783f8796808.jpg)

**Comment by BenGamma** [comment]
@tudi2d yes feel free to work on that 👍 
Were you able to reproduce the bug ?

**Comment by tudi2d** [comment]
Yes - will work on this tomorrow 👍
