### ISSUE TITLE
[feature request] Code minification

### ISSUE THREAD

**Issue by JanetLaysEggs** [ONEARMY/community-platform#1044]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Currently it seems that the pages at https://community.preciousplastic.com/ use no code minification in any of the JS files. I recommend webpack or something similar to help with this and reduce server+ bandwidth load. Also what is being used for the back end for users etc?

**Describe alternatives you've considered**
The alternative is not using minifcation?

**Additional context**

**Comment by BenGamma** [comment]
Can you point out which file you refer to  ?

The JS files in current build are minified see [here](https://community.preciousplastic.com/static/js/2.34918441.chunk.js) and [here](https://community.preciousplastic.com/static/js/main.4430561e.chunk.js)

**Comment by JanetLaysEggs** [comment]
Hiya @BenGamma, I mean files like ['scrollSpy.js'](https://onearmy.github.io/academy/js/scrollSpy.js) and ''[custom.js](https://onearmy.github.io/academy/js/custom.js)'.
Also some files that have been minified could be reduced even further by the use of webpack etc where they could all be wrapped into one file - so even function/class names that span across multiple files can be shortened. This would also mean the main page is no longer reliant on assets like '[button.js](https://buttons.github.io/buttons.js)' which reduces the page's reliability should that repo change and that link fail (it links to a github repo instead of a file on the https://preciousplastic.com/ server)? You should be able to use npm to do all this? Also comments still exist in some of the files.

I'd like to help in this effort if I can?

Thank  you for getting back to me.


-J

**Comment by JanetLaysEggs** [comment]
Oh and css files too!

**Comment by BenGamma** [comment]
Ah you are refering to the academy. The repo for the academy is https://github.com/ONEARMY/academy

We are using a tool called Docusaurus to build the academy section and we embed it in /academy. I never dive into the minified optimizations for it. I would say have a look if you like !

**Comment by chrismclarke** [comment]
Hi @JanetLaysEggs - thanks for pointing this out. Yes, confusingly enough all the content for the academy sits in another git repo (and we just display it in an iframe in the community platform). I've copied your issue over to https://github.com/ONEARMY/academy/issues/106 - if you did have a chance to look into ways we could improve on this then that would be great (although as a word of warning the repository isn't very actively maintained, so it could be some time for changes to be merged - but most welcome nonetheless)
