### ISSUE TITLE
[bug] Can't add profile details

### ISSUE THREAD

**Issue by JanetLaysEggs** [ONEARMY/community-platform#1051]
**Describe the bug**
'Save profile' button disabled even though all the required fields are filled and appear valid.

**To Reproduce**
Steps to reproduce the behaviour:

1. Make a fresh user using disposable email sharklasers.com.
2. Verify the user.
3. Go to: (RHS)Icon->Profile
4. Fill with the following dummy data:

- Select: 'I am a memeber'
- Your username
- Location: UK
- Description: Test1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhgggggggggggggggggggTest1234123456yhggggggggggggggggggg
- Cover image: https://ufile.io/qvl5x4xo
- 'Contacts & Links': test@example.com

**Expected behaviour**
To be able to apply my changes.

**Screenshots**
N/a

**Additional context**

-J

**Comment by markjbuss** [comment]
Hey, I'm new here, trying to find some issues to help out with. I tried reproducing this locally and I can successfully save my profile for a new user with the steps you mentioned, only thing I noticed was that the location isn't saved, everything else was good. What are you seeing when you do this? Is the button never enabled?

**Comment by JanetLaysEggs** [comment]
Hey @markjbuss. Odd it seems to work for me now too. It must only happen occasionally.
