### ISSUE TITLE
Social media icon not showing

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1062]
The social media icon on the profile is not showing at my end. Chrome Version 86.0.4240 

https://community.preciousplastic.com/u/precious-plastic-los-angeles

![image](https://user-images.githubusercontent.com/17761877/97011532-12f77280-1547-11eb-90af-89302d045989.png)

💪

**Comment by alromh87** [comment]
@mattia-io Could you show me the expected output, since none of my browsers show it :sweat_smile:

**Comment by davehakkens** [comment]
also here (Firefox) it doesnt show. Css says: undefined
<img width="295" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/97113478-f98f2b80-16ea-11eb-9ba4-164c52430698.png">

**Comment by mattia-io** [comment]
Exactly, here it is Alejandro 💪

[icon social media.svg.zip](https://github.com/ONEARMY/community-platform/files/5435783/icon.social.media.svg.zip)
