### ISSUE TITLE
Capitalization across Community Platform 

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1066]
**Describe the bug**
Humans are forgetful beings :) I could win a Guinness for that.
People uploading how-tos and content on the Community Platform could (and will) forget to capitalize their text. Which in turn looks amateur/less professional. Would be really good to run a script to capitalize the first letter of the following:

1. How-to 
1.1 How-to cover title and description
1.2 How-to steps title and description

2. Profiles
2.1 Name and description

3. Events? (can't see as there are no events :( )

**To Reproduce**
[Here](https://community.preciousplastic.com/how-to/bending-with-the-sheetpress) you can reproduce the error (all lowercase)

![Capitalize](https://user-images.githubusercontent.com/17761877/97587639-e5557200-19fb-11eb-8460-aae186f8c55c.jpg)

Big up you devs out there!

**Comment by chrismclarke** [comment]
So I see this as a 2-step issue for anyone who is interested in either/both:

1. Add a form validator to check if a field has been capitalised correctly, which we can use on things like how-to title fields and anything else in the future we want to enforce this on. This would be a good first issue, there are already validator examples in `src/utils` (e.g. email test) and form dev docs here: https://final-form.org/docs/react-final-form/examples/field-level-validation

2. Add a one-time migration script to update existing content. This could get a little more messy depending on how widely we want to check, but if even only a rough template were put in place to make minimal changes we could always expand on in the future.

**Comment by davehakkens** [comment]
cant we do this with css?
https://css-tricks.com/almanac/selectors/f/first-letter/
```

p::first-letter {
text-transform:uppercase;
}
```

**Comment by prolland006** [comment]
i found the soluce : Create a FormattedInputField that capitalized the firstletter. I pull the request it soon...

**Comment by prolland006** [comment]
for the script i don"t know how to do !
