### ISSUE TITLE
[new feature] useful button

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#1072]
### Component infos

A "useful" button in the description of a how-to page.

### Description
This button will allow users to give an appreciation on the content available in the how-to.

- The button is always visible to all users.
- Only logged in users can click it and increment it's value
- If user not logged in the button is disabled state and you get a message on hover (see mockup section of this issue)
- Every user can only give one “useful” per page 
- Clicking the button again removes the “useful”
- The amount of useful count is displayed in the button

### Page related
Will be used in :

- How-to page

### Mockup
<img width="602" alt="Capture d’écran 2020-11-05 à 18 02 52" src="https://user-images.githubusercontent.com/4993215/98272247-2b2cb000-1f91-11eb-8620-08d8d420b795.png">

<img width="578" alt="Capture d’écran 2020-11-05 à 18 09 43" src="https://user-images.githubusercontent.com/4993215/98273048-1dc3f580-1f92-11eb-97ab-89097b601f8b.png">

<img width="601" alt="Capture d’écran 2020-11-05 à 18 11 13" src="https://user-images.githubusercontent.com/4993215/98273242-54017500-1f92-11eb-9514-7597bd1b2473.png">

### Build suggestion
- [ ] Display the button on desktop and mobile. Color code of button background is `f5ede2`. Use [react-icons](https://react-icons.github.io) for the star icon.
Note : it will probably be in conflict with the admin moderation buttons. Align the useful button as on the mockup and align admin moderation buttons on the right on desktop. On mobile align the admin moderation buttons on the next line.
- [ ] link with database : add a `usefulCount` field on how-to model incremented or decremented on click. We should also create an array with the list of how-to a user as marked as "useful" in `userStats` collection.
- [ ] button display logic : clickable only for logged in users & display sign in message for not logged in users. Also display `usefulCount` in button if present.

If more questions feel free to ask them in this issue thread 🖖

**Comment by tudi2d** [comment]
I like the feature and the wording! I would like to implement this. Thanks for breaking down the task into smaller steps and suggestions - really helpful to directly have an overview of what has to be done. This would be my first time touching a Firebase backend so I might have some questions, but would like to give it a try! :)

**Comment by BenGamma** [comment]
Yes @tudi2d feel free to work on it 💯

**Comment by chrismclarke** [comment]
Implemented
