### ISSUE TITLE
Favicon is outdated

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1075]
Hey devs, a minor update concerning the favicon which is currently outdated. Below you can find the latest version that aligns with Precious Plastic visual identity. 

![favicon](https://user-images.githubusercontent.com/17761877/100028098-097f5580-2de6-11eb-86d3-e5a8e0a8aa19.png)

Merci :)

**Comment by tudi2d** [comment]
Saw this issue & created a quick pull request. Would look like the following @mattia-io  :)

Chrome (Light)
 ![icon_chrome](https://user-images.githubusercontent.com/8904624/102868494-8976fa80-443a-11eb-8ec5-24cd6ea5179f.png)

Firefox (Dark)
![icon_firefox](https://user-images.githubusercontent.com/8904624/102868497-8a0f9100-443a-11eb-93f6-b40f41db1f9b.png)
