### ISSUE TITLE
Research Module - Listing

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1080]
### Mockup

Requires #1079

![image](https://user-images.githubusercontent.com/10515065/101934855-07ade400-3b93-11eb-8366-d5cb612f8e69.png)

### Example(s)

If you have any examples of existing similar components, add the link here. It can be a link to a code snippet and/or to a page of a projet/website where we can interact with the similar component.

**Comment by danitrod** [comment]
Can I start working on it? I see the store and page are already setup

**Comment by davehakkens** [comment]
from my end yes! 
But not sure if you need some input from @chrismclarke?

**Comment by danitrod** [comment]
i think the implementation seems pretty straight forward - not sure if there's any prior work done before I should start though

**Comment by davehakkens** [comment]
the orignal plan was for @alromh87 to take it one. But don't think that ever took off.

**Comment by chrismclarke** [comment]
Thanks for moving forward on this, yeah from me happy to see any additions
