### ISSUE TITLE
[feature request] Fixed HowTo URL

### ISSUE THREAD

**Issue by tudi2d** [ONEARMY/community-platform#1089]
**Is your feature request related to a problem? Please describe.**

Following issue discussed in the Feedback channel on Discord: 

![image](https://user-images.githubusercontent.com/8904624/105518131-3235a580-5cd8-11eb-9b84-36b4540d5b18.png)

The title of the HowTo changed and this caused the URL to be invalid. The URL of an HowTo should not change by editing the title. Users won´t expect this and it will lead to missed leads for the creators of the HowTo´s when sharing the link on social media or whatever. It will also cause in frustration when opening the plattform

**Describe the solution you'd like**

A fixed URL saved when the HowTo is created. It can still depend on the be the first chosen title, but should not change, when the title changes.

Additionally/For further improvements the user could be able to edit the URL in a separate input field later on. It could be added to the "Intro" in the "HowToEdit".

**Describe alternatives you've considered**

An alternative would be to change the links to use the unique ID or an generated, unique hash for newly created HowTo´s. This would work without the title and would lead to shorter URLs. Old HowTo´s should keep there current URLs. Additionally this will allow people to create different HowTo´s with the same title.

**Comment by chrismclarke** [comment]
I like the idea of first making it more explicit to creators that their title will be used to create a slug (maybe we could show this somewhere?). 

I still think that there might be cases where people will want both the title and slug to change however, and would be really nice if any old links didn't break when doing so (like how Wordpress manages). A couple options could be:

1. We update the 404 page to show a list of howtos that might match their request (assuming we implement #1088)
2. We keep a list of redirects that we can lookup when a howto changes (e.g. as well as a `slug` field we could have a `previousSlugs` array and a fallback lookup to check for any howtos with the given slug if not initially found.

Happy if anyone wants to take on any of these possible solutions (quickfix or longer term)

**Comment by tudi2d** [comment]
We should also keep in mind that HowTos potentially have the same name, which would cause in conflicting URLs.

**Comment by chrismclarke** [comment]
I'm pretty sure we check the slugs when a howto is created/edited (the `validateTitle` function nested pretty deep inside the howto form component) so I think that should be ok, but worth double checking for sure.

**Comment by iSCJT** [comment]
@davehakkens can you clarify the additional functionality on this issue over and above #2183 that you'd like please:

1. link stays the same when title is changed
2. allow link to be changed independently of title
3. switch to a guid based url

**Comment by tudi2d** [comment]
The issue I raised back then seems resolved - would make sense for me to close this one. Thanks @iSCJT for your interest & hope there is a newer issue you can tackle! :)

**Comment by iSCJT** [comment]
Thanks @davehakkens @tudi2d, I've not been around for a few days so just catching up.  Will get #2183 done today or tomorrow using the same logic as #2064.
