### ISSUE TITLE
Add message to useful button for non logged in

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1096]
### Description

You can only use the  brand new useful button (#1074 )when you are logged in.  But if you are not logged in and click it, nothing happends. It looks broken. There is a message on hover (image below) But it would be good if it comes on click, and styled. 

### Page related
-  How to's

### Mockup Currently

<img width="307" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/106618416-56f70c00-6567-11eb-9933-35efaee25e8b.png">

------------

### Mockup How it should be (explained in this issue) #1072
<img width="293" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/106621506-8a876580-656a-11eb-9fee-16d2ff6cbca2.png">

### Alternativly

If it adds a lot of code or uneccesery complexcity we could also direct it straight to the login page. This option is less prefered though.

**Comment by chrismclarke** [comment]
This would be a good first issue if anyone wants to take it on. Up till now we haven't used tooltips in content (quick fix is adding a 'title' attribute to elements to use native browser tooltip as seen in the diagram), so we would likely want to add another library to do this. 

A quick search shows a few options, with react-popper looking like a favourite:
https://www.npmtrends.com/react-popper-vs-react-tooltip-vs-rc-tooltip-vs-react-overlays

So for this issue I would recommend adding the [react-popper](https://popper.js.org/react-popper/) library and using to style a message for the useful button on hover.

**Comment by mattia-io** [comment]
It could also work like the "Create how-to" in the home page where it redirects to the login page.

**Comment by danitrod** [comment]
Hi, I'm looking to start contributing, if you guys agree I could take this one.

**Comment by davehakkens** [comment]
Not sure if @tudi2d is already on it, otherwise go for it. Thanks! :)

**Comment by tudi2d** [comment]
@danitrod Nice! Go for it!

**Comment by danitrod** [comment]
Awesome, will start working then :)
