### ISSUE TITLE
[enhancment] Client-side update usefull state

### ISSUE THREAD

**Issue by tudi2d** [ONEARMY/community-platform#1099]
**Is your feature request related to a problem?**

When a user clicks the Useful-button the client waits for the successful server side update without loading indication. As this can take a while due to firebase it feels as the "Click" did not cause any action.

**Describe the solution you'd like**
Change it to handle the request not asynchronous, update the counter for the client & just handle potential update errors. This way the UX would feel a bit more direct for the user, no matter how bad the internet connection is, avoiding users to click the button multiple times.

**Additional context**

@tudi2d - definitely possible to manually override the number temporarily whilst waiting on the server updates. I was just too lazy to implement the logic (handle both cases where the number might go up or down, adding local state to the component to update the value (as it is passed from the store a prop the component can't directly edit so will need to first copy to local state).

_Originally posted by @chrismclarke in https://github.com/ONEARMY/community-platform/issues/1094#issuecomment-772653845_

**Comment by davehakkens** [comment]
I think this is an important one!
Small detail but would make the expereince feel much smoother.

**Comment by chrismclarke** [comment]
Thanks for capturing this in an issue. As mentioned in the linked PR comment, a little bit of extra work to map the injected props from the howto store to a local state variable and update on click (either +/- 1 depending on whether they have already voted or not), but should be pretty quick to do and agreed make for a much more natural feel in case anyone is interested taking it on.

**Comment by davehakkens** [comment]
anyone up for taking this issue? Then we can release the useful button into the world  💪

**Comment by tudi2d** [comment]
Sure - will create a PR later :shipit:
