### ISSUE TITLE
[feature request] - link howto search input with urls

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1100]
**Is your feature request related to a problem? Please describe.**
As discussed in #1088, would be great to be able to share a link that has the search field already filled (e.g. all howtos written by a specific creator). 

**Describe the solution you'd like**
Use [react router query params](https://reactrouter.com/web/example/query-parameters), so that URLs are stored like `https://community.preciousplastic.com/how-to?search=plastmakers`, and on open will show the howto page with the search populated with `plastmakers`. 

**Describe alternatives you've considered**
We could consider a more advanced search (e.g. `/how-to?creator=plastmakers`), but for now the simple search would still be a really good start

**Additional context**
As URLs will be encoded will be good to consider how best to handle (e.g. /how-to?search=precious%20plastic should decode before populating search). Similarly, we will want the URL bar to update when a user searches so that they can copy/paste their search link.

I think @danitrod said he would be happy to take this one on also, although if you don't have the time feel free to let us know and I can add a help-wanted label.

**Comment by danitrod** [comment]
Thanks @chrismclarke, I'll work on it during the week.
