### ISSUE TITLE
Change Icon Useful

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1103]
As seen on the Slack channel, it would be cool to change the Icon for the useful.
 From star to.. special star :)
 Attached the .svg for default (black) and active (colored)
 
![new-icon](https://user-images.githubusercontent.com/13672737/108004848-f1872e80-6fee-11eb-9b80-6e544202d616.jpg)

 Download .svg 👇
[useful-Icon-star.zip](https://github.com/ONEARMY/community-platform/files/5984867/useful-Icon-star.zip)

 
 *Sorry for the last minute change on this one.

**Comment by danitrod** [comment]
Cool! I'll make the change
