### ISSUE TITLE
Research Module - create/edit

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1111]
### Description

Add forms for creating and editing a research.

### Page related

Will be used in : #1110 and #1079 

### Mockup

[Add here the mockup of the component]
<img width="1248" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/110305973-33efca00-7ff5-11eb-99a4-14ae5d2a62a7.png">

### Additional information

On this page you can start a new research. The main thing you need is to create the first post. For this you need a title, description and select tags. (Tags are not displayed on the “module single” page yet in this version but already gathered in the backend.) Research can be saved as draft or published directly.

**First post**
Title (max 40 characters)
Description (max 400 characters)
Tags (max 4)

**Following posts**
Title (max 40 characters)
Description (max 700 characters)
Image upload (max 5)
Video embed (1 youtube link)

### Similair pages
- How to  (create and edit page)

**Comment by danitrod** [comment]
Working on this! Question: do we have the guidelines page to create a research already?

**Comment by davehakkens** [comment]
cool!
Not yet. But you can link it here https://community.preciousplastic.com/academy/guides/research
