### ISSUE TITLE
URGENT: Academy does not create unique URLs

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1117]
Hello,

I just noticed that the Academy does not create unique URLs any longer. 
This is kind of a big deal because tons of backlinks will be deadlink now :(  Plus the whole academy is kind of unshareable now. 

No matter which chapter I am in the URL is always 👉 https://community.preciousplastic.com/academy
![image](https://user-images.githubusercontent.com/17761877/112029244-efa21500-8b30-11eb-9e74-e5815242e5f5.png)

Is anyone able to help on this?
@martisj 🙏🙏🙏🙏

**Comment by davehakkens** [comment]
I just noticed it was probably me that broke it. :|
Could you give a try to see if it fixed now?
