### ISSUE TITLE
Change Profile tips

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1121]
### Description

We need to update our profile tips in the profile settings.
⭐️  Part of our new verification program #1123 

### Page related

Will be used in : https://community.preciousplastic.com/settings

### Mockup (original text)

<img width="317" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/113200148-e2d39e80-925f-11eb-96b5-06ef698bc6e0.png">

### New text:

# Profile Tips
1. Have a look at our [Profile Guidelines](https://community.preciousplastic.com/academy/guides/platform).
2. Choose your focus.
3. If you want to get a pin on the map check our [Community Program](https://community.preciousplastic.com/academy/guides/stars) 
4. Add a nice description, pics and details.
5. If something doesn’t work, [contact us.](https://discord.com/invite/SSBrzeR)

**Comment by tudi2d** [comment]
Will work on this one! :)

**Comment by davehakkens** [comment]
hi @tudi2d, planning to work on a release this morning and want to add this. So I took it over this one. 
Also left a comment in the pull request, perhaps you can help out? 
https://github.com/ONEARMY/community-platform/pull/1131

**Comment by tudi2d** [comment]
Hi @davehakkens - sorry, been of GitHub for a few weeks - will take a look at the PR later :)
