### ISSUE TITLE
Add data protection to profile updates

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1125]
**Is your feature request related to a problem? Please describe.**
A couple times in the past we've seen weird caching issues make it possible for users to accidentally create a new profile which would then overwrite their existing profile. Various attempts to recreate/fix have proven inconsistent, so we need a better system to prevent this happening altogether

**Describe the solution you'd like**
Some sort of `_revision` id that will be updated when a profile is updated, and can be used to prevent update if not matching (e.g. if I try to upload a blank profile but there is already a profile with a revision id present then it should prevent the write) - this could possibly be handled at the db rules level, or as a function that reverts unconfirmed writes

**Describe alternatives you've considered**
Possibly make all writes to users pass through an api endpoint instead of using database methods

**Comment by iSCJT** [comment]
Although we've not addressed this issue specifically, closing as we've done work on duplicate user profile creation recently and will address as part of a wider look at db integrity for updates.
