### ISSUE TITLE
Comments! 💬 (back end)

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1128]
### Description

We are introducing comments to the platform. More information on this issue #1127.
All the frontend work would be done in #1127, this issue is to connect it together in the backend.

### Task
Comments are used by how-to’s. They are chronologically sorted, latest one below. Above 10 comments there is a “load more comments” button displayed. The comment section is divided in 2 elements

### 1. New comment input field
- This element is always displayed when logged in
- If not logged in it shows a text “login to comment”
- The input field is plain text (Max 200 characters)
- The icon is based on your profile type
<img width="981" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/114777812-01f82300-9d6c-11eb-8da9-aa599506964a.png">

### 2. Comment field
- Comment fields are always displayed (for logged in & out users)
- Plain text from the new comment field (Max 200 characters)
- Username
- Location flag of the user (as used in [how-to overview](https://community.preciousplastic.com/how-to)
- Date of the comment
<img width="581" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/114777844-0d4b4e80-9d6c-11eb-8340-32e407625fe9.png">

### Will be used in :
- community.preciousplastic.com/howto/page

### Mockup overview

<img width="669" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/114778130-5e5b4280-9d6c-11eb-9405-8771648782f1.png">

**Comment by chrismclarke** [comment]
@danitrod will give a first go at this
