### ISSUE TITLE
[bug] How-to counter in profile looks broken?

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1154]
**Describe the bug**
The how-to counter in profiles doesn't work?

**To Reproduce**
See precious-plastic [how-tos](https://community.preciousplastic.com/how-to?search=precious-plastic) listed on the hompage and see the counter in [the profile](https://community.preciousplastic.com/u/precious-plastic)

**Expected behavior**
It should show all **Approved** how-tos

**Screenshots**
![broken-how-to-counter](https://user-images.githubusercontent.com/13672737/118656659-07251380-b7eb-11eb-9ac8-4f113b71a6df.jpg)

**Comment by chrismclarke** [comment]
That's really weird, not sure if it's an issue with the counter not incrementing properly, or maybe when the feature went live we didn't migrate existing data? If anyone wants to take it on they'll probably need access to at least the dev database to see how things are working there, and possibly live also

**Comment by davehakkens** [comment]
was looking at other accounts. Seems to be ok(in sync) for them. 
Might just be only for the Precious Plastic account. So not an urgent issue.

**Comment by chrismclarke** [comment]
OK, for a proper fix we would need to run a script to check all the backend howto data and recalculate, which I don't think we can easily do until we have local database emulator running correctly. 

In the meantime probably the easiest way would either be to go to individual howtos and just click to update/save/republish them. That should trigger the backend function to update the user profile. 

You can check things populated correctly by seeing if the howto id (which can be seen in the console when the howto is opened) appears in the list of `userCreatedHowtos`

![image](https://user-images.githubusercontent.com/10515065/126001388-17e327be-37d2-4506-8f50-cbc49a5c33fb.png)

![image](https://user-images.githubusercontent.com/10515065/126001466-044b9bba-ffcd-45d6-b0fc-a6d48eefe675.png)

**Comment by iSCJT** [comment]
Fixed as part of #2428
