### ISSUE TITLE
[bug] Country name in English

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1155]
**Describe the bug**
In the user-profile the location is shown in the native lagnuage. This should be in English

**To Reproduce**
Visit any (non English) user profile and the country is shown in their own language

**Expected behavior**
All countries should be written in English

**Screenshots**
![profile-country](https://user-images.githubusercontent.com/13672737/118657269-9d593980-b7eb-11eb-8287-b3d98d9cf67b.jpg)

**Comment by leonorader** [comment]
Hi there! I would like to try to fix this! :) Could you please assign it to me?

**Comment by davehakkens** [comment]
jeej! done

**Comment by thisislawatts** [comment]
Hey @leonorader, hope you're well. Have you had a chance to take a look into this issue?
We have our monthly dev call on Monday 6th December where we normally review any open PRs and issues. It would be great to take a look at this one if you've got a draft to review by then. 
Let me know if you're having any issues setting up a local dev environment.

**Comment by ryanwbass** [comment]
@thisislawatts @davehakkens Hey, just came across this after watching some Project Kamp videos and wanting to see how I could get involved. Im looking into this issue and am having trouble figuring out how to access i18n from the UserStats.tsx file. What would be the proper way to import it? It seems like there are a couple different versions of the package out there ("i18n", "react-i18next", etc...) but this seems along the lines of what we would want https://react.i18next.com/latest/trans-component. 

I would love to help if I could get some advice on this. I will continue to look around for some other issues to work on too.

**Comment by davehakkens** [comment]
hey thanks for wanting to help @ryanwbass.
I think this issue somewhat got fixed for all new users, or when a location is changed for existing users. Then it updates to the correct location.
Only existing static users still display the old location in their own language.
Right @thisislawatts?



Andd what kind of issues are you looking for? I can hook you up ;)

**Comment by ryanwbass** [comment]
> hey thanks for wanting to help @ryanwbass. I think this issue somewhat got fixed for all new users, or when a location is changed for existing users. Then it updates to the correct location. Only existing static users still display the old location in their own language. Right @thisislawatts?
> 
> Andd what kind of issues are you looking for? I can hook you up ;)

I was a web dev for 3 years where we mostly did MEAN stack apps. React is a little new to me but not all that different and I'm eager to learn. Currently in a Game Dev role where I have gotten some experience with Firebase Databases (Realtime DB) but I primarily use C# in Unity.

I'm pretty comfortable anywhere so let me know where you need help/what you would suggest.

It might take me a bit to get comfortable with things and I wont have loads of bandwidth but I'm confident I can figure things out (maybe with a little help) and am excited to work on a project like this helping out where I can! Would love to join the Monthly call on the 2nd so I can introduce myself more properly there.

**Comment by thisislawatts** [comment]
Hey @ryanwbass, welcome to the project. Thanks for volunteering on this issue!

As @davehakkens mentioned we've updated the app to only persist location data using the English variant of a country name. There is probably a separate task required to perform a migration on all existing location data within the production database but I don't think that is covered by this task.

**Comment by davehakkens** [comment]
Thanks for the background info @ryanwbass! Good to have you here :)
I would be up for closing this issue. Not really worth the work for only existing location data.
As daniel mentioned in another topic. This would be a good one to take on as well 
https://github.com/ONEARMY/community-platform/issues/1611
Currently used a lot for Project Kamp :)

More issues coming soon!
