### ISSUE TITLE
[feature request] Link username in comment to profile

### ISSUE THREAD

**Issue by tudi2d** [ONEARMY/community-platform#1157]
**Is your feature request related to a problem? Please describe.**

★ as a bonus you could also make it link to the user profile. But no need. We can also do it in an issue later

_Originally posted by @davehakkens in https://github.com/ONEARMY/community-platform/issues/1153#issuecomment-844372563_

**Describe the solution you'd like**

Link the username in a comment to the users profile, such that you can find more information about them. It should be clearly visible, that the name is a link - in the following an example of how a username is linked in the HowTo: 

![image](https://user-images.githubusercontent.com/8904624/118875099-ee505700-b8eb-11eb-9f18-d94236160426.png)

**Additional context**

PR #1153 has to be merged, before we can work on this feature

**Comment by patrycjapraczyk** [comment]
Could I have a look at it once [#1153](https://github.com/ONEARMY/community-platform/pull/1153) is merged?
