### ISSUE TITLE
Capitalize titles

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1166]
Would be great to have all titles capitalized (first letter) so we can rule out user mistakes

![image](https://user-images.githubusercontent.com/17761877/120643112-0ab8cb80-c476-11eb-9593-eb3c96b75643.png)

**Comment by davehakkens** [comment]
Just putting this here for future references. 
https://github.com/ONEARMY/community-platform/issues/1066
Not sure if the solution in #1066 was actually merged

**Comment by chrismclarke** [comment]
Yeah that one has been sitting unmerged for quite some time, wasn't sure if it was still relevant or not (take that as a yes!)

I'll try to take a look at it next week, and if working merge (otherwise I'll update this comment and add a help-wanted label).
