### ISSUE TITLE
Add Button to comment 

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1170]
## Component infos
Currently, you leave a comment by pressing the "return" key. This behaviour is fast and snappy but feels like a chat. It needs to behave more like a thoughtful comment

### Description

- Add a button to the comment section to post
- The "return" key should not send the message but make a new line in the message

### Page related
https://dev.onearmy.world/how-to/

### Mockup
![comment-button](https://user-images.githubusercontent.com/13672737/121227648-b6518980-c883-11eb-92e8-690994b97ac7.jpg)

**Comment by tudi2d** [comment]
@davehakkens PR created. Suggestion would be to move the button to the right, as it seems more common (e.g. GitHub comments) - what do you think about it? 🙂 It's possible to add new lines, but they won't be saved right now - not sure. @danitrod any idea why? 😕 

![image](https://user-images.githubusercontent.com/8904624/123541059-ab7f6b80-d742-11eb-9a56-75ad0124a749.png)

**Comment by davehakkens** [comment]
suggestion accepted!  ✅ 
Makes sense. Thanks :)

**Comment by danitrod** [comment]
> @davehakkens PR created. Suggestion would be to move the button to the right, as it seems more common (e.g. GitHub comments) - what do you think about it? 🙂 It's possible to add new lines, but they won't be saved right now - not sure. @danitrod any idea why? 😕 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/8904624/123541059-ab7f6b80-d742-11eb-9a56-75ad0124a749.png)
> 
> 

At a first sight not sure... it's probably something in the back end, I'll have a look tomorrow

**Comment by danitrod** [comment]
Just tested here, actually it looks like it is how the comment component works: the text of the comment is being displayed in a `<p>` tag, so any newlines are ignored. Since I have an open PR for adding comments editing, I'll include an update to fix that

**Comment by tudi2d** [comment]
Ah, haven't checked that. Thanks for taking care of that! :)
