### ISSUE TITLE
Add edit feature in comments

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1171]
### Description
Currently, comments can be deleted but not edited. Editting is essential for us.
Clicking edit takes you back to the text editor. Publishing date stays unchanged but a little note `edited` is added.

1. Add "edit" and "delete" to the bottom of the comment
2. Show if a message is edited `(edited)`

### Page related
https://dev.onearmy.world/how-to

### Mockup
![4_comments_edit_clean](https://user-images.githubusercontent.com/13672737/121227990-2102c500-c884-11eb-8887-2377508f3e09.jpg)
![5_comments_edit](https://user-images.githubusercontent.com/13672737/121227992-219b5b80-c884-11eb-887c-30b7ff7a1abb.jpg)

**Comment by chrismclarke** [comment]
Thanks for taking this on @danitrod, will try review the PR in the next couple days
