### ISSUE TITLE
Add dropdown filter for most useful

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1172]
### Description
Add a dropdown filter on the how-to overview page to sort on most useful.
- Default is latest.
- Ideally it works in combination with the other filters. So if you select a tag or search. You can also filter on "latest" or "most usefull"
- Will make more sense when #1174 is implemented

### Page related

Will be used in :https://community.preciousplastic.com/how-to

### Mockup

<img width="855" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/121241527-75617100-c893-11eb-8085-7b78d0942835.png">

###Live version
https://community-platform.webflow.io/u/how-to

**Comment by chrismclarke** [comment]
I think if anyone wants to give a first pass at this, focusing more on the UI (until we find a solution to merge the right data for sorting) would be the best start, and a basic sort function to work with the tagging system.

**Comment by danitrod** [comment]
I had a look into this but ran into what you mentioned in #1174, don't want to actually make one request for each howto to get their stats. I'll prepare the UI part then, and then we figure out how to integrate it later

**Comment by danitrod** [comment]
Waiting on #1204 to be merged before going into this one
