### ISSUE TITLE
Add verified filter to the map

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1197]
## Component infos
We need a filter on the map to filter our verified workspace. It would work the same as the existing dropdown filter`(workspace, extrusion, sheetpress, community point etc)` 
- When selected it will show verified workspaces. 

### Assets
The Verified user data is stored in the V3_users>username>badges>verified
The icon can be found [here](https://github.com/ONEARMY/community-platform/blob/master/src/assets/icons/icon-verified-badge.svg) And it uses our aggregation
### Page related

Will be used in :https://community.preciousplastic.com/map

### Mockup
![map-dropdown-verified-icon](https://user-images.githubusercontent.com/13672737/127496318-6df09f65-a6e7-467c-bf24-8d279886707b.jpg)

**Comment by chrismclarke** [comment]
See my comments #1198 and #1163
If anyone wants to get started on the frontend then should be ready to go on that, but will need a few small updates on the backend to get the filtering logic working correctly.

**Comment by davehakkens** [comment]
Sorry, missed this comment @elvezpablo. Are you still good to finish it? Then i'll assign

**Comment by thisislawatts** [comment]
:wave: Hey @elvezpablo, I wanted to check in on this issue and see if you've had a chance to work on it?

We try to make sure any PRs are reviewed ahead of a monthly dev call (which is the first Monday of each month), so even if you've only got an early stage draft PR it could be a good starting point for discussion 😁

Thanks again for offering to help with this issue ✨

**Comment by davehakkens** [comment]
> I've started working on this issue and have been able to add the verified filter icon and label to the map. I need to run the integration tests and ensure the functionality is working as expected (minus the back end changes.). Could I get this ticket assigned to me? Thanks!

Hi @elvezpablo. FInal check in. let me know within 2 days if you want to finish this issue or share the code you made.
If we don't here anything no problem but then we will forward it to someone else.

**Comment by kfern** [comment]
@davehakkens Can I get to work on this?

**Comment by davehakkens** [comment]
> @davehakkens Can I get to work on this?

Great. yes! :)

**Comment by kfern** [comment]
We need to make big changes to the map page components to close this issue.

Can we use an approach like [RFC: Unit Tests #1378](https://github.com/ONEARMY/community-platform/issues/1378)?

I can do it in the maps page component without any breaking changes.

@chrismclarke @thisislawatts What do you think?

**Comment by chrismclarke** [comment]
I think we're at slightly limited capacity right now for testing/reviewing/merging big changes, I still really want to find more time to review and move forward with the other changes you proposed for the map system before iterating too much further on large changes. Are you able to describe what the blocking issue is exactly?

**Comment by kfern** [comment]
HI @chrismclarke 

The component that manages the filter (GroupingFilterDesktop.tsx) receives pins grouped by IPinGrouping ('individual' | 'place') and type (IMapPinType)

A pin only belongs to one group and with this use case the same pin would have to be part of two groups (IMapPinType and "verified type").

I can't imagine a solution without making major changes. 

Any ideas?

**Comment by davehakkens** [comment]
@kfern I know you have been working on this. But after our chat last week you might understand our current problems better. Chris mentioned there is probably also an easier way to do this in the current setup.
Would you be interested to work on this Fernando and would you have any suggestions to get started @chrismclarke?
For anyone wanting to take on this issue

**Comment by kfern** [comment]
@davehakkens 

>Would you be interested to work on this Fernando
Yes. I can go ahead with @chrismclarke suggestions

**Comment by thisislawatts** [comment]
:wave: Hey @kfern, have you had a chance to pick this item up yet?

**Comment by kfern** [comment]
Hi @thisislawatts. I'm waiting for @chrismclarke suggestions

**Comment by thisislawatts** [comment]
🤦🏻 My apologies @kfern, I misunderstood your previous message. I incorrectly assumed you had chatted with Chris outside of this issue. Let me take a closer look and see if anything emerges 🔍

**Comment by thisislawatts** [comment]
@kfern I took a look into this and was able to get a functional verified filter working with some minor changes. Would appreciate your eyes on this as a starting point:
https://github.com/ONEARMY/community-platform/compare/spike/verified-dropdown

I see the next steps here being:
1. Introducing unit tests around _filterMapPinsByType_ and improve logic. My hacky implementation ignores the situation where multiple filters which include`verified` are passed in: [src/stores/Maps/filter.ts](https://github.com/ONEARMY/community-platform/compare/spike/verified-dropdown#diff-14fefc5811ce46d2c5ba42333d5fc188eea35d9a298e6478e1b276fd6d8950aa) 
1. Lift `GroupingFilters*` data structure transformations out of the UI components into a shared method. Removing the dependency these components have on `mapsStore`. The duplicated changes within GroupingFilterDesktop and GroupingFilterMobile point towards an optimisation that can be made here.


![Mobile filters](https://user-images.githubusercontent.com/472589/173224969-7fb2889c-3937-49d6-bbf8-6a3b1bd17dcc.jpg)
![Desktop filters](https://user-images.githubusercontent.com/472589/173224971-18316d4d-d9aa-4543-935f-b27e800baefc.jpg)

**Comment by kfern** [comment]
@thisislawatts For the next few months I will have little free time because I'm moving to a new job. Feel free to assign to another.

**Comment by thisislawatts** [comment]
Congratulations on the new job @kfern ✨ Enjoy getting settled in!
