### ISSUE TITLE
[bug] Image with identical filename gives errors

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1206]
**Describe the bug**
When users upload images in their research or how-to with the same file name they get mixed up and no error messages. Leaving the user confused.

**To Reproduce**

1. Create a few images with identical names` 1.jpg `or` image.png` etc
2. Create a new howto
3. Upload a different image (with the same name) for each step
4. Press publich and see the mixed up images

**Expected behavior**
Users should be able to upload images with identical names

**Comment by franknoirot** [comment]
Would it be acceptable to alter the filename upon upload? Adding a timestamp could ensure no name collisions are possible if you don't mind the filename being manipulated. For example:
- upload 1: `image.png` becomes `image-210921223533.png`
- upload 2: `image.png` becomes `image-210921223614.png`

**Comment by franknoirot** [comment]
I think I see where the image metadata is created and would love to try this if that's alright to assign it to me.

I just have one question: how do I sign in during local development? I see a mock User "chris-m-clarke" but don't see how to sign in as them to test making a new HowTo.

**Comment by davehakkens** [comment]
yeh we can give a timestamp to the upload, seems good to me @franknoirot 

For login
As far as I know (it might be changed)
It depends on which database you use locally ([staging](https://dev.onearmy.world/how-to) or [live](https://community.preciousplastic.com/how-to)) You can easily see the difference by checking the latest how-to's uploaded

From than you create an account online (on either dev or live) on whichever database you run locally. After created you should be able to login locally ..
