### ISSUE TITLE
[feature request] show display name on map pins, instead of the username

### ISSUE THREAD

**Issue by tiefpunkt** [ONEARMY/community-platform#1210]
**Is your feature request related to a problem? Please describe.**
My "username" doesn't quite match the workspace, so this is confusing both on the map and in the how-tos. See this:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/434444/132260417-f58fb091-3bd5-4ea0-9f55-383e557eda0a.png">.
Now when I click on that name, I get to the profile page, which doesn't say the name anymore, but rather the name of the workspace, or "Display Name" as it's called in the settings
<img width="640" alt="image" src="https://user-images.githubusercontent.com/434444/132260814-37d5df76-4833-4a2b-a4fd-db7ca771f698.png">

**Describe the solution you'd like**
Replace most/all instances of the user name with the "Display Name". Most importantly in the "popups" for pins on the map, but maybe also in the thumbnail things for how-tos: 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/434444/132260589-c5aa9b35-e02b-4b39-9048-4faa78eff3be.png">

**Describe alternatives you've considered**
Another and maybe better, but also probably much more involved and complicated solution would be to split users and map pins, so one user can maintain multiple map pins, with their own names. This would be much more complicated to implement I'd assume.

**Additional context**
I did some digging but could find any other issues matching this, but some that are related, like #1200 and also #773.

**Comment by davehakkens** [comment]
hey thanks for the issue. This is a bit of a more complex one though..
Sometimes we need usernames to refer to a member (especially with comments/ tagging people @username etc)
But `Usernames` do tend to look strange and are unchangable. 

And it does get confusing when we mix both, sometimes `Username` sometimes `DisplayName`


So for now I would say we can use `DisplayName` on the Map & Profile. Wouldn't use it in how-to, yet. 
This requires a bit more strategic thinking.

**Comment by tiefpunkt** [comment]
That sounds like it would eventually make sense to split workspaces/map pins & users into separate entities.

`DisplayName` on the Map would be a really great improvement though imho, sounds like a good start to me :)
