### ISSUE TITLE
[bug] Country flag not showing in comments

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1211]
**Describe the bug**
The country flag of a user is not showing in the comments.
[(example bottom of page)](https://community.preciousplastic.com/how-to/plastic-medals--free-injection-mould-design)

**Expected behavior**
Flag should be shown like in this issue #1127 
<img width="670" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/133866843-5eb7c720-49b8-4a28-808f-85065b33377c.png">

**Screenshots**
Possible problem mentioned by @tudi2d on Slack
Could this be the reason? (Image from the user page) For the `addComment` in the store it is only `creatorCountry: user.country ? user.country.toLowerCase() : null` saved to the backend.

![afbeelding](https://user-images.githubusercontent.com/13672737/133866812-eec0288e-1635-4675-9900-d71b0aaf96b3.png)

**Comment by danitrod** [comment]
Should be a quick one, I'll send a PR

**Comment by danitrod** [comment]
Re-opening, as apparently the merged PR had no effect in the [example page](https://community.preciousplastic.com/how-to/plastic-medals--free-injection-mould-design). We will have to further debug to find the root cause of this problem

**Comment by davehakkens** [comment]
closing this issue since new releases have made.
But the problem is still there: https://github.com/ONEARMY/community-platform/issues/1469
