### ISSUE TITLE
[bug] Links broken when inserted into Community contact fields (case-sensitive error)

### ISSUE THREAD

**Issue by shenoa** [ONEARMY/community-platform#1256]
**Describe the bug**
When editing the "Contacts and links" section of the https://community.preciousplastic.com/settings page, one of the options is to add a link type called Discord. Any link that is pasted into the text field is reformatted as all lower-case. Any URL that has uppercase letters in the URL is reformatted as lowercase. It is also not possible to type an uppercase letter into the box. This will break any URL that has uppercase letters after the domain. Discord invite links, for example.

**To Reproduce**

1. Go to 'Edit Profile'
2. Scroll down to 'Infos'
3. Click 'add link'
4. Type any address with an uppercase letter and it's inserted as lowercase

**Comment by thisislawatts** [comment]
Thanks so much for taking the time to file your bug report @shenoa, it is really appreciated ✨

It looks like this is the cause:
https://github.com/ONEARMY/community-platform/blob/master/src/pages/Settings/content/formSections/Fields/Link.field.tsx#L50

I think this should be removed entirely in favour of deferring to the user to format a URL correctly. Browsers are fairly tolerate of malformed hostnames, eg. [https://EXAMPLE.com](https://EXAMPLE.com)
