### ISSUE TITLE
[bug] yarn storybook: broken build error

### ISSUE THREAD

**Issue by kfern** [ONEARMY/community-platform#1308]
**Describe the bug**
I can't run storybook

**To Reproduce**
git clone
yarn install
yarn storybook

I have a lot of lines like...

      /node_modules doesn't exist or is not a directory
      looking for modules in /home/community-platform/node_modules
        using description file: /home/community-platform/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/community-platform/package.json (relative path: ./node_modules/@storybook/addon-knobs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/community-platform/node_modules/@storybook/addon-knobs doesn't exist
 
... Some lines like this (ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/addon-knobs')

      ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/addon-knobs' in '/home/community-platform/src/components/Icons'

**Additional context**
Ubuntu 21.04

node -v
v12.22.0

yarn -v
3.0.2

yarn workspaces list
➤ YN0000: .
➤ YN0000: functions
➤ YN0000: packages/cypress
➤ YN0000: packages/documentation
➤ YN0000: packages/storybook
➤ YN0000: scripts
➤ YN0000: shared

Any idea?

**Comment by thisislawatts** [comment]
Thanks for raising this bug @kfern, I haven't actually tried getting the Storybook instance up and running before. I will take a look and see what I can find.

**Comment by thisislawatts** [comment]
Confirming that I have been able to recreate this locally.

Looking further down the output I was struck by _ModuleParseError: Module parse failed: The keyword 'interface' is reserved (14:0)_ is this something you saw on your machine? It seems like maybe some typescript compilation is not quite right. 

As I've never seen this working, I would like to hear if @chrismclarke has any insight on what could be causing this. 

```
/home/oss/community-platform/node_modules/react-scripts/node_modules/@storybook/addon-knobs doesn't exist
ModuleParseError: Module parse failed: The keyword 'interface' is reserved (14:0)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| import { LinkTargetBlank } from '../Links/LinkTargetBlank/LinkTargetBlank'
|
> interface IProps {
|   event: IEvent
|   needsModeration: boolean
    at handleParseError (/home/oss/community-platform/packages/storybook/node_modules/webpack/lib/NormalModule.js:469:19)
    at /home/oss/community-platform/packages/storybook/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/oss/community-platform/packages/storybook/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/oss/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/oss/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/oss/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/oss/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/oss/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/oss/community-platform/packages/storybook/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:96:7
ModuleParseError: Module parse failed: The keyword 'interface' is reserved (50:0)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| import { DownloadIcon } from './DownloadIcon'
|
> interface IGlyphProps {
|   glyph: string
| }
```

**Comment by kfern** [comment]
HI @thisislawatts 

I don't see "ModuleParseError: Module parse failed: The keyword 'interface' is reserved (14:0)" but other module parse error like "ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/addon-knobs'"

**Comment by thisislawatts** [comment]
Hm… I did move a few things around in this commit that may have affected things, could you try pulling that down?
https://github.com/ONEARMY/community-platform/commit/5de47620c1d9032c3e5d921c3a0a66c814c61131

**Comment by kfern** [comment]
Hi @thisislawatts

I have a different error using investivation/bug-report-1308 branch 

```
git fetch --prune
git checkout investivation/bug-report-1308
yarn storybook
```
ModuleParseError: Module parse failed: Unexpected token (9:27)
  File was processed with these loaders:
   * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
  You may need an additional loader to handle the result of these loaders.
  | import { HeadingProps as RebassHeadingProps } from 'rebass/styled-components'
  | 
  > export const large = (props: ITextProps) =>
  |   props.large ? { fontSize: theme.fontSizes[6] } : null
  | export const medium = (props: ITextProps) =>
      at handleParseError (/home/community-platform/packages/storybook/node_modules/webpack/lib/NormalModule.js:469:19)
      at /home/community-platform/packages/storybook/node_modules/webpack/lib/NormalModule.js:503:5
      at /home/community-platform/packages/storybook/node_modules/webpack/lib/NormalModule.js:358:12
      at /home/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:373:3
      at iterateNormalLoaders (/home/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
      at iterateNormalLoaders (/home/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
      at /home/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:236:3
      at context.callback (/home/community-platform/packages/storybook/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
      at /home/community-platform/packages/storybook/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:96:7

  WARN Broken build, fix the error above.
  WARN You may need to refresh the browser.

**Comment by kfern** [comment]
Hi @thisislawatts 

This bug was introduced on May 10, 2021 by https://github.com/ONEARMY/community-platform/commit/db0b3b3280114ceab255f74be73ca51aa9b2d640

At this point it works (May 8, 2021) https://github.com/ONEARMY/community-platform/commit/098a1f795617ee1b8119701e93b241e4944cf3db
```
rm -rf node_modules/
git reset --hard
git checkout 098a1f795617ee1b8119701e93b241e4944cf3db
yarn install
yarn storybook
```
The following commit caused the error (May 10, 2021) https://github.com/ONEARMY/community-platform/commit/db0b3b3280114ceab255f74be73ca51aa9b2d640
 
```
rm -rf node_modules/
git reset --hard
git checkout db0b3b3280114ceab255f74be73ca51aa9b2d640
yarn install
yarn storybook
```

**Comment by thisislawatts** [comment]
![Great detective work](https://media.giphy.com/media/42wQXwITfQbDGKqUP7/giphy.gif)

Amazing detective work @kfern1

So if we revert that change were you able to get Storybook up and running against the `HEAD` of the branch?

**Comment by kfern** [comment]
@thisislawatts I'm not sure. Could you do it in a new branch?

**Comment by thisislawatts** [comment]
@kfern I would definitely like to get this working again, and probably add a CircleCI job that builds the Storybook library so we can keep an eye on this going forward.

Looking at the latest state of `master` we no longer have a yarn.lock within functions 🤔 
https://github.com/ONEARMY/community-platform/tree/master/functions

**Comment by thisislawatts** [comment]
@kfern, digging into this a little bit this morning, I have been able to build storybook at this point, 28th May:
85aaa9a3fec0047983d03120c3c39983a3d950b4 

Are you able to build storybook at this commit?

This is the first workable commit I found after it was moved into a subdirectory, which is good because I was worried the monorepo structure could have been causing this error.

**Comment by kfern** [comment]
@thisislawatts. I can confirm that at that commit storybook works 👍🏽

**Comment by thisislawatts** [comment]
Thanks for confirming @kfern, I was also able to get this installed and working with, e415cf6ceddd7008ede8068d8a4aa36f965219c8, which was the last commit affecting the contents of `packages/storybook`.

So next steps I guess are to dig in with  `git bisect` between HEAD and e415cf6ceddd7008ede8068d8a4aa36f965219c8, and see what we can find. 
> Bisecting: 196 revisions left to test after this (roughly 8 steps)

**Comment by thisislawatts** [comment]
Suspected candidate for causing storybook to break: https://github.com/ONEARMY/community-platform/commit/b864aea

Now to research whatever `nmHoistingLimits` is
https://github.com/ONEARMY/community-platform/commit/b864aea#diff-88fbe28c4102501b94961511a0d70ff895bf39970b4d3fc11917794a239117c5R11

**Comment by kfern** [comment]
@thisislawatts It works 👍🏽 Thank you

PS: I had to delete node_modules and run yarn install

**Comment by thisislawatts** [comment]
Good catch, thank you for clarifying that additional clean-up step @kfern ✨
