### ISSUE TITLE
[bug] Explore | Start exploring | Watch online content - "Wild Wild Country" & "The Experimental City" show twice

### ISSUE THREAD

**Issue by charEric** [ONEARMY/community-platform#1354]
**Describe the bug**

In the "Watch online content" table, _Wild Wild Country_ & _The Experimental City_ show twice. Also, there is a typo in _Wild Wild Country_ (says "County", not "Country")

See screenshot below.

**To Reproduce**

1. Go to: https://community.projectkamp.com/academy/explore/intro
2. Scroll down to "Watch online content" 
3. See _Wild Wild Country_ & _The Experimental City_ listed twice in table
4. Also, there is a typo in _Wild Wild Country_ 

**Expected behavior**
Each field should only show once.

**Screenshots**

![Screen Shot 2021-12-28 at 9 20 27 AM](https://user-images.githubusercontent.com/4203842/147591334-4656c5aa-cbee-4867-a9b8-cfb54187907a.png)

**Additional context**

**Comment by thisislawatts** [comment]
Thanks for raising this @charEric. It is not obvious but this content is managed within a separate GitHub repo. I've raised to address this: https://github.com/ONEARMY/project-kamp-academy/pull/30

I will leave this issue open so we can track progress :)

**Comment by charEric** [comment]
> Thanks for raising this @charEric. It is not obvious but this content is managed within a separate GitHub repo. 

@thisislawatts ah, ok good to know 👍

**Comment by thisislawatts** [comment]
Changes have been merged, and duplicates removed from: https://community.projectkamp.com/academy/explore/intro
