### ISSUE TITLE
[bug] howto filtering by tags persists after going back in history browser

### ISSUE THREAD

**Issue by jparadasb** [ONEARMY/community-platform#1358]
**Describe the bug**
When using the how-to filter by tags after selecting at least two and then going back forward in the browser history, the filters still appear selected although not present in the URL.

**To Reproduce**

1. Go to 'How-to'
2. Select one or more filters tags
3. Press the history back button on the browser
4. The content still is filtered and it appears selected in the SelectBox 

**Expected behavior**
When the filter by tags is selected if I go one time back in the browser history the last tag selected shouldn't appear and the content shouldn't be filtered by that tag, should have consistency with what the URL is showing.

**Screenshots**
![gif](https://user-images.githubusercontent.com/5114020/147450801-b2fedf4a-aa51-4eb6-857a-85e4dc204d9c.gif)

**Additional context**

**Comment by thisislawatts** [comment]
Thanks for raising this issue @jparadasb as discussed in #1238. Okay if I assign it to you?

**Comment by jparadasb** [comment]
Yes, please

**Comment by Ulian** [comment]
The tag filter doesn't exist anymore. This behavior happens to category and search filters as well, do I create a new issue or can I take this one @thisislawatts?

**Comment by davehakkens** [comment]
well spotted @Ulian, you can take this one and replace tags with categories
