### ISSUE TITLE
Add "Want to get started" to map.

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1362]
### Description
At the moment Workspace profiles can add a pin to the map to display their workspace. 
Member profiles cannot add a pin to the map.

This new feature would allow members (everyone) to create a "want to get started" pin on the map

### Pages
https://community.preciousplastic.com/settings
https://community.preciousplastic.com/map

### Related to
This is related to PR https://github.com/ONEARMY/community-platform/pull/1267 that will simplify member profiles. This will also create the function to upload an avatar for members.

### Function
📍 Add yourself to the map > Country flag is shown in profile and name
╳ If not added to the map > No Country flag is shown in profile and name

🇫🇮🏴󠁧󠁢󠁥󠁮󠁧󠁿🇧🇯🇬🇶🇱🇻 This would be fun/useful so you know that every user with a flag is on the map 

### Mockup

**How to add a pin:**
<img width="1031" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/147702549-e6e6342b-c644-4310-876a-bbdf0d043c36.png">

**How it's shown on the map**
<img width="1092" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/147702621-6a0841ed-7758-4e75-b90e-9ab858f331e4.png">

**Where it's shown on the map**
<img width="1138" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/147702650-442e5682-a0a9-4471-abce-d6ba1b8c3a35.png">

This issue is made as a conversation starter to discuss the best way to build it

**Comment by thisislawatts** [comment]
@davehakkens when looking at the referenced Workspace functionality I note the following:

> In order to have your pin accepted on our map you have to collect at least 6 stars in the Ally Checklist. Learn more about the Community Program and how you can join.

Would the above restriction apply to this new _Want to get started_ functionality?

**Comment by davehakkens** [comment]
Nope. There wouldn't be any verification on this. 

Also just realized this is still online and could serve as inspiration for this feature. "want to get started" pins from our old map
http://oldmap.preciousplastic.com/

**Comment by thisislawatts** [comment]
I will pick this item up, let me know if anyone would like to pair on this work.
