### ISSUE TITLE
Add Comments to Research Module

### ISSUE THREAD

**Issue by franknoirot** [ONEARMY/community-platform#1363]
## Description

This component is intended to add the ability to leave comments on each step of user-published Research Modules. It builds upon past work on the Comments feature (#1127, #1128, #1170, #1171).

Acceptance Criteria Checklist:
- [ ] Users can add and edit comments of their own only when logged in.
- [ ] If there are comments on a research step, a button appears at the end of its container that toggles open the comment viewer.
  - [ ] When expanded, comments are shown, followed by a comment submission form. These components should be reused from previous Comments feature work.
  - [ ] If the user is not logged in, the only difference is there is no comment submission form available to the user.
- [ ] If the there are no comments and the user is logged in, they will see a similar toggle button that invites them to start the discussion.
  - [ ] When expanded, this looked identical to the expanded comments section described above, but with no previous comments between the toggle button and the comment submission form.
- [ ] If there are no comments and the user is logged out, no toggle button or indication of comments are shown.
- [ ] All buttons have hover/focus states that align with the mockups and the existing design system.

## Related Pages

Will be used in:

- Research Module (#1110, #1111)

## Mockups

[Visit the Figma space](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/?node-id=10%3A72) where the mockups are hosted to fulling inspect the mockups. Comments and questions about them can be added by pressing `C` and clicking where you want to pin a discussion, tag @franknoirot or @davehakkens within.

Here are screenshots of the 3 main layouts taken on 30/12/21:

### 1. A logged-in user's view of 3 research steps: no comments, comments collapsed, and comments expanded
![Research Module - Logged In](https://user-images.githubusercontent.com/23481541/147775987-70888e32-c97a-41fb-a348-2a575e75cae0.jpg)

### 2. Hover/active states of a logged-in user's view. Note that the "no comments" step is shown expanded to add the first comment:
![Research Module - Logged In - Hover States](https://user-images.githubusercontent.com/23481541/147776864-e530902b-383b-428d-add1-321e638d2716.jpg)

### 3. A logged-out user's view of the same 3 research steps:
![Research Module - Logged Out](https://user-images.githubusercontent.com/23481541/147776886-8b4b400e-41c7-4aa3-822c-0c6c7847517a.jpg)

## Example(s)

See existing Comment component

## Build suggestions

I recommend creating a component that wraps the existing Comments component in a toggle button and container. The main state variables that influence this wrapper component are:

- Is the user logged in/authenticated
- Are there comments on this step or not
- Is this toggle to control the container on or off

There is backend work that will require someone with more knowledge on the system to weigh in on, but I believe [Firestore Subcollections](https://firebase.google.com/docs/firestore/data-model#subcollections) could serve to associate comments to steps within a Research module. The comments should follow the data model used to implement them elsewhere on the platform.

**Comment by thisislawatts** [comment]
@franknoirot it looks like comments are only available to beta-testers. Has the Comments feature reached a level of maturity that supports us introducing it to other document types?

```
<AuthWrapper
  roleRequired="beta-tester"
  fallback="You must be a Beta Tester to add a comment"
>
```
https://github.com/ONEARMY/community-platform/blob/master/src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx#L75-L78

**Comment by thisislawatts** [comment]
Given the above @franknoirot, I think the first two steps here are to:

1. Release comments to everyone
2. Extract comments frontend component ready for reuse elsewhere. I am not sure that the current implementation is ready to be dropped into Research straight away.

**Comment by thisislawatts** [comment]
Following up on this item, me and @franknoirot  had a call yesterday and we decided that:

* I would pick up the task of releasing the existing comments behaviour to everyone
* @franknoirot will work on introducing Comments to the Research document type.

**Comment by davehakkens** [comment]
sounds good! 
Any date/timeframe in mind, or first see how it goes first @franknoirot?
No pressure, just to roughly keep check of our calendar.

**Comment by franknoirot** [comment]
@davehakkens I'm really having trouble getting started even running the app any time I try to work in the codebase, so I'm hesitant to give an estimate. I'm gonna reach out to @thisislawatts on Slack but I just cannot get the hang of development here, I'm sorry.

**Comment by davehakkens** [comment]
Ah bummer. But no worries, thanks for letting me know! Would you prefer to work more on design/figma or want to try dev?

**Comment by thisislawatts** [comment]
@franknoirot do grab some time with me. It would be really helpful to understand what is making the development process more complicated. Any improvements we make here will benefit anyone looking to contribute to the project.

**Comment by jojudre** [comment]
Hey! i will try to do this)

**Comment by thisislawatts** [comment]
Thanks @jojudre, let me know if you want to jump on a kick-off call to talk through anything. Otherwise happy to chat async here or on the PR.
