### ISSUE TITLE
Add country flag to research username

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1406]
### Description

Everywhere on the platform we show username with country flag (comments/how-to) This was never integrated in the research module. That is an issue. Not cool.

### Page related

Will be used in :

- [Research page](https://community.preciousplastic.com/research/make-things-from-ocean-plastic) where it should come
- This layout already used in [how-to's ](https://community.preciousplastic.com/how-to/make-christmas-ornaments-from-upcycled-bottle-caps)
- Previous PR introducing the flag https://github.com/ONEARMY/community-platform/pull/1033

### Mockup
![Add flag research](https://user-images.githubusercontent.com/13672737/151039332-9bb1667a-800d-415d-925d-602eadeb0ec1.jpg)

**Comment by mmortar** [comment]
I would also like to correct this issue in the research module if you could please assign it.  Thank you!

**Comment by davehakkens** [comment]
great! But maybe start one by one?
I'm conscious it's your first contribution ;)

**Comment by thisislawatts** [comment]
Thanks for your interest @mmortar

I wanted to confirm know that @EmanueleGurini will be picking this up as part of #1407 ✨

**Comment by jojudre** [comment]
hi, i am working on this, as i understand we need to add flag near username in research modules

**Comment by davehakkens** [comment]
Jeej! Correct, and we already use this behaviour in our how-to's ([example](https://community.preciousplastic.com/how-to/make-christmas-ornaments-from-upcycled-bottle-caps))
