### ISSUE TITLE
Add username to profiles

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1407]
### Description

As we start using comments more, people will see usernames more. However, on the profile you can't see a username. Only the display name. This has been confusing to users.  We want to change three things.
1. Remove the label. This is redundant with the badge next to it.
2. Add username to the place of the label
3. Change the location of the country flag from `displayname` to `username` to stay consitent. 

The changes apply to all "space" profiles. (community point, machine shop, workspace, collection points)
### Page related

Will be used in :

- [Related page (profiles) ](https://community.preciousplastic.com/u/precious-plastic)

### Mockup

![username to profile](https://user-images.githubusercontent.com/13672737/151040409-de336741-7ac4-4cfe-8a2c-9b0499013e08.jpg)

**Comment by EmanueleGurini** [comment]
Hi, can i grab this issue?

**Comment by chrismclarke** [comment]
Sounds great! Feel free to drop a message in the thread if you have any issues while working on it @EmanueleGurini

**Comment by thisislawatts** [comment]
:wave: Hey @EmanueleGurini, I think that this item is closely related to https://github.com/ONEARMY/community-platform/issues/1406, introducing a reusable `UsernameWithFlag` component to both the Profile and Research articles would be a good path forward here. What do you think? Okay if I also assign the otherone to you as well?

**Comment by EmanueleGurini** [comment]
@thisislawatts Yes, don't worry

**Comment by davehakkens** [comment]
hey @EmanueleGurini. Just checking in. How is this one going, need any help?

**Comment by EmanueleGurini** [comment]
> hey @EmanueleGurini. Just checking in. How is this one going, need any help?

Hi @davehakkens, thanks for your interest. Sorry for the late: I'm preparing for an exam that I gonna make Monday. I will send you a PR with everything done this week. 

Just one question: I'm using fake data because I do have not the DB, do you know how can I emulate your one?

Thanks again, 
Emanuele

**Comment by EmanueleGurini** [comment]
@davehakkens sorry Dave, I'm continuously getting this message error that I'm not understanding, and it appears since I pulled updates from your master, to keep the fork synced. Do you know how can I fix it?

**Comment by chrismclarke** [comment]
Hey @EmanueleGurini - that's pretty weird, I can't recreate the problem myself but as a workaround could you try deleting the folder `types\mobx-remotedev-v4` and see if that fixes.

If I can remember correct that remotedev library used to be included for people who wanted to use the mobx extension but looks like it's not even in the repo anymore so see no reason to keep the type definition

**Comment by davehakkens** [comment]
hey @EmanueleGurini, this seems to be a bit stagnated. 
Let me know if you want/can to take this one on before the end of the week.
If it no worries but we will assign it to someone else :)

**Comment by jojudre** [comment]
i will take this issue
