### ISSUE TITLE
Replace react-multi-select component

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1409]
### Description

Mentioned #1378, the map page uses a component based on [ `@khanacademy/react-multi-select`](https://github.com/Khan/react-multi-select) which does seem to be actively maintained and starting to throw warnings during build (pinned to react 15, but we're currently using react 17).

A new component is therefore required which can replace the multiple item select seen on the map page dropdowns

### Page related

Will be used in : map

### Mockup

![image](https://user-images.githubusercontent.com/10515065/151091546-fbe6a6f1-9c54-467a-8f27-63dedd3a1238.png)

![image](https://user-images.githubusercontent.com/10515065/151091300-4288802d-8aa8-4119-b761-24d8d5801637.png)

### Example(s)

See live version on the map page
https://community.preciousplastic.com/map

### Build suggestion

The component doesn't need the full functionality of the original react-multi-select, can just base on the functionality of the current map page (e.g. passing custom image, counter, check symbol etc.). There is already a separate component used in the mobile version that has most of the same functionality so that might be a good place to start

![image](https://user-images.githubusercontent.com/10515065/151098029-c0ddcf58-a15b-442f-8aec-3c893b9b8ab9.png)

**Comment by davehakkens** [comment]
Little follow-up on this one. We plan to remove the double filter on Desktop and go for the Mobile approach everywhere.  One single filter: as raised in this issue. https://github.com/ONEARMY/community-platform/issues/1411

So yeh. good to start with mobile :)

**Comment by chrismclarke** [comment]
Oh perfect, I'll close this issue then and merge into #1411 as makes sense to work on the two together
