### ISSUE TITLE
Combine map filter Desktop

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1411]
### Description

Currently we have 2 filters for the map on Desktop. `Workspace` and `Others`. We need to combine these into 1 `filter`.
- This is needed for other projects (instances) that will use the platform, since not all of them have two filters to fill.
- This method is already used in Mobile, nice to align.

### Page related

Will be used in :

- [Map page](https://community.preciousplastic.com/map)
- Related to the issue to replace the react-multi-select component https://github.com/ONEARMY/community-platform/issues/1409
- Related to the issue of the verification filter https://github.com/ONEARMY/community-platform/issues/1197

### Mockup

![map filter](https://user-images.githubusercontent.com/13672737/151148395-c4753a74-b61d-4849-b326-3b1ce4294087.jpg)

### Build suggestion

A combined filter is already used on mobile. It works good and perhaps we could reuse it for the desktop to align.
<img width="446" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/151148818-6658fdca-8507-4c58-b3f6-9d5a7e65866c.png">

### Additional Info
After creating please also remove the old desktop filter component and dependency  [ `@khanacademy/react-multi-select`](https://github.com/Khan/react-multi-select)
(see original issue in #1409)

**Comment by jojudre** [comment]
Hi, i want to do this!

**Comment by chrismclarke** [comment]
Sounds great @jojudre ! Just to check, did the comment about linking the issue to #1409 make sense?

**Comment by jojudre** [comment]
Yes, i will delete dependency @khanacademy/react-multi-select
