### ISSUE TITLE
[bug] Deleting User Profile does not work

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#1412]
![Screenshot 2022-01-26 at 17 45 42](https://user-images.githubusercontent.com/472589/151207741-a8fa4007-b494-466c-b6ec-f333716795f4.jpg)

**Describe the bug**

It is not possible to delete a User profile.

**To Reproduce**

1. Go to User Profile > Settings
3. Scroll down to 'Account Settings'
2. Click on 'Delete Profile'
4. Nothing happens

In the browser console the following message is displayed:
`Uncaught (in promise) Error: PERMISSION_DENIED: Permission denied`

**Expected behavior**

A user should be able to delete their own account without contacting support/raising a ticket.

NOTE: Also need to clean up mappins on delete

**Comment by davehakkens** [comment]
hmm.. I tried it and managed to delete [my profile](https://dev.onearmy.world/u/davetest). Seems to work?
However due to caching it still shows in the local browser so probably the user thinks its not deleted.
If a try another browser it's not there..


![caching](https://user-images.githubusercontent.com/13672737/151209375-1379646f-99d7-4c65-9ae7-31bbd0d96203.jpg)

**Comment by IvaTsu** [comment]
Hey @thisislawatts @davehakkens 

I am not able to delete the account when hitting Settings -> Delete Profile at https://community.preciousplastic.com/settings

I have 1 warning and 1 error at the console:
`@firebase/database: – "FIREBASE WARNING: set at /v3_users/{my_username} failed: permission_denied "`
`Unhandled Promise Rejection: Error: PERMISSION_DENIED: Permission denied`

But, if I run the `master` branch of the fork (ONEARMY/community-platform), it does delete the account.

Hope it help.

**Comment by davehakkens** [comment]
thanks for looking into it @IvaTsu 
Strange.. perhaps a permission issue in Firebase?

**Comment by davehakkens** [comment]
@chrismclarke, tagging you in here. You might have some suggestions since you love dealing with Firebase permissions
