### ISSUE TITLE
Change email associated with account

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1414]
Hello 🤙

Was just trying to change the email associated with my account but realized it is not currently possible to do so. 
Would be great for a user to be able to change its own login data. 
Something like "Change email address"

<img width="857" alt="image" src="https://user-images.githubusercontent.com/17761877/151390941-bc02e4c9-04b4-4f50-adf0-63b04062e90f.png">

**Comment by jojudre** [comment]
Hello, i want to do this task, and see you have updateEmail function

**Comment by thisislawatts** [comment]
Hey @jojudre, happy to see you're interested in picking up another issue. Thanks for your continued interest on the project!

I had a quick look at the [updateEmail method](https://firebase.google.com/docs/auth/web/manage-users#update_a_users_profile) and the provided example seems like a good starting place. 

Does the _Change Password_ provide you enough guidance for how it should look and work? We can always pull together some visuals if you'd prefer.

**Comment by jojudre** [comment]
Hey! you can look my pr and i can fix it if needed
