### ISSUE TITLE
Improving SEO #1 - Indexable by search engine.

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1418]
### Description

The platform is currently very poorly indexed by search engines.
Our content is rendered dynamically and needs server-side rendering to improve.

### Page related
This issue is mainly important for the [how-to's](https://community.preciousplastic.com/how-to) since they contain the most indexable content.

### Additional work
Besides that, there are a few other smaller things to improve. You can find more of that below in the Additional Report
we had from an SEO Analist. Might be helpful..

1. [Sitemap]: you should add it in public folder, it's recommended to make it auto generated ( I can help in this ), don't try to use online website to generate it, because in your case it's SPA with CSR, so it's will detected just the / page ...
2. try to use href as possible because it's help a lot.
3. try to add "alt" to image.
4. maybe use pagination it's will help to have better performance ( you have an issue in this, and it's have very big impact)
5. you should use google search console to have a better view of the page that are indexed, and also to send request to google to index your page ( https://search.google.com/ ) 
6. [meta data] : you should insert meda data for every page with dinamyc content, to make this it's simple => use React Helmet 
7. if you have a server like apache you should make configuration to set 404 status error for errorPage, this is a solution for SPA CSR, in case of nextjs or ssr it's ok

**Comment by thisislawatts** [comment]
I think the highest priority item here is to get key content pages such as the How-to listing and individual How-to articles rendered via SSR. 
I am going to prototype an approach which will render these pages on the server, most likely via Google Cloud Functions so we can stick with our existing stack.

**Comment by chrismclarke** [comment]
Getting a decent dev workflow going for testing these things is always a bit of a pain (most testing tools require site to be live), although if running from localhost you could possibly use something like https://ngrok.com/ to temporarily expose to public web, or if you want access to a spare firebase platform to test deployments too I think we probably have a few lying around! 

I think server-side rendering is definitely the way to go here (with an unironic solution to dynamically create the static pages). Although if you did decide rather you'd want the client-side code to update meta tags and pass back to bots you could use something like [react-helmet](https://github.com/nfl/react-helmet) (or vanilla js) to update meta tags and then a custom API endpoint + [rendertron](https://github.com/GoogleChrome/rendertron) (or just puppeteer/playwright) to intercept bot requests, generate dynamic page and serialize back to static html.

If we really wanted to get fancy google has additional content types that you can try to align to (although feel like their howto might be harder to match, perhaps easier something like article)... but that could always be a future optimisation also.
https://developers.google.com/search/docs/advanced/structured-data/search-gallery
https://developers.google.com/search/docs/advanced/structured-data

As for the sitemap, easy enough to create serverside as a one-off/cron function (that just queries all relevant database endpoints and converts to XML), although keeping it updated in an efficient way will probably need some extra aggregator functions

**Comment by thisislawatts** [comment]
Thanks for the insight @chrismclarke! I have been hacking on a version which uses NextJS from within serverless functions to render these pages. Hoping that there will be something to demo during next week's Dev meeting 🤞

It is struggling to consume the components from the project root which is what has me raising PRs picking at the monorepo setup.

**Comment by chrismclarke** [comment]
I don't think there's a single corner of the project that wouldn't benefit from some additional housekeeping. Definitely happy to use these types of issues as motivation and guidance for ways we can keep pushing the overall codebase forward at the same time.

**Comment by davehakkens** [comment]
We are using prerender.io for now.
Will create an issue in the future to implement it better in the platform using SSR
But this is solved for now
