### ISSUE TITLE
Improving SEO #2 - Metatags 

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1419]
### Description
When sharing a link from the Community Platform the preview is not related to the content on the page. It shows a default text+image. Ideally, this represents the content. This is mainly important for the how-to's, since they all have a dynamic image + title + desciption

### Page related

- [How-to](https://dev.onearmy.world/how-to) 
- Already brought up in an older issue before https://github.com/ONEARMY/community-platform/issues/961
- Useful tool to [preview Metatags](https://metatags.io/)

### Mockup
![seo meta](https://user-images.githubusercontent.com/13672737/151660745-aeada644-133a-4ea9-a86a-f130dfea43e7.jpg)

![seo meta_01](https://user-images.githubusercontent.com/13672737/151660748-736ed189-b997-45cc-a318-a6878686557e.jpg)

**Comment by thisislawatts** [comment]
This would likely be resolved as part of #1418
