### ISSUE TITLE
[feature request] Subscribe to Research pieces

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#1438]
**Is your feature request related to a problem? Please describe.**

Research articles are intended to be an ongoing collection of updates around a single theme. The research themes will be documented during the process and will unfold over weeks, months and years. 

Ideally people are able to engage with the research process at an early stage and follow it's progress. 

**Describe the solution you'd like**

The option to subscribe to a Research post so that users could receive notifications as updates are made available. This could be done with one or both of the following options:

 * Platform notifications: we recently introduced the ability for Users to receive notifications around Useful Votes/Comments. 
* RSS feeds. This mechanism would allow readers to integrate it into their own workflow. The technology has fallen into disuse over the last few years due to gaps in the underlying technology which make it hard to monetise. Luckily that is not a metric which drives our decision making.

**Comment by davehakkens** [comment]
that sounds nice! 
Mainly see potential for integrating with notifications.- Do people still use RRS feed?  🤔

**Comment by davehakkens** [comment]
Something like this @thisislawatts?
![subscribe to research](https://user-images.githubusercontent.com/13672737/159466449-21cf80e7-e165-4d5c-854f-e8056dfb2531.jpg)
