### ISSUE TITLE
[bug] Country flag doesnt change or shows on older comments 

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1469]
**Describe the bug**
It seems that if a user changes or adds their location in the profile it doesnt update their flag on older comments.

**To Reproduce**

1. Go to how-to
2. Leave a comment
3. Change location
4. Check the comment
5. Leave a new comment to see the difference

**Expected behavior**
Ideally, this is in sync across the entire platform. Change your location (flag) > see the change everywhere.
in howto, research, comments etc.
(This functionaity does seem to work in user profiles. Change location and the flag changes there)

**Screenshots**
Same username, different location
<img width="878" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/153208310-50f3775e-cbb3-4eb1-a023-85f0c8fab4c5.png">

**Additional context:**

The Community Platform is built on top of [a document orientated database](https://firebase.google.com/docs/firestore#how_does_it_work) called FireStore. As a NoSQL data store it is not simple to perform join queries across multiple collections, for example Howto articles and Users. 

Existing behaviour:

1. We have the `User` entity, this is where a user can define their location, which we use to render a flag next to their username. 
1. We display the user name in multiple places across the site. Each query/read of a User document is considered a billable unit by Firebase.  
To reduce the number of billable operations we copy the location data into each of the following:
    1. Howto article
    1. Howto comment
    1. Research article
    1. Research comment
   
The implications of this approach are that each time a User changes their location we need to update the location data in each of the documents generated by that User.

The current implementation for syncing this content, is run as a [Cloud function triggered by changes in Firestore](https://firebase.google.com/docs/functions/firestore-events).
Code: https://github.com/ONEARMY/community-platform/blob/master/functions/src/userUpdates/index.ts#L16-L17

The drawbacks with the current approach are:
1. Each time we add the username location to a new place in our document store we need to extend our sync mechanism to ensure it stays up to date
1. The update method could fail and we have low visibility into this.
1. Duplicates the User model data structure in multiple places across the system. This means if we made a change to the User data structure we would have to remember to update; the sync mechanism, all existing documents and UI logic.

**Comment by chrismclarke** [comment]
I think short term the best we can probably do is a small fix and update the function mentioned above to also include the howto and research comments and any other places missing.

For anything _better_, we would probably either want a database that allows more automated updating/references, server-side-rendering, a summary aggregation of user flags (limited to those who have published content), or some novel use of cloud functions to return flags via an endpoint linked to the user's name. All of these would be a lot of extra work and take a long time to fix the immediate issue, so I think probably we should start with a simple fix first and decide where to go from there.

**Comment by eliasvelardezft** [comment]
hi! I'll try to fix this bug

**Comment by davehakkens** [comment]
hey @eliasvelardezft are you still good to take this one on, need any help?
Also send a message to you here https://github.com/ONEARMY/community-platform/pull/1681 but not sure if you get notifications on closed PR.

**Comment by eliasvelardezft** [comment]
@davehakkens hi!! Sorry for the late reply, I've been really really busy and haven't got the time to work on the bug. I started reading through the code when I said I would fix it and I couldn't easily find the solution and then I simply couldn't work on it. I'll try to solve it this weekend, if I can't I'll ask for help haha.
As for the bounty you're correct, I hadn't seen the message. As I said before in the issue comments, I don't want the bounty! I really like onearmy's projects (specially project kamp) so I'd like to contribute for free

**Comment by danitrod** [comment]
So as discussed on Slack, the current comments structure doesn't allow for queries such as "all comments for which the userId is X", which prevents us to update comments for an updated user (unless we query for all howto's and manually filter, which is inefficient).

The proposed solution is to add to the user info an array of all the howto (and research) id's where they commented. We still have to discuss how to apply this modification to every existing user. What I'm thinking is creating a one-time running function to update all the users. I'll be happy to work on this @eliasvelardezft if you're not able to
