### ISSUE TITLE
Improve Error page "report feedback"

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1478]
### Description

Every now and then an error occurs and you end up on the "report feedback" page. This page is very basic and not very useful 
<img width="628" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/154355165-0b708803-d29d-48e4-9bf3-01c5a49ef021.png">

### Suggestions
- Minimum: Link the `Report Feedback` to our Discord (https://discord.com/invite/SSBrzeR)  so people can send us feedback
- Optional: If you are excited we are open for a better designed error page.

**Comment by asheerrizvi** [comment]
I can take this up if we can have it designed by someone 😆

**Comment by davehakkens** [comment]
You could start by changing the text to:

-----
Woops. We got a little error, please [refresh the page](refreshpage.com) or send us a mail to improve our software platform@onearmy.earth
-----

**Comment by davehakkens** [comment]
Its improved!
