### ISSUE TITLE
Make simplified profile default

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1506]
**Is your feature request related to a problem? Please describe.**
We just released a simplified profile in #1267 this is used for `members. `
The extended (original) profile is used by `Spaces`. 
However by default, the extended profile is still used. 
This should be changed to the simplified layout. 

**Describe the solution you'd like**
If a user signs up and does not choose a profile type `member`, `space` etc. the default layout should be the simplified profile.

![default_profile](https://user-images.githubusercontent.com/13672737/155536144-b76a5258-34f8-4b75-87eb-90317f61d298.jpg)

**Comment by Kiebert** [comment]
Hello @davehakkens.
This was an easy fix. No need for the bounty.
I will create a pull request.

**Comment by Kiebert** [comment]
Oops. Not an easy fix. The Cypress tests fails... I will have an attempt on fixing this...

**Comment by Kiebert** [comment]
Added a fix to pass the Cypress test.

**Comment by Kiebert** [comment]
Main outcome now according to this communication flow:
https://github.com/ONEARMY/community-platform/pull/1961

"When users signup and didn't select a profiletype yet (not space or member), they got the layout of the 'SpaceProfile'. But it should show the 'MemberProfile'"
