### ISSUE TITLE
Admin Panel: Create routes & navigation

### ISSUE THREAD

**Issue by franknoirot** [ONEARMY/community-platform#1507]
## Description
Part of the larger effort to create an Admin Panel to allow admin users to manage content from within the platform itself. Overarching issue to come.

Create the protected routes within the `/admin` section of the site, a secondary navigation bar, and a primary menu item to reach the `/admin` page.

Acceptance Criteria Checklist:
- [x] Users with the `admin` user role can access a new Admin menu item within the user menu.
- [x] A new `/admin` directory that is protected to only allow users with the `admin` role to access it. Other users can be redirected to the home page.
- [x] Pages for each of the main content types to be managed within the Admin Panel, in addition to an Approvals page. Note that for now these pages can just have an H1 with their page title as a placeholder:
  - [x] Approvals: `/admin`
  - [x] Browse Users: `/admin/users`
  - [ ] Edit User: `/admin/users/[id]`
  - [x] Browse Map Pins: `/admin/map-pins`
  - [x] Browse Tags: `/admin/tags`
  - [x] Browse How To's: `/admin/how-tos`
  - [ ] Edit How To's: `/admin/how-tos/[id]`
  - [x] Browse Research: `/admin/research`
  - [ ] Edit Research: `/admin/research/[id]`
- [x] There is a secondary nav that appears on any of the pages above.
- [x] The current subdirectory/page is highlighted within the secondary nav

 ## Related Pages
Related to all other pages within the larger Admin Panel effort (overarching issue to come).

## Mockups
[Visit the Figma space](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/?node-id=10%3A74) where the mockups are hosted to fully inspect them. Comments and questions about them can be added by pressing C and clicking where you want to pin a discussion, tag @franknoirot or @davehakkens within.

Here are screenshots of the 2 relevant desktop designs as of 28/02/22:

1. A view of the primary nav expanded, showing where the Admin menu link should be included if a user has the Admin role.
![Pending Approvals - Top Nav Menu Expanded](https://user-images.githubusercontent.com/23481541/156103700-cf814147-a6af-4032-b27d-f73afbb4c046.jpg)

2. The browse view of all Users, which shows the secondary navigation with the Users link highlighted as the current page is within that directory.
![Users Browse](https://user-images.githubusercontent.com/23481541/156103787-fe5ee5e3-8ae1-4b07-854a-fe9e50953d95.jpg)

**Comment by chrismclarke** [comment]
Thanks for the great mockups @franknoirot - I've started the process of scaffolding out the main pages in #1510 and will start trying to build out functionality over the next couple weeks

**Comment by franknoirot** [comment]
Happy to help @chrismclarke, way to go powering through so much of this over the last couple days. I'll be working to scaffold out the remaining designs in the coming days (Map Pins and Tags tonight), and I'll have an overarching Admin Panel issue to group the sub-issues within soon. Love that it tracks the completed tasks on GH Issues, like a more intuitive form of Jira Stories and Epics.
