### ISSUE TITLE
Admin Panel: Create edit User page

### ISSUE THREAD

**Issue by franknoirot** [ONEARMY/community-platform#1509]
## Description
Part of the larger effort to create an Admin Panel to allow admin users to manage content from within the platform itself. Overarching issue to come.

Fill the `/admin/users/[id]` page's content and functionality, and style it to match the designs. The design of this page largely matches the normal User Settings page available to non-admins, so lessons can be learned from and code potentially reused.

Acceptance Criteria Checklist:
- [ ] View shows live view of the current user (based on the user ID in the URL) from Firebase.
- [ ] Back to Users CTA links back to the `/admin/users` browse view.
- [ ] Clicking the Save Profile button runs a mutation in Firebase to update all the edited fields on the current User.
- [ ] The Save Profile button is sticky, staying visible as the user scrolls down the page.
- [ ] A page heading block is populated with "Edit User { username }", with the current user's username, with the user's ID displayed lighter to the right.
- [ ] Required fields have an asterisk shown after their label (*) and the profile can not be saved when the values are empty.
- [ ] Admin users can edit each of the following fields on a user:
  - [ ] Type: reuse from user settings page
  - [ ] Email: email
  - [ ] Display Name: text
  - [ ] Status: dropdown with pending, approved, or rejected
  - [ ] Roles: text with info box beneath
  - [ ] Description: textarea
  - [ ] Cover Image: reuse from setting page
  - [ ] Links: reuse from setting page
- [ ] Map Pin settings are displayed in their own section like on the individual user settings page and can be edited in the same manner.
- [ ] User can be deleted by clicking the Delete User button that appears at the bottom of the page twice.
- [ ] Clicking the Delete User button once activates a confirmation state and requires a second click before deletion (see designs below).
- [ ] After deletion, admin is redirected to the `/admin/users` page with a notification that the user has been deleted. The user's edit page should no longer be accessible.

 ## Related Pages
Related to all other pages within the larger Admin Panel effort (overarching issue to come), including #1507 and #1508.

## Mockups
[Visit the Figma space](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/?node-id=10%3A74) where the mockups are hosted to fully inspect them. Comments and questions about them can be added by pressing C and clicking where you want to pin a discussion, tag @franknoirot or @davehakkens within.

Here are the 2 relevant desktop designs as of 28/02/22. 

1. The full edit User page example:
![Users Edit](https://user-images.githubusercontent.com/23481541/156105952-22eff1f0-908b-446f-bd11-5ed235b54824.jpg)

2. Snippet showing the confirmation state of the Delete User button that appears after clicking it the first time:
![Users Confirm Deletion](https://user-images.githubusercontent.com/23481541/156106039-e297c6d1-3d53-4f54-98bd-c072fd6e04cb.jpg)

### Build Recommendations
* If possible, try to reuse form and settings field components wherever possible. Keep in mind that the labels have been reworded to make sense for Admin users.

**Comment by franknoirot** [comment]
One thing I'm unsure of is what triggers a welcome email and everything to approved users? Is that handled in Firebase or does logic need to be added to the frontend to handle sending that?

**Comment by davehakkens** [comment]
> One thing I'm unsure of is what triggers a welcome email and everything to approved users? Is that handled in Firebase or does logic need to be added to the frontend to handle sending that?

Welcome mail for users comes from Firebase auth system. Cant change much about that process.
We use a webhook that sends a notification to our Slack channel with each new `map-pin` and `how-to`. 
This channel in slack shows them #pp-community-notifications.
It works for now in our situation. But in the future, a mail notification would probably be better.
