### ISSUE TITLE
[devops] Preview site fixes

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1512]
There are a few issues when trying to use the preview site, collated roughly as tasks

- [ ] Add option to toggle between dev/staging sites
- [ ] Add support for test admin/beta-tester users in preview site (either seeding users in same way as emulator or custom overrides - some of this was started in #1218 but left incomplete)
- [ ] Fix staging site reset scripts
- [ ] Integrate to circleCI pipeline

**Comment by evakill** [comment]
closing this as it seems like a stale issue
