### ISSUE TITLE
Add removable location dropdown

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1541]
### Description
We need a location field with country dropdown for members that don't add themselves to the map. This is mainly used for instances where the map is disabled.

1. By default it should display the dropdown in the info panel
2. If a user  will`add a map pin` the default dropdown disappears and the location is taken from the map

### Page related

Will be used in : 

- [User settings](https://community.preciousplastic.com/settings)

### Mockup
![add location](https://user-images.githubusercontent.com/13672737/158194044-f9249525-24d0-492e-9652-5464299cf3e2.jpg)

**Comment by ryanwbass** [comment]
@danitrod Are you still working on this? I just found this project, got setup, and am looking for something to work on. If so no worries I will keep looking around.

**Comment by danitrod** [comment]
Hey @ryanwbass ! Yes, I am actually in the final adjustments already, just paused for a long time due to stuff happening in my job. I'll hopefully be submitting a PR next week. If things go wrong and I can't work on it anymore I'll let you know so you can take it. Meanwhile, I think there are some other issues you could go ahead and pickup, such as https://github.com/ONEARMY/community-platform/issues/1611, or maybe @davehakkens can point you to another one. If you need any help on the setup let me know!

**Comment by davehakkens** [comment]
Hi @danitrod. Just doing my thing here and checking in how its going 🙃
Need help?

**Comment by danitrod** [comment]
Hey @davehakkens! I know I've been off recently and not delivering this issue for a while, I'm sorry for that 🙁

I did almost finish it though (you can check on the progress [here](https://github.com/danitrod/community-platform/tree/1541-removable-location-dropdown)), just needed some final adjustments BUT I am switching jobs right now and lost access to the machine I used to code. A new one was already ordered for my new job but they say it will probably take a few weeks before it arrives. And I don't know if I'll have a temporary one. So as there are other people willing to work on this issue who can probably finish it faster, I can let this one go and take another one later. For whoever's grabbing it, feel free to use the code from [my fork](https://github.com/danitrod/community-platform/tree/1541-removable-location-dropdown) to speed up.

**Comment by danitrod** [comment]
^ FYI @ryanwbass

**Comment by davehakkens** [comment]
No worries @danitrod. thanks for letting me know.
I'll try to find a new owner for this one!

**Comment by eliasvelardezft** [comment]
Hi! I just wanted to start contributing and found this issue. @danitrod said he almost had it so I figured I could finish what they had started, but their code is complete and functioning correctly. Should I create a pull request with their changes if they can't? Obviously danitrod should get the bounty.

**Comment by davehakkens** [comment]
Thanks for picking it up @eliasvelardezft! Yeh add a PR if you think its ready so we can test it! :)

**Comment by danitrod** [comment]
Actually I'm pretty sure there was an edge case where something wouldn't work out with my code, I don't quite remember it right now though 🫢
I think it's worth it to double check every possible behaviour (changing user's location, using pins and deleting pins), pretty sure some bug will happen xD
