### ISSUE TITLE
[bug] Guideline link when creating a Research topic is broken

### ISSUE THREAD

**Issue by elinnert** [ONEARMY/community-platform#1551]
**Describe the bug**
Testing on PK instance. If I'm creating a new research topic, I see the "How does it work?" side menu and an option to "Read our guidelines". If I click that guideline link it goes to a page not found

**To Reproduce**

1. Go to: https://community.projectkamp.com/research/create
2. Click on "our guidelines" link
3. redirects to Page not found

**Expected behavior**
Should redirect to correct page

**Screenshots**
<img width="560" alt="Screenshot 2022-03-16 at 7 39 01 PM" src="https://user-images.githubusercontent.com/4203842/159039358-625532dc-eb5b-4db1-b667-2b0b6d4e4042.png">

**Additional context**
Brought up in slack by one of the beta testers :)
https://onearmy.slack.com/archives/C036EANE7RQ/p1647430833821139

**Comment by davehakkens** [comment]
Added some guideliness (draft)
https://community.projectkamp.com/academy/guides/research
