### ISSUE TITLE
[bug] Change member icon PK instance

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1571]
**Describe the bug**
On the [Project Kamp instance ](https://community.projectkamp.com/u/projectkamp) profiles still have the Precious Plastic Icon. This should be changed to Project Kamp.

Badge can be found[ here in the repository](https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/project-kamp/badge.svg)

**To Reproduce**
See the icon on the [Member profile](https://community.projectkamp.com/u/projectkamp)

**Expected behavior**
![change icon](https://user-images.githubusercontent.com/13672737/160298115-1058dee5-2752-41c3-a162-243f8c8654bb.jpg)

**Comment by hunjunChoi** [comment]
.take

**Comment by davehakkens** [comment]
.go

**Comment by hunjunChoi** [comment]
Thanks, will keep you posted with the updates!

**Comment by hunjunChoi** [comment]
Hi @davehakkens, a group of us worked together and corrected a few files so that the badges would render correctly on their respective page. 
Now in testing, comes questions. After running the `yarn test` and getting the `cypress` screen up, what are the files that need to be checked?

**Comment by davehakkens** [comment]
Just double checking, have you seen our documentation about testing?
https://onearmy.github.io/community-platform/Testing/end-to-end

**Comment by hunjunChoi** [comment]
Yes! 
However, `yarn test` won't locate the `cypress` installing via `yarn workspace oa-cypress install`, so I used `yarn add cypress --dev` instead and got the `cypress` working

**Comment by hunjunChoi** [comment]
Have the test running right now, it's done by a simple button click at the top right corner of `cypress` screen
