### ISSUE TITLE
Add banner for users with incomplete profile

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1588]
### Description

We want a notification bar for users that **have not** filled in any profile information. ([example](https://community.preciousplastic.com/u/argentech), [example](https://community.preciousplastic.com/u/joel-tovar), [example](https://community.preciousplastic.com/u/aireverde), [example](https://community.preciousplastic.com/u/william-kadima-sakwah))
Specially with comments enabled more users will sign up. However having incomplete profiles is not good for the platform and doesn't show that nice little flag. This would remind people to fill in their information

### Behaviour
If no profile details filled in -> show banner
If profile is filled in -> remove banner

The entire red banner links to [profile page](https://dev.onearmy.world/settings)

### Page related

Will be shown in all pages

### Mockup
![Fill in Profile](https://user-images.githubusercontent.com/13672737/161614023-9c1f6e54-8329-40da-9a27-a97a2599f698.jpg)

**Comment by jojudre** [comment]
work on this
