### ISSUE TITLE
[feature request] Change Avatar upload for member profile

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1589]
### Description

`Member profiles` use a smaller image than `space profiles`.
However the current upload system works the same for both. It saves full size images.
Great for space profiles, not for members
This result into unnecessary large avatar images for members and strange cropping
Ideally the `member profiles` use an avatar upload system that saves max 400px x 400px images (square)

### Problem
![membervsspace](https://user-images.githubusercontent.com/13672737/161615932-ededd896-8f51-4afe-8143-f8b68f7f20d3.jpg)

Will be used in :

- [Member profiles](https://community.preciousplastic.com/settings)

**Comment by jojudre** [comment]
@davehakkens want to grab this issue, can i use react-image-crop, it's lightweight library to allow users crop images?

**Comment by thisislawatts** [comment]
@davehakkens I think it is worth clarifying the exact requirements here, which of the following do we want?

1. User type specific (Member _or_ Workspace) upload requirements.
2. User managed cropping

At the moment the same image upload mechanism is used for different user types, User or Workspace, whereas we need different behaviour.

**Comment by davehakkens** [comment]
1. This PR is focussed on `member` profiles. 
Since there will be much more of those than `workspace` (space) profiles
2. The cropping itself is somewhat flexible. The main goal is that the output is always square and max 400x400px.
Cropping in browser could be a very nice feature, if this gets to complex we could also ask for it when a user uploads. For instance. "Upload square image of max 400x400px" Less user friendly but perhaps an easier start?

**Comment by thisislawatts** [comment]
Cool, so I wouldn't necessarily build out an in browser editing/cropping for users straight away but it's definitely a nice feature to have. There are probably other opportunities to introduce elsewhere across the platform.

**Comment by davehakkens** [comment]
ok thanks. is that 👆 clear enough for you to move forward @jojudre?

**Comment by Justy116** [comment]
Hi, can you assign me this issues?

**Comment by iSCJT** [comment]
@jojudre are you still working on this?  I'm happy to add the cropping if you're tied up on other things.

**Comment by orditeck** [comment]
I made a tentative first PR/contribution ➡️ https://github.com/ONEARMY/community-platform/pull/2242

**Comment by mariojsnunes** [comment]
I'll work on this.
The approach I'll try is to do it automatically on a cloud function using this extension.
https://extensions.dev/extensions/firebase/storage-resize-images
Might have to create a bucket specific to user images to avoid unnecessary triggers.

**Comment by benfurber** [comment]
@thisislawatts So should this issue be closed then?
