### ISSUE TITLE
Add categories for How-to

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1590]
### Description

We will introduce categories to the how-to's.
This is needed to better organise them in specific areas.

- Unlike tags a howto's can only be in one category. 
- Categories are moderated by the community managers.
- Categories can be removed and added like the tags.

### Categories on release
- Products
- Moulds
- Machines 
- Guides
- Hacks

### Notes

Categories need to be released to `beta-testers` so the Precious Plastic community managers can organise them first

### Page related

Will be used in :

- [How-to
](https://community.preciousplastic.com/how-to)

### Mockup

Dropdown menu on the homepage
![category dropdown](https://user-images.githubusercontent.com/13672737/161617143-17efb870-381c-470e-a06d-94e0317c9886.jpg)

Select category when submitting a how-to
![Categories_submit](https://user-images.githubusercontent.com/13672737/161617235-153f61aa-d942-42ba-8e9c-6ac99110b947.jpg)

**Comment by jojudre** [comment]
working on this)

**Comment by davehakkens** [comment]
Nice! Not sure if you are aware. We also have a very basic admin panel where you can add tags here:
https://dev.onearmy.world/admin/tags
Perhaps a good place to add/remove the ability to add categories there? 

I've made `dreamdaura` admin so you should be able to see it now..
<img width="1316" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/162402036-0df37054-d6bb-422e-be7f-5645b060caa7.png">

**Comment by jojudre** [comment]
@dave yee, i wanted to ask about this, thanks

**Comment by jojudre** [comment]
@dave hmm admin panel is unavailable for dreamdaura (

**Comment by davehakkens** [comment]
try again @jojudre

**Comment by davehakkens** [comment]
thanks for asking!
But we don't need that for now. We can add later :)
Main thing we need now is the ability to filter on the overview page
