### ISSUE TITLE
[bug] Add CTA to log in to Research Comments section for logged-out users

### ISSUE THREAD

**Issue by franknoirot** [ONEARMY/community-platform#1591]
**Describe the bug**
This was a miss in my designs of the [Research Comments in Figma](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform?node-id=10%3A72) that was caught by @davehakkens.

The How-To comments on pages like [this one on Precious Plastic](https://community.preciousplastic.com/how-to/easily-hands-free-connect-moulds-to-the-injector) have a section that appears if the user is not signed in, which looks like a fake comment prompt (which is not editable as a text field) that contains a link to log in. The Comment button is disabled and set to 50% opacity as well. We should add this section to the Research Comments component to not confuse users who are not logged in and want to comment.

**To Reproduce**

1. Visit https://community.projectkamp.com/research as a logged-out user
2. Locate a Research module with comments (unsure if there is one currently, the test with comments was deleted).
3. Note how there is no clear way to comment, or reminder that you can't comment until logging in.

**Expected behavior**
Using a modified version of the comment prompt to invite the user to log in.

**Screenshots**
Here is a [link to the full design of this page](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform?node-id=208%3A814), but this is a close-up of the element we want to add to the component:
<img width="523" alt="Screen Shot 2022-04-04 at 10 12 09 PM" src="https://user-images.githubusercontent.com/23481541/161666629-e8bcee11-fd3d-4a0b-ac4d-d08b32277262.png">

Here is what it looks like on [a Precious Plastic How-To](https://community.preciousplastic.com/how-to/easily-hands-free-connect-moulds-to-the-injector):
![image](https://user-images.githubusercontent.com/23481541/161666755-ff40248e-abfc-4830-9ea5-7b2bbd26fb86.png)

**Comment by jojudre** [comment]
assign to me please
