### ISSUE TITLE
[bug] Collecting Mobile (reponsive) weirdness

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1610]
**Describe the bug**
This issue is to gather all the incorrect mobile behaviour on the website. Throughout time we've build new componenets and refractored the site but don't always keep a good eye on mobile.
This thread is to gather all the pages to improve. 

**Users:** Screenshot and dump them here.
**Developers:** Feel free to adress them and make a PR

**Comment by davehakkens** [comment]
**Page:** User(space) [Profile](https://community.preciousplastic.com/u/precious-plastic)
**To fix:** The icons is shown weirdly on top of the header image
<img width="560" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/163668930-57e5ccec-6994-47b9-9d6f-e2116d9f4090.png">

**Comment by davehakkens** [comment]
**Page:** **Single How to**
**To fix:** Header image should have a max-height
![IMG_3383](https://user-images.githubusercontent.com/13672737/163669265-33ceae35-8523-402f-9d87-94db7338da3d.PNG)

**Comment by davehakkens** [comment]
**Page:** [Single how-to](https://community.preciousplastic.com/how-to/easily-hands-free-connect-moulds-to-the-injector)
**To fix:** Images in steps should be reduced in height (or even show in normal ratio)
![IMG_3384](https://user-images.githubusercontent.com/13672737/163669285-aa99f1e7-517e-47f6-a3f4-f88540d02577.PNG)

**Comment by davehakkens** [comment]
**Page:**[Research](https://community.projectkamp.com/research/can-we-make-an-elevation-height-map-of-the-land) + [Howto](https://community.preciousplastic.com/how-to/easily-hands-free-connect-moulds-to-the-injector)
**To fix:** Comment components need to be made responsive. on both Research and How-to

![IMG_3385](https://user-images.githubusercontent.com/13672737/163669328-42925e3e-89e5-4232-9841-b7bc7b59e054.PNG) 
![IMG_3389](https://user-images.githubusercontent.com/13672737/163669401-7e54bf79-1ea5-4b91-a1d7-d85c8ee0dbf7.PNG)

**Comment by davehakkens** [comment]
**Page:** [Member profiles](https://community.preciousplastic.com/u/mattia)
To fix: Member profiles are not made responsive. Text should be below image
![IMG_3386](https://user-images.githubusercontent.com/13672737/163669451-f8f8b190-f209-463a-90df-c48e69b83912.PNG)

**Comment by ttddee** [comment]
**Page**: Intro
**To fix:** Table does not scroll horizontally and gets cut off in portrait mode. There is no way to see the right side of it. Tested on Android with Brave and Chrome

![Screenshot_20220416_111221_com brave browser](https://user-images.githubusercontent.com/16922381/163671718-bd964779-eace-4d77-815a-f61014d221fb.jpg)

**Comment by hunjunChoi** [comment]
Hi @davehakkens, I would like to work on [one of the issues](https://github.com/ONEARMY/community-platform/issues/1610#issuecomment-1100613200).
Also, @amandaqiu1, a member of my team, would like to work on an [issue](https://github.com/ONEARMY/community-platform/issues/1610#issuecomment-1100617255)

**Comment by davehakkens** [comment]
Sounds good @hunjunChoi and @amandaqiu1! Would you be good to freestyle the improvements or need a design?

**Comment by amandaqiu1** [comment]
@davehakkens I'm good to freestyle the improvements for now. I'll let you know if I encounter any design issues.

**Comment by hunjunChoi** [comment]
Hi, @davehakkens. Sorry for arousing confusion from switching around issues. Returned to work on one of the issues as #1619 is resolved.

**Comment by davehakkens** [comment]
doing it in separated issues
