### ISSUE TITLE
Add Download count to how-to

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1617]
## Component infos

We want to add a download counter for file download in the how-to. 
So users can track how often their content gets downloaded.

### Build suggestions
- It will be build using the aggregations.
- Ideally there is some sort of logic that only counts a download per day. ( To prevent it being mis-used clicking 200 times in a row)

### Page related

Will be used in :
[- How-to ](https://community.preciousplastic.com/how-to/beads-mould---a-lot-of-them)(with attachment)

### Mockup

![downloads_01](https://user-images.githubusercontent.com/13672737/165150285-aa0c4904-9506-4407-b4ab-79d7b1d71ff6.jpg)

**Comment by Zodraccir** [comment]
Hi, I found this project, and interested me, I would like to take this task in order to try to contribute, I've just configured the environment and I'm trying to figure out how to do. For any question can I ask to you?

**Comment by davehakkens** [comment]
awesome! yeh go for it! Post questions here if you have any :)

**Comment by davehakkens** [comment]
hi @Zodraccir how is this going, need any help?

**Comment by AlfonsoGhislieri** [comment]
Hello, I'd start contributing to the project and would like to take this task !

**Comment by davehakkens** [comment]
> Hello, I'd love to start contributing to the project and would like to take this task!

Sounds great! This would be a very useful one. Let me know if you need help

**Comment by AlfonsoGhislieri** [comment]
Thanks Dave, quick question regarding testing, I couldn't find anything concrete on the guidelines. Do you want this feature to be fully tested/should all features be fully tested?

**Comment by davehakkens** [comment]
> Thanks Dave, quick question regarding testing, I couldn't find anything concrete on the guidelines. Do you want this feature to be fully tested/should all features be fully tested?

Just double checking, have you seen our documentation on testing? https://onearmy.github.io/community-platform/Testing/end-to-end

**Comment by AlfonsoGhislieri** [comment]
Just read over it now and so I'm guessing no unit testing for me (yay!), if you do want me to implement some tests do let me know!

**Comment by thisislawatts** [comment]
Closed via https://github.com/ONEARMY/community-platform/pull/1687
