### ISSUE TITLE
Links open in new tab?

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1619]
Would be really great to make links target="_blank" to open in new window.

 
<img width="1241" alt="target blank" src="https://user-images.githubusercontent.com/17761877/165329536-9d81ba05-3496-48e0-bf9a-35c756012a51.png">

**Comment by davehakkens** [comment]
This would be good to include for all links posted in textfields in [Research Module](https://dev.onearmy.world/research) and [How-to's](https://dev.onearmy.world/how-to).
Let me know if anyone wants to take it on

**Comment by hunjunChoi** [comment]
Hello @davehakkens, this could be a friendly issue that a beginner might solve. May I take on the issue?

**Comment by davehakkens** [comment]
yeh sure go for it. But you also still have [this one](https://github.com/ONEARMY/community-platform/issues/1610) open right @hunjunChoi ?

**Comment by thisislawatts** [comment]
Hey @hunjunChoi, I have done exactly this inside a new PR adding Linkify to our comments.
You can see the specific change here:
https://github.com/ONEARMY/community-platform/pull/1639/files#diff-7aab05b5c350e50591b3ebe276a7734835df27cdd7b6e1f8f607576f2023cbddR76

**Comment by hunjunChoi** [comment]
@thisislawatts Understood

**Comment by davehakkens** [comment]
I'm not sure it's [resolved](https://github.com/ONEARMY/community-platform/issues/1610#issuecomment-1115560798) @hunjunChoi. I think Luke implemented this behaviour only in the comments but not in the actual content. Is that correct @thisislawatts ?

**Comment by thisislawatts** [comment]
Correct @davehakkens, I implemented this festure only for content within comments

**Comment by mattia-io** [comment]
I feel like also how-tos, profiles and cp as default would benefit from this. When users add links they are usually outgoing which would normally be nice to have on a new window. My 2cents.
