### ISSUE TITLE
Increase character limit Research comment

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1626]
### Description

We want to increase the character limit for comments to 1000.  (instead of current 400)
Main reason for increasing is that people post double comments and @jojudre made a nice "show more" button. 
So need anymore to keep it short :)
This is mainly needed for the research module. 

### Page related

Will be used in :

- [Research module](https://community.projectkamp.com/research)

### Mockup

<img width="826" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/165624104-9abd7da6-b5cc-411c-900d-2d57fcdd079e.png">

**Comment by jojudre** [comment]
@davehakkens only for research module? or for howto too ?

**Comment by davehakkens** [comment]
It would be nice to also have it there.
But I think the "show more" button is not implemented in the how-to comments. (which means long comments!)

So would be cool if we can add "show more" button + increase character limit together to how-to.
If it's to big we can also raise a new issue for it.
