### ISSUE TITLE
Weird email UI/UX

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1651]
Hello,

I am not sure I understand the intended behavior for this piece of UI found in users profiles. Feels a bit confusing to have 3 email fields. Is that how it is meant to be? 

<img width="321" alt="Screenshot 2022-05-03 at 16 47 08" src="https://user-images.githubusercontent.com/17761877/166476723-4f38347e-d491-4d6a-a2c6-0404405eb4d4.png">

**Comment by davehakkens** [comment]
this button is for admins only. Used to contact people through their sign up information.
Not available for other users.
