### ISSUE TITLE
[feature request] Notification lightbulb behaviour

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1654]
Hey team,

I am a little confused with the behaviour of the notification icon. Currently icon only turn grey when notifications are cleared.
<img width="212" alt="Screenshot 2022-05-06 at 16 08 43" src="https://user-images.githubusercontent.com/17761877/167149892-8b9a8ee9-6560-461a-855e-d6146bfd576c.png">

Currently:
- When icon is yellow, user clicks on the icon and sees notifications
- Icon stays yellow until notifications are cleared
- As a returning user you might be tricked into thinking you have new notifications (as icon is yellow) but in fact no new notification is there. 

Proposed behavior:
- Default icon is grey
- New notification  > icon becomes yellow
- User clicks on icon and sees notification
- Icon turn grey
- Icon stays grey until new notification
- If users clears notifications, notifications get cleared, icon stays grey

Hope it makes sense

**Comment by davehakkens** [comment]
yeh makes sense 
Soo what if you have two or more notifications popping up and you click only one of them. 
What would happen in that case?
1. Icon becomes Grey
2. Icon stays Yellow
3. Only the one notification message you clicked changes

**Comment by mattia-io** [comment]
1. Icon becomes Grey

Yellow icon signals there are new notification. Users might click on them or not but for the icon shouldn't matter I believe.

**Comment by davehakkens** [comment]
ok, so. Everytime you click a yellow icon it becomes grey, until a new notification comes in. Then it becomes yellow again?

**Comment by thisislawatts** [comment]
It may be worth considering an alternative visual approach to communicate the various states.

The contrast difference between the Gray and Yellow is not very apparent, especially if you:

* Have any issues distinguishing colours
* Are not paying attention
* Unfamiliar with the site

**Comment by mattia-io** [comment]
Sorry for late response, had a difficult couple of weeks. 
Shame conversation was closed (and deleted? can't find previous messages 😭)

Wanted to thank whoever posted the different notification icon behaviors (can't remember if it was @thisislawatts or @tedspare). Indeed there are many different options for this. 

My main worry is that users by seeing the notification icon always yellow they'll stop noticing it or looking at it (just like when you have 1589 unread emails on gmail you stop checking that number as it stops having semantic meaning). 

If @davehakkens wants this issue closed, might be smart to track clicks on notification icon + "Clear Notification" button this way, while @davehakkens decides it's time to work on this again, we can gather useful data to inform future design thinking and decision making.

**Comment by davehakkens** [comment]
You can still find the previous conversation back [here](https://github.com/ONEARMY/community-platform/pull/1688)  @mattia-io Only the PR is closed.

Also for anyone else following up on this issue. Might be good to have a look at that PR https://github.com/ONEARMY/community-platform/pull/1688 which shows the problem and the reason why its postponed for now

**Comment by mattia-io** [comment]
Oh, of course 🤦‍♀️
