### ISSUE TITLE
[feature request] Connect CP account with Discord

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1697]
This is a feature request/exploration. 

I've seen on multiple website the ability to connect 3rd party accounts to Discord accounts. Patreon of course is a good example. But also other smaller websites seems to feature this option. 

In our case would be:
Community Platform user connects their account with their Discord account.

How easy would be to develop something like this? 

I have not fully thought this through but I think moving forward there might be multiple scenarios where this comes in handy:
- Discord badges for different user types on the map 
- Unlocks specific channels for CP users
- Allow voting for people on the map/cp
- Couldn't think of any other yet 😅

Just a thought let me know if anyone has ideas/opinions on this

**Comment by davehakkens** [comment]
Agree interesting to connect platforms more together. However I think the first question is less wheter its doable or how easy it is. 

But more understanding what features we would really need from this connection and how its intergrated with the rest. It easily gets way more complex with different platforms/discords people having individual profiles or represent a Space (group) etc.

**Comment by thisislawatts** [comment]
There is this well documented example of how to add support for logging in with a Discord account
https://github.com/luizkc/firebase-discord-oauth2-example

So from a technical perspective it looks quite straightforward. 

The limitation here is that each CP instance is entirely isolated from another. So a user would have to log in/authorise with each one separately.

**Comment by mattia-io** [comment]
Thanks @thisislawatts for finding relevant documentation. 

Indeed what you described could be an issue. 

I guess the main challenge would be that:
- A user has multiple CP accounts (PP, PK etc..) but one Discord account. 

A way to circumvent this is that each connection gives a different role:
- If a user connects from CP PK they'll get a "Prokect Kamp Community Member" role on Discord (or whatever we want to call the role)
- If a user connects from CP PP they'll get a "Precious Plastic Community Member" role on Discord
- If a user connects from CP PK and CP PP they'll get a "Prokect Kamp Community Member" and "Precious Plastic Member Community" role on Discord

But I guess the question comes down to why? Why would we want this? Is there any value to know on Discord who's on the CP? What are the present and future use cases?

**Comment by davehakkens** [comment]
closing this for now. If you want to continue the conversation let me know and i'll change it to a discussion
