### ISSUE TITLE
[devops] configure database access rules

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#17]
currently in 'test' mode so all read-write ops allowed. Will need to restrict once user auth system established

**Comment by chrismclarke** [comment]
Need to also configure storage access rules. Currently open to all for read,write.
(auth config:

service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}

)

**Comment by chrismclarke** [comment]
yes I think for early implementation we can pretty much have:
1. Everyone can read data from a list of collections specified (i.e. howtos, qandas etc.)
2. Only logged in people can create new db entries
3. Only the people who created a db entry can modify it (i.e. modify my how-to)

Later we will probably have more fine-grained control for admin at the army and sub-army level, but not worrying for now.

**Comment by iSCJT** [comment]
@thisislawatts I know you did some work on db permissions, do you consider them fit for purpose now?

**Comment by evakill** [comment]
closing as this seems stale, feel free to comment or reopen if this still needs to be addressed
