### ISSUE TITLE
Enable Digital events

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1706]
### Description

Digital events are becoming more popular in the community. (hello 2022) 
This issue would allow members to share them in the events page.
If the checkbox "digital" event is selected it should show the `Digital.png` icon on the frontend.

⭐️Bonus: Ideally we can add this:
If the checkbox digital is selected > the field `In which city is the event taking place?`  is hidden or not a mandatory input field anymore.

### Page related

Will be used in : [Events](https://community.preciousplastic.com/events)

### Notes
Be aware the input fields are rearranged to make it visually more logical to follow.

### Mockups

![even_digital_02](https://user-images.githubusercontent.com/13672737/171496783-0b479224-38a7-45ec-b467-404a17bea33c.jpg)
![event_digital](https://user-images.githubusercontent.com/13672737/171496794-c6586387-64fb-4e62-9d00-663ea1b239ee.jpg)

### Icon attached
![Digital](https://user-images.githubusercontent.com/13672737/171496819-8805d6d3-9356-4228-9107-f91ca7f36890.png)

**Comment by missalyss** [comment]
Hi! Can I take on this issue? I've got code running and more docs to read but noticed all the other 'Good first issue's were taken 😊

**Comment by thisislawatts** [comment]
Absolutely @missalyss ✨ I have assigned the issue to you. Please let me know if you've any further questions. 

Additional details to be aware of:

1. The _﻿﻿In which city is the event taking place?_ field, which is currently marked as required. I would expect this field to be optional or completely hidden. 
2. For visibility, I'm [working on a PR](https://github.com/ONEARMY/community-platform/pull/1701) at the moment which refactors all Input elements, hoping to merge that in the next day or two. But note you'll want to rebase after #1701 is merged.

**Comment by davehakkens** [comment]
hey @missalyss how is this going? Need any help or guidance?

**Comment by davehakkens** [comment]
Good to hear some of it is working @missalyss! Did you manage to follow [these steps ](https://onearmy.github.io/community-platform/)to run locally?

**Comment by missalyss** [comment]
Yep—I believe I just had errors I couldn’t identify so localhost was hanging. but I have it fixed now. The event form is submitting correctly, just some cleanup and extra tasks before the PR will be ready to put up. 😊

**Comment by davehakkens** [comment]
Nice! Looking forward to it 💪
