### ISSUE TITLE
[bug] add update to someone else's research module

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1711]
Hey team,

I just found what looks like a pretty critical bug. I was able to add an update to someone else's research topic. You can see the latest update below 👇 As far as I understood I should only be able to comment on updates not create new ones.
https://community.preciousplastic.com/research/make-open-source-arbor-press-injection-machine

I am a beta tester I believe (that could simply be the reason).

**Comment by davehakkens** [comment]
Yeh
You are `beta tester` and `admin`
`Beta tester `can start + edit their own research topics
`Admin` can start + edit everyones research topic
So it's probably that..

**Comment by mattia-io** [comment]
Ok. All good then.
