### ISSUE TITLE
[bug] Fixing Fashion Map shows wrong spaces

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1731]
**Describe the bug**
The map for Fixing Fashion isntance still shows the Precious Plastic spaces.
It should show the ones from Fixing Fashion
- Member
- Space

**Screenshots**
<img width="1185" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/172067387-485a85c6-97c9-4802-a40c-7ca09c8bbcdb.png">

**Comment by thisislawatts** [comment]
@davehakkens would this work?

![Screenshot 2022-06-11 at 18 29 58](https://user-images.githubusercontent.com/472589/173196545-4318fe6d-2c1b-4f15-8a60-1e95929dc3c7.jpg)

**Comment by davehakkens** [comment]
It works. But.
1. Ideally the want to get started icon is red (Fixing Fashion)
2. "Space" sounds a bit strange like that, but should be good enough to get going! 🔥
