### ISSUE TITLE
[bug] Change webhooks Fixing Fashion notifications

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1734]
**Describe the bug**
We use both Discord and Slack webhooks to send a notification when a:
1.  `new map pin is waiting to be approved `(Slack #pp-community-notifications) 
2.  `map pin is approved and made public` (Discord #activity-bot)
Ideally these webhooks are changed for Fixing Fashion to have its own notifications.

**Screenshots**
<img width="615" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/172165722-bfd8ef35-7f4f-491e-bcc9-92d7de0cae00.png">
<img width="686" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/172166014-748c07bb-a27b-41fa-b84d-d92df3f5a533.png">

**Comment by thisislawatts** [comment]
@davehakkens would it be possible to get the Webhook URL for the Discord channel you want these notifications sent through to? I am guessing that this would be #activity-bot.

Please send me the URL via DM

**Comment by thisislawatts** [comment]
The secrets which manage these are defined via the Firebase CLI, it is currently unclear what key=value and format should be used to store these credentials

**Comment by davehakkens** [comment]
seems to be working 💪
