### ISSUE TITLE
[feature request] Placing multiple pins on PP Map with one account only

### ISSUE THREAD

**Issue by DataWorm** [ONEARMY/community-platform#1745]
**Is your feature request related to a problem? Please describe.**
My PP group has currently a focus on building a workspace. Nevertheless we already act in some parts as a community point. And now we are also starting to setup some small collection points at different locations. We intend to slowly start registering pins on the PP Map for all these spaces. But apparently with one account/profile we can only specify one pin on the map, so only one location of only one type. I would assume that there are many workshops that also act as a collection point. But if one would only specify this place as a workspace, people that are just searching for collection points might not know that they could also bring their plastic to that workspace.

**Describe the solution you'd like**
Being able to specify multiple pins on the map of different types at different locations.

**Describe alternatives you've considered**
Currently the only solution for me is to create a new account for every collection point, every workspace and the community point that my group does or is going to provide.

**Comment by davehakkens** [comment]
Thanks for the suggestion. Would love to see a map with many plastic drop off points!
We had the request a few times before througout the years, but not often.
Not many collection point have fixed pickup location yet so it doesn't really feel a feature worth integrating yet.

That said probably a good place to post this is here: https://feedback.preciousplastic.com/
In this way other people can upvote if they agree and it's easier for us to see the urgency of the feature.
