### ISSUE TITLE
[bug] Edit button on research in wrong position

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1776]
**Describe the bug**
The edit button in the research module moved. It should be aligned to the right 
(button can only seen by Research Author or Admin)

**Screenshots**
<img width="1086" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/174024243-cc52814b-2b36-459d-a2fd-00b6d63bd649.png">

**Comment by Xyli0** [comment]
Hi, I looked at the issue and it just need a quick fix. 
I will work on that.

side note: i looked at more advanced issues and didn't feel one I felt comfortable to tackle yet. I still need to familiarize myself with the codebase and many concepts. I hope I am not "stealing" to much good first issues. If it is a problem let me know 😀

**Comment by davehakkens** [comment]
steal them! Love it :D
