### ISSUE TITLE
Flag bug

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1777]
Precious Plastic flag is currently France. 
Recently its location has been changed to Portugal but the flag does not reflect the change. 
Might be a more common issues with other pins to. 
<img width="425" alt="Screenshot_2022-06-16_at_14_41_39" src="https://user-images.githubusercontent.com/17761877/174072234-9235538d-c11b-4b77-8ab9-e412469bb2ca.png">

**Comment by Kiebert** [comment]
Hi @thisismattia 
This looks like an administrative thing.
Isn't the location connected to the pin on the map?
Precious Plastic appears to be pinned in Francia?
![image](https://user-images.githubusercontent.com/3414938/193401609-afb858ff-7fa6-4fc2-858d-555497afe7ca.png)

**Comment by thisismattia** [comment]
On the map is in PT 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/17761877/193436878-0b074340-b9d0-4717-a842-e8d82859e47d.png">

However, flag might be connected to this location
<img width="902" alt="image" src="https://user-images.githubusercontent.com/17761877/193436905-ef232f29-46a0-43a0-b11a-dfff07bca083.png">

Gonna try to retrieve pp log in to check

**Comment by Kiebert** [comment]
Hello @thisismattia. 
Any new insights on this flag bug?

**Comment by thisismattia** [comment]
Yep so that was indeed the issue. Or actually no issue. User mistake. I will close this issue.
