### ISSUE TITLE
[bug] Disable modules for release Fixing Fashion

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1778]
**Describe the bug**
To release Fixing Fashion we need to disable a few modules.
- **Events** + **How-to's** won't be used and can be fully disabled.
- **Research** Should be live but hidden, for testing, so not in Navbar. (like how it is currently on [Precious Plastic](https://community.preciousplastic.com/research))

**Comment by Xyli0** [comment]
Would it be possible to take on this one?

**Comment by thisislawatts** [comment]
Updated @davehakkens, only the academy and map now appear in the top menu
https://fixing-fashion-prod.web.app/academy/start/intro.html
