### ISSUE TITLE
[feature request] Generate sitemap xml on the server

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1779]
**Is your feature request related to a problem? Please describe.**
To improve SEO we want to be able to submit a sitemap to search engines / bots etc. to let them know what pages are available within the site. This ideally should be accessible on a URL like `/sitemap` that proxies the function

**Describe the solution you'd like**
Ideally a cloud function that either triggers on demand or on a schedule, and tracks all the URLs that we want to share with bots. E.g. slugs of all howtos, events, research articles etc. 

**Describe alternatives you've considered**
Could try leave for automated crawlers to track through links on the page, however that is unlikely to work as things like the howto list page only show a subset of the available howtos (virtual scroller only renders howtos further down the page as they are about to scroll into view).

**Additional context**
A little bit of extra thought might be required to prevent sharing of non-approved content, and possibly limiting db requests (either caching the sitemap and only regenerating periodically, or using some sort of aggregations feature). Keen for any feedback from @davehakkens on thoughts for this

Testing new firebase functions can be a challenge, but hopefully recent updates we've made to the firebase emulators should make the process easier. Feel free to reach out if struggling to get up and running, emulator docs available at:
https://onearmy.github.io/community-platform/Backend%20Development/firebase-emulators-docker

Converting a list of generated links into a compatible sitemap XML file can be done with tools like [sitemap.js](https://github.com/ekalinin/sitemap.js). We have work in parallel for extracting metadata (e.g. individual title, description, image for a particular page) so I'd expect for a first pass we mostly just omit this from the sitemap, but look for a nicer way to integrate both systems in the future.

**Comment by davehakkens** [comment]
Sounds good.
Everything can be indexed except for `draft` and `non-approved` how-to's. 
(They are also not publicly available)

**Comment by chrismclarke** [comment]
Ok, I might take a quick go at drafting a PR for this myself as it will have quite a few moving parts to it (mostly in the backend)
