### ISSUE TITLE
Updates to Research Landing Page

### ISSUE THREAD

**Issue by franknoirot** [ONEARMY/community-platform#1838]
## Overview
The [Research Landing Page](https://community.preciousplastic.com/research) launched with the essential information included in it 🎉. This update adds some UI polishing touches to the page, including headers to the table on larger screens and a responsive design update for the research listing card component.

All designs can be inspected within the [ONE ARMY Figma](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform?node-id=887%3A7137). If you have any questions or issues tap the `C` key within Figma and click to leave a comment. Tag @franknoirot and @davehakkens for any clarifications or questions.

## Acceptance Criteria
Here are all of the things that should be true for this to be considered complete:
### Page
- [ ] The page now queries for the number of comments and number of useful points of each Research module.
- [ ] The header component with the H1 heading has font and spacing values that scale down responsively to match the designs.
- [ ] A new table header has been added containing 4 columns: Title, Updates, Comments, and Useful
### Table Header
- [ ] The final three column headers each contain their appropriate icon. (The necessary icons can be exported from Figma by clicking on the **Export** pane in the right sidebar with the icon selected.)
- [ ] The table header row is responsive across Desktop and Tablet, and is hidden on Mobile
### Research Item Card
- [ ] The Research item card is reformatted to  Show the username and last updated beneath the title, with the username now accompanied by the appropriate flag emoji.
- [ ] The Research item card now shows counts for Updates, Comments, and Useful points in three columns to the right which align with their corresponding column header.
- [ ] The Research item card adjusts both font and spacing values between Desktop and Tablet according to designs.
- [ ] On Mobile, the Research item card layout shifts to a more compact version which drops the number of updates and uses icons as labels in accordance with [the designs](https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform?node-id=976%3A7334).

## Design Screenshots
Below are exported images from the Figma designs:
### Desktop
![Research Landing Page - Desktop](https://user-images.githubusercontent.com/23481541/180356649-c4c493c8-c55b-4cb4-a7b9-391514c0f560.jpg)

### Tablet
![Research Landing Page - Tablet](https://user-images.githubusercontent.com/23481541/180358234-68a14eb1-ad1a-4eda-8878-1fbc1bd2bf02.jpg)

### M
![Research Landing Page - Alternative Card Design - Mobile](https://user-images.githubusercontent.com/23481541/180358244-7e2e5543-f3e8-4d08-acff-10d8373bca75.jpg)
obile

**Comment by asheerrizvi** [comment]
Is this issue still open for work?

**Comment by davehakkens** [comment]
yes! Nice one to take on!

**Comment by asheerrizvi** [comment]
@davehakkens can you assign this to me :D

**Comment by asheerrizvi** [comment]
Have created a PR for this: https://github.com/ONEARMY/community-platform/pull/1905

@franknoirot @davehakkens
