### ISSUE TITLE
[mobile] Zoom in/out buttons unusable

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1839]
Issue:
Browsing the map from mobile I am not able to use zoom in/out buttons as they're either completely or partly outside of the screen. 

Link:
https://community.preciousplastic.com/map

Screenshots:
Same issue on Ecosia, Chrome, Firefox and Brave. 
![Screenshot_20220723-132415_Ecosia](https://user-images.githubusercontent.com/17761877/180603902-974f1da2-da49-4ef3-bac7-75954dd8acab.jpg)

Proposal: 
Given the more common pinch behavior on mobile to zoom in/out we could simply hide.

**Comment by LucasGabrielBecker** [comment]
Hi, @thisismattia 

I would like to contribute on this one, can you assign it to me?

**Comment by thisismattia** [comment]
Be my guest 😁
