### ISSUE TITLE
[mobile] Reset email sent

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1840]
Issue:
After clicking "lost password?" message "reset email sent, check your inbox/spam" appears misaligned 

Link:
https://community.preciousplastic.com/sign-in

Screenshots:
![Screenshot_20220723-132645_Ecosia](https://user-images.githubusercontent.com/17761877/180604119-79677ec3-1748-44e0-b7ba-9ac40c6bbf71.jpg)

Proposal:
Push the message to the next line and align left
![Screenshot_20220723-132645_Ecosia](https://user-images.githubusercontent.com/17761877/180604149-a0f60610-c416-43ef-b538-9dccad2dc1f8.png)

**Comment by cschilbe** [comment]
@thisismattia 👋 Hey, I'd love to pitch in to help this cool community! I can take on this issue to get to know the setup.

**Comment by thisismattia** [comment]
Hello @cschilbe thanks! Go ahead and ping if you need any help.
