### ISSUE TITLE
[mobile] Profile Focus alignment

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1841]
Issue:
Profile Focus options is hard to use and misaligned

Link:
https://community.preciousplastic.com/settings

Screenshots:
![Screenshot_20220723-132948_Ecosia__1_](https://user-images.githubusercontent.com/17761877/180605226-1fd7b82f-fc97-46a8-9641-87cb5acafee5.png)

Proposal:
<img width="317" alt="Screenshot 2022-07-23 at 14 37 25" src="https://user-images.githubusercontent.com/17761877/180605243-3115a726-d921-4cc9-b21c-4214166929d8.png">

css changes:

.css-rnzcqg {
    justify-content: space-between;
}

.css-1n8artz {
  width: 45%;
}

.css-rz7xpj {
  flex-direction: column;
  align-items: center;
}

.css-5ob1ci {
  text-align: center;
}

**Comment by thisismattia** [comment]
All yours 🫶

**Comment by asheerrizvi** [comment]
@thisismattia have created a PR for this here: https://github.com/ONEARMY/community-platform/pull/1886

Have also left a comment for you. Let me know if you need any changes. 😄
