### ISSUE TITLE
[bug] Delete field full width

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1842]
Issue:
Delete icon + field misaligned

Link:
https://community.preciousplastic.com/settings

Screenshots:
![Screenshot_20220723-133014_Ecosia](https://user-images.githubusercontent.com/17761877/180605566-ba0cbbe8-cbe0-46fb-ada3-f304a5946799.png)

Proposal:
We stretch the field to 80% of its parent container and push the delete icon to the right with the parent stretching the full width. 

<img width="294" alt="Screenshot 2022-07-23 at 14 46 55" src="https://user-images.githubusercontent.com/17761877/180605631-31ec1a32-12f1-4808-979e-da5925053d3e.png">

css changes:
.css-stkt98 {
  justify-content: space-between;
}

.css-1i8p52d {
  width: 80%;
}

**Comment by asheerrizvi** [comment]
can you assign this to me? @thisismattia

**Comment by thisismattia** [comment]
All yours 🫶

**Comment by asheerrizvi** [comment]
@thisismattia have created a PR for this: https://github.com/ONEARMY/community-platform/pull/1882
