### ISSUE TITLE
[bug] remove brackets

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1843]
Issue:
Strange brackets in account settings 

Link:
https://community.preciousplastic.com/settings

Screenshots:
<img width="890" alt="Screenshot_2022-07-23_at_14_51_47" src="https://user-images.githubusercontent.com/17761877/180605759-96b0ae71-86b1-4662-93d2-869f8617f43f.png">

Proposal:
Remove the brackets (unless they have a purpose I am missing)

**Comment by asheerrizvi** [comment]
can you assign this to me? @thisismattia

**Comment by thisismattia** [comment]
All yours 🫶
