### ISSUE TITLE
[mobile] settings page endless scroll

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1844]
Issue:
On settings the page extends vertically indefinitely 

Link:
https://community.preciousplastic.com/settings

Screenshots:
![Screenshot_20220723-133340_Ecosia](https://user-images.githubusercontent.com/17761877/180605851-64fea59c-4da3-4ae5-882a-d41b945bcd97.jpg)

Proposal:
Page ends with One Army footer

**Comment by asheerrizvi** [comment]
I can take this @thisismattia

**Comment by thisismattia** [comment]
All yours 🫶

**Comment by asheerrizvi** [comment]
@thisismattia created a PR for this: https://github.com/ONEARMY/community-platform/pull/1885
