### ISSUE TITLE
[bug] location icon color

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1845]
Issue:
Location icon is inheriting some default colour

Link:
https://community.preciousplastic.com/u/mattia

Screenshots:
<img width="140" alt="Screenshot 2022-07-23 at 14 59 45" src="https://user-images.githubusercontent.com/17761877/180606038-e2a4895d-6b82-49cc-b07c-54112369a4e7.png">

Proposal:
Chane location color to color: var(--theme-ui-colors-black);
<img width="142" alt="Screenshot 2022-07-23 at 14 58 39" src="https://user-images.githubusercontent.com/17761877/180606054-235100a0-1d55-40db-9211-adbfd34106a6.png">

**Comment by osouthwell-scottlogic** [comment]
@thisismattia, am I okay to pick this up?

**Comment by thisismattia** [comment]
That'd be sweet 👻
