### ISSUE TITLE
[bug] Change inline link colour

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1846]
Issue:
Inline links (maybe all links) seem to be set to browser default colours which looks.. well.. defaulty. 
Also the "visited" state to purple looks so unloved :)

Link:
https://community.preciousplastic.com/

Screenshots:
<img width="1177" alt="Screenshot_2022-07-23_at_15_18_22" src="https://user-images.githubusercontent.com/17761877/180606918-60987ceb-860e-4840-9881-c3d1d1246764.png">

Proposal:
we set links to {
color: grey;
text-decoration: underline;
}
 
:hover {
underline: none;
}
:visited {
color: grey;
text-decoration: underline;
}

<img width="1125" alt="Screenshot 2022-07-23 at 15 19 47" src="https://user-images.githubusercontent.com/17761877/180606970-162d8a8a-d9c5-45f2-acf8-0aa9c7292044.png">

**Comment by Connor-McMillin** [comment]
I'm interested in taking on this one. First time looking at/contributing to the codebase, but I'm excited to learn :)

**Comment by Connor-McMillin** [comment]
I might need a bit of guidance on making this change.

I attempted to stylize Linkify within src/pages/Howto/Content/Howto/HowtoDescription and wasn't able to find a way to stylize the links with hover and visited. I also saw the global style which allowed me to style those links (and every other link on the site). I don't know if this change should be made at the precious-plastic theme level or on the individual howto pages shown above.

**Comment by thisismattia** [comment]
Hey @Connor-McMillin nice one, thanks for taking this issue :) 
@davehakkens any ideas who could be the best person to point Connor to for this?

**Comment by davehakkens** [comment]
Thanks for askin @Connor-McMillin, the style should be at theme level. For all body text

**Comment by asheerrizvi** [comment]
@Connor-McMillin hey are you still working on this?

**Comment by thisismattia** [comment]
Maybe @asheerrizvi you good to go ahead with this issue. Seems like @Connor-McMillin is not able to work on this anymore. Thanks both ✌️

**Comment by asheerrizvi** [comment]
Have created a PR for this: https://github.com/ONEARMY/community-platform/pull/1891

**Comment by thisismattia** [comment]
hey @asheerrizvi thanks man 🤘 this works as expected 💪
As you're at it could you please add an hover state where the underline gets removed?

Big up!

**Comment by asheerrizvi** [comment]
@thisismattia yea that's the tricky part. The code uses a library to highlight links and I am not able to set the hover styles through that library. Have added a comment on the PR. Can you help me tag relevant people there so that I can have some help? 😅

**Comment by thisismattia** [comment]
I see. 
Maybe @thisislawatts or @chrismclarke ? 
Or anyone else @davehakkens ?

**Comment by asheerrizvi** [comment]
Never mind guys, was able to work out a solution.
