### ISSUE TITLE
[feature request] Sort by "Most downloads"

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1847]
As we now have download counts could we sort by most downloads? 
Would it make sense bring value to the users?

<img width="264" alt="Screenshot 2022-07-23 at 15 27 36" src="https://user-images.githubusercontent.com/17761877/180607129-025e45dc-37bf-421c-9927-920f34fe32b7.png">

**Comment by davehakkens** [comment]
Good idea but a bit early and not really useful yet.
1. Currently only PP uses how-to's
2. Counts are still very low..
3. Most crucial. Only a few new how-to's there are counting, old how to's still just have a link with no files attached. They need to be changed before counting even starts.

Would say lets revisit this issue when more how-to's use counting
