### ISSUE TITLE
[mobile] Hide Bazar/Global site from menu dropdown

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1848]
Issue:
The drop down menu has some unintended legacy links to Bazar and Global Site.

Link:
https://community.preciousplastic.com/

Screenshots:
![Screenshot_20220724-172156_Brave](https://user-images.githubusercontent.com/17761877/180654250-4a69e7c9-5646-4ba4-ae6b-d35659606144.png)

![Screenshot_20220724-142438_Brave](https://user-images.githubusercontent.com/17761877/180654189-d4e1b7b3-62fe-4a4b-be8b-3ce5d1923bdb.jpg)

Proposal:
We hide/delete them

**Comment by asheerrizvi** [comment]
I can take this up.

**Comment by thisismattia** [comment]
Thanks! Simple change but so valuable for the UX 😎

**Comment by asheerrizvi** [comment]
@thisismattia have opened a PR for this:

https://github.com/ONEARMY/community-platform/pull/1858

😃
