### ISSUE TITLE
[mobile] Reduce header padding

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1849]
Issue:
The hero header has a big margin that hides the first how-to, ux would be improved if the first how-to was more shown inviting the user to scroll. 

Link:
https://community.preciousplastic.com/how-to

Screenshots:
![Screenshot_20220724-172748_Brave](https://user-images.githubusercontent.com/17761877/180654624-5be17c13-b61a-4202-8d92-3443abbfb75c.png)

Proposal:
Reduce top and bottom padding to 50px

css:
.css-144acuz {
  padding-top: 50px;
  padding-bottom: 50px;
}

<img width="368" alt="Screenshot 2022-07-24 at 17 33 01" src="https://user-images.githubusercontent.com/17761877/180655015-488c34b3-2e93-4177-a2e8-68ead4cb1cb4.png">

**Comment by asheerrizvi** [comment]
I can take this up.

**Comment by asheerrizvi** [comment]
Opened a PR for this:

https://github.com/ONEARMY/community-platform/pull/1859
