### ISSUE TITLE
[bug] How-to step layout 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1851]
Issue:
How-to step layout is hard to read. 

Link:
https://community.preciousplastic.com/how-to/injection-machine-automatic-connection-upgrade-

Screenshots:
![Screenshot_20220724-174722_Brave](https://user-images.githubusercontent.com/17761877/180655782-574934e3-1635-4484-a3ed-a2810470e77b.jpg)

Proposal:
A simple flex-direction: column could fix it + column reverse to have image first

css-s86h58 {
  flex-direction: column;
  flex-direction: column-reverse;
}

As a plus I would also reduce the height of the image to 300px (currently 450px)
.css-18eyh6c {
  height: 300px;
}

<img width="326" alt="Screenshot 2022-07-24 at 17 56 01" src="https://user-images.githubusercontent.com/17761877/180655676-737566f9-5231-41fb-b334-4a988361ea62.png">

**Comment by asheerrizvi** [comment]
@thisismattia I can take this up 😄

**Comment by asheerrizvi** [comment]
@thisismattia have opened a PR for this, lmk how it looks?

https://github.com/ONEARMY/community-platform/pull/1855
