### ISSUE TITLE
[mobile nice-to-have] Apply filter button

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1852]
Issue:
On the map the filter drop down could benefit from a "Apply Filters" button to help with the UX. As now you select the filters and are left wondering, "what's next?" no sign/hint of what to do next. 

Link:
https://community.preciousplastic.com/map

Screenshots:
![Screenshot_20220724-180259_Brave](https://user-images.githubusercontent.com/17761877/180656056-1af09922-3e61-4db5-9d28-ef08429af28b.jpg)

Proposal:
If we think this is necessary I could design the button

**Comment by asheerrizvi** [comment]
Does this needs to be done?

**Comment by thisismattia** [comment]
Thanks @asheerrizvi , @davehakkens what do you think?

**Comment by davehakkens** [comment]
I would say low priority @asheerrizvi and we didn't make a very clear plan for it yet.
But if you have inspiration and want to propose something go for it :)

**Comment by asheerrizvi** [comment]
@thisismattia do you have a design in mind for the button?

**Comment by Sc4ramouche** [comment]
Hey there, I'm new to the project, although I thought it might make sense to use the same button as we do in other places where it's suggested for user to initiate an action. Let me know if it makes sense to you and feel free to leave your feedback in the PR linked above 🙌 

![Screenshot 2022-10-15 at 21 49 44](https://user-images.githubusercontent.com/25829136/196005246-392045db-2d9f-45cf-8a52-dc45a7083f13.png)

**Comment by thisismattia** [comment]
hey @Sc4ramouche that's great! Yep primary button works in this case. Make sure it is hidden on desktop.
