### ISSUE TITLE
Research module user consistency

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1853]
Issue:
Users look different on research module when compared to how-tos and the rest of cp. Would be great to have them aligned and consistent

Link:
https://community.preciousplastic.com/research

Screenshots:
<img width="1624" alt="Screenshot_2022-07-24_at_18_16_04" src="https://user-images.githubusercontent.com/17761877/180656517-1f87386e-52d0-4285-aa17-ad928a0adc10.png">
<img width="1623" alt="Screenshot_2022-07-24_at_18_16_46" src="https://user-images.githubusercontent.com/17761877/180656530-20588931-da14-49ed-aa9f-7d605916711d.png">

Proposal:
We aligned the look of users on research module with the look of users on how-tos (flag + grey)

**Comment by davehakkens** [comment]
Should be fixed in this issue https://github.com/ONEARMY/community-platform/issues/1838
