### ISSUE TITLE
404 page redesign

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1863]
404 page for a more fun experience :)

Design
Image + text with link to homepage
![404_UI](https://user-images.githubusercontent.com/17761877/182430236-deb3ae54-d21e-4375-8dbd-b59663e7c67c.jpg)

Here's the optimized png for the illustration 
![404](https://user-images.githubusercontent.com/17761877/182430329-a7c960d4-6b8c-425b-bc55-a9092fe89241.png)

Mobile should be straightforward. Everything (image + text) is centered. 
Let me know if you need a design for it.

**Comment by pkpndy** [comment]
can I take this?

**Comment by thisismattia** [comment]
Be my guest 🙂
