### ISSUE TITLE
[bug] Cant edit or delete comments

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1864]
**Describe the bug**
The edit and delete feature doesnt work in comments.
For both the research module and the how-to's
1. In the research module the button is there but non clickable
2. in How-to's the `Remove` and `Edit` button are not present

This probably got broken when migrating the component
In this https://github.com/ONEARMY/community-platform/pull/1742 or this https://github.com/ONEARMY/community-platform/pull/1772 one

**To Reproduce**
Steps to reproduce the behaviour:

1. Login [deviste](https://dev.onearmy.world) 
2. Leave a comment in research or howto
3. try to edit or delete

**Screenshots**
In research module after leaving a comment 
<img width="848" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/182897139-7bd10b4b-7d86-4062-908f-7417f2c9fe16.png">
In how-to after leaving a comment
<img width="830" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/182897309-a18ef28f-108d-4447-afc7-a6e2f16153ad.png">

**Comment by asheerrizvi** [comment]
@davehakkens I can work on this :D

**Comment by davehakkens** [comment]
that would be great @asheerrizvi! Let me know if you need any help :)

**Comment by cschilbe** [comment]
The delete worked for me on mobile. The delete confirmation appeared to be an iOS dialog and not the delete confirmation dialog seen in other areas.

**Comment by davehakkens** [comment]
Thanks for letting us know @cschilbe are you still on this @asheerrizvi?

**Comment by asheerrizvi** [comment]
@davehakkens haven't been able to start on this as of now.

**Comment by asheerrizvi** [comment]
Guys, delete was already working. Have fixed the issue with editing the comment. Here's the PR: https://github.com/ONEARMY/community-platform/pull/1901
