### ISSUE TITLE
[bug] Contacts & links overflow hidden

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1866]
Issue:
In the user settings > Info > Contacts & Links the dropdown menu to select user preferred way to be reached is cut off by the parent container. Might be an overflow:hidden  on the parent causing it
https://community.preciousplastic.com/settings

Bug
<img width="857" alt="Screenshot_2022-08-06_at_22_17_20" src="https://user-images.githubusercontent.com/17761877/183264860-2e7c3c2a-cf16-442b-8961-85ea07122ab9.png">
<img width="843" alt="Screenshot_2022-08-06_at_22_17_28" src="https://user-images.githubusercontent.com/17761877/183264862-70523a80-a0d0-4a87-8ebb-957920ebd085.png">

Desired behaviour, the dropwdown menu and options don't get cut off and display all items
<img width="865" alt="Screenshot_2022-08-06_at_22_17_14" src="https://user-images.githubusercontent.com/17761877/183264858-f624ab32-8580-4a2f-a5a7-5c79cc090e92.png">

**Comment by LucasGabrielBecker** [comment]
Hi, I would like to help on this one.

Can I open a PR for it ?

**Comment by Yash-Var** [comment]
@thisismattia I want to fix this can you  assign it to me .....

**Comment by Yash-Var** [comment]
@thisismattia i want to fix this ....

**Comment by thisismattia** [comment]
Hey guys thanks for the eagerness. We'll work on a first come first served basis. @LucasGabrielBecker will assign this to you. @Yash-Var we have many other open issues waiting for your contributions :)
