### ISSUE TITLE
Profile Settings UX rework

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1870]
**Issue**
Many users create their accounts but don’t update their infos resulting in incomplete/spam accounts diminishing the overall UX on the Community Platform. 
![image3](https://user-images.githubusercontent.com/17761877/183437025-7e1feeaa-6ae6-4590-92aa-b38a34e90d50.png)

**Solution**
There are probably multiple solutions to tackle this problem. With this issue we want to improve the overall UX of the user settings page to make sure anyone that makes it to their settings is able to complete their profile with as little effort and frustration as possible.

**Current behavior**
“Save profile” button is greyed out (not clickable) by default until users input all fields correctly. There is no indication of what fields are mandatory (beyond a little star*), what fields are missing or mistaken for completing the profile. This might leave many users confused on what they have to do to complete their account. 
<img width="446" alt="image6" src="https://user-images.githubusercontent.com/17761877/183437102-69b97a19-3857-44dc-9223-93548f39141f.png">

**Proposed behavior**
“Save profile” button is enabled at all times (even when editing settings). When user clicks “Save profile” there are two possible outcomes:

1. Success. All mandatory fields are filled correctly and profile is saved. This triggers:
a. Success message
<img width="594" alt="image2" src="https://user-images.githubusercontent.com/17761877/183437486-7483fa41-cf59-41ef-843d-f232ef0eee96.png">

2. Error. Some mandatory fields are missing or wrong. This triggers 2 things happen:
a. Missing/wrong fields become red + alert text (change to "Make sure this field is filled correctly.") using [this](https://onearmy.github.io/community-platform/storybook-static/index.html?path=/story/base-components-input--error) component
<img width="835" alt="image5" src="https://user-images.githubusercontent.com/17761877/183437793-fce061ae-23ab-4f47-9d33-f0d23e783f82.png">
b. Error message below “Save profile” button
<img width="401" alt="image4" src="https://user-images.githubusercontent.com/17761877/183437894-858c7f3f-ebd3-473c-8959-036594fc391c.png">

This is kind of a big issue so if you have any questions feel free to comment or reach out. 
Big up ✌️

**Comment by ThakurKarthik** [comment]
Hello I am Karthik, I am new here and I would like solving this issue, is there a timelimit for this to be fixed ?

**Comment by ThakurKarthik** [comment]
I have done the local setup of this repo, I can allot couple of hours on week days for this and I think it should be done within 3 days from tomorrow, if that is fine please assign this to me :)

**Comment by thisismattia** [comment]
That'd be great. Issue is yours 👍

**Comment by asheerrizvi** [comment]
Is this done?

**Comment by davehakkens** [comment]
yeh it's merged but I think @mattia had a few changes for it

**Comment by asheerrizvi** [comment]
@thisismattia can you open an issue with the changes you want and assign it to me? I can work on those if you want.

**Comment by ThakurKarthik** [comment]
Hello, I have been busy lately. The PR opened by me is shown as closed. If some one wants to pick up the issue it is fine :)

**Comment by thisismattia** [comment]
Yep, will do it by the end of today 🤞🤞
