### ISSUE TITLE
[bug] Sign-up consent terms checkbox alignment and label click

### ISSUE THREAD

**Issue by cschilbe** [ONEARMY/community-platform#1877]
**Describe the bug**
Within the sign-up form, the terms and conditions checkbox and label are misaligned and the label is not clickable.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to '/sign-up'
2. Observe the alignment of the consent checkbox
3. Attempt to click the label
4. Observe that the checkbox is not checked

**Expected behaviour**
* Checkbox and label should be aligned
* Label should be clickable

**Screenshots**
<img width="633" alt="image" src="https://user-images.githubusercontent.com/485557/183773882-4818f4ce-ef05-4cc4-9bc4-298309f1abc9.png">

**Comment by thisismattia** [comment]
Thanks @cschilbe this was bugging me for a while ✌️
