### ISSUE TITLE
[bug] Country container overflow

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1890]
Issue:
On profile page the country container gets overflown when country name is too long. 

Link:
https://community.preciousplastic.com/u/biso-plastique
<img width="282" alt="Screenshot 2022-08-12 at 08 38 16" src="https://user-images.githubusercontent.com/17761877/184299563-48cf16e3-48aa-4fcc-a88b-0155039aeab3.png">

Proposed fix:
Currently the size of the container is defined by the parent 
<img width="198" alt="image" src="https://user-images.githubusercontent.com/17761877/184299863-70dce37b-da83-4c91-afb4-a37efd8e1c04.png">
Maybe simply adjust the parent container to be more responsive and not fixed width?

**Comment by Light2Dark** [comment]
Hi, I found that removing the max-width's of both the child and parent container and making the parent container a flexbox works. 

Let me know if I can help with a PR, the code seems to work on my side! :)

**Comment by thisismattia** [comment]
Hey @Light2Dark nice one!
Yes I would say make a PR and we can check if everything works. 
Thanks ♡
