### ISSUE TITLE
[bug] Remove Logout active state

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1897]
**Issue:**
User menu shows "Log out" as active navlink on all pages
<img width="1713" alt="Screenshot_2022-08-18_at_11_26_27" src="https://user-images.githubusercontent.com/17761877/185361918-9cbd8e6d-1559-483f-98e3-f4b88dc60e7d.png">

**Link:**
https://community.preciousplastic.com/academy/intro.html

**Proposed change:**
"Logout" not highlighted and same colour as other nav elements

**Comment by fk00750** [comment]
Hey @thisismattia can you assign me this issue

**Comment by thisismattia** [comment]
Hey @fk00750 sorry for the slight delay. All yours 👍

**Comment by thisislawatts** [comment]
@fk00750, following up on this, we have a fix inbound in #1902 so I am going to remove you from this issue. Apologies for the short notice on this.
