### ISSUE TITLE
User menu items active state

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1898]
**Issue:**
Navbar items active state is still set to default (I think)
<img width="221" alt="image" src="https://user-images.githubusercontent.com/17761877/185363327-558ec97e-3bdd-4f2e-b956-8d6cbf9a200c.png">

Link:
https://community.preciousplastic.com/u/your-username

Proposed change:
:active state is same as :hover state (grey bg + black font-color)
<img width="249" alt="image" src="https://user-images.githubusercontent.com/17761877/185364448-9b6154e6-e371-4dd7-ad02-f51fe31c817e.png">

**Comment by asheerrizvi** [comment]
@mahmoud-elgammal are you working on this?

**Comment by thisismattia** [comment]
you go 😁

**Comment by asheerrizvi** [comment]
@davehakkens we can close this as well.
