### ISSUE TITLE
Remove how-to download button margin-left

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1916]
Heyo annoying designer coming at you 😆

How to download button is slightly misaligned. Can we remove margin-left on the button? 
<img width="1331" alt="Screenshot_2022-09-09_at_05_58_28" src="https://user-images.githubusercontent.com/17761877/189269374-f0330b60-0089-4fda-8cd5-e7bb07ff518c.png">

Thanks!

**Comment by asheerrizvi** [comment]
@thisismattia I'll tinker with this lol

**Comment by thisismattia** [comment]
Thanks for sorting out my OCD 👻

**Comment by asheerrizvi** [comment]
hahaha I have OCD as well. Can you assign this to me?

**Comment by thisislawatts** [comment]
@asheerrizvi be sure to pull the latest version down. I merged a change a few hours ago that moved some of these files around

**Comment by asheerrizvi** [comment]
@thisismattia do you want the number of downloads text below the button to also be aligned to the left? Currently it has a left padding of 8px:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/17976252/191499055-9a1d302a-bb1e-4e72-8a6b-eb43586c2f86.png">

**Comment by asheerrizvi** [comment]
Have opened a PR without removing the padding but let me know if you need it removed @thisismattia 

https://github.com/ONEARMY/community-platform/pull/1939

**Comment by thisismattia** [comment]
Yes please 👊 would be great
