### ISSUE TITLE
Download button text wrong color 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1937]
The text of the download button on how-tos is blue when I think it should be (and already was) black.

<img width="887" alt="Screenshot_2022-09-19_at_07_11_06" src="https://user-images.githubusercontent.com/17761877/191414497-c823bdd0-d597-4081-b6ab-c77841d4bc13.png">

**Comment by Kiebert** [comment]
Hello @thisismattia 
This looks indeed like a 'Good first issue' for me.
Could you add a 'live' url of this issue? And maybe the browser you are using?
Thanks in advance.

**Comment by Kiebert** [comment]
Hello.
Created a pull request for the update.
Please let me know, if you have questions or remarks.

**Comment by thisismattia** [comment]
thank you ♡

**Comment by Kiebert** [comment]
Hello,
I created a new PR with the right commit message format.
Please let me know, if you have questions or remarks.

**Comment by thisislawatts** [comment]
Closed by https://github.com/ONEARMY/community-platform/pull/1945
