### ISSUE TITLE
Error message －  Nowrap

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1940]
Issue
Error message displaying on settings page could be improved for better ux. 

To reproduce the issue 
https://community.preciousplastic.com/settings

Screenshot of issue
<img width="431" alt="188541797-a3aab39d-4f36-444d-9dfd-6aabd6bb1628-1" src="https://user-images.githubusercontent.com/17761877/191796759-128b69ac-f99a-4d2f-8888-0de533633d16.png">

Desired behavior
The text does not wrap and stays on one line

**Comment by Kiebert** [comment]
Hello,
Created a pull request for this one.

**Comment by thisismattia** [comment]
Thanks!

**Comment by Kiebert** [comment]
Hello @thisislawatts, I did an update of the PR. The changes are visible here:
https://github.com/ONEARMY/community-platform/pull/1946

**Comment by Kiebert** [comment]
@thisismattia This bug fix is merged
