### ISSUE TITLE
Error message － Contacts and links

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1941]
Issue
Error message displaying on settings page could be improved for better ux.

To reproduce the issue
https://community.preciousplastic.com/settings

Screenshot of issue
<img width="837" alt="188542098-e0bee05f-ca97-432a-95eb-399f42ce9b27" src="https://user-images.githubusercontent.com/17761877/191797328-727b4ecf-5bff-4dc8-9874-6839b4f5737b.png">

Desired behavior
Remove the error message on link input field (border on field stays red)

**Comment by Kiebert** [comment]
Hello @thisismattia 
The 'link' input has a separate error field that also is used to show the 'required' message (after you select a 'type): do you really want to delete it?
I assume the height of the link input should also align with the 'type' selectlist list height?

**Comment by thisismattia** [comment]
hey @Kiebert thanks for looking in to this. I see.. in my way of looking at it from the end user point of view I would see this block as one, the required info necessary to complete your profile (not the individual type + field)

<img width="889" alt="Screenshot_2022-09-25_at_14_13_54" src="https://user-images.githubusercontent.com/17761877/192142896-38711eec-09e1-49c2-8ca9-da6acb5502f0.png">

I guess my desired scenario would be something like this
<img width="672" alt="image" src="https://user-images.githubusercontent.com/17761877/192143136-2eb7bb88-b692-494b-8b07-d600b8180094.png">

But if this complicates the code too much may be good to skip it and keep things simpler. Maybe @thisislawatts can shine some light on amount of work and possible repercussion on other areas of the site?

**Comment by Kiebert** [comment]
Hello @thisismattia. 
As far as I know: the error fields are 'connected' to every single input field.
This is the current proposal I could create. It is aligned with the image upload field:

![error_contact_links_full_width](https://user-images.githubusercontent.com/3414938/193399831-4d897cac-2285-44eb-9d92-fe7afbc76473.jpg)
![error_contact_links_mobile_width](https://user-images.githubusercontent.com/3414938/193399839-6f8b434a-28f0-4a33-a3fc-f083c9b53148.jpg)

I will create a pull request. 
If you have a question and/or remarks, let me know.

**Comment by thisismattia** [comment]
hey @Kiebert I see. Your proposed solution also works great. 
Thank you :)
