### ISSUE TITLE
Error message － Collection Opening time

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1942]
Issue
Error message displaying on settings page for Collection Point profile could be improved for better ux.

To reproduce the issue
https://community.preciousplastic.com/settings

Screenshot of issue
<img width="804" alt="Screenshot_2022-09-22_at_18_10_59" src="https://user-images.githubusercontent.com/17761877/191798349-e967ce83-bfdd-4eb1-bd9b-07192b7ae2a4.png">

Desired behavior
Push error message below "select day" input field and remove error message from other input fields

**Comment by asheerrizvi** [comment]
@thisismattia I will take this.

**Comment by thisismattia** [comment]
Thank you man!

**Comment by asheerrizvi** [comment]
@thisismattia here's a PR for this:

https://github.com/ONEARMY/community-platform/pull/1989

**Comment by thisismattia** [comment]
Thanks man 🙏
