### ISSUE TITLE
Error message － Consistency 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1943]
Issue
There are two type of error messages displaying on settings page. Would be ideal to align and have only 1 type of error message for consistency. I found the different messages on the following sections:

I run a workspace > Workspace 
I build machines > Expertise
I collect & sort plastic > Collection

To reproduce the issue
https://community.preciousplastic.com/settings

Screenshot of issue
<img width="857" alt="image" src="https://user-images.githubusercontent.com/17761877/191799331-96c91aab-2c7f-4db7-b77e-3a9dfb8d04ff.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/17761877/191799390-3d2bae9d-232c-44a6-baee-ce6954a058ca.png">

Desired behavior
We merge the two error messages into one consistent approach. Ideally we keep the one from second screenshot.

**Comment by sev-osr** [comment]
lol, the time you clowns spend writing that issue, you could have perfectly fixed it - at least once, you'd get your hands dirty on anything - I suppose, that nonsense serves well to justify your ridiculous existence. 

In the meantime, there are families, workers, and investors paying a big price for your incompetence and abuses, across the entire project and community. 

Let's see what the community has to say about this.

**Comment by sev-osr** [comment]
@davehakkens , @thisismattia

**Comment by asheerrizvi** [comment]
@thisismattia I will take this.

**Comment by thisismattia** [comment]
All yours :)

**Comment by asheerrizvi** [comment]
hey @thisismattia below is a PR for this. I have only changed the text styling for now and have left the text copy as it is. Let me know if you want changes to the text as well.

https://github.com/ONEARMY/community-platform/pull/1988

**Comment by thisismattia** [comment]
beautiful thanks ♡

**Comment by thisismattia** [comment]
Perfect! Thank you
