### ISSUE TITLE
[bug] Wrong Icon size on Fixing Fashion Map

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1948]
**Describe the bug**
The icons on the map of Fixing Fashion are not correct.
The icons shown are for large display size, but they should be for small display size.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://community.fixing.fashion/map
2. See the icons

**Expected behaviour**

1. Space icon should be: 
https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/fixing-fashion/avatar_space.svg

2. Member icon should be: 
https://github.com/ONEARMY/community-platform/blob/master/src/assets/images/themes/fixing-fashion/avatar_member.svg

**Screenshots**
![FF-map-icons](https://user-images.githubusercontent.com/13672737/192154581-dde4d48f-0fa6-40e0-8966-55ba90cc4755.jpg)

**Additional context**
Add any other context about the problem here

**Comment by asheerrizvi** [comment]
@davehakkens I can take this.

**Comment by davehakkens** [comment]
great. thanks!

**Comment by davehakkens** [comment]
Would be cool to try and get this done before Thursday @asheerrizvi if possible.
Sharing a Patreon article about it. :)

**Comment by asheerrizvi** [comment]
hey @davehakkens this should be done for all screen sizes right?

**Comment by davehakkens** [comment]
yes.

**Comment by asheerrizvi** [comment]
Got you, it's somewhat tricky. Currently, the codebase uses `src/modules/profile/SupportedProfileTypesFactory.ts` to fetch the type of icons it shows on the map. And all of them are generic icons. We will have to come up with a way to show theme based icons instead.

**Comment by asheerrizvi** [comment]
@davehakkens here's what I was able to come up with:

https://github.com/ONEARMY/community-platform/pull/1978

**Comment by davehakkens** [comment]
Hmm but it seems to already show correct on the Precious Plastic Instance..
Or because it doesnt use theming?

**Comment by asheerrizvi** [comment]
Yea that's because it is not using theming. That's the default one.

**Comment by asheerrizvi** [comment]
It is using pt-member badge there which is basically this:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/17976252/194038506-aae9acbb-f5e4-4a0b-85db-bb0475a1f6e5.png">
