### ISSUE TITLE
[feature request] Show `-` instead of `0` on the Research Listing page

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#1971]
**Is your feature request related to a problem? Please describe.**

![Screenshot 2022-10-02 at 15 54 01](https://user-images.githubusercontent.com/472589/193605894-adcb6a85-dd7c-4876-9108-34c93fadbbd8.jpg)

At the moment we show a full `0` character for instances where there have been, no updates, no comments or no useful votes.

**Describe the solution you'd like**

![Screenshot 2022-10-02 at 15 53 43](https://user-images.githubusercontent.com/472589/193606137-ea03db19-b18d-4c50-85d0-3843e7ff4414.jpg)

Using a `-` character would reduce the visibility of this state and make it easier to identify where there _have_ been update, comments or useful votes.

**Comment by thisislawatts** [comment]
One to take a look at during the next monthly dev call :)

**Comment by Sc4ramouche** [comment]
Hey @thisislawatts 👋 

Have you started working on this one? I took a look out of curiosity and looks like the required changes are simple from the first glance.

I'll open a draft PR shortly, hope you wouldn't mind. Feel free to build upon it or scrap it :)

**Comment by thisislawatts** [comment]
Thanks for looking into that so quickly, apologies for any confusion. This was an Issue I created specifically for walking through the contribution flow end to end. Closing now as the fix was merged.
