### ISSUE TITLE
Add categories to research module

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2002]
### Description

We've recently added categories to our how-to's module (https://github.com/ONEARMY/community-platform/pull/1624), now we would like to also add them to the research module.
Note: There are different categories for how-to's and research. (Unlike tags they are not sitewide). So each module would need to be able to configure their own categories.

### Page related

Will be used in : 
- [Research overview](https://dev.onearmy.world/research)
- [Research Create](https://dev.onearmy.world/research/create)
- [Admin Panel](https://dev.onearmy.world/admin) (to add categories)

### Frontend
![Categories_frontend](https://user-images.githubusercontent.com/13672737/203425595-118ff05b-5e7d-4151-ab09-271ff5f124ee.jpg)

### Research creation
![Categories_inputfield](https://user-images.githubusercontent.com/13672737/203425684-c62d5645-7efd-4bea-90b7-ac94ec119fd1.jpg)

### Current admin panel for categories.
Add another set for research
![Categories_admin](https://user-images.githubusercontent.com/13672737/203425792-ffeb7748-2d41-48b5-97e2-d7985ed65442.jpg)

**Comment by asheerrizvi** [comment]
@davehakkens I can take this up :)
