### ISSUE TITLE
[bug] Poorly documented max string length for How-to title

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2015]
**Describe the bug**

It is not possible to type more than 50 characters into the How to title field. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'How to -> Create'
2. Click on 'Title of your How-to *'
3. Type or copy a long string into the box, for example:
> Duis nec sollicitudin mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris condimentum erat vitae lorem viverra, lobortis iaculis enim tincidunt. Vestibulum tempus ex eget nunc vulputate tempus. Phasellus pulvinar imperdiet ligula in iaculis. Morbi ac gravida mi.
4. Notice the absence of any visual indicators or explanation to the user about why the input is no longer working. 

**Expected behaviour**

It should be possible to type more than 50 characters for a title, or if this hard limit is really required then there should be an indication to the user and explanation on why they are not able to enter more text. For example see attached screengrab of how we implement a similar function in the comments box. 

**Screenshots**

Screen grab demonstrates hitting the max limit where the cursor stops moving forward, there is no explanation for the user. 
![Screenshot 2022-11-27 at 16 13 14](https://user-images.githubusercontent.com/472589/204142689-8e95127f-0abe-47e0-af74-dc8a7d875244.jpg)

![Screenshot 2022-11-27 at 16 21 34](https://user-images.githubusercontent.com/472589/204143097-72f614f7-de04-4ece-b23d-28cafea93488.jpg)

**Comment by thisislawatts** [comment]
Oh wait... it's there in the placeholder hint 😬 
I was demonstrating how hard it is to expect folks to read things 😰 

![Screenshot 2022-11-27 at 16 38 21](https://user-images.githubusercontent.com/472589/204143881-114e736a-f3ed-46df-af9c-70186cab161a.jpg)

**Comment by asheerrizvi** [comment]
I think it would be better to have this information as part of the input label itself (Title of your How-to (max 50 characters). Placeholders are not great for accessibility.
