### ISSUE TITLE
[bug] Inputs for adding tags and categories re-render on each key stroke

### ISSUE THREAD

**Issue by asheerrizvi** [ONEARMY/community-platform#2017]
**Describe the bug**
The inputs for adding a tag and adding a category are somewhat broken. These inputs re-render on each keystroke and thereby makes the input go out of focus on each such action.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Admin panel.
2. Click on Tags Admin or Categories Admin.
3. Trying adding a tag or a category
4. See the behaviour by typing the tag or the category name.

**Expected behaviour**
Inputs should not re-render on each key stroke and the user is able to type without losing focus.

**Screenshots**

https://user-images.githubusercontent.com/17976252/205485688-72d04442-ba36-4d8d-814f-20c55f9ee1cf.mov

**Additional context**

**Comment by RumplerLukas** [comment]
can you assign this issue to me

**Comment by davehakkens** [comment]
how is this going @RumplerLukas? Going good, need help or should we assign to someone else?

**Comment by RumplerLukas** [comment]
i was ill till today but i will look forward to go on working

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Dave Hakkens ***@***.***>
Gesendet: Monday, January 2, 2023 10:47:32 AM
An: ONEARMY/community-platform ***@***.***>
Cc: Rumpler Lukas, 5AHIF ***@***.***>; Mention ***@***.***>
Betreff: Re: [ONEARMY/community-platform] [bug] Inputs for adding tags and categories re-render on each key stroke (Issue #2017)


how is this going @RumplerLukas<https://github.com/RumplerLukas>? Going good, need help or should we assign to someone else?

**Comment by asheerrizvi** [comment]
@RumplerLukas any update on the progress here?

**Comment by RumplerLukas** [comment]
I am sorry
i am busy with my master finals right now

you can assign that issue to someone else


________________________________
Von: Asheer Rizvi ***@***.***>
Gesendet: Freitag, 27. Jänner 2023 22:01
An: ONEARMY/community-platform ***@***.***>
Cc: Rumpler Lukas, 5AHIF ***@***.***>; Mention ***@***.***>
Betreff: Re: [ONEARMY/community-platform] [bug] Inputs for adding tags and categories re-render on each key stroke (Issue #2017)


@RumplerLukas<https://github.com/RumplerLukas> any update on the progress here?

**Comment by asheerrizvi** [comment]
@davehakkens you can assign this to me.

**Comment by davehakkens** [comment]
hey!
`localhost:3000/admin_v2` is the new admin panel we are working on
`localhost:3000/admin` is the old one where you find the categories.
