### ISSUE TITLE
Create email template for notifications

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2026]
### Description

We are working on email notifications and need this attached template made in [Handlebars](https://handlebarsjs.com/playground.html). We will later hook it to backend and probably use [postmarkapp](https://postmarkapp.com/) for sending them.

### Mockup

![notifications_mailtemplate_1 (1)](https://user-images.githubusercontent.com/13672737/206877777-babfc139-b05c-490b-bf77-b4a2e4e1fa1c.jpg)

**Comment by asheerrizvi** [comment]
Here's what the template looks like at the moment:

https://codesandbox.io/s/clever-tdd-6xfvfe?file=/index.html

**Comment by chrismclarke** [comment]
Thanks @asheerrizvi - looks good to me, I've created a follow-up issue #2091 to use the template to generate a notification list which I'm handing over to @evakill , so I think good to close the issue here and follow-up with anything as needed. Thanks again!
