### ISSUE TITLE
Add mail notifications setting to user profile (frontend)

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2028]
### Description

For the upcoming email notifications we need a dropdown in the user profiles where users can select to receive updates.
We're making a notifications digest with all the recent unseen updates.
The dropdown needs to contain the 4 options:
- Never
- Daily
- Weekly
- Monthly

### Page related

Will be used in : [/settings](https://dev.onearmy.world/settings)

### Mockup

![mail notifications](https://user-images.githubusercontent.com/13672737/206925405-e5c54f9d-5511-4028-a04a-6a87dcf92fcc.jpg)

**Comment by RumplerLukas** [comment]
Can you assign the problem to me?

**Comment by davehakkens** [comment]
To late.. there is already a PR made for it https://github.com/ONEARMY/community-platform/pull/2039
