### ISSUE TITLE
Contact & Links top margin

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2036]
Contact and link section is glued to the profile description and would benefit from some 30px top margin

You can check it on any profiles https://community.preciousplastic.com/u/seko-upcycle

<img width="1181" alt="Screenshot_2022-12-15_at_18_36_13" src="https://user-images.githubusercontent.com/17761877/207990051-e46b796e-8bf4-4284-95f0-4797e8fd33a2.png">

Fix: add 30px top margin

Thanks!

**Comment by maddy020** [comment]
Please assign this issue to me

**Comment by davehakkens** [comment]
how is this going @maddy020?

**Comment by maddy020** [comment]
I am unable to set it on my local machine
Getting the following error
![eq](https://user-images.githubusercontent.com/103564105/210073829-74435944-d5ea-491b-81c6-a81cd521fb45.PNG)

**Comment by davehakkens** [comment]
hmm did you see our documentation about it [here](https://onearmy.github.io/community-platform/)?
ANd if you have questions or problems best to got to our [Discord](https://discord.com/invite/SSBrzeR) to get some help

**Comment by asheerrizvi** [comment]
@davehakkens can you assign this to me please?
