### ISSUE TITLE
Add CTA for How-to and Research

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2053]
## Component infos

We want to add a Call to action at the bottom of Research and How-to's. This will give more visibility to the creator and encourages users to leave a comment or mark as useful. 

### Description
- It shows the [username component](https://onearmy.github.io/community-platform/storybook-static/index.html?path=/story/components-username--verified) of the uploader
- It could show additional contributors ([depending when this PR gets finished](https://github.com/ONEARMY/community-platform/pull/2007))
- Both have the `useful` button + amount (is already added in the top as well)
- Only how-to has the `comment` button 

### Actions
- Clicking username goes to profile
- Clicking contributor goes to profile
- Clicking useful adds +1 to the counter
- Clicking comments scrolls down to comments input field

### Page related

Will be used in :

- A [How-to page](https://dev.onearmy.world/how-to/portrait-images)
- A [research page](https://dev.onearmy.world/research/test-research)

### Mockup
CTA for how-to and research
![footer_howto+research](https://user-images.githubusercontent.com/13672737/210022483-d79481f0-2123-440f-ac51-d3f3307323c9.jpg)

![footer_overview](https://user-images.githubusercontent.com/13672737/210022827-aed2adae-9be4-4a0d-ac0f-f528d4e0ebaf.jpg)

### Responsive
![footer_responsive](https://user-images.githubusercontent.com/13672737/210023230-0f1e6316-9a21-4ed6-8685-ce935da2b167.jpg)

### Potentional future things to add

- `Subscribe` to a research button https://github.com/ONEARMY/community-platform/issues/1438

**Comment by thisislawatts** [comment]
Can I work on this one @davehakkens ?

**Comment by davehakkens** [comment]
Yeh works for me. 

Sidenote: Did also ask @evakill and @asheerrizvi since it could be a good first issue to get to know the platform. But they could potentionally also do the review on your work. Also a good maintainer exercise :)

Hope thats ok for everyone

**Comment by thisislawatts** [comment]
@davehakkens is there a Figma link as well as the images?

**Comment by davehakkens** [comment]
You need it for something specific?
Was just looking at the preview in research that looks good to me! 
(figma file is messy, hehe. But can cleanup if you want)
<img width="947" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/210244584-f06ef9c0-ff2a-43cd-b151-f1c7a46f4a51.png">

**Comment by thisislawatts** [comment]
I wanted to double check the following:
* Spacing (padding) between the black borders and content. This means; Between _made by_ and below buttons.
* Check fonts being used for various typographic elements, as the Heading in the original screenshots seem to use Inter whereas the current convention across the site is to use `Varela Round` for Headings.

**Comment by davehakkens** [comment]
Spacing: `Padding: 30px` should be better there instead of `20px`
Font: Good catch, align with the heading component we use.
