### ISSUE TITLE
[feature request] Custom links

### ISSUE THREAD

**Issue by MIfoodie** [ONEARMY/community-platform#2060]
**Is your feature request related to a problem? Please describe.**

You cannot make a custom description for your links on your profile. Example: Twitter, GitHub. This is a problem because when you have multiple social medias or contacts things get messy when they are all the same name.

**Describe the solution you'd like**
In the drop down where you currently select what type of link you want to add, there should be a “custom” option. When you select the custom option, a text box should appear to the left of the link field where you can type what ever you want. text in the “custom” field would become the link type.

i hope this isn’t too confusing. Sorry I’m not able to help make this, I don’t know enough to do that yet :(.

**Describe alternatives you've considered**

**Additional context**

**Comment by davehakkens** [comment]
Thanks for the suggestion @MIfoodie . We will keep it in mind when planning the upcoming issues. But no direct development planned for this now so closing the issue.
