### ISSUE TITLE
[bug] It wants me to save when I haven’t changed anything

### ISSUE THREAD

**Issue by MIfoodie** [ONEARMY/community-platform#2061]
**Describe the bug**
On the page to edit your profile it wants me to save even though I didn’t change anything.
**To Reproduce**
Steps to reproduce the behaviour:

1. Go to your profile settings
2. Click on another link on the page such as the map.
3. It will ask you if you want to save even though you haven’t changed anything.

**Expected behaviour**
i expected there to be no pop up.

**Comment by davehakkens** [comment]
thanks for posting these issues @MIfoodie. A bit weird indeed This would be a good one to pick up for someone!

**Comment by Kiebert** [comment]
Hi @davehakkens you can assign this to me.

**Comment by davehakkens** [comment]
how is this one going @Kiebert, need any help?

**Comment by Kiebert** [comment]
Hi @davehakkens I haven't spent a lot of time on this bug.
Tomorrow afternoon I should have time so let's see.
