### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by MIfoodie** [ONEARMY/community-platform#2063]
**Describe the bug**
On a docs page at the bottom there is a “Edit this page” link. When you click on this you are redirected to a GitHub 404 error page.

**To Reproduce**
1. Go to to [Community Platform Documentation](https://onearmy.github.io/community-platform/). 
2. Scroll down and click “Edit this page”.
3. You will see a GitHub 404 error.

**Expected behavior**
I expected it to send me to GitHub.com/ONEARMY/community-platform

**Comment by thisislawatts** [comment]
Thanks for flagging this @MIfoodie. This is an odd one as the URL appears to be correct when running/building the documentation locally. I wonder if there's something magic happening during the GitHub pages publication which could be affecting the URLs here. 

Build/publish seems to take place as part of this workflow:
https://github.com/ONEARMY/community-platform/actions/workflows/pages/pages-build-deployment

**Comment by davehakkens** [comment]
fixed
