### ISSUE TITLE
Update UI useful button

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2080]
### Description

The useful button could use an UI update to align with the rest of components and make the interaction more clear.
What needs to be done:

1. Move the number in the useful button to the front
2. Switching the active/marked state to make it more prominent
3. Aligning the style to a [default button-component](https://onearmy.github.io/community-platform/storybook-static/index.html?path=/story/components-button--icons)

### Page related
- [How-to](https://dev.onearmy.world/how-to/test-count) header
- [Research](https://dev.onearmy.world/research/testing-mentions) header
- [Call to Action (open PR)](https://github.com/ONEARMY/community-platform/pull/2056#discussion_r1089701275) (coming soon in howto+research)

### Mockup
<img width="775" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/215263027-d5c25ffb-1029-41ee-8d68-2631aef486bd.png">

### Example(s)

![useful_howto_done](https://user-images.githubusercontent.com/13672737/215263422-3780d09a-dab2-4974-b6cf-89d2753ee589.jpg)
![useful_howto](https://user-images.githubusercontent.com/13672737/215263424-c598f2ae-c644-4e07-9bfa-95c8eb21e4ca.jpg)
![useful_research](https://user-images.githubusercontent.com/13672737/215263425-edebd215-c06e-4477-b6f3-c3ba127e1415.jpg)

### Build suggestions
- Have a look/fork at[ this PR](https://github.com/ONEARMY/community-platform/pull/2077/files) as a starting point 
- Watch Figma File [here](https://www.figma.com/file/1n4ed1KjFpZtlNDuifUub1/ONE-ARMY-Community-Platform-(Copy)?node-id=637%3A6225&t=JWneYd69BXLpClWC-1)

**Comment by asheerrizvi** [comment]
@davehakkens I can take this.

**Comment by davehakkens** [comment]
Nice. sounds like a good one for you!
