### ISSUE TITLE
Filter dropdown missing bg on map

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2084]
Issue
On mobile the filter dropdown is missing the bg or is somehow transparent.
Reproduce it here https://community.preciousplastic.com/map

![Screenshot_20230130_130613_Brave (1)](https://user-images.githubusercontent.com/17761877/216157695-367d6776-1efd-4619-92af-3116c767ec3b.jpg)

Ideally it has a white bg for a smoother ux ✌️

**Comment by thisislawatts** [comment]
Thanks for raising the issue @thisismattia, I wasn't able to recreate the bug locally using Chrome/Android. I wonder if you can recreate the behaviour in a private/incognito tab? The reason I ask is that this bug _did_ exist in production in Dec 2022, however a fix was shipped. So I am curious if there is some caching affecting this.

If you do see the behaviour in a clean tab then please can you visit: https://www.whatsmybrowser.org/ and share the information it provides you. This way we can make another attempt at recreating the issue. 

![Screenshot_20230202-195000](https://user-images.githubusercontent.com/472589/216423511-2210866a-9930-4d1d-89f8-48c94f799548.png)

**Comment by davehakkens** [comment]
@thisismattia  I see the same as @thisislawatts, could you test again? Otherwise we close the issue

**Comment by thisismattia** [comment]
Yep just checked again and is resolved. Sorry for the bother, not sure what happened.

**Comment by davehakkens** [comment]
you know exactly what happend
