### ISSUE TITLE
[feature request] Email notification list

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#2091]
**Is your feature request related to a problem? Please describe.**
We've slowly been trying to build infrastructure to allow sending user notifications for various interactions like howto/research like, comment and mention. We would like to send a daily or weekly summary email of any notifications that a user hasn't seen.

**Describe the solution you'd like**
As of #2027 we have an aggregation that automatically collates all unread user notifications in a single `user_notifications` db endpoint. Ideally we want to run a scheduled function (like a cron task) that will process this list on a daily basis, collate a single email for each user with a summary of all notifications, send the notifications and mark as sent on the user profile notifications.

For this issue most likely it will be best to focus on just converting the `user_notifications` list into a format ready for email, and populating to a separate `emails` db collection. The format required should match the [firestore-send-email](https://firebase.google.com/docs/extensions/official/firestore-send-email) extension. It will require an additional call to the firebase-auth system to retrieve the email from the user auth id (example code in `functions\src\admin\getUserEmail.ts`)

**Describe alternatives you've considered**
Sending notifications at the time a notification is triggered instead of a digest, however could become quickly excessive.

**Additional context**
A base template has already been created in #2026, which can be adapted to include retrieved notifications. 

Getting a good workflow setup might be a bit tricky, would likely recommend trying to use the existing spec testing system in functions to test the code that converts the user_notifications list to emails, and viewing the output HTML in a HTML editor to see if it looks as expected.

Additonally as the user_notifications aggregation code has only just been merged it doesn't yet appear in the most recent docker image. I will try to update later this week, but if starting work before then the _easiest_ way to generate the list is to follow the steps from pr #2027 (log in as demo_admin, comment on howto for demo_beta_tester, or vice-versa - this will seed the aggregation). 

![image](https://user-images.githubusercontent.com/10515065/218815834-782baeee-9853-462e-bafe-6b61234871bf.png)

Alternatively could likely just create some mock data

**Comment by davehakkens** [comment]
Are you good for this one @evakill?
Just double checking if its not to overwhelming and falls within your skills/knowledge...

**Comment by evakill** [comment]
@davehakkens yup i'm good to give this a go! will try to get a start this weekend
