### ISSUE TITLE
[bug] Remove effects from ResearchDescription and HowToDescription and fix research routes test

### ISSUE THREAD

**Issue by asheerrizvi** [ONEARMY/community-platform#2095]
**Describe the bug**
Need to remove effects from `ResearchDescription` and `HowToDescription` and fix test for research routes.

**To Reproduce**
No reproduction is required for this.

**Expected behaviour**
The components should work without needing effects to set the initial state.

**Comment by thisislawatts** [comment]
Thanks for picking this up @asheerrizvi
