### ISSUE TITLE
[bug] Admin cant change email

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2108]
**Describe the bug**
✅ User can change their own email.
✅ Admin can edit user profiles.
❌ Admin cannot change user emails

Ocasionally an admin needs to change a mail address, when users lost access to their mail. Currently there is no way to get access back to the account. They cannot login or change email. We cannot change emails (also not in Firebase Backend. )

**To Reproduce**
Steps to reproduce the behaviour:

1. Login as admin
2. Visit a profile
3. Click `edit` (or visit https://community.preciousplastic.com/u/username/**edit**)
4. Scroll down to change the email. You will end up chaging the mail you're logged in with

**Screenshots of current problem**
Below you can find the part to edit the email.
Current mail adress is where the admin is logged in with, not the one from the user.
<img width="870" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/220248651-7ab53071-5a0c-4545-9ce9-681eebfef011.png">

**Expected behaviour**
Admin is able to edit the email of the user. The UI is already there. Just need to make sure you edit the email of the user, not the admin.

**Comment by Kiebert** [comment]
@davehakkens You can assign this one to me.

**Comment by davehakkens** [comment]
thanks for picking up all these very useful issues!

**Comment by AlfonsoGhislieri** [comment]
Did this ever get solved? Is @Kiebert still working on this?

**Comment by Kiebert** [comment]
Hi @AlfonsoGhislieri. I have done two attempts to solve this issue. But still no solution found. If you want to take this issue please go ahead. Or if you have a suggestion please let me know. Thanks in advance.

**Comment by AlfonsoGhislieri** [comment]
Ah I see @Kiebert, sorry to hear that, could you tell me what you've tried? I can have a look!

**Comment by AlfonsoGhislieri** [comment]
I think I'll have a go at this by rendering a different form for the admin, I'll look into this next week!

**Comment by AlfonsoGhislieri** [comment]
Going to have to remove myself from this as I don't have the time to also take this on, but happy to support anyone if they need help.

**Comment by thisislawatts** [comment]
Given this has so far had two different contributors take a look at it I think we need to conclude that `Good first issue` may not be an appropriate tag 🤔

**Comment by thisislawatts** [comment]
@davehakkens is there someone specifically at PreciousPlastic who is looking to do this? It would be great to reach out and verify with them the solution I have come up with.

**Comment by thisislawatts** [comment]
For visibility we are looking a different approach to enable this functionality for admin users :)

**Comment by thisislawatts** [comment]
This behaviour is now available for moderators via a Retool workflow
