### ISSUE TITLE
[bug] Discord link expired

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2109]
**Describe the bug**
For some reason the "join our chat" link to Discord is expired.
Would need to be replaced
Old url: https://discord.com/invite/cGZ5hKP
New url: https://discord.gg/gJ7Yyk4

<img width="228" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/220633258-9ce17f34-81ef-4c68-895a-3128b706e1b8.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. go to the platform on desktop
2. Click the button "join our chat"

**Comment by adityakanu** [comment]
Hey, @davehakkens I am new to open source and would like to contribute to these good first issues. Can you assign me this?

**Comment by davehakkens** [comment]
Good to see you here. Go for it! :)

**Comment by adityakanu** [comment]
Thank you I have done it but I have some doubts before doing the PR
For the commit message what type would this fall under(build|ci|docs|feat|fix|perf|refactor|test)?

**Comment by davehakkens** [comment]
`fix` would be good

**Comment by adityakanu** [comment]
> `fix` would be good

Thanks Dave, I have created the PR kindly review it.
