### ISSUE TITLE
Align how-to CTA component 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2118]
At the bottom of how-to page the CTA component is misaligned. See screenshot below.

https://community.preciousplastic.com/how-to/coaster-from-coffee-waste

<img width="1149" alt="Screenshot_2023-02-22_at_14_16_43" src="https://user-images.githubusercontent.com/17761877/220751960-4de2bc2a-807a-4301-9466-b2d2d14bf3aa.png">

Would be great to simply align it with comments module. 
Thanks!

**Comment by ronaldpaek** [comment]
I want to try to tackle this issue, thank you.

Can you tell me what branching convention you would suggest as well? :)

**Comment by thisismattia** [comment]
Hey @ronaldpaek nice one 🤙
Will assign you the issue. 

Not sure I have the answer to your answer, core maintainers should be able to help asap. 

Thanks!

**Comment by ronaldpaek** [comment]
@thisismattia, for this fix, I have a question the widths of these two elements are not the same length. Is it just an alignment issue, or fixing the width so that it matches the width of the comment?

**Comment by ronaldpaek** [comment]
I think my code should work and pass, all test pass except one
