### ISSUE TITLE
Add "supporter" badge to profiles

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2130]
### Description
We want to introduce a `badge` for people supporting on [Patreon](https://www.patreon.com/one_army). (we recently changed our packages there so people can support specific projects) This is the start of intergrating memberships into the platform, for now the link between Patreon and the Platform will be done manually and it only shows a badge in the profile. But we can continue to build on this in the future

### Page related

Badge will be visable in : Member + Space Profiles `https://dev.onearmy.world/u/username`
Badge will be assigned in: User Profile Edit `https://dev.onearmy.world/u/username/edit` (new issue https://github.com/ONEARMY/community-platform/issues/2131)

### Mockup
![supporter badge](https://user-images.githubusercontent.com/13672737/221417697-4a1cce82-45e7-4a18-8227-bbc99edeccd5.jpg)

### Build suggestion
We already have `badges` intergrated and use it to show `verified` users.  Have a look at that code to intergrate it

Icon.svg download here
[supporter.svg.zip](https://github.com/ONEARMY/community-platform/files/10833946/supporter.svg.zip)

**Comment by thisislawatts** [comment]
Can I work on this one @davehakkens? Should have a PR ready later this evening

**Comment by davehakkens** [comment]
haha yeh sure!

**Comment by thisismattia** [comment]
Yas ♥️ this is sooooo much needed. Question, shouldn't the icon follow users around the website like verified? 
Ideally you want people to see this as much as possible throughout the site.

**Comment by thisislawatts** [comment]
@thisismattia, would we also want to meet explain what 'Supporter' means? I guess that the aim is for there to be *more* supporters

**Comment by thisismattia** [comment]
Yes indeed we need some sort of explanation somewhere on the site for supporter. Just like for verified. Maybe we build the functionality while we design these pages/explanations?

**Comment by davehakkens** [comment]
Agree it would be nice. But it still raises some questions. Do we see the badges on homepage, do we show two badges when they are verified etc. This still requires some design work. (Feel free to make a proposal @thisismattia )

This PR is to add the first basic functionaility.
What I would prefer to see next is for the community managers to use it.
Intergrate the flow to assing badges, since we haven't got a smooth system yet to go from Patreon to Platform.
Once we make sure we can manage this manually we can expand the feature. itself
