### ISSUE TITLE
Add ability for admin to assign badges Frontend

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2131]
### Description

The current way to assign badges for an admin is to do it directly in the Firebase Backend. This is complex and risky. We want to add this ability to the user profiles so admins can do it on the frontend.

Currently we use `badges` for `verified` users. But we are introducing a new one for `supporters` in https://github.com/ONEARMY/community-platform/issues/2130

### Page related
Will be used one user edit page(admin only) : https://dev.onearmy.world/u/username/edit

### Mockup
![admin badges](https://user-images.githubusercontent.com/13672737/221417953-ea7269f9-8492-4362-b9a8-b63fcc7630e5.jpg)

**Comment by thisislawatts** [comment]
Will have a PR for this available in an hour or two. ⏳
