### ISSUE TITLE
Show total amount of useful on user profile.

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2136]
### Description

On the user profiles we want to show the total amount of 'useful' a user gathered.
The useful is gathered through their content (how-to's an research) that other users mark as useful

note: If the user gathered no useful yet, nothing should be shown.

### Page related

Will be used in :

- [User profile](https://dev.onearmy.world/u/username) (spaces and members)

### Mockup
![useful](https://user-images.githubusercontent.com/13672737/221925546-f98056dd-8d08-4787-974a-17a129178704.jpg)

**Comment by AlfonsoGhislieri** [comment]
I can pick this up, should have a little time over the next few weeks!

**Comment by davehakkens** [comment]
cool!
