### ISSUE TITLE
[feature request] Consistent use of alert/modal 

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2154]
### Description of issue

There is an inconsistent use of modals across the website which isn't great from a user experience perspective. An example of this is that deleting comments for research articles and howtos uses `window.confirm`  Modals should be used to replace these window alerts and confirmations.

**Window.confirm**
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/652368/226983301-85ff30be-2072-429a-be13-07855b03e5c5.png">

**Modal**
<img width="857" alt="image" src="https://user-images.githubusercontent.com/652368/226983382-c853957c-ece9-422b-a0c9-7a0bd4fee78a.png">

**Comment by iSCJT** [comment]
I'll get this one done when I've got some time over the next couple of weeks.

**Comment by AlfonsoGhislieri** [comment]
Thanks @iSCJT! Let me know if you have any issues or need any help :-)

**Comment by iSCJT** [comment]
Thanks @AlfonsoGhislieri I was struggling to get the firebase emulators running last night, couldn't work out why it kept hanging.  In the end I changed the docker image slightly and it now boots up ok.

Had a quick look through the code base, looks like it will be pretty simple but I'll let you know if I run into any problems.

**Comment by thisislawatts** [comment]
@iSCJT, I am curious to hear more about the issues you had with the Docker setup. Maybe something it would be useful to raise a PR for?

**Comment by iSCJT** [comment]
> @iSCJT, I am curious to hear more about the issues you had with the Docker setup. Maybe something it would be useful to raise a PR for?

My docker 'fix' is very temperamental, in fact it's not really a fix at all, using an alpine build of node it will successful boot up maybe 1/5 attempts rather than 0/5.  I think it's because I'm on apple silicon, seems to eat all of my available memory and then hang indefinitely, not at a consistent stage either.  Will look into it more and see if I can find an actual solution so that it runs consistently.
