### ISSUE TITLE
bug: map pins rendering with unknown country

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2171]
**Describe the bug**

All map pins are showing the `unknown-flag`

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [Map](https://community.preciousplastic.com/map)
2. Click on any map Pin
3. See error

**Expected behaviour**

Well this is a little unclear, it could show the flag for the current map pin location **OR** the flag associated with the user profile. User profile seems reasonable. 

**Screenshots**
![Screenshot 2023-03-25 at 23 46 07](https://user-images.githubusercontent.com/472589/227746015-a16de0e0-ff13-42de-b319-21078f348b35.jpg)

**Comment by davehakkens** [comment]
<img width="653" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/227746267-a746aa8b-9da4-47d6-b971-9dad547d0797.png">

Same for event page
I think its because originally on those two places it only showed the username. (no flag)

**Comment by thisislawatts** [comment]
![Sad nodding](https://media.giphy.com/media/Ib6HUhF07BzRcma1MD/giphy.gif)

So… another approach here could add a `hideFlag` option to the `Username` component. But it seems preferable to aim for consistency in the UI.

**Comment by davehakkens** [comment]
Agree. Would go for consistency. Its a cool component 💪

**Comment by davehakkens** [comment]
Just noticed on [PK devsite](https://dev.community.projectkamp.com/research) they are also gone in the research module (not on [PP dev](https://dev.onearmy.world/research))
<img width="483" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/227786727-95c6b536-f567-49cf-a0af-212223f1a631.png">
