### ISSUE TITLE
[bug] Tag display doesn't handle multiple categories gracefully

### ISSUE THREAD

**Issue by cerkiewny** [ONEARMY/community-platform#2181]
**Describe the bug**
Multiple categories can be added to tags, however when they are added they don't look so good

**To Reproduce**
Navigate to http://localhost:3000/admin/

1. Go to http://localhost:3000/admin/tags
2. if needed modify existing tag by clicking on int and ctrl+clicking more than 1 category
3. save changes
4. See the bug in the table

**Expected behaviour**
Better separation (coma, semicolon or graphical indication) should be shown

**Screenshots**
how-to + events shown in screenshoot
![image](https://user-images.githubusercontent.com/4504330/228353550-9b197ab8-7b09-465b-98b2-7f0463caf449.png)

**Comment by AlfonsoGhislieri** [comment]
Thanks @cerkiewny, I'm curious how you navigated to http://localhost:3000/admin in the first place. When I try to access the admin page through the website (clicking on my avatar and then admin) I get directed to http://localhost:3000/admin_v2 which is completely different to when I use the link you give and doesn't have fully fledged functionality. Also, interestingly, accessing http://localhost:3000/admin/tags directly also gives a blank page with no rows... 

Curious @davehakkens which page is intended to be used and if there is some duplication or old pages/functionality that is left around here?

**Comment by cerkiewny** [comment]
I manually typed in the address, is it not exposed anywhere?

**Comment by davehakkens** [comment]
http://localhost:3000/admin is the old admin page. But still in use to assing roles like `beta-tester` and `admin` or creating tags & categories.
http://localhost:3000/admin_v2 is the new admin we started working on. Mainly for community managers to have an overview of members and content to moderate. The goal is to expand this and add the features from the original admin panel
Both should be accessible at this point, we use them on live @AlfonsoGhislieri. 
But indeed.. messy

**Comment by AlfonsoGhislieri** [comment]
I see, is there any way to access the http://localhost:3000/admin page from the UI, or is it only reachable by typing the url? Because @cerkiewny I dont think it is exposed anywhere from what I can see. A temporary fix could be at least to move the roles, tags, and categories all to the new admin page to condense this.

**Comment by davehakkens** [comment]
Just gave a test for me the admin pages al work locally for me
<img width="1264" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/233490207-9d8ddfa1-81b4-46ce-b62e-eadb357fbbe2.png">
The old admin panel is only accesible by url. The new one intergrated in the submenu
<img width="156" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/233490817-a8f079d9-9792-4986-b748-821e83ac0e60.png">

Atm the separation is a bit:
**Old admin panel** Complex ui, mainly used by website admins (to configure things)
**New admin** More user friendly and used by community managers (to manage the users and content)
Agree would be nice to have 1 panel, but might need some thinking on what user (role) has access to what features

**Comment by cerkiewny** [comment]
There is still a bug on that screen, if you look at the 9th from bottom categories thingy -> it has 2 categories, they aren't separated by any space or coma, and it looks like "how-toevent" and it should be "how-to, event" or something indicating 2 categories :)

**Comment by AlfonsoGhislieri** [comment]
Yes sorry for sidetracking here @cerkiewny, I’ll add a new issue for the old/new pages so we can chat about that there instead and focus on the bug here.

I think the addition a comma to separate seems like the most logical. Are you interested in taking this up or else I can have a look into it?

**Comment by AlfonsoGhislieri** [comment]
Thanks!
