### ISSUE TITLE
Refactor of components to remove React.FC

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2182]
**Is your feature request related to a problem? Please describe.**
As noted by @AlfonsoGhislieri on #2178 use of React.FC is no longer suggested best practice due to the reasons [mentioned here](https://github.com/facebook/create-react-app/pull/8177).  A number of components in the code base require refactoring.

**Describe the solution you'd like**
Refactoring of components still using React.FC

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/80723794/228361294-75940f45-449d-427d-861f-2b21f0af0713.png">

**Comment by thisislawatts** [comment]
Thanks for raising this, it would be useful if  some linting could be introduced which also restricts usage of this type. 

Perhaps using: `@typescript-eslint/ban-types`

**Comment by iSCJT** [comment]
Good idea

**Comment by SophXN** [comment]
I can work on this.

**Comment by SophXN** [comment]
@thisislawatts regarding `@typescript-eslint/ban-types` - do you have any opinions on whether it should be a light/strong warning or strict error?
