### ISSUE TITLE
Feat/Research redirect url when name changes

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2183]
### Problem
When you change the name of a Research topic to it will update the URL but old links to the previous URL no longer works.

### What we need
We want to keep the old link active but it redirects to the new URL that way any links to the old URL will still be valid.

### Build
We've already added this feature for How-to's in this PR: https://github.com/ONEARMY/community-platform/pull/2064
The same mechanism can be used for the Research topics

### Page related

Will be used in :https://dev.onearmy.world/research

**Comment by iSCJT** [comment]
I'll do this one.
