### ISSUE TITLE
[feature request] Research interactive header elements

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2191]
**Is your feature request related to a problem? Please describe.**

There is a lot of noise at the top of Research/How-to description blocks which get between the user and their objective (reading content!) A particular issue I see is on the mobile where there is a lot of congestion before the user gets to the meaningful content.

This requires some work from @ONEARMY/design 

## Currently it looks like:

Desktop layout:
![Screenshot 2023-03-30 at 20 03 07](https://user-images.githubusercontent.com/472589/228925162-61a6798f-7485-46fd-a8e5-41809675f1e4.jpg)

Mobile layout:
![Screenshot 2023-03-30 at 20 05 37](https://user-images.githubusercontent.com/472589/228925822-02fc4cf5-a277-4c83-8c3d-3b1f954a34e6.jpg)

Original [screengrab](https://github.com/ONEARMY/community-platform/issues/1438#issuecomment-1075024980) for reference:
https://user-images.githubusercontent.com/13672737/159466449-21cf80e7-e165-4d5c-854f-e8056dfb2531.jpg

**Comment by thisismattia** [comment]
eheh that's indeed quite some congestion ;)

**Comment by AlfonsoGhislieri** [comment]
I'm not exactly a desiner but I thought about this a little bit and one approach I could see to remove some congestion could be combining the useful and following buttons into one "engagement" button (better name needed). When clicked it opens a dropdown menu with the option to mark as useful or follow.

I also think it could be nice to have the back button with the Title next to it. Something like this:

[Back] [Article Title]
[Creator] [Creation date | last edit date] 
[Engagement] [Edit]
...

Not too sure where to place the views counter though, could be on the right of the title? Also happy to draw this up if it's of interest.

**Comment by systm-spec** [comment]
Maybe reducing it to the picto is an idea?
![pr](https://user-images.githubusercontent.com/83221877/230112223-12e36c4d-681d-4681-ab63-775d6e1bafda.jpg)

**Comment by asheerrizvi** [comment]
@davehakkens should I wait for @thisismattia to design something or go with the idea @systm-spec has suggested?

**Comment by davehakkens** [comment]
I thought maybe you have a good option @asheerrizvi 
The one from @systm-spec is a good start but not complete yet. For instance the `view` icon is pointless without seeing views.

**Comment by asheerrizvi** [comment]
> I thought maybe you have a good option @asheerrizvi The one from @systm-spec is a good start but not complete yet. For instance the `view` icon is pointless without seeing views.

@davehakkens so I went to the pages and had a look. Here's my two cents:

1. The views text looks like a button but it isn't, it's just text. We should probably place it where the author and the date is and style is more prominently in terms of color if we want.
2. The edit button can probably be just an icon button with the pencil icon. That's pretty much globally recognizable.
3. I also think that we should move "mark as useful" someplace else. There's a lot of space towards the bottom of the card which isn't getting utilized:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/17976252/236848152-a82c7bfe-b39c-4992-bba4-9e341998e201.png">

**Comment by asheerrizvi** [comment]
Maybe "Mark as Useful" can be something like how medium does it? check out the floating buttons in this screenshot:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/17976252/236848451-4f3ab512-7c50-49f3-a502-bde36cd383ce.png">

**Comment by thisislawatts** [comment]
@asheerrizvi do you have access to the Figma assets? It may be worth sketching out some options in that tool.

**Comment by asheerrizvi** [comment]
@davehakkens I don't think so, can you link me and give me access please?

**Comment by davehakkens** [comment]
i think so.. send it over on Discord
But for those that need it in the future, you can find it here
https://www.figma.com/file/nPDwFo0Ee4wcHvtnEGtAu9/ONE-ARMY-Community-Platform

**Comment by Toshthecreator** [comment]
hey all, 

I've mocked-up a stripped back version of the interface with a focus on guiding users to the core of the information as swiftly as possible.

* Title now sits at the top so they know they're on the right track immediately
* 'view contributors' would of course be expandable and show all names when clicked.
* 'Back' button is gone (I think we all have one of those on our browser by now)
* I notice you already removed the 'views' icon.

Anyway, here are the before/ after shots. let me know your thoughts! 👍
![Mobile After](https://github.com/ONEARMY/community-platform/assets/139007488/2e73c5ab-152f-4c80-b154-2b0727cd13f6)
![Mobile before](https://github.com/ONEARMY/community-platform/assets/139007488/edd6d969-eca8-4b87-8dc8-5238eb9666f4)
![Desktop Before](https://github.com/ONEARMY/community-platform/assets/139007488/95783776-4b50-4caf-be08-7b170483dee7)
![Desktop After](https://github.com/ONEARMY/community-platform/assets/139007488/0bf3e1bb-49bd-4745-b99e-bb5430c2f046)

**Comment by Toshthecreator** [comment]
Here's an updated 'Mark as useful' button and expanded contributors section for both desktop and mobile

![Desktop 1 2 Contributors](https://github.com/ONEARMY/community-platform/assets/139007488/8658b336-c838-430e-887c-7ed57848043d)
![Desktop 1 2](https://github.com/ONEARMY/community-platform/assets/139007488/1294193e-d18c-4607-8f8c-3a6622649f63)
![Mobile 1 2 contributors](https://github.com/ONEARMY/community-platform/assets/139007488/7939ab8a-7faa-4c07-8240-befa50522d0c)
![Mobile 1 2](https://github.com/ONEARMY/community-platform/assets/139007488/a8b58b0f-a6ff-43a1-83f9-f6ee001ca14e)

**Comment by davehakkens** [comment]
Closing this to continue in two new issues https://github.com/ONEARMY/community-platform/issues/2735 + https://github.com/ONEARMY/community-platform/issues/2734
