### ISSUE TITLE
[feature request] Add button to delete (or draft) research step

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2199]
**Is your feature request related to a problem? Please describe.**
Currently a user can't delete a research step.  Atm we deleted them directly in Firebase.
_This problem is mainly occuring on newly created steps, not old ones with comments._

**Page**
https://dev.onearmy.world/research/[insert-research-topic-title]/edit-update/

**Describe the solution you'd like**
A button that can delete a research step 

**Describe alternatives you've considered**
Another way to fix the problem is we could add the feature to "save as draft" for the latest step. In this case if a new step gets posted but is not completed enough it could be reverted to a draft. 

**Additional context**
Not sure  how much complexcity this adds in the changing the order of the research articles if an older step gets deleted. Since steps numbers might be linked to notifications or urls.

**Additional context**
![delete research step](https://user-images.githubusercontent.com/13672737/229360757-6f0372f3-6c5b-4a33-b92f-703f7f0cfec9.jpg)

**Comment by thisislawatts** [comment]
Thanks for taking the time to write up these steps. I think we would probably want both options here:
- The ability to unpublish something
- The option to delete a step


In fact you could argue that a deleted status is similar to the draft status, the post is not publicly accessible but available for the author. Think of it as the trash/recycling bin common to most operating systems, so it's still there for a period of time to recover if the author changes their mind.

**Comment by davehakkens** [comment]
Agree both are useful.
Should we keep both in one issue or split them?

**Comment by thisislawatts** [comment]
I think a single issue is reasonable, there may be multiple PRs required to deliver the changes but that would be for the implementer to decide

**Comment by thisislawatts** [comment]
I think this has already been closed by: https://github.com/ONEARMY/community-platform/issues/2199
