### ISSUE TITLE
[feature request] Change icon color when following

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2200]
**Is your feature request related to a problem? Please describe.**
We recently added the option for user to follow a research here https://github.com/ONEARMY/community-platform/pull/2145
But the active/non-active state is not very clear.

**Describe the solution you'd like**
Once the button is toggled (user is following) the icon should be colored.
(color can be same as the active notifications icon)

**Describe alternatives you've considered**
This is part of a bigger design issue outlined [here](https://github.com/ONEARMY/community-platform/issues/2191) to improve the UI of that area.

**images**
<img width="503" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/229550469-86422513-bf50-4044-91c9-23f370785df0.png"> 
<img width="190" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/229551332-89a5dde2-f946-4668-b11b-6fb083c97fb0.png">

**Comment by NoHara42** [comment]
I could take on this one as a first issue!
@davehakkens mentioned this one was relatively urgent, what's the time-frame roughly?

**Comment by davehakkens** [comment]
Ideally before the weekend 😇
