### ISSUE TITLE
[feature request] Dont mention all contributors on research steps

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2222]
**Is your feature request related to a problem? Please describe.**
Currently you can see to many contributors on a research step. You loose track of who is the creator and who just did some small grammar fixes.

**Describe the solution you'd like**
Dont mention contributors that `edit` research steps only that `create` steps

**Example of the problemt**
Is can be found in the research module here. [Step 6](https://community.projectkamp.com/research/how-can-we-protect-our-outdoor-wooden-structures-long-term)
<img width="1002" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/231543907-a0b71bad-5b8e-4d4c-8836-0b79587da4d7.png">

**Comment by davehakkens** [comment]
Agree this would be a better and more complete solution.
So show the creator on the frontend, store the data of contributors on the backend. To be figured out later how to best use it.

**Comment by alexHoggett** [comment]
Hey everyone, I'd like to give this is a go so long as it's still an open issue.

**Comment by davehakkens** [comment]
Just checking in. How is this one going @alexHoggett ?

**Comment by iSCJT** [comment]
Putting this one back to the pool @alexHoggett, if you want to carry on with it just let us know.
