### ISSUE TITLE
[feature request] Low visibility for creating a new research 

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2224]
I noticed that it may become an issue to have the add reserach button at the bottom of all the research articles, this has very low visibilty and will get worse as more get added. Should this maybe get moved to the top? I know this doesn't affect many users, but just thought it might be worth considering.

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/652368/232292152-96d2e3e6-c46a-4b57-a19c-71f16c84a4b9.png">

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/652368/232292091-9f92579c-4b90-4388-ad3b-a2a0bc2da136.png">

**Comment by davehakkens** [comment]
Agree. could use a better place. Ideally its similair to how-to's to keep consitent. 
But this page is a bit different so needs some thinking (also for mobile)

**Comment by iSCJT** [comment]
Added button to top as page as part of #2279
