### ISSUE TITLE
[bug] Useful votes not working correctly

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2231]
**Describe the bug**
Useful count is not working as intended, it seems like the aggregations are messing up and that clicking useful on a howto or research is affecting another unrelated item. This is most likely related to the bugs that have been reported by @thisismattia 

It seems to me like all of the research aggregations may not be actually working properly and that only the howto aggregations are working but still affecting the research articles like seen in the video below.

**To Reproduce**
Follow steps like in video:

At the start the Howto has a useful count of 1, after a research useful count is decreased it also affects the howto's count. They seem to be interlinked.

https://user-images.githubusercontent.com/652368/233655059-fe1ebcde-aa80-4100-99c7-1e624dc8040b.mov

**Expected behaviour**
Clicking useful on a Research or Howto should not affect entities that are not the specific one in question

**Comment by davehakkens** [comment]
ai.. This would be quite an important one to look into

**Comment by iSCJT** [comment]
Can someone tag me on this please.
