### ISSUE TITLE
[bug] Upload file not working in howto

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2244]
**Describe the bug**
Can't upload a file and then publish or edit a howto

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'howto' you authored / create a howto if you havent
2. Click on 'edit.'
3. Scroll down to 'Or upload your files here'
4. Upload file
5. Try to revert to draft or publish

**Expected behaviour**

You should be able to revert to draft or publish when uploading a file

**Screenshots**

https://user-images.githubusercontent.com/652368/234537935-cd000a2d-8329-4c8a-9c37-2509252635fc.mov

**Additional context**

**Comment by davehakkens** [comment]
I just tried this (in a preview link)
Seems to work here...
<img width="411" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/234852066-b4f1a94b-d619-4240-845a-9d4177386362.png">
What happend in your case, couldnt click publish?

**Comment by AlfonsoGhislieri** [comment]
This happens everytime when editing the howto, I didn't check when creating it. I will add some tests to address this bug and work from there!

**Comment by davehakkens** [comment]
tried it a bit more.
✅ It works if you edit/add files to a howto that had no files before.
✅ It works if you edit/replace uploaded files by another uploaded file
🉐 It does not work when you try to edit a how-to that had files uploaded before and want to replace it by a URL to download

**Comment by AlfonsoGhislieri** [comment]
Thanks for this @davehakkens, good to know exactly which behaviour is currently bugged!

**Comment by AlfonsoGhislieri** [comment]
So finally understood what the issue is, this issue exists for both updating and creating. Basically the way it is currently setup you can EITHER upload a file or add the download link. You can't do both which I think is the intended design? The issue here is that the user has no way of knowing that they need to remove one of the two file download options in order for them to upload/edit. 

The issue is that the following code seems to not be working:

`  public checkFilesValid = (formValues: IHowtoFormInput) => {
    if (formValues.fileLink && formValues.files.length > 0) {
      this.setState({ showInvalidFileWarning: true })
      return false
    } else {
      this.setState({ showInvalidFileWarning: false })
      return true
    }
  }`

Going to try and get this back to working!

**Comment by davehakkens** [comment]
thanks for digging in it.
Yeh there used to be a message there for the user. Like here in the original issue https://github.com/ONEARMY/community-platform/issues/1609

**Comment by AlfonsoGhislieri** [comment]
I've added it back, must have been removed at some point... Going to make some tests to make sure this is now going to be covered going forwards!

**Comment by davehakkens** [comment]
great. thanks a lot
