### ISSUE TITLE
[devops] 🐌 Slow CircleCI build times

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2249]
**Describe the bug**

The dependency installation process runs for 1-2mins at multiple stages within the deployment pipeline. This unnecessarily slows down the feedback cycle and wastes a bunch of compute time. This is bad for the planet and developers. 

**To Reproduce**

1. Take a look at any of [the build pipelines](https://app.circleci.com/pipelines/github/ONEARMY/community-platform).
2. Check one of the jobs, ie. Unit tests
3. See that _install dependencies_ has run for a few minutes or more.

**Expected behaviour**
Dependency installation should run only run twice (once for all dev dependencies and again for production dependencies)

**Comment by inad9300** [comment]
I've been doing some experiments in this area. I couldn't figure out why this is a problem in CI while it works normally locally, but I did find that adding `enableScripts: false` to `.yarnrc.yml` speeds things up quite a bit, while probably being a good idea anyway.

Other secondary findings:
- Upgrading to `cimg/node:20.4.0-browsers` didn't help.
- Dependency `@types/jest` targets version `^27.4.3`, but `27.4.3` doesn't exist (`27.4.1` is the latest). I would recommend avoiding wildcards in `package.json` in general; with such complex dependency graph, I feel like the more control you have over which exact packages are being pulled, the better.

I will try to create a pull request in the incoming days if nobody does it first 🙂
