### ISSUE TITLE
Add drag and drop reordering for images uploaded to how-to steps

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#227]
Sometimes can happen that a user uploads pics in a step in the wrong order. We should enable users to move pics up and down to fix this little issue

child of #3

**Comment by BenGamma** [comment]
When creating a how-to on the page `https://dev.onearmy.world/how-to/create`, you can upload multiple images to a step. For now the images are displayed in the uploaded order and if you want to change this order, you need to manually delete the uploaded image (by clicking the top right cross on it) and reupload in the wanted order. It can be painfull/long when you have a lot of images.
The wanted behavior here is the ability to drag and drop images up and down to change their order.

**Comment by mattia-io** [comment]
@sanjuskm05 is working on this  🥳

**Comment by sanjuskm05** [comment]
@BenGamma @chrismclarke Do we have an edit feature for the "How to" and its steps? If not, i think we should address that first. Also, I was thinking can we address reordering or steps rather than drag and drop the images. 'Drag and drop' feature could be more helpful when we are creating and editing.

**Comment by chrismclarke** [comment]
Issue is there (#103) but nobody is currently assigned to it. Your call if you want to first work on images, editor or anything else. Reordering steps would also be a good feature, in the past I've used libraries like [dragula](https://github.com/bevacqua/dragula) but sure there are plenty of options out there so might be worth a quick bit of research. In all of these cases we're essentially just talking about ways of reordering arrays.

**Comment by sanjuskm05** [comment]
thanks for the input on dragula. I will try to implement this.

**Comment by chrismclarke** [comment]
I think there might be more popular choices for react:
https://www.npmjs.com/search?q=react%20drag%20and%20drop&ranking=popularity

Will leave you to experiment and see what works

**Comment by chrismclarke** [comment]
https://www.npmjs.com/package/react-beautiful-dnd seems particularly nice

**Comment by mattia-io** [comment]
@sanjuskm05 I know you said you won't be able to help us anymore for the time being but are you gonna complete this issue or shall I de-assign you from this?
Thanks for your work so far 👊

**Comment by sanjuskm05** [comment]
Thanks. Please unassign it

**Comment by chrismclarke** [comment]
Thanks for the update, I see you have been unassigned and I have just added back the `Help wanted` label. I would suggest you unsubscribe from the thread if you wish to stop receiving notifications on it (totally optional of course)

**Comment by drydenwilliams** [comment]
I've used [`react-sortable-hoc`](https://github.com/clauderic/react-sortable-hoc) for re-ordering before which works really nicely.

**Please note:** We do not currently have ability on the backend for image ordering.

**Comment by chrismclarke** [comment]
merge into #939
