### ISSUE TITLE
[bug] Useful counter profile not accurate

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2277]
**Describe the bug**
We recently introduced the useful counter on profiles here https://github.com/ONEARMY/community-platform/pull/2233  (only visable for beta-testers)

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [research overview](https://community.projectkamp.com/research) to see the gathered useful
2. Compare with the[ user profile](https://community.projectkamp.com/u/projectkamp)(make sure you are a beta-tester to see total useful in profile)

**Expected behaviour**
It should show the total amount of useful in the profile

**Screenshots**
Total useful on Project Kamp Profile (4)
<img width="770" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/235456469-3fe48385-0f74-46ed-847b-4865237873bf.png">

Total useful this account got (+40)
<img width="1305" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/235456540-ad689d8c-568c-429a-977b-484c554ee15f.png">

**Comment by AlfonsoGhislieri** [comment]
This issue is linked also to #2231, aggregations are clearly not working as intended.

**Comment by iSCJT** [comment]
Can someone assign me to this please.
