### ISSUE TITLE
[bug] Userflags of contributors are not shown in Research

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2278]
**Describe the bug** 
The country flags of the contributors are not shown in the research module

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [a research topic](https://community.projectkamp.com/research/make-a-basekamp-extension-in-a-container)
2. Scroll down the page
3. Flags are grey
4. Click the username to see the profile with original flag

**Screenshots**
<img width="650" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/235475150-528099f6-0151-437a-8d89-d920556fedf8.png">
<img width="433" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/235475181-d3010b93-b42b-46c9-b3e1-c3c16b6b722c.png">
<img width="379" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/235475206-e5d7d967-228e-47eb-90d7-a2b39198d37b.png">

**Comment by AlfonsoGhislieri** [comment]
Taking this, I think I know the issue, contributors probably need to have their country fetched from the userStore.

**Comment by AlfonsoGhislieri** [comment]
Follow up question @davehakkens , with what could be added after. Do we want to have verified also showing for contributors?

![image](https://user-images.githubusercontent.com/652368/235682017-e77049ae-5e67-4098-b1d9-d39c60fa4f72.png)

**Comment by davehakkens** [comment]
Not needed at this point. So if we can hide it would be good!
If not no worries and display it :)

**Comment by AlfonsoGhislieri** [comment]
All good its hidden in the current PR, was just curious if this was a future issue of interest!
