### ISSUE TITLE
[bug] updating user location updates research article

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2283]
**Describe the bug**

When you change your location on your profile page it triggers an edit of all the research articles you have created, seems to be that the countrycode is being stored in the research and the user and research are intertwined. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Research'
2. Click on 'Username' of the creator an older research article
3. Switch to admin mode
4. Click edit
5. Change location of user on the page you are viewing
6. Save changes
7. Go back to research page
8. See error that all research articles created by this user are now showing as just edited and at the top of the list

**Expected behaviour**
Updating user location should not trigger the update of research articles, these two things should probably be decoupled.

**Screenshots**

**Additional context**

**Comment by SophXN** [comment]
I can work on this if no one else has started

**Comment by SophXN** [comment]
@AlfonsoGhislieri My apologies for not following up, gosh time flies so fast. 
I did look into this however unable to solve at the moment. Maybe we can pair sometime on it this week or next weekend? 
Or, i'll leave my notes below and feel free to unassign me if you need someone else to take over and get this done.

**Comment by AlfonsoGhislieri** [comment]
Hi sorry for not getting back to you here @SophXN, I've been quite busy in the last week, and still now is not great time wise. If you could drop any of your notes I could have a look at the issue and see where to go from there!

The main issue I would assume is that the user's location is probably stored in the research document as well as the user document as well?

**Comment by thisislawatts** [comment]
👋🏻 Heya @AlfonsoGhislieri, @SophXN, I am going to pick this one up if thats okay with you.

Currently my thinking is we want to go from storying the author country on the Research document and instead fetch it off of the user object.

**Comment by AlfonsoGhislieri** [comment]
@thisislawatts absolutely that’s the implementation I was thinking… I completely forgot/didn’t realise I was even assigned to this issue..

**Comment by SophXN** [comment]
Thanks sorry I’ve still been with no laptop but will be back on picking up
tickets this week!

**Comment by pizzaisdavid** [comment]
fixed with: https://github.com/ONEARMY/community-platform/pull/3646

Someone please click close on this issue.
