### ISSUE TITLE
[refactor] Remove direct usage of Theme from "Logo.tsx"

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2307]
Remove the following

```ts
// TODO: Remove direct usage of Theme
import { preciousPlasticTheme } from 'oa-themes'
const theme = preciousPlasticTheme.styles
```

At the moment we are importing the theme object directly and accessing its style properties. We should avoid doing this and instead make use of `sx` property available on all ThemeUI components to load these values out of the theme definition.

Read more about it here: 
> The `sx` prop lets you add any valid CSS to an element, while using values from your theme to keep styles consistent. You can think of the style object that the `sx` prop accepts as a _superset_ of CSS.
https://theme-ui.com/sx-prop

The aim should be for there to be no visual differences. However there may be circumstances where this would introduce better visual consistency across the UI. Feel free to reach out on [Discord ](https://discord.com/channels/586676777334865928/938781727017558018) if you think you have found one of those scenarios.

Here's an example where the same change has been made, although I would call out that this specific file required more work than most 🤗  https://github.com/ONEARMY/community-platform/pull/2282

**Comment by BaltacMihai** [comment]
Hola , Can i work on this ?
