### ISSUE TITLE
[feature request] Merge admin and adminv2

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2321]
**Is your feature request related to a problem? Please describe.**

There are two admin areas:

* Legacy – http://localhost:3000/admin
* New – http://localhost:3000/admin_v2

**Describe the solution you'd like**

These should be consolidated into a single admin area.
* Ideally, ensure all of the functionality from legacy admin (`/admin`) is available in the new admin (`/admin_v2`).
* New admin routes are moved to exist on the `/admin` URL

**Comment by CDeighton** [comment]
@thisislawatts do you mind if I grab this one?

Looks to me like only Tags and Categories are left to move given that there is already a nice new users page:

<img width="1914" alt="Screenshot 2023-06-22 at 6 31 42 PM" src="https://github.com/ONEARMY/community-platform/assets/13475443/f154c32b-5b3e-43cc-b8be-7342c681ec2b">
