### ISSUE TITLE
[bug] White screen of Death 💀 

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2324]
**Describe the bug**

Regular visitors to the site are intermittently presented with a blank screen. This is because the primary JS/CSS bundles have failed to load. This is a result of a new release being rolled out. 

**To Reproduce**
Steps to reproduce the behaviour working locally. 

1. `npm run build`
2. `npx serve -s build`
3. Delete/rename one of the JS files in dist
4. Witness the white screen of Death

It is worth noting that this demonstrates the failure state of the site when part of the JS bundle is missing, rather than strictly recreates the behaviour in our deployments. 

**Desired Behaviour**

* No error state, partial errors should deployments do not cause a white screen of death.
* OR a meaningful error about broken build

**Screenshots**

![169112328-1aabdc2d-33f7-4668-8b26-88460f2dcfd5](https://user-images.githubusercontent.com/472589/236466129-025ed503-29d5-4e3c-b523-b1a0b15a1c89.jpg)

**Additional context**

* Discord feedback - https://discord.com/channels/586676777334865928/1103192067083087882/1103192067083087882

**Comment by davehakkens** [comment]
Is there a way to see how many users get this screen? In analitics or something?
Seems like a very crucial bug, would be curious how many users it effects

**Comment by thisislawatts** [comment]
@davehakkens we will first need to add some logging/error handling to better understand the extent of the problem.

**Comment by davehakkens** [comment]
I'm currently getting white screen on live on firefox, not chrome.
Might help in debugging...


https://github.com/ONEARMY/community-platform/assets/13672737/94b2010f-df1f-4615-95b9-ed637baa870e
