### ISSUE TITLE
[enhancement] Admin – Include Username in notifications listing

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2327]
**Describe the bug**

Would it be possible to add username or link to profile here? This will be quite useful for testing and trouble shooting for admins. To understand what happens and connect with users.  

**Screenshots**
![AdminNotification](https://user-images.githubusercontent.com/472589/236497935-e1345469-23d4-4055-8bb3-dcef7941ede8.jpg)

**Comment by asheerrizvi** [comment]
@thisislawatts I can try this one out.

**Comment by asheerrizvi** [comment]
@thisislawatts I can try this one out.

**Comment by thisislawatts** [comment]
Closed by @evak in https://github.com/ONEARMY/community-platform/pull/2351
