### ISSUE TITLE
[feature request] allow use of multiple role options in AuthWrapper

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2329]
**Is your feature request related to a problem? Please describe.**
[AuthWrapper](https://github.com/ONEARMY/community-platform/blob/master/src/common/AuthWrapper.tsx) currently allows a single role to be provided for the roleRequired property.

**Describe the solution you'd like**
Ability to provide multiple role options as an array, for example ['beta-tester','admin'].

**Describe alternatives you've considered**
Currently if multiple roles required access to a certain feature you would need to duplicate the element, not a good alternative.

**Additional context**
N/A

**Comment by thisislawatts** [comment]
Hey @VincentNikkelen, thanks for taking the time to write up your thoughts. I [totally agree](https://github.com/ONEARMY/community-platform/pull/2595#issuecomment-1627240663) and whilst permissions are not something we have on near term roadmap to revisit this work does need doing. 

I think we probably need a separate Issue/Feature Request as a starting point for that discussion.
