### ISSUE TITLE
[bug] Cant post update in Research Module

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2330]
**Describe the bug**
Two (out of three) users reported they can't upload an update to a research on Project Kamp. 
It's gives the message `beta-tester role required to access this page`
We tried refreshing and using another browser. 

**Expected behaviour**
all three users have a beta-tester role.
[marionagimenez](https://community.projectkamp.com/u/marionagimenez) **can** post updates [kevincheung](https://community.projectkamp.com/u/kevincheung) and [kaegh](https://community.projectkamp.com/u/kaegh) **can not**.
<img width="961" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/236638699-81b567c2-37f4-422d-903d-e69dea337a7e.png">

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/13672737/236638682-0f0a5ab7-b64f-413a-93bb-a27be824602c.png)

**Additional context**
All three are added as a contributor to an existing research topic

**Comment by thisislawatts** [comment]
Interesting 🤔 I am seeing a similar bug in an e2e test.

Somewhat related, do we think that Research should still only be for `beta-users`?

**Comment by iSCJT** [comment]
Something cache related?

**Comment by thisislawatts** [comment]
@davehakkens Can you include which Research article this was?

**Comment by davehakkens** [comment]
this one for [kaegh](https://community.projectkamp.com/u/kaegh): 
https://community.projectkamp.com/research/making-a-sturdy-single-person-tent
this one for [kevincheung](https://community.projectkamp.com/u/kevincheung)
https://community.projectkamp.com/research/can-we-turn-invasive-trees-mimosa-into-something-useful

> Somewhat related, do we think that Research should still only be for beta-users?

Dont think we are ready yet to release public on Project Kamp. The mission + moderation is not yet in place. Would be more ready for Precious Plastic though

**Comment by thisislawatts** [comment]
Interesting both of these humans have 2 entries in the `v3_users` table associated with their usernames.

![Screenshot 2023-05-07 at 13 41 27](https://user-images.githubusercontent.com/472589/236675332-0eab77df-a5e5-4838-aa25-30141a3810c9.jpg)

I will need to root around in the code bit more to understand the why here. But I believe that there is a manual intervention I can make that will fix this. 

Note the creation dates on `kaegh` 2 user objects:
* 2023-04-03T17:18:47.891Z
* 2023-04-03T17:18:47.891Z

**Comment by davehakkens** [comment]
Thanks for digging. 
This double entries for certain usernames gets a bit messy.. I thought it was a thing from the past, but still seems to happen with newer accounts as well. I'd be up for manual intervention for now!

**Comment by thisislawatts** [comment]
Any idea how these accounts were created? I attempted to recreate the issue by going via the Join use flow and ended up with a single entry in `v3_users` each time.

**Comment by thisislawatts** [comment]
In the meantime I have removed the user accounts, so the ones remaining have the userName as the _id

**Comment by davehakkens** [comment]
> Any idea how these accounts were created? I attempted to recreate the issue by going via the Join use flow and ended up with a single entry in v3_users each time.

Not sure.. But this also reflects in the admin panel. Maybe a duplicate for everyone that gets a beta-tester role?
<img width="1203" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/236677708-54a50781-abe6-44e8-b5b8-2424100422aa.png">

 I think @chrismclarke knows more about this.

**Comment by thisislawatts** [comment]
I would welcome a second set of eyes here, but this looks to be the bug to me. We're writing User documents using the `._authID` property rather than the `_id` property.
https://github.com/search?q=repo%3AONEARMY%2Fcommunity-platform%20doc(updatedUser._authID)&type=code

**Comment by iSCJT** [comment]
Duplicate user issues have been addressed through various pr's and manual data fixes.
