### ISSUE TITLE
[feature request] Add follow button to Research CTA

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2332]
**Is your feature request related to a problem? Please describe.**
We recently introduced the `follow` button for the research module. It's shown in the header but is easy to forget after scrolling down a research.

**Describe the solution you'd like**
Add the `follow` button to the CTA on the bottom on the research (same as done with useful button)

**Visual**
![follow](https://user-images.githubusercontent.com/13672737/236672630-888ab8e2-c8b8-436f-bd1c-fbd30a29d988.jpg)

**Additional context**
The CTA components is also used in the how-to module. But there we do not want to display a follow button. Only the research module

**Comment by asheerrizvi** [comment]
@davehakkens I can take this up.

**Comment by achiverram28** [comment]
can I work on this
