### ISSUE TITLE
Show follow button for non-logged in users

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2337]
### Description

We want to make the follow button we just released (https://github.com/ONEARMY/community-platform/pull/2331) visable to non-logged in users.
It can use the same function as the useful button. Using a tooltip that says "login to follow"

### Page related

All research topics
https://dev.onearmy.world/research

### Mockup

![tooltip](https://user-images.githubusercontent.com/13672737/237023451-44a06431-9ce8-4e26-a94c-5b7c08cba405.jpg)

**Comment by soumya-b019** [comment]
@davehakkens Hey! I can try on this one.

**Comment by davehakkens** [comment]
Go for it! Thanks for helping

**Comment by achiverram28** [comment]
Hey can I also work on this?

**Comment by AlfonsoGhislieri** [comment]
Hi @soumya-b019, thanks for taking this on! You can find the button in question in the [Research Description](https://github.com/ONEARMY/community-platform/blob/master/src/pages/Research/Content/ResearchDescription.tsx#L107), let me know if you have any questions or need any help.

**Comment by soumya-b019** [comment]
Hey! @AlfonsoGhislieri I'm done with the conditional rendering part and now I'm trying to understand the tooltip part where it is using the same function as the useful button.
