### ISSUE TITLE
[feature request] Pull wrappers and mocking out of individual test files and into utils file

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2341]
**Is your feature request related to a problem? Please describe.**

There is too much duplication of wrappers and mocking in test files like can be seen in [ResearchArticle.test](https://github.com/ONEARMY/community-platform/blob/04c8b7f822f2e0fdeb328502f0bb617b3dcd8c69/src/pages/Research/Content/ResearchArticle.test.tsx#L23) and [ResearchUpdate.test](https://github.com/ONEARMY/community-platform/blob/04c8b7f822f2e0fdeb328502f0bb617b3dcd8c69/src/pages/Research/Content/ResearchUpdate.test.tsx#L13). When changes are made tests have to be fixed across different files.

**Describe the solution you'd like**

These wrappers should be imported instead from a common utils file, similarly to what was added for theme in #2340 to improve the developper experience.

**Comment by benkelaar** [comment]
I was looking for a good first issue to pick up, and this one seems to be the only one available, but I'm uncertain what the scope of the request is exactly.

Is it primarily the mocking of the useCommonStores method and setup of the mockUser?

Isn't it better to resolve that issue at the root as is suggested in the comments [here (in Academy.test.tsx)](https://github.com/ONEARMY/community-platform/blob/master/src/pages/Academy/Academy.test.tsx#L8) and [here (in research.routes.test.tsx)](https://github.com/ONEARMY/community-platform/blob/master/src/pages/Research/research.routes.test.tsx#L19)?

**Comment by AlfonsoGhislieri** [comment]
Hi @benkelaar, sorry for just getting to you now on this was away on holiday!

Thanks for taking the time to look at this, I proposed the exporting of these already existing wrappers as a simpler solution to address the messy code. We could certainly explore a mock store, I just wonder if this is potentially adding an unecessary level of complexity/work that we don't need at this stage?

Maybe @iSCJT @thisislawatts have some thoughts/can weigh in here?

**Comment by leoasimon** [comment]
Hi @AlfonsoGhislieri

I'm looking for a good first issue to work on, and it seems like this one hasn't been tackled yet.
Am I good to start working on it?
