### ISSUE TITLE
[bug] safari contact details auto complete blocking notification frequency dropdown

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2343]
**Describe the bug**
Safari's built in contact details autocomplete is blocking the notifications frequency dropdown in beta profile settings screen.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open safari when autocompletion of contact details is enabled
2. Go to profile settings page for user with beta-tester role
3. Try to change notification frequency

**Expected behaviour**
Need to find a way to suppress the popup, safari is checking more than just the input field itself.

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/80723794/a3d4a3b4-191a-4f43-b460-7586eb860899)

**Additional context**

**Comment by davehakkens** [comment]
You have this in other dropdowns in the site, or only the email notifications?

**Comment by iSCJT** [comment]
> You have this in other dropdowns in the site, or only the email notifications?

@davehakkens I've only noticed it on this one.

@payalpm thanks for wanting to help with this 😃

- run the platform locally and open using safari
- login with the following details:

demo_beta_tester@example.com
demo_beta_tester

- navigate to http://localhost:4000/settings
- scroll down the page and you should be able to see the email notifications beta section.

This is the file that relates to the section: https://github.com/ONEARMY/community-platform/blob/master/src/pages/Settings/content/formSections/EmailNotifications.section.tsx

**Comment by payalpm** [comment]
@iSCJT safari version possible in windows

**Comment by payalpm** [comment]
@davehakkens @iSCJT This error is caused by Safari's built-in contact auto-completion feature. This feature attempts to auto-complete the email address in the input field when the user starts typing. To fix this error, you need to turn off the autocomplete feature for the input field. To do this, set the disableAutocomplete property to true on the select component.

**Comment by payalpm** [comment]
@davehakkens @iSCJT <Field name="notification_settings.emailFrequency">
          {({ input }) => {
            return (
              <Select
                options={emailFrequencyOptions}
                defaultValue={defaultValue}
                onChange={({ value }) => input.onChange(value)}
                disableAutocomplete
              />
            )
          }}
        </Field>try this i think work it

**Comment by davehakkens** [comment]
hey @payalpm. Thanks for looking into it.
But in order to get the code in you need to out the code in, test it and if it works make a PR which we can merge in.

**Comment by payalpm** [comment]
Ok i will check it out can u clear my safari browser possible in windows?

**Comment by iSCJT** [comment]
> Ok i will check it out can u clear my safari browser possible in windows?
> […](#)

I don't think safari is available on Windows anymore.  If you add a pr I can test if it works on safari on mac for you but otherwise might need a mac user to take this one on.

**Comment by payalpm** [comment]
Ok, I'll check it out.

**Comment by iSCJT** [comment]
Adding back to pool as needs a mac user to investigate.

**Comment by BeeMargarida** [comment]
Hi! I tried replicating this on Safari running on the latest version of the master branch, it seems like it's fixed. Also could not replicate in dev.

**Comment by payalpm** [comment]
Ok I will reasearch then i tell you
