### ISSUE TITLE
[feature request] Change text follow notification 

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2346]
**Is your feature request related to a problem? Please describe.**
It's unclear why you get a notification of certain actions. This can bring confusement

**Describe the solution you'd like**
Change the text from the `follow` notification

**Now:**
[Eike ](https://community.projectkamp.com/u/eike)posted an update to their [research article](https://community.projectkamp.com/research/can-we-turn-invasive-trees-mimosa-into-something-useful)
**Next:**
[Eike ](https://community.projectkamp.com/u/eike)posted an update to this [research](https://community.projectkamp.com/research/can-we-turn-invasive-trees-mimosa-into-something-useful) you follow

**Notifications here**
<img width="296" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/2c1c126f-65bc-44a9-b980-800f94e5249b">

**Comment by tungbq** [comment]
Do you need help? May I pick up this task?

**Comment by tungbq** [comment]
Hi @ONEARMY/maintainers, it's good to see the work completed, I just curious how could we avoid duplicated work like this case? Actually, I have commented to the issue before the PR raise.
