### ISSUE TITLE
The website is not very visually appealing. The design is outdated and it does not look very professional.

### ISSUE THREAD

**Issue by payalpm** [ONEARMY/community-platform#2361]
### Description

Write a quick descritpion of what is the component for, and as mainy details you consider useful to the person that will have to build it.

### Page related

Will be used in :

- Related page name (#issue-number)

### Mockup

[Add here the mockup of the component]

### Example(s)

If you have any examples of existing similar components, add the link here. It can be a link to a code snippet and/or to a page of a projet/website where we can interact with the similar component.

### Build suggestion

Here describe how you would build it, briefly but clearly. For example : the component MyComponent will take 2 props : `prop1`& `prop2`. It will extend the existing `Heading` component.

**Comment by davehakkens** [comment]
Thanks for the feedback. But closing this issue since its to abstract for someone to work on.
If you want to talk about this more you can also join our Discord, we have a channel specially for design! :)

**Comment by davehakkens** [comment]
It's in the readme. 
But here as well https://discord.com/invite/SSBrzeR
