### ISSUE TITLE
[bug] Small Button height has been increased

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2369]
**Describe the bug**

_Current_ The small button size has the same height as the default button.

![Screenshot 2023-05-20 at 07 34 02](https://github.com/ONEARMY/community-platform/assets/472589/695027a8-bf9c-4372-b216-84f51b1127f0)

_Previous_ The small button size has a different height to the default button

![Screenshot 2023-05-20 at 07 35 51](https://github.com/ONEARMY/community-platform/assets/472589/e35cd619-0dcc-407f-b647-b129709af38c)

Suspected cause:
https://github.com/ONEARMY/community-platform/blob/master/packages/themes/src/common/button.ts#L13

Possible options: 
* Drop hard coded height definition (missing context on why it was added)
* Add hard-coded height definition for small button variants

**Comment by Mayank2808sharma** [comment]
Hi,
can you please explain what do you mean by these points:-

Drop hard coded height definition (missing context on why it was added)
Add hard-coded height definition for small button variants
