### ISSUE TITLE
[feature request] allow admin and users to have dialog related to a post awaiting approval

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2378]
**Is your feature request related to a problem? Please describe.**
Before how to and research articles are approved they may need some changes to be made, it is currently hard for moderators to have conversations with the user to let them know what needs changing.

**Describe the solution you'd like**
This would build on top of https://github.com/ONEARMY/community-platform/issues/2377 and allow admins and the user to have back and forth conversations linked to the respective how to or research item prior to approval.

**Describe alternatives you've considered**
User and admin could have email conversation.

**Additional context**

**Comment by AlfonsoGhislieri** [comment]
This would still require email notifications each time a message is posted right?

**Comment by iSCJT** [comment]
Yes I think so.

**BLOCKED** by #2377
