### ISSUE TITLE
[feature request] add ability to filter how to / research list by created by user

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2380]
**Is your feature request related to a problem? Please describe.**
No problem as such, nice to have feature or improvement [raised on discord](https://discord.com/channels/586676777334865928/1110629403857268766).

**Describe the solution you'd like**
Improvements to search feature so that it is possible to specifically search by created user.

**Describe alternatives you've considered**
Manually check list for items created by user interested in.

**Additional context**

**Comment by davehakkens** [comment]
I think this is already possible in how-to's. (just noticed it gets very slow though)
Or mean more like a site wide search?
<img width="1405" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/2caf0de1-75a1-4147-8c93-679b37b6f2c3">

**Comment by iSCJT** [comment]
You can kind of search it but it's a general search and you get other items not created by the user coming back in the search. It's also quite slow like you've seen.

With a simple specific function in the backend it would make things more performant.

**Comment by iSCJT** [comment]
Low priority as ability to view how-to and research created by a user on their user profile is now in testing.

**Comment by goratt12** [comment]
Would you like the filter to search author and contributers or only author?
