### ISSUE TITLE
[feature request] add total research articles count to user profile page

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2382]
**Is your feature request related to a problem? Please describe.**
Would add consistency to have a badge and count as there is for how-to items, events and useful.

**Describe the solution you'd like**
Badge and count for created and collaborated on research items in the same way that one exists for how-to items, events and useful.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by AlfonsoGhislieri** [comment]
#2382 should probably be resolved before this is added, I wouldn't be surprised if the research counts also don't add up.

**Comment by thisislawatts** [comment]
🙏🏻 Do we have a design icon we can use for Research @ONEARMY/design?

**Comment by davehakkens** [comment]
Attached!
![icon-research](https://github.com/ONEARMY/community-platform/assets/13672737/7502b984-bae7-4432-9af1-d9384241cbe9)
