### ISSUE TITLE
Ability to delete comments as an admin

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2385]
### Description

Ocasionally we have double comments coming in. Sometimes as a fault by the users, sometimes a bug in the platform.
Regardless it would be good if community admins can delete comments to keep things clean

### Page related

Will be used in :

- [how-to's](https://dev.onearmy.world/how-to)
- [Research](https://dev.onearmy.world/how-to)

### Problem examples

[Example in howto](https://community.preciousplastic.com/how-to/shr---33-)
<img width="889" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/631fce85-f1d6-421d-ab53-5d4aa0e2a2da">

[Example in research ](https://community.projectkamp.com/research/make-a-basekamp-extension-in-a-container)(in step 7)
<img width="833" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/c96a89c0-8569-4086-91a7-e98a477f3cca">

### Build suggestions

There is already a button to delete comments if you are the author. This functionality needs to be extended to admins.
<img width="254" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/e0029f65-e454-40bd-a59c-5b17d0b1d91b">

**Comment by AlfonsoGhislieri** [comment]
I can take this one
