### ISSUE TITLE
[feature request] allow user to delete their posts

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2391]
**Is your feature request related to a problem? Please describe.**
User adds post (how-to / research) in error or realises it's a duplicate and would like to delete post and is unable to.

**Describe the solution you'd like**
Addition of a delete button that is visible to the user that created the post on how to and research articles.

**Describe alternatives you've considered**
Manually finding the item in the database and deleting it.

**Additional context**
[Discord request](https://discord.com/channels/586676777334865928/1108116011191902218/1111559755169800292)

**Comment by KungRaseri** [comment]
Is this one good to pick up?
