### ISSUE TITLE
[feature request] Make it harder to create duplicate How-tos  

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2394]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a recurring problem I've noticed for some time now. It's frustrating when the How-to's (HTs) are submitted and appear in duplicate in the system. While I have tried submitting a HT myself and did not see a duplicate, I am concerned that this may not be the case for all users.

**Describe the solution you'd like**
I believe the problem might be that users are not receiving a confirmation message that their HT has been successfully submitted. Therefore, I propose that upon successful submission, a pop-up message should appear to inform the user that their HT has been sent and is now pending PP team approval.

**Describe alternatives you've considered**
An alternative solution could be to implement a backend check in the system to identify and prevent duplicate submissions. However, a user interface-based confirmation would provide instant feedback to the user and could improve their experience.

**Additional context**
While the presence of duplicate HTs is the primary issue, the lack of immediate feedback to the users regarding their submission status might contribute to user confusion and further duplicate entries. Therefore, improving the user interface with a confirmation pop-up could potentially mitigate the duplication problem while also enhancing the overall user experience.

Reference: 
Original report – https://discord.com/channels/586676777334865928/1113549605972484148/1113549605972484148

**Comment by davehakkens** [comment]
Not sure if this is still a problem.  We used to have multiple how-to's coming in but not anymore.
We thought it was replicated by the user but it could have been a bug the auto duplicates.

Might be worth to keep an eye on it (or replicate the issue) before trying to fix

**Comment by benfurber** [comment]
This hasn't come up for a while. Should we close the issue?

**Comment by davehakkens** [comment]
Agree can be closed, many things changed in the meantime
