### ISSUE TITLE
[feature request] ensure research collaborator usernames exist when adding collaborators

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2409]
**Is your feature request related to a problem? Please describe.**
Currently the research collaborators field is a text string with no validation that the usernames entered exist.

**Describe the solution you'd like**
Change to a typeahead search that checks existing usernames and allows tagging of collaborators.

**Describe alternatives you've considered**
Checking each username in the string as part of form validation.

**Additional context**
N/A

**Comment by thisislawatts** [comment]
Sounds great! I can think of lots of places where a component like this would be useful ✨

**Comment by benkelaar** [comment]
Can I have a stab at this one?  Sounds like fun.  Any existing element I can reuse?

**Comment by thisislawatts** [comment]
Nothing current in the system at the moment @benkelaar, it would require some work. Perhaps using the [Autocomplete](https://mui.com/base-ui/react-autocomplete/) from Mui Base with the existing [Username](https://docs.platform.onearmy.earth/storybook-static/index.html?path=/story/components-username--verified) would be a good start.

**Comment by goratt12** [comment]
I'm wondering what the best approach will be to getting the available users list for the autocomplete engine.
There are three approaches as I see it:

1. Requesting all the usernames from the DB and providing the list to the autocomplete
    * Pros:
        - One request to the DB
        - Instant autocomplete
    * Cons:
        - The request is taking a lot of time (about 1.5 seconds)
        - Provide information security issue where the list of users is in the client side
2. For every update to the input, search the usernames that start with the text the user entered (With minimum of 2 letters)
For example: `Sam` will output `[Samuel, Samantha, Santiago]`
    * Pros:
        - The requests take less time (few milliseconds) - ideal for autocompletion
        - There is no list of **all** users in the browser
    * Cons:
        - More requests to the DB
        - Can cause lag in the autocomplete when the DB is lagging
3. Not using autocomplete at all - only checking if username exist when the user finish entering the username
    * Pros:
        - Less requests to the DB
        - There is no list of **all** users in the browser
    * Cons:
        - Less user friendly 

Would love to hear your thoughts on that 😊

**Comment by davehakkens** [comment]
Thanks for looking into this. Nice feature! Not sure what would be the best technical approach @thisislawatts can advise better.

But one thing to keep in mind is that this feature would probably later be extended to @mentions in content and comments across the platform. 

Perhaps that helps to decide how robust the approach should be

**Comment by iSCJT** [comment]
For the auto complete my gut says option 2 with a timeout on the user input before performing a db search to minimise db requests and potential lag.  Let them click to select from the autocomplete but also if they've typed a correct username just flag that as ok... give it a tick, put the text in green or something.  If the entered username isn't valid then set an error state on the field and prevent form submit.

**Comment by goratt12** [comment]
I looked up best practices and GitHub perform the mention operation as the first suggestion - getting all the relevant usernames as the page/component load (can be seen in the attached screenshot)

As for the security issue, it can be performed using a Firebase Function that will filter only the relevant fields from the users collections.

![image](https://github.com/ONEARMY/community-platform/assets/23094928/106999b7-849c-493a-98fd-d8734e3d1682)
