### ISSUE TITLE
[Style] improve navigation bar

### ISSUE THREAD

**Issue by devWonderkind** [ONEARMY/community-platform#2416]
Hey @thisislawatts I want to add some hover effect on navigation bar and change style.
please assign this issue to me.

**Comment by thisislawatts** [comment]
Given you raised this issue @coder-chahal do you have any designs you would like to share?

**Comment by AlfonsoGhislieri** [comment]
Any update on these proposed design changes @devWonderkind?

**Comment by devWonderkind** [comment]
no because i've a doubt or confusion @AlfonsoGhislieri 
I wanna change this webpage navigation
![chng](https://github.com/ONEARMY/community-platform/assets/110322061/a04adcc3-1c8e-4fc7-940d-574d43fa3333)
but when i run a code on my local machine so why open this webpage. what's going on🥲
![change](https://github.com/ONEARMY/community-platform/assets/110322061/174d2831-c892-405d-bc20-773b6946c927)

**Comment by AlfonsoGhislieri** [comment]
That would be because the page you first posted is not not actually the community platform, but the platform website where general info is available (https://github.com/ONEARMY/community-platform-website). I can see that this may be a little confusing, but these are two separate entities.

**Comment by devWonderkind** [comment]
Ok so which repo i would be contribute under GSSoC.?

**Comment by AlfonsoGhislieri** [comment]
It would have to be in https://github.com/ONEARMY/community-platform-website, you could raise the issue there. But I’m not sure that’s open for contributions you’d have to see with @davehakkens.

In the meantime in going to close this issue as it does pertain to this repo.
