### ISSUE TITLE
[feature request] Show Password Icon

### ISSUE THREAD

**Issue by BaltacMihai** [ONEARMY/community-platform#2467]
**Is your feature request related to a problem? Please describe.**
When I make a mistake, especially at the end, it irritates me that I either forgot to save the password for quick access or that I was in a rush. I believe being able to view the password you type would be helpful.

**Describe the solution you'd like**
The password would initially be hidden, i.e. with stars. We have in the right corner of the input a button ( icon ) that show/hide the password

**Additional context**
I quickly implemented this to demonstrate how it will seem.

![Group 106](https://github.com/ONEARMY/community-platform/assets/72079422/d297eb51-f7f9-4fe7-9540-75d475e2081e)

**Comment by AlfonsoGhislieri** [comment]
Good suggestion @BaltacMihai, definitely a nice quality of life change. Would you like to take on issue?

**Comment by BaltacMihai** [comment]
Yes, you can add me.

I will need 2 icons for show/hide, I will use some substitutes until then.

**Comment by AlfonsoGhislieri** [comment]
Sounds good, if you can get a draft PR in then we can see if @davehakkens has any icons he would like to use!

**Comment by davehakkens** [comment]
Nice detail! :)
Icons attached 
![icon_hide](https://github.com/ONEARMY/community-platform/assets/13672737/d171f5f9-c48c-4759-aa20-61b639e791f1)
![icon_show](https://github.com/ONEARMY/community-platform/assets/13672737/105faeb3-ff66-49a4-8247-5a91e23f8876)
