### ISSUE TITLE
[refactor] consolidate common sytle variables

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2474]
**Is your feature request related to a problem? Please describe.**

We have multiple different files for the different platforms and there is a lot of overlap and duplication of the different variables, these are the files in question below:

[Project kamp](https://github.com/ONEARMY/community-platform/blob/master/packages/themes/src/project-kamp/styles.ts)
[Fixing fashion](https://github.com/ONEARMY/community-platform/blob/master/packages/themes/src/fixing-fashion/styles.ts)
[Precious plastics](https://github.com/ONEARMY/community-platform/blob/master/packages/themes/src/precious-plastic/styles.ts)

**Describe the solution you'd like**
Consolidation of variables that are the same across all the different platforms into common files. This makes it easier to make changes, maintain and keep uniformity across the platform.

Similar to what was done for:
[colors](https://github.com/ONEARMY/community-platform/blob/master/packages/themes/src/common/colors.ts)
[text variant](https://github.com/ONEARMY/community-platform/blob/master/packages/themes/src/common/textVariants.ts)

**Comment by thisislawatts** [comment]
Thank you for raising this @AlfonsoGhislieri, this is something I had been thinking about for a while :) Although I hadn't quite decided on the best approach.

Each theme only varies on a few properties at the moment so should we have a single base theme which each instance imports, overwrites the necessary properties and then reexports. I suspect that the composable approach we get with common attributes introduces more complexity than utility at this point. What do you think?

**Comment by bagiyal** [comment]
can we discuss more about this feature and i want to working on this feature

**Comment by AlfonsoGhislieri** [comment]
That’s a really good point @thisislawatts, I completely agree! I should have taken a closer look at how much overlap there really was. The single base theme is definitely the cleaner implementation. This has become quite apparent from the PR that @BaltacMihai raised #2477..

**Comment by AlfonsoGhislieri** [comment]
Also @bagiyal, sorry I think @BaltacMihai will probably want to keep on this issue as he has already been working on it.

**Comment by BaltacMihai** [comment]
If it's ok, I think I'll stay, I've already started working a little and I've got an idea of how I can implement it.
