### ISSUE TITLE
[feature request] align research filter section with how-to

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2480]
### Description

We want to align the research filter section with the how-to's
This could be seen as 3 different things to do.
1. Add a "sort by" dropdown that filters on `most useful`, `most comments`, `most updates` and `latest`
2. Add a search bar
3. Move `add research` button to the right. 

### Page related

Will be used in : [Research overview](https://community.projectkamp.com/research)
Similair to the [How-to overview](https://community.preciousplastic.com/how-to)

### Mockup

![Update research layout](https://github.com/ONEARMY/community-platform/assets/13672737/d0efc34f-ca85-4bab-90de-6624116cddf9)

**Comment by AlfonsoGhislieri** [comment]
We should be able to re-use the logic that exists for the howtos right?

**Comment by davehakkens** [comment]
I think so. Except filter on` most comments` and `updates` is new and not used in how-to's

**Comment by AlfonsoGhislieri** [comment]
I reckon we should still aim to consolidate all this logic into a reusuable component, a lot is going to be the same as for howto's, will really help to avoid having to repeat the code. We can have some extra logic for the extra filters?

**Comment by BaltacMihai** [comment]
Hi, can you assign me? I will try to do something, now I hope it will work out.
