### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by katbot-osr** [ONEARMY/community-platform#2485]
Hey there,

is or was there a roadmap ? howtos, user-directory, academy, etc.. have been so far migrated over to osr-plastic, using Discourse instead.

cheers,
g

**Comment by katbot-osr** [comment]
![image](https://github.com/ONEARMY/community-platform/assets/126605383/f4b9f41c-e4b6-4d21-a82a-0f46d73f41f7)

https://forum.osr-plastic.org/c/wiki/howtos/72/ :-)

**Comment by iSCJT** [comment]
Closing this issue as it's not directly related to the community platform.  Best place for questions would be our Discord.
