### ISSUE TITLE
[bug] Unclear wording for Draft button

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2508]
**Describe the bug**

The Draft button text when loading the create Research Item is unclear.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to http://localhost:3000/research/create
1. See that `Revert to Draft` text appears on button
1. `Revert` wording is unclear here as the Research piece does not make sense.

`Save as Draft` would be a clearer term.

**Screenshots**

![Screenshot 2023-06-30 at 18 14 10](https://github.com/ONEARMY/community-platform/assets/472589/d6905bdb-d578-4d2c-8de1-9f96f56d7d32)

**Comment by CYBWEBALI** [comment]
I can fix this issue assign it to me.

**Comment by AlfonsoGhislieri** [comment]
Thanks @AlimurtuzaCodes

**Comment by AlimurtuzaCodes** [comment]
Done PR #2533
