### ISSUE TITLE
feat: enforce character limits for how to title (20 > 200)

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2510]
Add validation to the how to title field when adding or updating a how to item.

- minimum character length 20 characters
- maximum character length 200 characters

Hint text and character counter should be updated accordingly.

**Comment by AliAbuSalam** [comment]
Hello, can i try to tackle this issue? @iSCJT

**Comment by iSCJT** [comment]
Go for it @AliAbuSalam. Thank you!
