### ISSUE TITLE
feat: enforce character limits for how to steps (100 < 700)

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2511]
Add validation to the how to steps when adding or updating a how to item.

- description minimum character length 100 characters
- description maximum character length 700 characters

Hint text should be updated accordingly.

Add a character counter to the description text in the step.

**Comment by aaronguernsey** [comment]
@iSCJT It cool if I take a crack that this?

**Comment by iSCJT** [comment]
That would be great, thanks @aaronguernsey!

Hopefully the contribution guidelines read in combination with our [developer docs](https://onearmy.github.io/community-platform/) should be enough but if you find any holes please let us know so we can get them updated.

P.S. we broke the developer docs styling earlier 🙈  should be fixed in a few minutes.

**Comment by aaronguernsey** [comment]
Awesome, thanks @iSCJT!

Good luck with Dev Docs! I think I read them before the latest changes 😄
