### ISSUE TITLE
[doc request] Missing step to firebase emulator running for the first time

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#2530]
**Is your feature request related to a problem? Please describe.**
There's a missing step in the [Firebase setup](https://onearmy.github.io/community-platform/Backend%20Development/firebase-emulators-docker) as `yarn start:emulated:docker` expects a built app/folder which I didn't have yet. 

**Describe the solution you'd like**
Add `yarn build` as a prerequisite command.

**Describe alternatives you've considered**
Could add `yarn build` as the first get started step.

**Comment by benfurber** [comment]
Happy to do this quickly once I get a thumbs up.

**Comment by iSCJT** [comment]
Feel free to @benfurber, thanks!

**Comment by asdFletcher** [comment]
I have run into this issue as well, and can successfully start the local emulators after running `yarn build`
