### ISSUE TITLE
[feature request] enforce a minimum of 3 steps for a how-to

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2542]
**Is your feature request related to a problem? Please describe.**
Currently a how-to can be saved with very little information which requires the moderation team to go back to the original poster which required changes.

**Describe the solution you'd like**
Implement a minimum of 3 steps to save / publish a how to.  When saving a draft this limit should not be enforced.

**Describe alternatives you've considered**
N/A - request from moderation team

**Additional context**

**Comment by iSCJT** [comment]
@benfurber will pick this one up alongside #2540

**Comment by benfurber** [comment]
👋
