### ISSUE TITLE
[feature request] allow admins to leave moderation comments on map pins

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2543]
**Is your feature request related to a problem? Please describe.**
Admins would like to leave a moderation comment when moderating map pins.

**Describe the solution you'd like**
Luke to implement as part of retool admin screens.  Requires design for human facing screens within the community platform to be provided by precious plastic team.

**Comment by thisislawatts** [comment]
Update, first pass on this. Retool admin interface allows saving messages to the MapPin entity under the prop `comments`.  There is a bug within the UI however as the posted message is not visible to the moderator. A further cycle here to work out why this is happening.

**Comment by thisislawatts** [comment]
@thisismattia do you have any designs around how this message could be shown to the user?

**Comment by thisismattia** [comment]
hey @thisislawatts thanks for following up. I am not entirely sure of the desired outcome here. 

Ideally, when we have a new map pin request, we have 3 options: 
1) approved --> change of status to approved & email sent to user 
2) rejected --> change of status to rejected & email sent to user 
3) needs more work (or needs more work/missing information...) --> change of status to missing info & email to user that they need to review the content in their map pin before it can be approved

What is the goal of adding a comment on the pin? Traceability?

**Comment by sigolenej** [comment]
Ideally, when we change the status to needs more work, we would be able to tell the user what they need to improve: photos, description, map pin type...

Currently, we send out a standard email with the map pin guidelines (so a non personal email) to map pins that need improving. 

How would I imagine this: 
--> admin checks the map pin
--> admin changes status to need improvments 
--> users receives an email asking to improve their map pin 

For now, this can be a standard email for all improvments.

**Comment by thisislawatts** [comment]
Thanks for clarifying @sigolenej, do you have workflows in Monday that send these emails or is this something you would like the Community Platform to do?

**Comment by sigolenej** [comment]
@thisislawatts currently these emails are sent via monday.com -which works fine for the moment-. 

What is important for us now is to have a status to assign to these pins that just need more work, for them not to be considered as rejected. 

How can we manage flagging/knowing when a map pin request is actually a modified one? 

New pin comes in for approval --> status changed by admin to improvements --> human edits the map pin & re-submits for approval --> would it come in as "to be approved", or would we be able to see the status was "improvements needed"?

**Comment by thisislawatts** [comment]
@sigolenej I've updated the admin panel, you can now mark the moderation status of a Map Pin as `Improvements Needed`. Any pins marked with this value will not be visible on the Map. 

![Screenshot 2023-07-26 at 21 08 34](https://github.com/ONEARMY/community-platform/assets/472589/eef34845-8f6b-48b4-9f2b-dcc67f639a10)

**Comment by thisislawatts** [comment]
Comments can be persisted to the Map Pin documents in Firestore. This string value will be added to documents under the key `comments`. 

```ts
export interface IMapPin {
  moderation: IModerationStatus
  _createdBy?: string
  _id: string
  _deleted: boolean
  type: IMapPinType
  location: ILatLng
  subType?: IMapPinSubtype
  verified: boolean
  comments?: string # New Field
}
```

There is a separate ticket focused on how to expose this for end users as a potential candidate for the August sprint. https://github.com/ONEARMY/community-platform/issues/2668

**Comment by sigolenej** [comment]
Thanks @thisislawatts !! 
Amazing, can you confirm that when a human will edit their pin, it will be flagged once again as pending approval?
