### ISSUE TITLE
[feature request] allow admins to export data

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2544]
Admins would like to export data.  Required further scoping.  Luke to address as part of retool work.

**Comment by sigolenej** [comment]
Thanks for this! 

Here is what comes to mind now !

Ideally we can select the user data while selecting HT data (eg we can see the email of the author while downloading HT data, if not, we can always do excel hook ups via the username)/

**USER DATA** 
username 
email 
account creation date 
last log-in date 
location (at least country)
pin type 
badge

**HOW-TO** 
title 
author (username & email)
category 
tags 
number of useful 
number of views (since creation date)
creation date (= submission date)
modification date 
status (approved, rejected) 
status date (= approval date)
_(this would be a lower priority)_ HT info: number of steps, time to buid, difficulty

**MAP** 
username & email 
pin name 
pin type 
short description
links 
badges 
creation date 
modification date 
number of views (since creation date)
status (approved, rejected) 
status date (= approval date)

**Comment by thisislawatts** [comment]
@sigolenej I've updated the Admin area to introduce these new columns, there were a few items which were not are immediately available as it would require joining data across multiple source. Such as Google Analytics + Map Pins to understand the number of views, we can look to connect these datasets but it is better handled as a separate follow up work item than increasing the scope of this ticket (Enabling moderators to download data from CP production database)

**Comment by sigolenej** [comment]
Thanks @thisislawatts looks great :) 

Few questions:
USERS
- why are so many users under "awaiting moderation" status?
- I would like to filter only on approved map pins, but I need to put in a role, if i am not mistaken, I do not see the role of a normal user: 
- would it be possible to filter on profile type?
![Screenshot 2023-07-18 at 16 47 09](https://github.com/ONEARMY/community-platform/assets/138245356/4de57480-c494-48d1-ad32-43a38e4735cc)
- why do we have the country only for some users?

HT
- could we have the author email? 
- OK for the crossing with G Analytics, not needed in the short term. Where does the current data on views come from then? 

MAP 
- Map pin name is not the same as the username, the username can not have spaces, but the pin name can :) 
- i'm sorry I missed it, can we also add the country to the map pin table?

**Comment by thisislawatts** [comment]
### USERS

> - why are so many users under "awaiting moderation" status?

That is not a question I can answer. I guess that there is maybe a backlog in the moderation queue or a lot of stale accounts created from a few years ago. Perhaps worth doing a clean up exercise with emails as well. Send a reminder email to log in and if they do not log in with 30 days we delete the account this would be good for:
* Ensuring accurate numbers
* Reducing unnecessary data held in our systems

> - I would like to filter only on approved map pins, but I need to put in a role, if i am not mistaken, I do not see the role of a normal user. 

This can be done on the Map Pin page. 
![Screenshot 2023-07-24 at 22 08 56](https://github.com/ONEARMY/community-platform/assets/472589/435e82f1-2de3-4f2b-92dc-5548c6d9a99a)
**Note:** There is no role for a normal user, at the moment roles are only provided for additional permissions such as beta testers, admins and super-admins. 

> - would it be possible to filter on profile type?

Absolutely, you can do this via the Filter drop down at the top of the table
![Screenshot 2023-07-24 at 22 06 57](https://github.com/ONEARMY/community-platform/assets/472589/82db2455-f40a-40a2-a994-45827d6a62ff)


> - why do we have the country only for some users? 

There are a few reasons here, we have some needlessly complex logic around capturing user countries which means it is possible to have a user profile without a country available. 

### HT
> - could we have the author email? 

> - OK for the crossing with G Analytics, not needed in the short term. Where does the current data on views come from then? 

Views are a feature that has been built into the Platform so they are also being gathered outside of Google Analytics.

### MAP 

> - i'm sorry I missed it, can we also add the country to the map pin table?

We don't currently store a country for the map pin, we persist only lat and long co-ordinates. I've pulled in the Country as it is displayed on the User record but there could be a difference between the two. Perhaps we should create a separate issue and ensure that in addition to the geographic co-ordinates we are storing fields such as country on the Map Pin. WDYT?

**Comment by thisislawatts** [comment]
Marking as closed for now :) Any additional questions or requests around exports can be introduced as a future issue.
