### ISSUE TITLE
[feature request] add email notifications for admins when new items added

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2545]
**Is your feature request related to a problem? Please describe.**
Admins need to be made aware by email when a new item is added which requires moderation.

**Describe the solution you'd like**
Look to take care of as part of retool work.

**Comment by thisislawatts** [comment]
Introduced a [Retool Workflow](https://docs.retool.com/docs/retool-workflows) which runs hourly to determine if any new map pins have been created.

**Comment by sigolenej** [comment]
@thisislawatts does this mean the emails should be being sent out to the community@pp email ? or have i misunerstood?

**Comment by thisislawatts** [comment]
@sigolenej these emails will be sent to community@preciousplastic.com email address from bots@preciousplastic.com. Have you received any of these emails yet?

**Comment by sigolenej** [comment]
We received the first one today! 

![Screenshot 2023-07-25 at 22 05 22](https://github.com/ONEARMY/community-platform/assets/138245356/4eb7f995-266c-4e87-94d5-b233acf405a4)

**Comment by thisislawatts** [comment]
Great @sigolenej! I will mark this item as resolved and we can continue to iterate on the notification in the future.

**Comment by sigolenej** [comment]
Perfect ! 
Thanks :)

**Comment by sigolenej** [comment]
Can you please confirm we will also get an email when we have a new HT correct? 
This applies for all new items on the CP pending approval.
