### ISSUE TITLE
[feature request] pin draft / awaiting moderation / rejected research created by the logged in human to top of listing

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2550]
**Is your feature request related to a problem? Please describe.**
If a human using the platform adds a draft research item then they can lose visibility of it.

**Describe the solution you'd like**
If the logged in human has any draft, awaiting-moderation or rejected status research created by them then they should be pinned to the top of the research list so they see can always find them.

**Describe alternatives you've considered**
N/A - Agreed at June meetup

**Comment by maxbethke** [comment]
Hey, I am a first time contributor and I am currently looking into this.

**Comment by iSCJT** [comment]
Thanks @maxbethke 🚀

**Comment by maxbethke** [comment]
I think I need a little help setting things up on my end.

When I run `yarn test:unit` I would get this error
```
{"level":50,"time":1688548794956,"pid":26220,"hostname":"Maximilians-MacBook-Pro.local","err":{"type":"Error","message":"User not found.","stack":"Error: User not found.\n    at MockNotificationsStore.triggerNotification (/Users/maxbethke/Projects/community-platform/src/stores/User/notifications.store.ts:93:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Object.<anonymous> (/Users/maxbethke/Projects/community-platform/src/stores/User/notifications.store.test.tsx:63:5)"},"msg":"User not found."}

I need the test suite to be running to be able to write the tests covering this feature. Maybe this is a known problem? Did I miss something during the setup?

**Comment by iSCJT** [comment]
@maxbethke I have encountered this myself.  Do you error if you use `yarn test:unit:ci`?

**Comment by maxbethke** [comment]
> yarn test:unit:ci

Well, the error is this thrown but the test suite executes and the corresponding test passes
```
 PASS  src/pages/Research/Content/ResearchArticle.test.tsx (800 MB heap size)
 PASS  src/pages/Howto/Content/Howto/Howto.test.tsx (927 MB heap size)
 PASS  src/stores/User/notifications.store.test.tsx (1000 MB heap size)
{"level":50,"time":1688551378510,"pid":26916,"hostname":"Maximilians-MacBook-Pro.local","err":{"type":"Error","message":"User not found.","stack":"Error: User not found.\n    at MockNotificationsStore.triggerNotification (/Users/maxbethke/Projects/community-platform/src/stores/User/notifications.store.ts:93:17)\n    at Object.<anonymous> (/Users/maxbethke/Projects/community-platform/src/stores/User/notifications.store.test.tsx:63:5)"},"msg":"User not found."}
 PASS  src/pages/common/Header/getFormattedNotifications.test.tsx (1093 MB heap size)
 PASS  src/pages/Research/Content/ResearchUpdate.test.tsx (1187 MB heap size)
 PASS  src/utils/helpers.test.ts (939 MB heap size)
 PASS  src/stores/Research/research.store.test.ts (1009 MB heap size)
 PASS  src/stores/Howto/howto.store.test.ts (1008 MB heap size)
 PASS  src/modules/admin/pages/__tests__/adminCategories.test.tsx (1082 MB heap size)
 PASS  src/modules/admin/pages/__tests__/adminTags.test.tsx (1157 MB heap size)
 PASS  src/stores/Maps/maps.store.test.ts (1193 MB heap size)
 PASS  src/stores/common/mentions/index.test.ts (1208 MB heap size)
 PASS  src/modules/profile/index.test.ts (1219 MB heap size)
 PASS  src/pages/User/workspace/Workspace.test.ts (1236 MB heap size)
 PASS  src/pages/Academy/Academy.test.tsx (1246 MB heap size)
 PASS  src/utils/formatters.test.ts (1255 MB heap size)
 PASS  src/utils/getUserCountry.test.ts (1263 MB heap size)
 PASS  src/modules/index.test.ts (1272 MB heap size)
 PASS  src/stores/Maps/filter.test.ts (1288 MB heap size)
 PASS  src/stores/common/FilterSorterDecorator/FitlerSorterDecorator.test.ts (1301 MB heap size)
 PASS  src/pages/Research/Content/helper.test.tsx (1308 MB heap size)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------

Test Suites: 24 passed, 24 total
Tests:       2 todo, 202 passed, 204 total
Snapshots:   0 total
Time:        35.839 s, estimated 79 s
Ran all test suites.

**Comment by maxbethke** [comment]
By the way, alongside the moderation status 'draft' and 'awaiting-moderation' there is also 'rejected' (and 'accepted' of course).
I think it would be wise to also pin rejected research postings to the top of the list, as the user would otherwise loose visibility of it once it got rejected. Otherwise it would then, depending on the chosen sorting option, move down and get burried in the list.

**Comment by iSCJT** [comment]
Good idea, please pin rejected as well.  I'll update the description.

**Comment by maxbethke** [comment]
Im finding it hard to test this manually, because I dont know how to put a research item into the 'awaiting-moderation' state. I cant only draft and publish it, which makes it accepted.
However, the tests are passing and I have opened #2573 as a draft for now.
Maybe @iSCJT can elaborate on how to test this manually?

**Comment by iSCJT** [comment]
hi @maxbethke, good spot and sorry for the confusion.  Because the only project currently using research is Project Kamp and they're also the only one adding research items we have it set to be auto-accepted.

If I wanted to manually test in your position then my suggestion would be to open up the local emulator firestore on http://localhost:4001 and to change the value for the record.

**Comment by iSCJT** [comment]
@maxbethke do you think you'll have time to finish this off or should I release it back to the pool for someone else to pick up please?

**Comment by maxbethke** [comment]
@iSCJT sorry, I went on holiday and forgot about it. I will finish it in the next days

**Comment by evakill** [comment]
this issue is back up for grabs if anyone is interested in closing it out 💪 
[here](https://github.com/ONEARMY/community-platform/pull/2573) is a previous draft PR that can be drawn from
