### ISSUE TITLE
[New feature] Introduce nested comments (draft)

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2564]
### Description

We want to introduce nested comments to be able to answers specific comments without messing up the thread. This is a big issue since it will require some refractoring, take into account @mentions and properly deliver notifications.

### Page related

Will be used in :

- Single Research page ([example](https://dev.onearmy.world/research/make-a-house-from-recycled-plastic))
- Single How-to page ([example](https://dev.onearmy.world/how-to/test-moderation))

### Release plan
The plan is to
1. Release first in the Research module
2. Display the reply button only for beta-testers
3. Make a seperate PR for web and email notifications

### Mockup

![Slice 1](https://github.com/ONEARMY/community-platform/assets/13672737/c92e5b58-97ec-42d0-a49c-a8e012a8ce07)
![Slice 2](https://github.com/ONEARMY/community-platform/assets/13672737/6b5ec4ca-dabf-4968-8636-bf7d73b77fe7)
![Slice 3](https://github.com/ONEARMY/community-platform/assets/13672737/c40ee647-5907-4257-b86c-4759986b19d7)
![Slice 4](https://github.com/ONEARMY/community-platform/assets/13672737/ab805795-8e11-4519-afe0-7f7a786faebc)

### Build suggestion

This will require a bigger refractor to store comments in collection. More information about that coming....

**Comment by kensiecodes** [comment]
I'm open to doing the client side of this! Too new to touch collection with confidence lol

**Comment by davehakkens** [comment]
thanks for wanting to help @kensiecodes!
Could possible be done in collaboration with a maintainer for the backend work.
But everyone is currently busy working through our [july milstones.](https://github.com/ONEARMY/community-platform/milestone/10)

Could we get give you a ping when we are done to checkin again?

**Comment by iSCJT** [comment]
Also to include consideration for how new comments are surfaced when someone received a notification of a new comment and clicks through.

**Comment by thisismattia** [comment]
Heyo,

I hope this is not too out of the blue and feel free to ignore if so. I found this great UI for nested replies which thought might be of help or at least inspiration, it's from LOOM

<img width="387" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/8a9fdd0b-cb48-40cf-9096-c3ed60509b1f">

**Comment by thisislawatts** [comment]
> I hope this is not too out of the blue and feel free to ignore if so. I found this great UI for nested replies which thought might be of help or at least inspiration, it's from LOOM

Sounds good to me 😍

**Comment by goratt12** [comment]
> thanks for wanting to help @kensiecodes! Could possible be done in collaboration with a maintainer for the backend work. But everyone is currently busy working through our [july milstones.](https://github.com/ONEARMY/community-platform/milestone/10)
> 
> Could we get give you a ping when we are done to checkin again?

Hi! I'm up to handling the DB/data side of things if it's still relevant :)

**Comment by davehakkens** [comment]
hey @goratt12 thanks for wanting to help. There is a PR open that includes most of it already so i think we are good on this.
https://github.com/ONEARMY/community-platform/pull/3007 (correct me if you need help @thisislawatts )

We still have this large issue open (divided in many small ones) that could use help, would be great to use this module for our projects next year! https://github.com/ONEARMY/community-platform/issues/2992

**Comment by benfurber** [comment]
Considering how far discussion has come, I think this can be closed.
