### ISSUE TITLE
[change] remove moderation options from draft research items

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2571]
**Is your feature request related to a problem? Please describe.**
Moderators are given the option to approve / reject a draft research item.  This could lead to them approving an item that is not finished.

**Describe the solution you'd like**
Remove the moderation section from the research article view.

**Describe alternatives you've considered**
N/A

**Additional context**

![](https://user-images.githubusercontent.com/37253846/250968784-77f5ee0c-22a0-42dd-b889-f4fa0ccbaf2b.png)

**Comment by maxbethke** [comment]
From my (very limited) understanding of the system, this intermediate state of a research item which you called 'finished draft' would be modeled by the 'awaiting-moderation' moderation status (See IModerationStatus).
In my mind, after an item gets published by the creator, it should still remain hidden from the public but now get shown to moderators in the form of the screenshot above. Once they approve it, it would get assigned the status 'accepted' or 'rejected' respectively.

Let me map out the visibility of an item here:

|  Actor  |  Moderation Status  |  Visible  | 
|  ---  |  ----------------  |  -----------  |
|  Creator  |  Any  |  Yes | 
|  Moderators  |  draft, rejected  |  No  |
|  Moderators  |  awaiting-moderation, accepted  |  Yes  |
|  Everyone  | draft, awaiting-moderation, rejected  |  No  |
|  Everyone  |  accepted  |  Yes  |

Do you @iSCJT, confirm with this view of how its suppost to work?

**Comment by iSCJT** [comment]
Thanks @bagiyal for thinking through a solution and @maxbethke for providing your input on how the moderation is working.

The first thing to point out is that for research we currently automatically set the moderation status to 'accepted' as it's only Project Kamp who can add new research, this will change in future though. The normal moderation flow which we use for how-to's and will be the same for research once used more widely would be: draft > awaiting-moderation > accepted / rejected.

In terms of closing this issue @bagiyal my suggestion would be to make the moderation buttons section conditional on the moderation field being equal to 'awaiting-moderation'.

@maxbethke almost:

|  Actor  |  Moderation Status  |  Visible  | 
|  ---  |  ----------------  |  -----------  |
|  Creator  |  Any  |  Yes | 
|  Moderators  |  Any  |  Yes  |
|  Everyone  | draft, awaiting-moderation, rejected  |  No  |
|  Everyone  |  accepted  |  Yes  |

Moderators do/will want to be able to view any research type if they need to:

Drafts - need to monitor ones that get left hanging around so they can prompt the user to finish them
Rejected - rejected ones can be resubmitted with changes to them so the moderators sometimes need to be able to review the content so they can work with the original poster to make improvements.

**Comment by iSCJT** [comment]
@bagiyal  you'll need to have the admin userRole.  Try logging in as demo_admin@example.com / demo_admin and you should see them.

**Comment by evakill** [comment]
hey @bagiyal! to use this login you need to start the emulators. you can read more about this here: https://docs.platform.onearmy.earth/Backend%20Development/firebase-emulators-docker
let me know if you have any problems with this

**Comment by evakill** [comment]
@bagiyal got it - can you post your terminal logs please? 
and are you able to log in with the demo_admin account on http://localhost:4000?

**Comment by AlfonsoGhislieri** [comment]
There is a hackier approach as well, if you're still having isues with the emulators. If you change the view to admin then visit http://localhost:3000/admin/users, you can then just add your account to the admin list there.
