### ISSUE TITLE
[feature request] Improve usability of how-to form (design idea)

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#2574]
**Is your feature request related to a problem? Please describe.**
As I've been looking at #2540 (to allow users to save draft how-tos more easily), I was wondering how to make this new feature clearer to the user and generally improve the experience a little. 

**Describe the solution you'd like**
Make it clearer to the user when a how-to is incomplete but show they can still save their draft.
I'm also suggesting a change to the submit wording for users who need approval - I believe the previous wording of 'publish' is misleading, as it won't be published without admin approval.

**Describe alternatives you've considered**
I thought about changing the required field labels, but that felt annoying as they are required fields still. Could add something to the top of the page, but most users eyes will go straight to the first form field. 

**Additional context**
<img width="583" alt="Screenshot 2023-07-06 at 09 43 02" src="https://github.com/ONEARMY/community-platform/assets/16688508/1a3333f6-c84d-4ce5-842c-8c706c4fddbc">

**Comment by benfurber** [comment]
I imagine something for your eyes, @davehakkens?

**Comment by davehakkens** [comment]
Thanks for looking into it!
Makes sense to me @benfurber, would reduce confusement and questions :)
You want to take it on?

**Comment by iSCJT** [comment]
I like this @benfurber.  We've got a draft issue on our planning board to surface validation errors in a better way, either a modal, or listing them under the publish button etc.  It's currently with the precious plastic team to come up with a design suggestion but I feel like wrapping that in with this bit of work might be nice.

Would you be happy to work with @sigolenej and @thisismattia to come up with a good design and implement it for us?

**Comment by BaltacMihai** [comment]
Hey, 

I created an idea for this issue; while I appreciated your notion to include disclaimer text, I believe there is a better way to make it more user-friendly.


I've listed my idea below.

![Group 117](https://github.com/ONEARMY/community-platform/assets/72079422/c6cce9eb-c3de-4d44-8b2d-47f0832d4de5)

By doing this, we are able to clearly explain what each button will do when it is pressed and the reason the "Send for approval" option is disabled.

I believe we can improve the presented texts.

**Comment by sigolenej** [comment]
Hey @bagiyal we discussed the proposed update & change of wording . 
Green light from our end to continue with your proposal in the last screenshot. 

We agree this would apply only to the HT submission?

**Comment by benfurber** [comment]
I liked @bagiyal's approach better so included the draft button part in #2609 - as I was changing the functionality so much I thought it appropriate to include some clear UI change.

**Comment by thisismattia** [comment]
Thanks @bagiyal 🤙

**Comment by sigolenej** [comment]
Hey hey @bagiyal ! what is the status on this one?

**Comment by sigolenej** [comment]
Hey @bagiyal was wondering where we were standing on your proposal :)

**Comment by davehakkens** [comment]
Sounds good, go for it @bagiyal!

**Comment by benfurber** [comment]
We'll probably be able to close this issue soon. There's a line for the draft button as part of #2609 - which got merged in a while back.

[And there will be more complex error rendering as part of this](https://github.com/ONEARMY/community-platform/issues/2684#issuecomment-1678914780).

**Comment by thisislawatts** [comment]
@benfurber do you think this Issue is ready to be closed?

**Comment by sigolenej** [comment]
Hey @benfurber so has this been merged with another item? not clear for me :) thanks !

**Comment by benfurber** [comment]
Three messages in a row I haven't responded to! My apologies all. Yes, I think this can be closed for now.
