### ISSUE TITLE
[bug]  "Support us on Patreon" button is available on the Project Kamp Season 3 webpage, but it does not perform any action when clicked.

### ISSUE THREAD

**Issue by bagiyal** [ONEARMY/community-platform#2579]
**Describe the bug**
The "Support us on Patreon" button is available on the Project Kamp Season 3 webpage, but it does not perform any action when clicked.

**To Reproduce**

1. Go to 'https://projectkamp.com/season-3.html'
2. Look for the "Support us on Patreon" button.
3. Click on the Button

**Expected behavior**
After clicking on the "Support us on Patreon" button, you should be redirected to the Patreon support website.

Please note that this assumes the "Support us on Patreon" button is present on the webpage but not functioning as expected. 

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/63339447/2e7dc765-0d13-4412-b93b-3cf24ffe3baa)

**Comment by iSCJT** [comment]
Thanks very much for reporting @bagiyal 👍

I'm going to close the issue as the website is separate to the community platform.  @davehakkens can you take a look please.
