### ISSUE TITLE
[refactor] update FieldInput component to use new CharacterCount component

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2598]
A CharacterCount component has been added to the platform.  FieldInput can be refactored to use the new CharacterCount as pointed out by @aaronguernsey :

Much of the `TextLimitIndicator` / `CharacterCount` logic came from the `FieldInput` component. Should I update that component with the new `CharacterCount` component? Or would that be a separate task?

_Originally posted by @aaronguernsey in https://github.com/ONEARMY/community-platform/issues/2581#issuecomment-1625430907_

**Comment by aaronguernsey** [comment]
Awesome @iSCJT , I'll try to look at this issue after the weekend! Hopefully, it should be a straightforward update. 

I will be out of town for a few weeks. So, if I don't pick this up soon, please don't let me hold up the progress on this issue 😃
