### ISSUE TITLE
[feature request] Removing styled components in favour of ThemeUi components 

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2619]
**Is your feature request related to a problem? Please describe.**

The code base is littered with both ThemeUi components and styled components (which I’m guessing were what was originally used). The use of both of these is redundant and makes the developer experience confusing, particularly for new contributors.

This makes even more sense now as we refactored a bunch of components to be theme aware TheneUi components that use sx.

This should also help to decrease the bundle size as we don’t have to have 2 styling libraries.

**Describe the solution you'd like**
Remove styled components and replace them with ThemeUi components.

**Comment by thisislawatts** [comment]
@AlfonsoGhislieri can you point to some of these styled-components?

**Comment by AlfonsoGhislieri** [comment]
Sure, here are just a few examples
[ThumbCard ](https://github.com/ONEARMY/community-platform/blob/0913e7cb4c40f1f3f5e29a571551862010ae81e2/packages/components/src/ImageGallery/ImageGallery.tsx#L31)in ImageGallery

**Comment by thisislawatts** [comment]
Thanks @AlfonsoGhislieri 🤦🏻 I was looking `styled-components` imports. I completely forgot about it being exposed via emotion.

**Comment by iSCJT** [comment]
@thisislawatts @AlfonsoGhislieri Do we want to split this out to separate issues like we did before or have someone tackle it as one task?

**Comment by evakill** [comment]
@AlfonsoGhislieri we split these out into individual issues so i believe we can close this! feel free to reopen if i'm missing something
