### ISSUE TITLE
[test] add tests to validate functionality of ImageGallery component

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2633]
ImageGallery.test.tsx needs to be updated to add tests that validate the current functionality of the ImageGallery component.

- Clicking through the thumbnail images changes the main image displayed
- Clicking on the main image displayed opens that specific image larger within the lightbox
- Clicking the previous and next arrows within the lightbox changes the image displayed to the correct previous and next images.

**Comment by balhelhas** [comment]
@bagiyal Are you still up to do this task?

**Comment by AlfonsoGhislieri** [comment]
Yes feel free to go ahead with this @BeeMargarida!

**Comment by BeeMargarida** [comment]
@AlfonsoGhislieri Thank you, working on it! The most challenging part is testing the lightbox behaviour.
Related to that, are you aware that `react-image-lightbox` is deprecated? Are you planning on migrating to another package?

**Comment by AlfonsoGhislieri** [comment]
Thanks for looking into this @BeeMargarida, I did not see that we were still using lightbox, thanks for pointing that out. Definitely don't focusing on testing a component using a deprecated package. 

 This would be a good opportunity to move on and use `Photoswipe` and `react-photoswipe-gallery`, unless you have any other suggestions? 🤔

**Comment by BeeMargarida** [comment]
@AlfonsoGhislieri Yap, sounds good to me 👍. I can work on migrating it, and looks like a good way to also use the unit tests to verify that no functionality was lost.

**Comment by BeeMargarida** [comment]
Update: I've migrated to photoswipe, just having some troubles with the tests. To test the lightbox behaviour, it's necessary to use canvas with jsdom, since jsdom does not support fetching external resources. However, this also requires some mocking of Image and window methods, so I'm investigating exactly what's necessary to make this work.
