### ISSUE TITLE
[bug] whitespace not stripped on howto form inputs

### ISSUE THREAD

**Issue by asdFletcher** [ONEARMY/community-platform#2635]
**Describe the bug**
How-to `title`, `step description` and `step title` allow whitespace inputs. Leading and trailing whitespace count toward the character count, and validation passes when the user enters a bunch of spaces.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `http://localhost:3000/how-to/create`
2. Fill out the form entirely so that it is valid (except the how-to title, step title, and step description)
3. Enter whitespace in the how-to title, step title, and step description until the form is valid
4. Save as draft, or publish. The save will succeed, but it should not.

**Expected behaviour**
We should validate against a trimmed input, and save a trimmed input. However I don't think we should require the user to manually delete any leading/trailing spaces (i.e. a valid input is still valid even if there are trailing spaces, as we will strip them on save)

**Screenshots**
Blank how-to title:
![image](https://github.com/ONEARMY/community-platform/assets/42685363/59b51b52-598e-4731-b854-15d9a1ed7686)

Here is a step that is filled entirely with spaces:
![image](https://github.com/ONEARMY/community-platform/assets/42685363/6a41366f-d2ac-44ba-8252-934f80a56be0)

**Additional context**
- Does the server provide redundant validation?

**Comment by CrowsVeldt** [comment]
I'd like to take a try at this. If that's ok
