### ISSUE TITLE
[bug] How-to intro description character limit doesn't work

### ISSUE THREAD

**Issue by CrowsVeldt** [ONEARMY/community-platform#2645]
**Describe the bug**
The placeholder text on description field of the How-to intro says there is a limit of 400 characters, but
there doesn't seem to be any limit enforced, and it doesn't show a warning when the limit is reached.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Create How-To'
2. Scroll down to 'Short description of your How-to'
3. Add more than 400 characters to the text field
4. See that there is nothing enforcing the limit on the amount of characters, and no warning when the limit is reached

**Expected behaviour**
When the character limit is reached, there should be a message indicating so. There should also be
a functional limit preventing the user from adding more characters than allowed

**Screenshots**

**Additional context**

**Comment by CrowsVeldt** [comment]
I'd be happy to try and fix this

**Comment by AlfonsoGhislieri** [comment]
I think there needs to be some thinking around how to handle this, currently there is a lack of actual validation done for a lot of these Fields not just the one you mentioned. I noticed this when going through the codebase to add the character counters to other Fields. I'm going to close this issue as I opened #2655.
