### ISSUE TITLE
[bug] Field character limits are not being enforced or giving warnings

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2655]
**Describe the bug**

A lot of the fields thata are using the character counter or have limits on the total number of characters do not actually have these enforced. The only validation is for the most part just checking that the field is not left blank rather than checking against mininum and maximum character lengths.

This is an issue in the following files:
- Howto.form
- HowtoStep.form
- Research.form
- ResearchUpdate.form

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Create How-To'
2. Scroll down to 'Short description of your How-to'
3. Add more than 400 characters to the text field
4. See that there is nothing enforcing the limit on the amount of characters, and no warning when the limit is reached

**Expected behaviour**

There should be some feedback given to the user and these limits should be enforced.

**Potential solutions**
The first solution could be to stop further characters from being able to be typed by the user once the max limit is reached, this would remove the need for any validation for upper limits. But this doesn't solve the issue for minimum limits.

The best approach I can think of is to create some reusable validation functions that can be reusued across the codebase, here is an example of one of the validation functions already in the [codebase](https://github.com/ONEARMY/community-platform/blob/a88a3c3d6368bc28b20a8772ac52d26dab838eb6/src/pages/Howto/Content/Common/HowtoStep.form.tsx#L83)

**Comment by y-bhargava** [comment]
I'd be happy to try and fix this

**Comment by AlfonsoGhislieri** [comment]
Thanks for taking interest in this issue @y-bhargava, unfortunately I have already implemented a fix in #2654
