### ISSUE TITLE
[bug] Flaky user menu e2e test

### ISSUE THREAD

**Issue by asdFletcher** [ONEARMY/community-platform#2657]
When running e2e tests, there is a consistently flaky one: in `packages/cypress/src/integration/common.spec.ts`

Repro steps:
- run `yarn test`

Additional context:
- Go to [closed pull requests](https://github.com/ONEARMY/community-platform/pulls?q=is%3Apr+is%3Aclosed) and look at the last few CI reports. They'll have this test listed as flaky

Suggested next steps:
- re-write the test to not be flaky
- Stretch goals: re-write the user menu to not close-and-then-open if it is already open. Should it close, or stay open if clicked while it is open?
- Re-work the function `cy.clickMenuItem`. Right now it opens the menu **and** clicks an item. We could add a separate function to simply click an item, and rename the existing one to `openMenuAndClickItem`

**Comment by thisislawatts** [comment]
> Stretch goals: re-write the user menu to not close-and-then-open if it is already open. Should it close, or stay open if clicked while it is open?

This component could probably do with a button that you can click to close the menu, but skipping the design work associated with that kind of change it seems that the best behaviour here would be for the menu not to flicker close and open again if it is already open. Would you be up for making that change @asdFletcher?
