### ISSUE TITLE
Module - Automated Tests

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#266]
Currently our system of testing relies on confirmation of successful build during CI pipeline process, use of typescript models to enforce sensible data structures, code reviews on PRs, manual quick testing and general common sense. 

Whilst this is reasonable for small projects and few contributors we're quickly moving beyond what is time-efficient or reasonably robust. I would suggest in the first instance we create a few simple e2e tests to make sure core platform features work as expected, and provide a basis to build on as more things crop up.

Open to suggestions on favourite tooling to do so, or anything else we might want to implement

**Comment by tx4x** [comment]
hey, the most leg work is done [here](https://github.com/tx4x/test-stack/); basically a combination of puppeteer and cucumber.

in short, 
1. you write all the cucumber step definitions like [this](https://github.com/tx4x/test-stack/blob/master/test-suite/step-definitions/recorder/recorder.step.ts) 
2. you reference the steps as [this](https://github.com/tx4x/test-stack/blob/master/test-suite/features/record.feature), in any order you like, and also pass parameters to it.

this runs in the CI as well, the stuff outside of './test-suite' is just fancy CLI tooling to fire up sample page

currently there is code in place to measure/intercept network requests as well, so you can add here your KPI for app size and what not. I still have somewhere a full chrome event log parser to analyze other things like LongTask-Reports, rage clicks but I left this to google lighthouse later on.

let me know, i can adjust this quickly for the current dev ops, it's BSD-3 so do whatever you like :-)

A typical cucumber test would look as follows:

Background:
**Given** I am connected to the one-army setup at 'your url here'

@debug
**Scenario**: User can not create poll
**Given** a user with less than '100' points
**Then** the poll button is not shown

I love it however, you can pipe this reports than also into automatic issues

**Comment by chrismclarke** [comment]
Cool! Yeah I'm pretty fixed personally on puppeteer, I've used it with a few other projects and really like it (and am not aware of any widely used alternatives for e2e)

I know react comes with jest, I've also used Mocha (+chai) and a bit of Jasmine before which I had no issue with. I can see cucumber is pretty popular too but haven't ever used. I really like the look of what you've described.

My gut feeling at the moment is:
**Unit** - Jest + Enzyme (although not implemented for all components)
**E2E** - Puppeteer + cucumber

We could also push the boat out a little with the like of:
**Lighthouse** - we could link into their cli tools to run automated, this would be pretty straightforward and could be quite cool as an additional performance metric
**Bundle size analyzer** - something which we've seen come up is people adding dependencies which bloat. Might be nice to try catch these automatically too

A couple links which might be of use to people who are interested (and please add more if you come across any)
- [jest + enzyme](https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675)
- [puppeteer + jest](https://blog.logrocket.com/end-to-end-testing-react-apps-with-puppeteer-and-jest-ce2f414b4fd7)
- [puppeteer + cucumber]https://medium.com/@anephenix/end-to-end-testing-single-page-apps-and-node-js-apis-with-cucumber-js-and-puppeteer-ad5a519ace0
- [2018 (Feb) tools roundup](https://gojko.net/2018/02/25/javascript-testing-tools.html)
- [React Docs - Jest testing](https://facebook.github.io/create-react-app/docs/running-tests#filename-conventions)

@PepijnSenders - I know you've used enzyme in the platform already, do you have any thoughts on the above conversation?
@SpaceK33z - Maybe you'd be able to share some quick thoughts too?

**Comment by chrismclarke** [comment]
Also I've just started using [cypress](https://www.cypress.io/) on another project and really like it

**Comment by tx4x** [comment]
@chrismclarke , looks good, i am just concerned about : it doesn't seem to run locally, and adding performance KPIs tests won't be that easy but ok

**Comment by PepijnSenders** [comment]
Hey all, lighthouse is a good idea, but google analytics recently integrated this into their tooling. So you don't need to manually set it up anymore.

Jest + Enzyme are the tools I usually use for testing and nock for http mocking, or moxios specifically for axios.

For e2e I really like testcafe because they don't use the browser api which can be buggy sometimes. Cypress uses a similar method but was only for chrome when I started researching

**Comment by chrismclarke** [comment]
Thanks @PepijnSenders  and @tx4x , really interesting points. Cypress is still only chrome, more browsers on the roadmap but no real timeframe given from what I can see. 

I'll try find some time this week to continue exploring a few options and push for small implementation, then create more specific issues to follow-up on.

(also an extra mostly for my own reference/talking with the design team - https://cssstats.com/ could help us keep an eye on unnecessary duplication/convolution across frontend dev)

**Comment by PepijnSenders** [comment]
In chrome devtools you can also calculate how much of your css is actually used. Or we can move to a library like emotion!

**Comment by tx4x** [comment]
@PepijnSenders : yup, that's I'd always recommend to split the whole story up into cross browser e2e/functional testing and KPI testing: basically all the stuff you want to run as pre-commit hook which are so much easier with a few puppeteer scripts and a handful chrome event parsers. KPIs should act here ideally as early safety net, so no one can add resources/scripts that exceed size, LongTask, FPS, memory, gpu,... budgets. There's also 'App-Index' btw. (i have some background in APM/RUM ;-)
g

**Comment by chrismclarke** [comment]
Life in acronyms :p

**Comment by tx4x** [comment]
:p
yep, I should have write these things out. that are the lessons learned 

- larger sites (ebay, atm, etc..) instrument their pages at run-time for KPIs they can improve progressively. the collected beacons(first render, resource-timing-api, rage clicks,...) go then back into the dev cycle but also trigger alarms when users have crashes. this is done by injecting their sites with 3th party monitoring agents.... possibly we  can skip this for some time and go straight to
- have at least some build-time tests in place preventing too big builds, slower frame rates, unresponsiveness, etc.. from getting into master. these tests should run fast and honestly i don't know better than chrome APIs and parsing events. this safes you from lots of trouble :-) as said, a few puppeteer sctipts (i have:-) and we're set.
- functional/e2e tests running on CI are independent and kinda own story
g

**Comment by tx4x** [comment]
any news or decisions ? if not to I add Cucumber as proposed, as Typescript based CLI tool via puppeteer scripts. I don mind the tooling per se. Soon we should have some basic tests (local, pre-commit hook) in place, no ?

**Comment by chrismclarke** [comment]
I'm still pretty keen to put in cypress as I really like it and want to get more familiar, however finding it hard to find the time for everything right now (more people in project means a lot more oversight work + based in various parts of Africa for work for next 6 weeks) so if anybody wants to add anything else then they can feel free.

The main downside to cypress is it's freaking huge as a dev dependency! (like 500MB), so probably best to add scripts with expectation that anyone running tests has installed globally (easy enough to add to cli pre-build script too)

**Comment by chrismclarke** [comment]
We've (finally) gotten around to implementing cypress testing, with a bunch of specs and integrations already done (thanks @tmhung88!)

Closing this issue here as dealing with specific tests on a case-by-case basis
