### ISSUE TITLE
[Suggestion] Support badge added to username component

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2662]
Heyo a little proposal here for the supporter badge. 

Currently when a user is a supporter on Patreon they receive a badge on their profile 
<img width="1105" alt="Screenshot_2023-07-25_at_06_46_28" src="https://github.com/ONEARMY/community-platform/assets/17761877/50834d78-7898-46b5-84d0-fe82942c02e8">

Wouldn't it make sense to follow the verified badge behavior and add the support badge to the username component so it follows the username everywhere around the platform inviting more people to potentially become supporters?
![Group_3](https://github.com/ONEARMY/community-platform/assets/17761877/84001a3c-3e59-4f59-8b31-1fb3eeb480ab)

**Comment by davehakkens** [comment]
Makes sense but we are first making the connection with patreon users before rolling out more supporter features. 

How do you see this with verified users, show both badges?

**Comment by thisismattia** [comment]
There are two options that I can think of which we're defining now as part of pp community program:
1. All verified must also be supporters
2. Show both badges

**Comment by goratt12** [comment]
> Makes sense but we are first making the connection with patreon users before rolling out more supporter features. (Same goes for #2663)
> 
> How do you see this with verified users, show both badges?

How is connection currently work?
I found out Patreon have public [API](https://docs.patreon.com/#get-api-oauth2-v2-campaigns-campaign_id-members)
I suggest using a scheduled firebase function that will query Patreon for all members of the campaign, and update the supporting members document with the `badges.supporter` attribute to `true/false` by email

**Comment by davehakkens** [comment]
@goratt12 Thanks for thinking about it, we have an issue open for this connection here: https://github.com/ONEARMY/community-platform/issues/2537
@AlfonsoGhislieri is currently working on this

**Comment by davehakkens** [comment]
Closed this for this new issue:
https://github.com/ONEARMY/community-platform/issues/3068
