### ISSUE TITLE
[Suggestion] Add support link to user dropdown menu

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2663]
Hello another request regarding the supporter flow. 

Issue:
Currently there is no flow from Community Platform to Patreon where people can become supporters. 

Solution:
Add a link to Patreon from the user dropdown menu

![Group 2](https://github.com/ONEARMY/community-platform/assets/17761877/b73a5339-6dc2-4d58-8bee-827ee47fac82)

**Comment by swap9820** [comment]
Hey, Would love to take this one up and contribute. Please let me know if I can proceed. Thanks!

**Comment by AlfonsoGhislieri** [comment]
Is the dropdown menu the best location for this? To me support here is a bit confusing and makes me think this has more to do with customer support/help/faq kind of info. Visibility wise it is also quite hidden away, especially to any users that are not logged in, they won't be able to see it.

Might it not be better to include it on the main navbar, would definitely get more visibility.

**Comment by swap9820** [comment]
I agree, Nav bar would be a great place to get support button its visibility.  Maybe just beside Academy would be a good place to place it. I can try getting started on this if no one else is already working on this issue. 

Cc @AlfonsoGhislieri , @thisismattia

**Comment by thisismattia** [comment]
Hey guys thanks for the messages. Yep your comments makes a lot of sense. 

As far as I am concerned this issue is on pause waiting for a Patreon integration, @davehakkens ?

Agree main navabar could be a more prominent place for the support button but not sure how prominent we want to make this. Again @davehakkens ?

**Comment by pizzaisdavid** [comment]
>  Lets get that merged and reassess how to best implement traffic from CP>Patreon

@davehakkens the referenced ticket has been completed, so this ticket is unblocked.

So... should the support <3 be added to the dropdown?

**Comment by davehakkens** [comment]
Good point. Yes can indeed be added now!
