### ISSUE TITLE
Remove repetition of wording in HT form

### ISSUE THREAD

**Issue by sigolenej** [ONEARMY/community-platform#2666]
In the current How-To form, we repeat very often "of your How-to" or "of this step", which is quite redundant, can this be removed?

![Screenshot 2023-07-25 at 12 35 11](https://github.com/ONEARMY/community-platform/assets/138245356/96167083-d136-47ab-951f-e88529807d09)
![Screenshot 2023-07-25 at 12 34 43](https://github.com/ONEARMY/community-platform/assets/138245356/adfcbcf7-63a5-4caf-ba2a-87c4fed43f0d)

cc @thisismattia

**Comment by lzizn** [comment]
I got this!
