### ISSUE TITLE
[feature request] add moderation feedback display for map pins that 'need improvement' or are 'rejected'

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2668]
**Is your feature request related to a problem? Please describe.**
Map pins that have been 'rejected' / need updates before they can be approved need to be able to show any moderation feedback left by admins so that the user can make changes and re-submit.

**Describe the solution you'd like**
The feedback comments should be shown in 2 places:
- On the map pin card displayed on the map along with a link to edit their map pin
- On the profile settings page where the map pin is edited it should display the status and if 'rejected' the feedback comments.

Describe alternatives you've considered
N/A

**Comment by sigolenej** [comment]
---- Title ---
{username} - Your map pin needs some more work

---- Content ---
Hey {pulse.name},
We're really happy to see you on the Precious Plastic Map 👐

To get your map pin published, please complete your profile information.
Check the profile guidelines*, and especially pay attention to these points:
* https://drive.google.com/file/d/1fXTtBbzgCO0EL6G9__aixwqc-Euqgqnd/view

Please review the following & re-submit your Map Pin:
 {admin comment added via retool}

Until you update your information, your pin will remain hidden from the map.

We hope to see your edits soon, so we can get your project online as soon as possible :)
Thank you,
Charlie your Precious Plastic Community Manager

**Comment by sigolenej** [comment]
Hey @iSCJT is anyone working on this? are you missing info from our end?

**Comment by thisislawatts** [comment]
👋🏻 Hey @sigolenej, I am going to pick this one update

**Comment by thisislawatts** [comment]
Can I ask about these details:

* `{pulse.name}` what does this mean?
* `Charlie your Precious Plastic Community Manager` – was Charlie used as an example here, and it should update based on the moderator who added the comment?

**Comment by sigolenej** [comment]
Thanks @thisislawatts for picking this up !

1) {pulse.name} --> sorry, this is a dynamic field from monday.com, it consists of username.

2) Charlie is the name we have given the community manager :) so all emails should be sent by this name, regardless if it is me or marcela or any other admin who modifies the status. :) 

3) The format has not really followed in the text I have sent, ideally the "guidelines" would have a hyperlink to the gdrive link below. Is this possible?

**Comment by sigolenej** [comment]
Hey @thisislawatts I see you re-assigned this item to yourself, do you need any additional information from us?

Here is a re-worked version of the email that we would like to see for "needs for improvements"

MAP PINS
---- Title ---
username - Your map pin needs some more work

---- Content ---
Hey username,
We're really happy to see you on the Precious Plastic Map. 👐

Your map pin needs a bit more work before we can publish it. 
Please take into account our comments, go through our guidelines _(add embed url https://drive.google.com/file/d/1fXTtBbzgCO0EL6G9__aixwqc-Euqgqnd/view)_ and re-submit your pin 😄 
{admin comment added via retool}

Until you update your information, your pin will remain hidden from the map.

We hope to see your edits soon, so we can get your project online as soon as possible :)
Thank you,
 The Precious Plastic Team

HOW-TO
---- Title ---
Your How-to needs more work: {HT title}

---- Content ---
Hey username,

Your How-To -{HT title}- needs more work before we can publish it.

Please review the following & re-submit your How-to:
{admin comment added via retool}

Looking forward to hearing back from you,
 The Precious Plastic Team
