### ISSUE TITLE
[Design optimisation] Remove margin Research comments

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2681]
**Describe the bug**
The comment section on research module has an unnecessary margin taking up screenspace

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a [research topic](https://community.projectkamp.com/research/make-a-basekamp-extension-in-a-container)
2. Click on comments
3. See padding
4. Scale screen to see on mobile

**Expected behaviour**
Remove the white margin around the blue comment box

**Screenshots**
NOW
<img width="1048" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/945ecbba-00c8-429d-b10a-9b9a199dd3d4">

SHOULD BE
<img width="975" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/9290076a-da67-4ffd-a449-b6e9f8f99e8b">

**Additional context**
Double check on mobile, most needed there
![IMG_5938](https://github.com/ONEARMY/community-platform/assets/13672737/1e04c929-a367-4965-8f2e-c1be2af25982)

**Comment by sberlati** [comment]
Hey there! I can fix this

**Comment by davehakkens** [comment]
yeh go for it! Submit a PR an we assign the issue to you
