### ISSUE TITLE
[feature request] list form validation errors under publish button if how-to / research form validation fails

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2684]
Replicate any validation errors to a list under the publish button.

**Is your feature request related to a problem? Please describe.**
It is not always immediately obvious which fields have not been completed when creating/updating how-to and research and pressing the publish button.

**Describe the solution you'd like**
We would like to replicate any individual validation errors that appear beneath each field into a combined list beneath the Publish button if the form validation fails.

To be clear we would like the existing validation messages to stay where they are and for these to be duplicated into the list.

**Describe alternatives you've considered**
Modal - not considered a good user experience as requires clicking out of it and then you lose the list.

**Comment by benfurber** [comment]
Working on this now. 

**Here is as suggested:**
<img width="548" alt="Screenshot 2023-08-11 at 18 16 50" src="https://github.com/ONEARMY/community-platform/assets/16688508/ab636e4a-45d2-4273-980b-a68acc0fb4bf">

The problem with this is that on smaller screens you won't be able see all the errors on first look if there are many, you'll have to scroll down to the bottom of the page.

**Another approach:**
<img width="1009" alt="Screenshot 2023-08-11 at 18 17 46" src="https://github.com/ONEARMY/community-platform/assets/16688508/e6ffa15e-3878-439a-9dd5-f3359430bf0a">

At the top of the form.

Something for you @davehakkens or @thisismattia?

**Comment by davehakkens** [comment]
nice to see an overview of errors @benfurber!
I would say it could go underneath the button. Dont think its often many errors + its closer to the publish button.

This would also be nice to align for user profiles. That currently says this: 
<img width="500" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/85bf2e2c-08e4-4752-9012-314b5b40ff61">

**Comment by benfurber** [comment]
@davehakkens How's this? I'd say the second sentence of the user profile error button isn't needed in this case as the reset of the text explains what the user needs to change. Happy to change it though. As it's definitely going in the sidebar too I've tidied up the spacings.

<img width="473" alt="Screenshot 2023-08-15 at 14 09 36" src="https://github.com/ONEARMY/community-platform/assets/16688508/138265f0-611f-4364-b750-04343ac1a473">


I'll add updating to include the errors on the user profile to the list - especially as that white text on red [doesn't have a high enough colour contrast](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=F58D8E)

**Comment by davehakkens** [comment]
agree. Second sentence is not needed, color contrast is better like this and nice you gained some spacing!

**Comment by sigolenej** [comment]
FYI @thisismattia

**Comment by benfurber** [comment]
So the above PRs (in addition to #2707*) setup displaying the error messages that final-form understands as errors (e.g. problems that happen during the main validation flow.) 

There's a few fields here and there which won't nice a error message display yet because they have a different validation flow. For example the files field on how-tos validate after the main flow and there's at least a couple of user settings fields which do their own thing too. I'm very happy to bring these rouge fields in line but as these other five(!) PRs are pretty chunky. I'd suggest I work on this once they're merged in. 

\* = which should make future changes to how-tos easier

**Comment by sigolenej** [comment]
Will let @thisismattia get back to you on this 😄

**Comment by thisismattia** [comment]
Thank you guys for this. Not sure my input is still needed but one thing I thought is that "Make sure this field is filled correctly" is used everywhere. We could semantically restructure it to only list things that need to be filled correctly. 

Let me try to explain, it could go something like this:

Ouch something is wrong. Make sure the field(s) below are filled correctly:
Intro
- Title of your How-to
- Description of your How-to
- ...


Hope I could explain myself properly :)
