### ISSUE TITLE
[feature] badges add transactional email notifications for users and admins

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2688]
Precious plastic to provide listing of required transactional emails, their trigger and the email content.

**Comment by sigolenej** [comment]
Here are the additional email that would be nice to send to users:

               1. Supporter badge given
-- Title --
{username} - Your Precious Plastic Supporter Badge!

-- Content --
Hey {username},

Thank you for becoming a Precious Plastic Patreon supporter!

We have added your shiny new supporter badge to your community profile, YAY 🚀

Thanks,
The Community Management Team

               2. Supporter badge removed
-- Title --
Precious Plastic Supporter - We are sad to see you go.

-- Content --
Hey {username},

We are sad to see you go!
Thank you for the support you have provided to Precious Plastic, it has enabled us to continue to work to create the largest open-source community around plastic recycling.

You can support us again any time via Patreon,
Thanks,
The Community Management Team

_TO BE COMPLETED BY SIGOLENE_
               3. Verified badge given
-- Title --


-- Content --

               4. Verified badge given
-- Title --

-- Content --

**Comment by sigolenej** [comment]
I don't have the final version yet as it is connected to the redefinition of the scope of the badge. 
can we put this for now & update it later? 

Can all of the emails be signed the same "The Precious Plastic Team"?

Verified badge given

-- Title --
username - You are now part of the Verified Workspaces :)
-- Content --
 Hey {username},

We are glad to have you in our Verified program.

We have added your shiny new supporter badge to your community profile, YAY 🚀

Thanks,
The Precious Plastic Team

**Comment by thisislawatts** [comment]
Should this 
> We have added your shiny new supporter badge to your community profile, YAY 🚀

be:
> We have added your shiny new verified badge to your community profile, YAY 🚀

**Comment by thisislawatts** [comment]
> Can all of the emails be signed the same "The Precious Plastic Team"?
@sigolenej on the signoff, the system is currently using _Charlie your Precious Plastic Community Manager_

Are you looking to align **all** emails or only the ones around badges?
