### ISSUE TITLE
[bug] Step images disappear when a step is moved 

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#2701]
**Describe the bug**
When a step is moved, if images are attached to it they're no longer present/shown to the user.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to create/edit a how-to.
2. Upload an image to a step.
4. Move the step you've added an image to.
5. The image disappears.

**Expected behaviour**
The images should still be present.

**Screenshots**
<img width="677" alt="Screenshot 2023-08-01 at 19 46 47" src="https://github.com/ONEARMY/community-platform/assets/16688508/63f63a0e-25d4-4fd8-b797-a0362e1d4ec0">
<img width="677" alt="Screenshot 2023-08-01 at 19 47 27" src="https://github.com/ONEARMY/community-platform/assets/16688508/b34d091f-c38f-4194-b4c8-8e6971d83fd8">

**Additional context**
I wonder if it's something about how the images are passed to each HowtoStep and when the move callback is called, something gets lost in the mix. Not sure yet though, any other thoughts?

**Comment by benfurber** [comment]
This is happening locally, can someone confirm this happens on production too please?

**Comment by davehakkens** [comment]
yes can confirm! thanks for flagging
