### ISSUE TITLE
osr - migration / recycling 'one-army' 'platform

### ISSUE THREAD

**Issue by katbot-chained** [ONEARMY/community-platform#2706]
@davehakkens , @iSCJT , @thisislawatts , @cschilbe , @thisismattia, @katharinaelleke 

Hey everyone, 

as some of you might have noticed, the tech, needs, data, designs, ... moved far beyond the promises and statements you've made :-)

To recycle 'one-army' platform, I'd suggest stripping Mobx and other proprietary dependencies. With a bit of luck, we can use it as wizards for Discourse (world-leading community platform). I am sure, it could be useful, outside the 'island' you're building here.

I migrated so far all known designs, despite all the back-stabbing, hit-and-run, censorship, sabotage, ... : https://forum.osr-plastic.org/c/components/49 

The user directory will be next, curated by subcontractors (be my guest). There are currently 500+ censored, 5 verified - out of 1300 pins (from 10k users, during v3 - being cut off from each other), lovely

After that, I am hooking up the bazar data, without your permission. If you need a copy of the system, no problem either :-) Most of it is public : https://git.osr-plastic.org/ - solving daily problems in the field :-)

As already asked, if there's something I missed (roadmap: https://git.osr-plastic.org/osr-plastic/system/src/branch/master/diagrams/packages%20-%20q4.jpg), let me know. 

Have a nice one, 

ps: don't hesitate to censor & delete this issue as well. We don't know you differently, your violence & bullshitting isn't new :-)

**Comment by davehakkens** [comment]
closing because its not the right place for this information

**Comment by katbot-osr** [comment]
Luckily, it's not longer up to you, who's saying what, to who, what's being sold, by who, to who, the what, and how - one scandal and abuse after the next - you will held accountable for every cent and harm you've done knowingly, and on purpose
