### ISSUE TITLE
[bug] Sort Research by latest update (not useful,comment or following)

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2709]
**Describe the bug**
Currenty the research overview show all the research topics, with the `latest updated` on top.
However at the moment an update means:
- Posting a new update to the research
- Editting an existing update
- Leaving a new comment
- Marking the research as useful
- Following the research

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [research overview](https://dev.onearmy.world/research)
2. Interact on a research (useful comment etc)
3. See how the research goes to the top

**Expected behaviour**
What we would prefer to include as `latest update` is: 
- Posting a new update to the research

The other actions should not change the `update` status

**Screenshots**
<img width="1768" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/d8d600c2-cd0d-4b8e-8a5a-208d240e244a">

**Additional context**

**Comment by goratt12** [comment]
Can we close this issue? 
the fix PR was merged to master

**Comment by davehakkens** [comment]
yes. Nice one @goratt12

**Comment by davehakkens** [comment]
wait. sorry saw that wrong. It's not merged yet
https://github.com/ONEARMY/community-platform/pull/2723

**Comment by goratt12** [comment]
you are write, sorry I miss read it
