### ISSUE TITLE
[bug] Academy - Can't collapse a collapsable element

### ISSUE THREAD

**Issue by secondlnl** [ONEARMY/community-platform#2721]
## Describe the bug
In academy, an element that looks collapsable isn't.
## To Reproduce
Steps to reproduce the behaviour:
1. Go to [ Precious Plastic Academy - intro ](https://community.preciousplastic.com/academy/intro.html)
2. Click on '3. Build' in the sidebar on the left
3. Scroll down to 'Shredder Pro', expand it and attempt to collapse it
4. See bug
## Expected behaviour
A collapsable element should collapse when interacted with.
## Screencast
[Screencast from 2023-08-19 22-53-03.webm](https://github.com/ONEARMY/community-platform/assets/142692021/a52b6736-4c90-4d9c-a535-7473b75433d2)
## Additional context
System Info;
OS, "Fedora Linux 38.20230816.0 (Silverblue)"
Graphics, "NV137 / Intel® HD Graphics 630 (KBL GT2)"
Browser used "Firefox 116.0.2 (64-bit)"
*Further information may be asked for*

**Comment by prasannakarki77** [comment]
I went through it and it is an issue. but it seems that in the community platform the academy's body below navbar is a separate academy website being rendered with code from another repo [@academy](https://github.com/ONEARMY/academy). The issue has to be raised in that repo. If possible, to contribute to that repo, I would like to work on this issue. 

Please let me know. I am trying to start contributing actively and it could be my first contribution.

**Comment by evakill** [comment]
hi @prasannakarki77 - you're right, the academy is hosted in a separate repo. thanks for reporting the bug @secondlnl, i will pass it on to the maintainers of the academy! 

cc @davehakkens
