### ISSUE TITLE
[bug] category does not prepopulate when editing a how to post or draft

### ISSUE THREAD

**Issue by evakill** [ONEARMY/community-platform#2725]
**Describe the bug**
The category field appears empty when editing an existing how to that has a category selected.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a how to, select a category tag, save as draft or publish
2. Return to edit this how to
3. Category is not present in fom

**Expected behaviour**
Category should persist when saved and appear in the form when in edit mode.

**Screenshots**

**Additional context**

**Comment by jwjacobs88** [comment]
It looks like when draft saves were enabled, `category` was left out of the DB population here.

**Comment by evakill** [comment]
@jwjacobs88 great catch! do you want to put up a fix for this?

**Comment by jwjacobs88** [comment]
I was looking at trying to test it, but running into a couple snags. :)

**Comment by evakill** [comment]
ok - let me know if i can help :)
