### ISSUE TITLE
[feature] add tooltips to the research listing page

### ISSUE THREAD

**Issue by evakill** [ONEARMY/community-platform#2728]
**Is your feature request related to a problem? Please describe.**
The icons on the research page aren't always clear to users.

**Describe the solution you'd like**
Add a tooltip on the icons on the [research overview](https://community.projectkamp.com/research) to show what they mean. When hover more info pops up
(We already use tooltip in various places on the site. For instance to tell a user to login when wanting to useful or download files from a how-to)

![image](https://github.com/ONEARMY/community-platform/assets/37253846/403231c3-abb3-4a94-a74e-dd84b239f559)

**Describe alternatives you've considered**

**Additional context**

**Comment by aaronguernsey** [comment]
If no one is assigned, I could take a crack at this.

**Comment by davehakkens** [comment]
nice @aaronguernsey. Yep you can use that text!

**Comment by AlfonsoGhislieri** [comment]
Sorry to have jumped on this, @aaronguernsey, didn't see you were taking a crack at it, was working through an issue and added it.

**Comment by davehakkens** [comment]
nicee @AlfonsoGhislieri !
Could also add it to useful on how-to's for consistency. (or better new issue?)
<img width="409" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/6e6d6615-c661-4d30-97b4-42d3c156f02c">

**Comment by AlfonsoGhislieri** [comment]
Sure thing, just added it now!
