### ISSUE TITLE
[feature request] Add stats to header How-to and Research

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2734]
### Description
Add space to include more statistics in the header of the research and how-to's

Stats to include:

**Research**
- Viewcount (currently live in beta)
- Users Following (stat is not shown yet)
- Useful (stat is live on research overview)
- Comments (stat is live on research overview)
- Updates (stat is live on research overview)

**How-to**
- Viewcount (currently live in beta)
- Useful (stat is live on how-to overview)
- Comments (stat is not shown yet)
- Steps (stat is not shown yet)

**Notes:**
- This allows in the future to make "useful" and "following" clickable so you can see which users enagegd
- There will be another issue to follow up **mobile** (#2735)
- All icons are already available on live. 

### Page related

Will be used in :
[Research](https://dev.onearmy.world/research/more-draft-checking) 
[How-to](https://dev.onearmy.world/how-to/test-title)

### Mockup
<img width="1164" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/eacde74a-8074-427b-bc00-9fae0b4dadb1">

<img width="1105" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/d8d456ec-d3ba-4748-83cc-86e66697edba">

**Comment by CheRayLiu** [comment]
Hey all, happy to help out and work on this issue. Would you mind assigning this issue to me? Thanks!

**Comment by davehakkens** [comment]
Go for it @CheRayLiu. Thanks! We will officially assign to you when a PR, or draft PR is made. (Its a new thing we are trying to avoid assigning people that might not be able to build it)

**Comment by thisismattia** [comment]
For HT I believe steps is irrelevant for the component infos as it is a static number that won't change + it's already here 
<img width="279" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/dae7d7b2-36e9-45bf-99f9-ed3db176b419">

Maybe a way of looking at it is that it only contains dynamic stats that change over time to give it some semantic meaning.

**Comment by thisismattia** [comment]
Downloads?

**Comment by davehakkens** [comment]
Ideally download count stays near the download button . 
In that way we can re-use the same download component on research as well (there can be multiple download buttons on one page there) 

So for this issue we could:
- Show `download` stat twice
- Shows `steps` stat twice
- Only show `useful` `comment` and `view` stats
Let me know what you prefer

**Comment by davehakkens** [comment]
Its seems to open up more boxes along the way.
I'd suggest we release as planned to move forward so the function is there. (and pr is already made https://github.com/ONEARMY/community-platform/pull/2737)
And when merged we can already move forward to develop mobile https://github.com/ONEARMY/community-platform/issues/2735 and see if the function works well . (We can also release in beta if you prefer)

But please make a proposal if you want changes to be made.
Can be a nice follow up issue since your changes seem quite small.
