### ISSUE TITLE
[feature request] Optimize mobile layout How-to and Research

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2735]
### Description
It's getting busy in the headers and it could use some optimisation on mobile. As mention in issue #2191
This issue is a follow up from https://github.com/ONEARMY/community-platform/issues/2734

We want to add hide some more detailed information by default that can be shown on a click using the "accordion" style

### Page related

Will be used in :
[Research](https://dev.onearmy.world/research/more-draft-checking)
[How-to](https://dev.onearmy.world/how-to/test-title)

### Mockup
Example for the research module, same principle applies to how-to's
<img width="682" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/f97db6f4-fb74-42ed-af77-0ac189a0aa77">

### Note
It contains the new stats from #2734 but also moves the contributors on mobile.

**Comment by thisismattia** [comment]
My 2cents on here would be that the back button is redundant on mobile as I believe most people use native gestures (swipe left) to go back a page. Removing the back button would free up some crucial real estate.

**Comment by davehakkens** [comment]
Agree @thisismattia but i think the back-button could use a critical look as the same logic applies on desktop, since browser have a back button. Something like a breadcrumb there makes more sense

**Comment by psyfire25** [comment]
Hi there. I’m now a carpenter but in a past life was a front end developer. I’m recovering from a very bad broken ankle and have a lot of time on my hands. I would be happy to help with this task and others. My main experience is in front end but have also done full stack some time ago. If you are up for me helping out then respond to this and we can have a chat about login details etc.

**Comment by davehakkens** [comment]
Cool @psyfire25, go for it! The moment you subbmit a PR (can be a draft) we will assign the issue to you.
Here you can find information on how to get started and run locally: https://docs.platform.onearmy.earth/

Good luck with the ankle!

**Comment by psyfire25** [comment]
Great will get on it tomorrow probably

**Comment by thisismattia** [comment]
@davehakkens would agree, not very useful on desktop too. Remove altogether?

**Comment by davehakkens** [comment]
You manage to get it up and running @psyfire25?

**Comment by denyilm** [comment]
Hello! I would like to work on this issue and I have a question. I am not able to add a research or how to item in the dev mode. Do I need to get the emulators running to be able to add any?

![image](https://github.com/ONEARMY/community-platform/assets/65300462/cb512157-7f62-40a8-acde-38f964810813)

**Comment by denyilm** [comment]
Hi @davehakkens, I would like to keep working on this issue. Feel free to assign it to me, thanks!
