### ISSUE TITLE
HT Sorting 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2746]
It is unclear to me how the sorting works on the How-to page.
<img width="1409" alt="sort" src="https://github.com/ONEARMY/community-platform/assets/17761877/64c51421-83bc-4d84-8c6a-5f7022d278cd">

We currently have 3 options (I think):
- On load, seems to be random but not sure about it
- Created, I think it means latest created but wording is confusing to me
- Most useful, this is clear. 

Proposed way forward:
- On load, random sorting to give returning users a feeling things are changing or new
- Newest, chronological order from the latest created (not edited)
- Most useful, HT with most usefuls first
- [Optionally] Most view, HT with most views first
- [Optionally] Most downloads, HT with most downloads first
- [Optionally] Most comments, HT with most comments first (not sure if we're counting comments already given small interaction currently)

Looking forward to hear what everyone thinks.

**Comment by goratt12** [comment]
The PR #2753  set the default sorter to 'Created':
https://github.com/ONEARMY/community-platform/blob/49831f57ef543a3fde066656b699ad54576c6d1c/src/pages/common/SortFilterHeader/SortFilterHeader.tsx#L56-L61

The option 'Created' is sorting by the field `_created` that is set at HowTo creation only
The option 'Most Useful' is sorting be the length of the array field `votedUsefulBy` that is updated every time a user mark HowTo as useful/un-useful

**Comment by thisismattia** [comment]
@AlfonsoGhislieri thanks for the clarification. Indeed a bit confusing. 

As far as I understand it, the underlying goal of the Community Platform is to store useful knowledge. Ideally a HT from 3 yrs ago is as useful as a HT from yesterday. From this logic I think a "random" sorting can still offer a positive UX to the user as they'd be presented/surprised with new HT they might not have known about. 

I propose"

1. HT to be displayed "random" on load
2. The sorting dropdown having the following items:
- Newest
- Most useful
- Latest updated? (I am not sure I see the underling benefit for a visitor)
- Random

A third point would be regarding the sorting options I was listing above:
[Optionally] Most view, HT with most views first
[Optionally] Most downloads, HT with most downloads first
[Optionally] Most comments, HT with most comments first (not sure if we're counting comments already given small interaction currently)

Do you know if we can sort by these metrics?

**Comment by AlfonsoGhislieri** [comment]
Yeah that totally makes sense @thisismattia! We can get all this implemented like you suggested, the only issue I think is with:

> [Optionally] Most view, HT with most views first

Since views remain in beta, it might confusing to roll it out as a sorting filter if most users can't see anything related to views?

In any case I can get everything else done; however, this would first require #2752 to be merged in as this would have to build off of it!

**Comment by thisismattia** [comment]
Nice one! 
Can we develop the views sorting in Beta too and release it when out of beta?

**Comment by AlfonsoGhislieri** [comment]
I can have a look into that, but I'm not sure how easy/do-able  that is since it would be a list item within another component. In any case we can certainly try :)

**Comment by thisismattia** [comment]
thank you @AlfonsoGhislieri sorting looks very good ♥️ I believe UX will improve manifold thanks to this work!

Only tiny correction (not urgent) I would propose is regarding the placeholder text on load. 
Currently it says "Random" which to a new user without much context might be confusion. What is random? Also I guess the word random without context doesn't have great connotations. Is it the work shown that is random? 
<img width="1662" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/fea58a61-2a09-468e-bea8-c86929d34896">

I propose having the onload placeholder text to say "Sort by" (while keeping the sorting order random). This way (new) user can understand the function of that field. 

No rush just a tiny improvement, would you need a new issue for that?

**Comment by AlfonsoGhislieri** [comment]
That’s a good point @thisismattia! Yes maybe open a new issue so someone else can have a crack at contributing to the codebase with a smaller issue :)

**Comment by thisismattia** [comment]
Yep will do!
