### ISSUE TITLE
[bug] old research updates not deleted properly

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2760]
**Describe the bug**

Correct number of updates are not actually being stored, this probably has to do with updates in the past not having been correctly deleted from the item in the database? Not sure how big of an issue this is, and considering this is no longer an issue as deletion is correctly handled, if we even want to go back and fix it?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'research'
2. Look at a 'make a house from recycled plastic' researches total updates
3. Click on 'make a house from recycled plastic'
4. See that there are not actually the same number of updates

**Expected behaviour**

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/652368/4d5574ba-7c68-44d0-91d9-a7821569ea71)

![image](https://github.com/ONEARMY/community-platform/assets/652368/6e6ea04b-deb4-4642-a12b-02c7c91e0e69)
**Additional context**

**Comment by laviodias** [comment]
I can't assign myself to this, but I already opened a PR.
