### ISSUE TITLE
[bug] Text overflow for long strings in how-to steps

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2763]
**Describe the bug**

If there is a long unbroken string of characters in a How-to step it will overflow the bounding box and disappear behind the media.

**Expected behaviour**
The text should flow over multiple lines.

**Screenshots**

![Screenshot 2023-09-10 at 10 40 36](https://github.com/ONEARMY/community-platform/assets/472589/eb194ea3-ce0b-4283-ad3d-71a84ca8bcdd)

**Comment by Shubh8899** [comment]
I would like to work on this.

**Comment by manuelrurda** [comment]
How can I work on this or get this issue assigned
