### ISSUE TITLE
How-to sort by placholder

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2804]
A tiny improvement for the sorting feature. 

Currently on load the sort by text placeholder says "Random" which is a bit confusing (specially for new users). 
<img width="1662" alt="270152066-fea58a61-2a09-468e-bea8-c86929d34896" src="https://github.com/ONEARMY/community-platform/assets/17761877/0111f0e3-ff54-4c4d-b7bb-ae361c9ec995">

Would be great to have the placeholder text say "Sort by" while the sorting criteria still being random. 

Once user selects a certain sorting criteria the placeholder text can then change to whatever choice has been made by the user. Basically keeping it as it is currently.

**Comment by arthurtyukayev** [comment]
I've addressed this bug here:
https://github.com/ONEARMY/community-platform/pull/2805

I've also updated the sort and filter inputs to hide the already selected option as it's already in the input.

**Comment by thisismattia** [comment]
Nice one! Thanks 🤙

**Comment by thisislawatts** [comment]
Closed via #2847
