### ISSUE TITLE
[bug][doc request] Wrong link in README.md

### ISSUE THREAD

**Issue by ajotka** [ONEARMY/community-platform#2806]
**Describe the problem**
I wanted to dive into this project and find place for myself. But the very first thing that I discovered was wrong link for "good first issues" in README.md

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/15144546/96f46cba-dbfa-4bca-a706-56dc856b1d7a)
![image](https://github.com/ONEARMY/community-platform/assets/15144546/d7d6e579-ac32-48be-a3c8-88dfe474a4de)

(but without labels in search field, there are results with good first issue label)
![image](https://github.com/ONEARMY/community-platform/assets/15144546/c83a4b17-f440-421e-be97-6358a4906e18)

**Comment by ayachish** [comment]
@onearmy-bot I've created a pull-request to resolve this issue, please check. Thank you
