### ISSUE TITLE
[feature request] Loader or information about fetching research data in Research page

### ISSUE THREAD

**Issue by ajotka** [ONEARMY/community-platform#2808]
**Is your feature request related to a problem? Please describe.**
When I opened Research page I saw info about no results. After 1 second, results list jumped in. But first information was misleading.

**Describe the solution you'd like**
Loader. Or information about active fetching process.
Ideally, cache the list, because it's fetching after every page opening.

**Video with reproducing the problem**
[scrnli_26-09-2023_15-15-48.webm](https://github.com/ONEARMY/community-platform/assets/15144546/803ad93d-9156-49f0-8632-13adb1ed131f)

**Comment by thisislawatts** [comment]
Thanks for the bug report @ajotka 💚, I totally agree this is something which needs to be resolved.

**Comment by ajotka** [comment]
PR is ready: https://github.com/ONEARMY/community-platform/pull/2819
