### ISSUE TITLE
[feature request] Add visual character limit to map pin

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2865]
**Is your feature request related to a problem? Please describe.**
There is a character limit to map-pins but this is hard to see, specially when you start typing since it goes away

**Describe the solution you'd like**
We recently added a new method to display a character limit  in the how-to's. Would be nice to use the same component for the map pins

**Page**
User profile [Settings](https://dev.onearmy.world/settings) page (Click: "add map pin" button)

**Mockup**
Currently - Limit is only shown in input field
<img width="869" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/6700f3d6-6d29-44ad-b207-6fe5f93158f3">

After - Limit is shown at the bottom on the input field as well

<img width="464" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/2efa7faa-c138-4b31-abe2-359c72622f32">

**Notes**
Here you can find the component in [Storybook](https://docs.platform.onearmy.earth/storybook-static/index.html?path=/story/components-fieldtextarea--with-character-counts)
[Create a new how-to](https://dev.onearmy.world/how-to/create) to see it in action

**Comment by richardrdev** [comment]
I can work on this, should be a quick one 👍

**Comment by davehakkens** [comment]
niceee. Submit a PR (can be a draft) and we assign it to you

**Comment by cjh1212** [comment]
Hi, I also want to work on this and submitted a draft PR. Thanks.

**Comment by thisislawatts** [comment]
Closed by: https://github.com/ONEARMY/community-platform/pull/2869
