### ISSUE TITLE
[feature request] Add character limit in user profiles description

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2866]
**Is your feature request related to a problem? Please describe.**
Some profiles have a large amount of text in their description which breaks the design layout. 

**Describe the solution you'd like**
Part 1:
We would like to add a character limit for Individual ([member](https://community.preciousplastic.com/u/yohanna-jiel-nyok)) & Group ([spaces](https://community.preciousplastic.com/u/annaborohova)) Profiles
For individuals: Max 500 characters
For Groups: Max 2000 characters

Part 2:
Add the character limit component to the input field (see in [storybook](https://docs.platform.onearmy.earth/storybook-static/index.html?path=/story/components-fieldtextarea--with-character-counts))
You can test it live when creating a [new how-to](https://dev.onearmy.world/how-to/create) in the title field

**Additional notes**
The question was raised wheter we want long profile descriptions, no decision was made. But for now this issue is here to prevent breaking the design layout and aligning data sizes for profiles. We might increase the limit at a later point

**Comment by kensiecodes** [comment]
Been looking to get involved in this project, would love to take this on

**Comment by laviodias** [comment]
Any thoughts on how to display the current larger names? Or we'll be only preventing new cases?

**Comment by davehakkens** [comment]
Good to hear @kensiecodes:)
Submit a PR (can be draft) and we assign the issue to you!

This is only to prevent the new cases @laviodias, the current ones got lucky.

**Comment by davehakkens** [comment]
Are you planning to take this on @kensiecodes?
If not it's open for others to contribute!

**Comment by Erkanerkisi** [comment]
I'd like to take it if @kensiecodes not working on this?
