### ISSUE TITLE
[feature request] documentation site search

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2874]
**Is your feature request related to a problem? Please describe.**
Users of our documentation site frequently struggle to locate specific pieces of information efficiently due to the absence of a search functionality. The current navigation system, relying on a nested hierarchy of pages, requires users to click through multiple layers to find the content they need, leading to frustration and wasted time. Without a direct and fast way to access required information, users are often left sifting through pages of content, which hampers their experience and may discourage them from fully utilizing our resources.

**Describe the solution you'd like**
We propose the integration of a robust search functionality into the documentation site. This feature should allow users to input search terms into a search bar located at a prominent position on the site, most conveniently at the top of the page. The search engine should then return a ranked list of relevant results drawn from the site’s content, with links directing users straight to the pertinent sections of text.

For optimal user experience, the search function should also support:

- Autocomplete suggestions based on popular and recent searches.
- Filtering options to narrow down results by categories or tags.
- Highlighting of search terms within the retrieved text for easy identification.
- Responsive design to ensure usability on devices of different sizes.

**Describe alternatives you've considered**
One alternative would be to improve the site’s existing navigation system, perhaps by implementing a more intuitive category structure and adding an index or sitemap. This approach, while helpful, would still require users to navigate through the site manually and would not offer the same level of convenience and speed as a search function. Another option would be integrating third-party search solutions, but these may not offer the same level of customization and integration as a built-in feature, potentially leading to a disjointed user experience.

**Additional context**
The introduction of a search feature would significantly enhance the user experience by providing immediate access to desired content, reducing the time and effort currently required to navigate the site. The enhanced efficiency and ease of use are likely to encourage users to engage more deeply with the available resources, fostering a more positive relationship with our platform. This feature would be particularly invaluable for users who are not familiar with the site’s structure or are looking for information located deep within the site's hierarchy. For these reasons, the addition of search functionality represents a critical improvement to the usability and user satisfaction associated with our documentation site.

**Comment by davehakkens** [comment]
Would intergrating one of these options from docusaurus be a good plan, like agolia?

https://docusaurus.io/pt-BR/docs/2.0.1/search

**Comment by thisislawatts** [comment]
Yep Algolia would be a good starting point

**Comment by darigovresearch** [comment]
Can confirm this would be really helpful when going through the docs to find the relevant page.

Is there a new link @davehakkens? (It currently links to a 404 for us)

There may be other plugins which come out of the box that provide more than, in the past have found algolia to be very powerful (which is good), there may also be a "good enough" fuzzy search that comes with docusaurus which may be easier to enable as a first iteration
