### ISSUE TITLE
[feature request] move how to moderation feedback to retool

### ISSUE THREAD

**Issue by evakill** [ONEARMY/community-platform#2876]
**Is your feature request related to a problem? Please describe.**
we allow admins to leave feedback comments when moderating how tos. this was added in [this scope of work].(https://github.com/ONEARMY/community-platform/issues/2377) 
current input:
<img width="1792" alt="Screen Shot 2023-10-20 at 8 05 29 AM" src="https://github.com/ONEARMY/community-platform/assets/37253846/71df8a23-cba9-46a0-a55a-bdae7e3d7de3">
<img width="1271" alt="Screen Shot 2023-10-20 at 8 19 30 AM" src="https://github.com/ONEARMY/community-platform/assets/37253846/8931874c-de42-433e-937a-6ebb2f731d87">

now that we are using retool as our moderation interface, we should enable this capability in retool and remove it from the platform. 

**Describe the solution you'd like**
- [x] review the moderation feedback structure and workflow with the PP team 
  - also consider that this is currently different between how tos and map pins, and would be good to have a shared model between them
- [x] add inputs for moderation feedback in retool
- [x] remove the moderation feedback from the UI
- [ ] update the dependent structures (notifications, in-app messaging, emails) to work with the new structure

**Describe alternatives you've considered**

**Additional context**

**Comment by thisislawatts** [comment]
>  update the dependent structures (notifications, in-app messaging, emails) to work with the new structure
@evakill is there much still to be done on this item?

**Comment by evakill** [comment]
nope! all looks good 👍
