### ISSUE TITLE
[feature request] Upgrade React Router to v6

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2881]
React Router version 6 introduces several powerful new features, as well as improved compatibility with the latest versions of React. It also introduces a few breaking changes from version 5. This document is a comprehensive guide on how to upgrade your v4/5 app to v6 while hopefully being able to ship as often as possible as you go.

The examples in this guide will show code samples of how you might have built something in a v5 app, followed by how you would accomplish the same thing in v6. There will also be an explanation of why we made this change and how it's going to improve both your code and the overall user experience of people who are using your app.

In general, the process looks like this:

- [X] [Upgrade to React v16.8 or greater](https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-v168)
- [X] [Upgrade to React Router v5.1](https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v51)
- [X] [Remove `<Redirect>`s inside `<Switch>`](https://reactrouter.com/en/main/upgrading/v5#remove-redirects-inside-switch)
- [ ] [Remove all RouteComponentProps types](https://copyprogramming.com/howto/react-typescript-module-react-router-dom-has-no-exported-member-routecomponentprops)
- [ ] [Refactor custom `<Route>`s](https://reactrouter.com/en/main/upgrading/v5#refactor-custom-routes)
- [ ] [Upgrade to React Router v6](https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v6)

https://reactrouter.com/en/main/upgrading/v5

**Comment by ajotka** [comment]
@thisislawatts I checked point `Remove <Redirect>s inside <Switch>`. It's already done. All Redirects are out of Switch component.

**Comment by ajotka** [comment]
@thisislawatts also please add task no.6 "Remove all RouteComponentProps types". 
It's because react-router-dom has no RouteComponentProps anymore. 
More details: https://copyprogramming.com/howto/react-typescript-module-react-router-dom-has-no-exported-member-routecomponentprops

**Comment by mariojsnunes** [comment]
I'll look into this

**Comment by mariojsnunes** [comment]
I've opened the PR.
Would be nice to have someone go to the branch and do more functional tests :)
