### ISSUE TITLE
[feature request] Change wording and default filter options in research

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2925]
**Is your feature request related to a problem? Please describe.**
The filter options in the research module are not very clear. This was already fixed for the how-to's in this issue https://github.com/ONEARMY/community-platform/issues/2746. Now we want to clear it up for Research.

<img width="744" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/8480d5a4-e20b-4913-b0f0-a5fe46e8f7e1">

**Proposed filter names + default setting**
- Newest
- Latest update (this should be set to the default)
- Most useful
- Most comments
- Most updates

**Comment by mayalmog** [comment]
Hi @davehakkens , I'd like to take this as my first issue.

**Comment by davehakkens** [comment]
nice go for it @mayalmog.
Submit a PR (can be draft) and we will assign the issue to you
