### ISSUE TITLE
[feature request] Hide "member" mappins by default on PP

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2927]
**Is your feature request related to a problem? Please describe.**
The map is getting crowded (cluttered) which makes it harder for workspaces to pop out + slow loading times.

<img width="1299" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/a588e10c-d844-42d8-b207-8fb214f533dd">

**Describe the solution you'd like**
We would like to hide the "want to get started" pins by default on [Precious Plastic map](https://community.preciousplastic.com/map)

**Notes**
This is a specific setting for Precious Plastic with a mature community.
Other projects (instances) probably dont want to hide this in their early stages. 
So ideally it's a setting that can be configured per instance.

**Comment by benfurber** [comment]
@davehakkens It's fairly straightforward to add a function to how `filtersSelected` is loaded on the map `Controls` (src/pages/Maps/Content/Controls/Controls.tsx). And only for PP is straightforward. Making it an admin controlled configuration option is a lot more work. 

As sorting it for PP only as a small task and as a admin (i.e. non-code) configuration is a big one, is there a priority difference for you on getting this work done?

**Comment by davehakkens** [comment]
good to hear its fairly straightforward @benfurber .
For now we just need to have it configured for PP. No admin interface needed.

**Comment by benfurber** [comment]
Doesn't look like #2975 worked. So the method used to switch instances must be different from how it's worked out during build. I'll try another approach.
