### ISSUE TITLE
[QuestionPage] Content Statistics

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2961]
Reuse `ContentStatistics` module from How-to/Research. This should only be done after Comments, Following and Vote Useful behaviour has been implemented for Question content type.

**Comment by davehakkens** [comment]
Image as reference 
![stats](https://github.com/ONEARMY/community-platform/assets/13672737/9f340228-3ec6-49fe-a0d1-069090905fae)
