### ISSUE TITLE
[QuestionPage] Comments

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2962]
Use `Discussion` module once it has been merged https://github.com/ONEARMY/community-platform/issues/2564

**Comment by evakill** [comment]
reminder to also add updates for comments made on questions when a user's username or country changes; see discussion [here](https://github.com/ONEARMY/community-platform/pull/3053#pullrequestreview-1785261150)

**Comment by thisislawatts** [comment]
Marking as closed here as Comments are now available in Questions
https://dev.onearmy.world/questions
