### ISSUE TITLE
[QuestionCreate] Select category

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2963]
It should be possible to define the Catgories which are appropriate for the content based on a predefined set of tags. Look at Research/How-to for an example.

Stretch. Refactor our current implementation to remove duplicate collections.

**Comment by davehakkens** [comment]
Image as reference 
![categories](https://github.com/ONEARMY/community-platform/assets/13672737/e0652349-97ff-4389-a344-506f656bd889)
