### ISSUE TITLE
[QuestionCreate] Select tags

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2964]
It should be possible to define the tags which are appropriate for the content based on a predefined set of tags. Look at Research/How-to for an example.

Stretch. Refactor our current implementation to remove duplicate collections.

**Comment by davehakkens** [comment]
Image as reference 
![tags](https://github.com/ONEARMY/community-platform/assets/13672737/7ea1339d-2391-4316-80f2-ace08cf55096)

**Comment by onim-at** [comment]
Hello, I'd like to work on this issue
