### ISSUE TITLE
[QuestionCreate] Sidebar with explanation

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2965]
Currently the sidebar block for the Edit/Create forms is being loaded from the Research section. This should instead be written specifically for the Question content type.

**Comment by davehakkens** [comment]
Image as reference 
![sidebar](https://github.com/ONEARMY/community-platform/assets/13672737/2290ea2c-9024-4a76-91ae-8615b0b4bd9e)

**Comment by onim-at** [comment]
Hello @thisislawatts, I'd like to start working on this issue
