### ISSUE TITLE
[QuestionCreate] Publish or save as Draft

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2966]
It should be possible to save an item as either a Draft or published document.

**Comment by davehakkens** [comment]
Image as reference 
![publish](https://github.com/ONEARMY/community-platform/assets/13672737/1e044778-7588-4780-ab5d-9d55a92e9330)

**Comment by onim-at** [comment]
Hello, I have some questions about this issue
- Who should be able to view a draft document? Only the user that created it or also the admins?
- Which fields should the form validate in case of draft?
- Once published, can a question go back to being a draft?

**Comment by davehakkens** [comment]
hey thanks for working on this @onim-at!
Best would be to copy behaviour from the research module to align them.
