### ISSUE TITLE
[QuestionListing] Category filter

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2967]
It should be possible for someone to filter the Question listings for items which based on the available categories.

Look at the implementation for the how to listing for reference.

**Comment by davehakkens** [comment]
Image as reference 
![category](https://github.com/ONEARMY/community-platform/assets/13672737/ac13a786-c80d-4697-85f7-1928b57bea5d)

**Comment by zweertsk** [comment]
I'm not sure why there is a common `SortFilterHeader` component used in the `HowtoListing` that is circling back depending on a `CategoriesSelect` observable from Howto scope.

It looks like The `CategoriesSelect` observable should be abstracted as common functionality as well.

**Comment by thisislawatts** [comment]
Sounds good @zweertsk, it definitely seems like this area of the code would benefit from a refactor.

**Comment by zweertsk** [comment]
> Sounds good @zweertsk, it definitely seems like this area of the code would benefit from a refactor.

@thisislawatts I would like to start on the questions page but have questions my self 😅. Where can I have a discussion with the business about requirements?

**Comment by thisislawatts** [comment]
Happy to provide clarity if I can, either here or on the Issue which best relates to your questions. Alternatively come on over to the Discord

**Comment by thisislawatts** [comment]
Marking as complete
