### ISSUE TITLE
Feature: Q&A Module (overview)

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#2992]
### Description

We started the development work of the Questions and Answers module. The goal is to help people and store valuable long term answers for others to benifit from. Transitioning from Discord to the Platform

**This issue is to show the overview.** 
It's broken up into many small ones so its easier to contribute.
Here are the specific issues to work on (many are good first issues)
https://github.com/ONEARMY/community-platform/issues/2969
https://github.com/ONEARMY/community-platform/issues/2968
https://github.com/ONEARMY/community-platform/issues/2967
https://github.com/ONEARMY/community-platform/issues/2966
https://github.com/ONEARMY/community-platform/issues/2965
https://github.com/ONEARMY/community-platform/issues/2964
https://github.com/ONEARMY/community-platform/issues/2963
https://github.com/ONEARMY/community-platform/issues/2962
https://github.com/ONEARMY/community-platform/issues/2961
https://github.com/ONEARMY/community-platform/issues/2960
https://github.com/ONEARMY/community-platform/issues/2959
https://github.com/ONEARMY/community-platform/issues/2958
https://github.com/ONEARMY/community-platform/issues/2957

**Visuals**
![questions_overview](https://github.com/ONEARMY/community-platform/assets/13672737/cb94a0f2-7388-47f9-8bb4-88eb7fc259db)
![questions_single](https://github.com/ONEARMY/community-platform/assets/13672737/e05973ba-05c2-4cd0-98b4-6491f9ea5bd5)

![question start](https://github.com/ONEARMY/community-platform/assets/13672737/ddb0b5b6-cd0e-485a-8cd9-d6d618581cbe)

**Comment by thisislawatts** [comment]
Closing as this is covered by the Milestone feature within GitHub.
