### ISSUE TITLE
Map settings optimizations

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2999]
Currently the map component on the [user settings](https://community.preciousplastic.com/settings) is a little confusing for the end user. Greatest problem being that a user **_with_**  a map pin has no way of knowing they have one. 

The proposed redesign would have 3 states:
- Add map pin
<img width="431" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/14ecbabf-4794-4742-96b3-7465ee738243">

- Edit map pin (as is right now no changes needed)
<img width="639" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/1e49aaa0-659c-4c0b-bd19-52e8cd07f732">

- Your map pin
<img width="643" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/6e94c55c-e6e0-4495-b587-de73c1ccb6c5">

Here you can find the [figma file](https://www.figma.com/file/N1O9TzrKijPaZfYXqBboC8/Community-Platform?type=design&node-id=910%3A3371&mode=design&t=tMvrF1sfeBHnqEFu-1) for design reference
Here you can watch [a loom](https://www.loom.com/share/72dc8083d25044d1b1eb9c933c07010d) explaining the feature 

I hope I was able to explain myself somewhat decently. Let me know if you have any further questions or doubts. 

Cheers

**Comment by davehakkens** [comment]
@benfurber just tagging you here to make sure you've seen this when thinking of signup flow.

**Comment by thisismattia** [comment]
Thanks @oktomus replied there :)
