### ISSUE TITLE
Display impact data on profiles

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3001]
### Description

Write a quick descritpion of what is the component for, and as mainy details you consider useful to the person that will have to build it.

### Page related

Will be used in :

- Related page name (#issue-number)

### Mockup

[Add here the mockup of the component]

### Example(s)

If you have any examples of existing similar components, add the link here. It can be a link to a code snippet and/or to a page of a projet/website where we can interact with the similar component.

### Build suggestion

Here describe how you would build it, briefly but clearly. For example : the component MyComponent will take 2 props : `prop1`& `prop2`. It will extend the existing `Heading` component.

**Comment by benfurber** [comment]
Just putting this here so I have the id. @thisismattia would you mind adding some details please? This is just for the public display element of the work.

**Comment by benfurber** [comment]
@thisismattia Edge case not covered in the designs: User has provided impact data but doesn't want any visable.

**Comment by thisismattia** [comment]
Good point. Let me try make a design for it.

**Comment by thisismattia** [comment]
For context:

Here you can find the figma file with the designs https://www.figma.com/file/N1O9TzrKijPaZfYXqBboC8/Community-Platform?type=design&node-id=722-2&mode=design&t=AM2kToEG1w8Fn3gJ-0
While here is a loom explaining the core of it https://www.loom.com/share/47d2517cedfb4bec952f902d725afe7b

Let me know if more explanation is needed from my side
