### ISSUE TITLE
Feature: Use custom functions to send authentication emails

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3058]
**Is your feature request related to a problem? Please describe.**
While we have a lovely email templating system now ('functions/src/emailNotifications') when users sign-up or need to reset their password, they got a boring basic text email - the horror. This is because the authentication related messages use the default firebase flow.

This is important because we like the platform to be exciting and it's just a boring introduction to being a member to get that plain text message.

**Describe the solution you'd like**
Using a [cloud function](https://firebase.google.com/docs/auth/extend-with-functions), link up the authentication messages with our templating system.

**Comment by thisislawatts** [comment]
To configure your Firebase auth templates you can find them under:

- Open your project in the [Firebase console](https://console.firebase.google.com/).
- Go to the Email Templates page in the Auth section.


![Screenshot 2024-02-01 at 19 00 29](https://github.com/ONEARMY/community-platform/assets/472589/721e686e-9b15-4ba9-91b1-2c611ddae3ed)
