### ISSUE TITLE
[bug] Emoji not rendering in `Start Contributing` docs page

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/community-platform#3128]
**Describe the bug**
Multiple square blocks instead of the emoji

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [start contributing](https://docs.platform.onearmy.earth/Contributing/start-contributing)
2. Search for `🪛` in the page
3. See squares which can be found in four locations

**Expected behaviour**
Given the format assuming there should be an emoji in there

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/30328618/5ad6e0c7-81a7-4e5f-bcda-fcb0fe5c03cd)

**Additional context**
Will try to put in a pull request with something that's relevant

**Comment by iSCJT** [comment]
Thanks for picking up on this @darigovresearch, the screwdriver does look like a relatively recent addition from  2020.

Out of interest what operating system are you using?
