### ISSUE TITLE
[Suggestion] Create a hamburger menu component

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3206]
Currently we are using the react-hamburger-menu package for the mobile hamburger menu.

I think it would be better to have our own component and trim down the dependencies.

This would be a good first issue!

**Comment by thisislawatts** [comment]
Good idea @mariojsnunes. What do you think about using https://theme-ui.com/components/menu-button#menubutton as the base for this component?

**Comment by mariojsnunes** [comment]
Sure, reusing anything from our UI library of choice would be good.
