### ISSUE TITLE
[QuestionPage] Set max width to 1000px

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3220]
The current width of the [question page](https://dev.onearmy.world/questions/test-test-eko-test) is very wide making the content very stretched.
It should be set to max 1000px (same as[ research page](https://dev.onearmy.world/research/make-a-house-from-recycled-plastic))

**Example:**
<img width="1332" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/09ae8c4b-4250-4655-8a8b-c0e113196ac6">

**Comment by Gashmoh** [comment]
Hey, currently working on this and I think I managed to get it done. Could I get rights to create a branch, MR and everything ? Thanks :)

**Comment by benfurber** [comment]
@Gashmoh - I just got back to you on discord.
