### ISSUE TITLE
[bug] Hide slideshow arrows if only has one image

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3242]
**Describe the bug**
User profiles for groups have the ability to upload multiple header images.
This creates a slideshow. However it also shows the arrows if there is only one image uploaded which is confusing and seems like its broken

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a user profile with one header image (like [this one](https://community.preciousplastic.com/u/precious-plastic))
2. Click on header arrows
3. See nothing happening

**Expected behaviour**
Only show arrows when there are multiple images
If user uploaded only 1 image, hide arrows.

**Screenshots**
<img width="1066" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/95e84214-2402-46a1-b6a8-6a7e1182ad28">

**Comment by dariusmihut** [comment]
[@ONEARMY/maintainers](https://github.com/orgs/ONEARMY/teams/maintainers) i have started working on this issue
