### ISSUE TITLE
Feature: Add Breadcrumbs

### ISSUE THREAD

**Issue by SickSixtySeven** [ONEARMY/community-platform#3245]
Breadcrumbs design without icons.

All states included with example of what it should look like on page

![image](https://github.com/ONEARMY/community-platform/assets/158217111/e90f8168-5f70-437b-a65c-e3baaa95ba9c)

This will be on next pages:
- How-to
- Research
- Questions

Location of breadcrumb will be under navigation bar, and above content of the page, positioned on the left side of page.

Naming should work in next manner: Name of module > category > title of content (example: How-to > Moulds > Flowerpot Mould)

If the title of content is too long, category should be hidden like in next example 

![image](https://github.com/ONEARMY/community-platform/assets/158217111/83f47ecc-3385-4fee-bf95-3cfc9db0ccef)

All additional info is provided in figma file that is attached below

[Breadcrumbs.zip](https://github.com/ONEARMY/community-platform/files/14113332/Breadcrumbs.zip)

**Comment by davehakkens** [comment]
@goratt12 nice to meet you today. As mentioned here is the breadcrumbs issue. Would you be able to take it on?

**Comment by goratt12** [comment]
Hi! 
yes, I will be happy to take this issue.
