### ISSUE TITLE
[feature] Let users request a fresh account verification issue

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3249]
**Current problem**
Right now a bunch of users (for whatever reason) don't appear to receive the firebase email to verify their email address
/account. And poor Dave gets emails from them users eagerly wanting to verify their accounts. 

**Describe the solution you'd like**
While there's more things that need to be done (like probably not relying on the default firebase emailer), the first step is to let users request a fresh verification email.

On `SettingsPage`, add a component before `FocusSection` that displays if the store says that the user account isn't verified.

The component highlights the importance of having a verified account(!) and a button they can click which sends them a refresh one (using the existing store function to do this).  

I think it's best to put most of the component in `packages/components`.

Component and feature tests please!

More exact UX/UI tbc.

**Comment by dcustodio** [comment]
Happy to help with this one!

**Comment by benfurber** [comment]
Awesome, thank you @dcustodio!

**Comment by davehakkens** [comment]
Nice issue. Thanks for taking on @dcustodio 

We also use this banner on top. It's shown if people didnt complete their profile data (a step that comes after email verification)

<img width="1202" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/8b052dc6-0f66-4630-b63c-23db91de71f8">


Perhaps we can use the same banner:
1. If users didn't do email verification > Show banner that says:
**_"✉️ Click here to receive an email to confirm your account"_**
2. If users verified their email but didnt complete their profile > Show banner that says:
**_" 📝 Fill in your profile details before posting"_**

**Comment by dcustodio** [comment]
Hi @davehakkens thanks for the input! After the user clicks the banner and the email is successfully sent should we change the banner to something like this, or should we just hide it?
![image](https://github.com/ONEARMY/community-platform/assets/2907004/16fa7003-d18a-4242-95b1-37a63d9d801a)

**Comment by davehakkens** [comment]
> After the user clicks the banner and the email is successfully sent should we change the banner to something like this, or should we just hide it?

Looks nice. No strong preference on whats best here. Depends a bit on how it works /feels when moving forward
Since after seeing this banner you would propbaby get the other one "📝 Fill in your profile details before posting"

Maybe make a proposal/PR to what you think is best and we will test it out to see how it goes?

**Comment by dcustodio** [comment]
I've opened the PR #3258 to get the ball rolling 👍

**Comment by angelperezleon** [comment]
Happy to help with this issue too if require more hands on deck.
