### ISSUE TITLE
[feature request] Configure firebase authentication emails to use custom domain

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#3250]
**Is your feature request related to a problem? Please describe.**

Yes, the current Firebase Authentication email templates use a generic Firebase domain which can be confusing for users and doesn't match the branding of the application. This can lead to:

* Misfiled as spam: Users may not see the messages if they end up being incorrectly classified.
* Potential Security Concerns: Users might be less likely to recognize phishing attempts if emails don't originate from the expected domain.
* Reduced trust and engagement: Users might be hesitant to click on links in emails that appear to be from an unknown sender.
* Inconsistent brand experience: The email appearance doesn't align with the overall user experience of the application.

**Describe the solution you'd like**

I would like to see a feature that allows users to configure Firebase Authentication emails to use a custom domain. This would allow emails to be sent from the application's own domain, such as noreply@myapp.com, improving trust and brand consistency.

The ideal solution would include the following:
https://firebase.google.com/docs/auth/email-custom-domain

**Alternatives include:**

Using a third-party email service provider: This adds complexity and increases costs.

**Additional context**

This feature is crucial for applications that value brand consistency and user trust. It would improve the overall user experience and make Firebase Authentication more attractive for a wider range of applications.

**Comment by pizzaisdavid** [comment]
If I understood this ticket correctly, the goal is to send emails from custom email address.

It seems this ticket is already done, unless I misunderstood something.

Here are the emails I got from production:

Email confirmation:

![Capture](https://github.com/ONEARMY/community-platform/assets/4391884/71fdc007-79b0-4999-8639-0db43d4fb5bd)

Password reset:

![Capture_1](https://github.com/ONEARMY/community-platform/assets/4391884/6d43ec82-af2c-4c24-a911-0ecd6760aa59)


The emails came from `community@preciousplastic.com`, therefore already done, right?

Or is the problem that it is hard-coded as that email?
