### ISSUE TITLE
[bug] Impact fields not always listed in correct order

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3251]
**Describe the bug**
There is meant to be an assigned order to the impact fields displayed on [workspace profiles like this](https://community.preciousplastic.com/u/transmutation).

But if only some of the fields get added/updated at a later point in time the order goes wrong.

**Expected behaviour**
The order should be:
* Plastic
* Revenue
* Employees
* Volunteers
* Machines

**Solution**
Please update the necessary impact component(s) (probably `ImpactItem`) to enforce the correct order.

Please include a unit test to order this change. You can probably use `ImpactField.test.tsx` as a template.

**Comment by paposeco** [comment]
Hi. Can I help with this one? :)

**Comment by benfurber** [comment]
Hey @paposeco! Thanks for asking! It's yours! :)
