### ISSUE TITLE
[feature request] Get notification if someone replies to one of your comments

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#3259]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by benfurber** [comment]
First thought. I think it's best that the implementation for the `new_comment` notification stuff is parent content type agnostic so first I'll refactor `new_comment` so that it's the same implementation for how-tos and replies. 

Then I'll add comments as a possible parent to new_comment.

**Comment by benfurber** [comment]
Oh. For the refactor, a data migration would be needed for the how-to notifications as they don't currently receive `relevantTitle`

**Comment by benfurber** [comment]
Looks like comment notifications for how-tos was never implemented..?
