### ISSUE TITLE
Feat: Make the sign-up journey more exciting and on-brand

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3266]
I think it's worth making the sign-up journey more exciting and on-brand. A quick idea is something like this. Would love a more talented illustrator to have a go!

<img width="638" alt="Screenshot 2024-02-12 at 10 25 26" src="https://github.com/ONEARMY/community-platform/assets/16688508/27f7d2e4-f795-42a1-92ab-8f9f6679940c">

<img width="856" alt="Screenshot 2024-02-12 at 10 24 55" src="https://github.com/ONEARMY/community-platform/assets/16688508/a06047ac-8e27-4f98-a6d2-7f9b998fec6a">

_Originally posted by @benfurber in https://github.com/ONEARMY/community-platform/discussions/3236#discussioncomment-8439804_

**Comment by benfurber** [comment]
So what do you think @davehakkens - worth getting the illustrator to polish this up?

**Comment by benfurber** [comment]
Just realised you've responded on https://github.com/ONEARMY/community-platform/discussions/3236.

I'll start implementing a simple message version of this without the updated illustrations.

**Comment by ceconcarlsen** [comment]
@benfurber I can certainly work on this one. Can you keep us updated on your progress?

**Comment by benfurber** [comment]
@ceconcarlsen This is probably a little out of date now and should be closed. Any other issues take your fancy?

**Comment by ceconcarlsen** [comment]
@benfurber To be honest, anything front-end related

**Comment by benfurber** [comment]
@ceconcarlsen How's about #3786?

**Comment by benfurber** [comment]
(Reply on the ticket and I'll assign you.)
