### ISSUE TITLE
Tweak: Improve design/layout of the sign-up page

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3272]
There's a list of little improvements, that can be done as a single PR, we'd like to do to the sign-up page.

Currently:
<img width="381" alt="Screenshot 2024-02-12 at 17 15 30" src="https://github.com/ONEARMY/community-platform/assets/16688508/06e2e60b-d9c2-4070-8c26-403104b348d3">

Broad end state:
<img width="381" alt="Screenshot 2024-02-12 at 17 15 52" src="https://github.com/ONEARMY/community-platform/assets/16688508/34671299-7120-4d97-8d75-28374ea825da">

**Changes to make:**
- [ ] Move 'already have an account' to the top, the link colour is the community brand colour and underlined
- [ ] Each label can have a comment, which is smaller and slightly lighter than the main label
- [ ] (Not pictured) Move errors to the top
- [ ] Consistent placeholders (both examples)

**Comment by devChary** [comment]
Hey Ben. I'm interested in contributing to this first issue on the platform. I've forked the project and created a branch to make some changes.

Quick couple of questions
-  Is this the right place to ask questions or should I be asking them somewhere else?
- I need to change the eye icon. Do you guys have a svg-icon list or can I add one?

**Comment by benfurber** [comment]
That's great, thanks @devChary - it's yours! :)

Yes, ask questions here. Don't change the eye icon please.

**Comment by devChary** [comment]
Alright! Got it. Thanks!

What does the 3rd point exactly mean? Do I move the error code to the top?

**Comment by devChary** [comment]
Hey Ben. I've raised a PR. Do let me know if it's missing something.
