### ISSUE TITLE
[feature request] Impact - change currency from "$" to "USD" 

### ISSUE THREAD

**Issue by m-azoubel** [ONEARMY/community-platform#3289]
**Is your feature request related to a problem? Please describe.**
As many countries use "dollar" as a currency, there has been some confusion about which dollar are we talking about in the impact feature.

**Describe the solution you'd like**
Change from "$" to "USD"

**Additional context**
<img width="577" alt="image" src="https://github.com/ONEARMY/community-platform/assets/90778074/7b5a7573-d0ff-410e-a1cf-b23e20f0a06b">

**Comment by lucaasrojas** [comment]
Hi @m-azoubel I think this issue can be closed. The PR #3674 was merged to fix this issue.
