### ISSUE TITLE
[bug] Impact - negative numbers allowed

### ISSUE THREAD

**Issue by m-azoubel** [ONEARMY/community-platform#3291]
**Describe the bug**
On the impact feature, users are able to add negative numbers

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Settings'
2. Scroll down to 'Positive impact 🤙'
3. Click on 'Expand and edit'
4. Click on 'Edit data'
5. Add negative numbers
6. See error

**Expected behaviour**
Only numbers above 0 should be considered. If a negative number is written, some behaviours could be considered:
1. Show error message to remove the "-" sign before saving
2. Automatically delete the "-" sign when saving

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/90778074/8a1228cf-c865-45da-b84e-519781df6d21)

**Comment by manacespereira** [comment]
I can fix it real quick...
