### ISSUE TITLE
Deal with all the jest console warnings

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3303]
There's loads of console warnings/errors that make reading through the test suite annoying and difficult to find real test errors, especially on CI.

This error is common:
```
Warning: An update to observerComponent inside a test was not wrapped in act(...).
```
These errors should be dealt with as advised by the message.

Another log that's typical is a console log we're choosing to call, in which case the tests should be calling expectations, etc. in a block so that the actual log isn't visible when running the tests.

**Comment by kimskovhusandersen** [comment]
I can grab this ticket [@ONEARMY/maintainers](https://github.com/orgs/ONEARMY/teams/maintainers).
