### ISSUE TITLE
Move mentions and totalCommentCount responsibility out of research

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3324]
**Is your feature request related to a problem? Please describe.**
We're making progress with #3296 in seperating out the responsibilities for comments/discussion to the new Discussion store. But mentions and totalCommentCount remain.

**Describe the solution you'd like**
1. Update Discussions for mentions (#3318)
2. Workout a new approach for totalCommentCount (it's more complex as each Research Item has a seperate Discussion).
3. More responsibility from Research to Discussion.

**Additional context**
This will also involve some data migration work.

**Comment by benfurber** [comment]
1. Due to the filtering/index work, totalCommentCount does need to stay on research. 
2. I think mentions might be better to move to a cloud function called when a comment is created/updated. There's no reason it should block the application.

So closing this for now.

**Comment by benfurber** [comment]
Due to the filtering/index work, totalCommentCount does need to stay on research.
    I think mentions might be better to move to a cloud function called when a comment is created/updated. There's no reason it should block the application.

So closing this for now.

**Comment by mariojsnunes** [comment]
Note that AFAIK totalCommentCount is not working well for research, it's not counting comments on updates. Maybe it shouldn't... but if it should, the solution isn't trivial to me.
