### ISSUE TITLE
[bug] Add spaces to notification urls 

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3330]
**Describe the bug**

Notification text doesnt have space between the links

<img width="328" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/119340c4-0e81-4792-ab25-54b23ee6873f">

**To Reproduce**
Try to get your research content marked as useful

**Comment by phlapjack** [comment]
Hi @davehakkens  and @benfurber , I see this hasn't been worked on in some time - would it be useful for me to finish it up ?

**Comment by davehakkens** [comment]
yes!
