### ISSUE TITLE
Feat: Replace display of tags by categories

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3337]
### Description

We want to replace the tags by categories on how-to's and research.
- Categories functionality is better intergrated in filters
- Categories will be used more with breadcrumbs coming https://github.com/ONEARMY/community-platform/pull/3333
- Safer for displaying without breaking design since you can only select one category but multiple tags

### Page related

Will be used in :
[Research overview](https://dev.onearmy.world/research)
[How-to Overview](https://dev.onearmy.world/how-to)
### Mockup
![how-tos](https://github.com/ONEARMY/community-platform/assets/13672737/e1935255-371a-4cf5-8990-7d71b68c015c)
![research](https://github.com/ONEARMY/community-platform/assets/13672737/3ec417af-a14e-4b90-a6ed-7f8c24fe52f5)

**Comment by saile515** [comment]
I will try to implement this.
