### ISSUE TITLE
[bug] ActiveUser randomly cleared on Questions page

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3362]
**Describe the bug**
For some reason, when you're on one of your own Question pages and refresh the page, the activeUser is cleared and so the edit button disappears.

**To Reproduce**
Steps to reproduce the behaviour:

1. Make question.
2. View it (see the edit button).
3. Refresh the page (see the edit button has gone).
4. Go to any other page.
5. Click forward to the question page (see the edit button is back).

This doesn't seem to happen on any other content types (e.g. How tos).

**Comment by mariojsnunes** [comment]
Is this happening locally? I can't seem to replicate... maybe there is some race condition and the distance from the server could impact it.
