### ISSUE TITLE
[dev] Increase code line width to 140

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3379]
**Is your feature request related to a problem? Please describe.**
Currently the code line width is 80, which is too short IMO.

**Describe the solution you'd like**
Increase it to 140

**Additional context**
It should improve readability **in most cases**,
I've tested locally on some files and saw ~30% code line reduction.

**Comment by thisislawatts** [comment]
@mariojsnunes could you include a specific example of where you feel the readability is improved with the increased line width?

**Comment by mariojsnunes** [comment]
Sure, two examples here:
typescript
![image](https://github.com/ONEARMY/community-platform/assets/8073622/c6fa8d22-8799-4e1a-a041-49b817e65a9b)
vs
![image](https://github.com/ONEARMY/community-platform/assets/8073622/3290c78d-efe0-4ac9-bf1e-481080ddebbb)

html
![image](https://github.com/ONEARMY/community-platform/assets/8073622/ca6e9050-42e8-4de0-9c76-61a73bd64d50)
vs
![image](https://github.com/ONEARMY/community-platform/assets/8073622/409fd48a-a09f-4106-ae57-31e46a71f6ff)

you can do the .prettierrc change locally and just save any file to check.

**Comment by thisislawatts** [comment]
For me the shorter line lengths are preferable and easier to read, but I accept that is down to what you are used to. See attached for example, I tend to work with a split editor with tests + code running next to each other

![Screenshot 2024-04-05 at 22 06 10](https://github.com/ONEARMY/community-platform/assets/472589/94cf0bc3-11ae-4ce5-875b-81d62fcc2841)


I'm not going to block this change being made, but neither will I approve it right now. I would prefer to see a few more regular contributors asking for this formatting adjustment.

**Comment by mariojsnunes** [comment]
> I'm not going to block this change being made, but neither will I approve it right now. I would prefer to see a few more regular contributors asking for this formatting adjustment.

I understand, and agree with that.

**Comment by benfurber** [comment]
When I think about your two examples @mariojsnunes, the ternaries on multiple lines always annoys me and seems like an anti-pattern but I much perfer having individual props on individual lines.

Not sure if I agree with the proposed change or just don't really care...

I _probably_ find the shortly lines easier to read...
