### ISSUE TITLE
[bug] Unable to edit or delete comments

### ISSUE THREAD

**Issue by Robert-LC** [ONEARMY/community-platform#3385]
**Describe the bug**
Edit and delete comment does not function properly. The buttons are there, they prompt properly on click, but do not execute on what their job is once given the go ahead.

If you refresh the page it shows the proper changes, but still gives console errors when doing the actions.

**To Reproduce**
Steps to reproduce the behaviour:

1. Comment one anything
2. Try to edit or delete the comment you just made
3. See that the update didn't happen and you get console errors.
4. But if you refresh it does happen.

**Expected behaviour**
The comment is suppose to delete or be edited.

**Screenshots**
Edit does not work
![Edit bug](https://github.com/ONEARMY/community-platform/assets/72999492/54080fe3-6dc5-435f-a4c1-cfe2736cc4dc)

delete does not work
![delete bug](https://github.com/ONEARMY/community-platform/assets/72999492/afca6f22-9ef7-49a2-aab3-6ea2ad9bc06d)

**Additional context**

The comment component seems to be bugged. It won't let me delete or edit my comments, despite the buttons for them appearing.

When I open a comment to edit, and hit save I get this in console
```
�[37m2024-03-27 12:59:44.136�[39m�[0m�[0m	�[34m�[1mINFO�[22m�[39m�[0m�[0m	�[37m�[39m�[0m�[0m�[1m�[37m�[39m�[22m�[0m�[0m	{
  _id: �[32m'4Sht8EDWtUjXmkcOsqnY'�[39m,
  comment: �[32m'hello edit'�[39m 
} question comment edited
```

When I click confirm delete on my comment, I get this in my console.
```
�[37m2024-03-27 13:04:52.742�[39m�[0m�[0m	�[31m�[1mERROR�[22m�[39m�[0m�[0m	�[37m�[39m�[0m�[0m�[1m�[37m�[39m�[22m�[0m�[0m	Comment can not be deleted by user {
  user: 
   {
     collectedPlasticTypes: �[1mnull�[22m,
     country: �[1mnull�[22m,
     isV4Member: �[1mnull�[22m,
     machineBuilderXp: �[1mnull�[22m,
     profileType: �[32m'member'�[39m,
     _modified: �[32m'2024-03-26T03:52:22.434Z'�[39m,
     _created: �[32m'2024-03-15T03:37:24.142Z'�[39m,
     _deleted: �[33mfalse�[39m,
     notification_settings: 
      {
        emailFrequency: �[32m'weekly'�[39m 
      },
     coverImages: 
      [
        �[36m[Object]�[39m 
      ],
     mapPinDescription: �[1mnull�[22m,
     userName: �[32m'localhosttest2'�[39m,
     isContactableByPublic: �[33mtrue�[39m,
     notifications: 
      [
        �[36m[Object]�[39m,
        �[36m[Object]�[39m,
        �[36m[Object]�[39m,
        �[36m[Object]�[39m 
      ],
     location: �[1mnull�[22m,
     _id: �[32m'localhosttest2'�[39m,
     profileCreationTrigger: �[32m'registration'�[39m,
     about: �[32m'tewatattttttttttad'�[39m,
     profileCreated: �[32m'2024-03-15T03:37:24.142Z'�[39m,
     _lastActive: �[32m'2024-03-26T03:52:22.434Z'�[39m,
     isExpert: �[1mnull�[22m,
     moderation: �[32m'awaiting-moderation'�[39m,
     links: 
      [
        �[36m[Object]�[39m 
      ],
     openingHours: 
      [
        {
        
        } 
      ],
     displayName: �[32m'localhosttest2'�[39m,
     _authID: �[32m'v9KCslAo7RX9wdishEZDRb8r1o83'�[39m,
     verified: �[33mfalse�[39m 
   } 
```

**Comment by benfurber** [comment]
Hey @Robert-LC. Can you please provide details of the context please.

**Comment by Robert-LC** [comment]
Just noticed this in the tests...
![image](https://github.com/ONEARMY/community-platform/assets/72999492/c5e9cc54-7434-43f5-9cd7-257ae571e3fe)

Test can see comment not editable as an error, but it doesn't fail the test

**Comment by benfurber** [comment]
Fixed for replies (nested comment) on questions but it looks like for research for comments (initial comment) on research it's still an issue.

https://github.com/ONEARMY/community-platform/assets/16688508/481b4912-16c4-45a5-b77c-5838ceca22ef

**Comment by benfurber** [comment]
My hunch is the flow is different when you start a discussion as it's a different store action.
