### ISSUE TITLE
[bug] You can edit the comments of people on your research

### ISSUE THREAD

**Issue by Robert-LC** [ONEARMY/community-platform#3386]
**Describe the bug**
You can edit the comments people put on the research you post.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a research, or open a research you already made,
2. Look at comment from someone else
3.  See that you can EDIT and DELETE It

**Expected behaviour**
You should only be able to delete a comment on your research.

**Screenshots**
I am logged in as localhosttest2, but can edit davetest1's comment
![image](https://github.com/ONEARMY/community-platform/assets/72999492/bfcb9652-1f93-4811-b714-9becd92e9398)

![image](https://github.com/ONEARMY/community-platform/assets/72999492/567b7ed8-0e44-497b-a7cf-0b9d9771d59a)

**Additional context**
I believe Delete should be the only allowed feature, because editing allows user's to speak for another under their name which is dangerous.

Editing for comments is currently broken in general, reported in another issue, but when that gets fixed this will be a problem as well.

**Comment by phlapjack** [comment]
Hi @Robert-LC  is there more information on how to reproduce this? I'm trying on my local build (latest code from master) and it looks like I can only edit comments that I created.
![Uploading edit_comments.png…]()

**Comment by Robert-LC** [comment]
@phlapjack you have to create a research, and then if someone comments on your research you can edit the comment.
But something occurred to me when answering this, to make a research, at least on local, you have to put yourself as an admin, so I'm wondering if the reason I was able to edit's peoples comments was because I was an admin and didn't realize. I'd test now, but all the researches made by other people got deleted.

@benfurber might know if admins can edit peoples comments, or if they can only delete them. If that's the case this issue can be closed.

**Comment by benfurber** [comment]
@Robert-LC @phlapjack Apologies for not reviewing this sooner. Yes I think the behaviour is due to the admin role. A nice to have would be a little visual wrapper for admin actions, but I can't imagine that becoming a real priority to develop.
