### ISSUE TITLE
Questions: Page title should update with question title

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3409]
At the moment, the title of the page doesn't change when viewing an individual question.

Please add this. 

Nice easy thing to cover in the 'Individual questions' cypress feature test for question/read too.

**Comment by amitdave222** [comment]
Hey, I would be very happy to work on this issue. Does the "tab" title / "window" title need to change to match the question?
<img width="1016" alt="image" src="https://github.com/ONEARMY/community-platform/assets/165437009/dfb83ef0-2c2d-45fa-9e3d-52bf9e131807">

**Comment by benfurber** [comment]
Thanks great, thank you @ADTmux - it's yours!

Yes, I hope using a function in `react-router-dom` will sort you out.

**Comment by benfurber** [comment]
Hey @ADTmux! 👋  Any luck on this yet?
