### ISSUE TITLE
[bug] No warning when editing a comment to an empty comment

### ISSUE THREAD

**Issue by sorikang0806** [ONEARMY/community-platform#3411]
**Describe the bug**
There is no warning or error message that notifies the user that an edited comment cannot be empty.

**To Reproduce**
Steps to reproduce the behaviour:

1. Write a comment eg. on one of the research threads
2. Click on Edit comment
3. Remove all the characters and make an empty comment then save
4. It doesn't change the original comment

**Expected behaviour**
When the save button is clicked, display a warning message that a comment cannot be empty

**Screenshots**
<img width="680" alt="Screenshot 2024-04-02 at 11 44 59 PM" src="https://github.com/ONEARMY/community-platform/assets/74334981/3e8a7ef6-0ba6-4946-9214-7eb0ab9bfdb8">
<img width="659" alt="Screenshot 2024-04-02 at 11 45 07 PM" src="https://github.com/ONEARMY/community-platform/assets/74334981/a37c24fc-96d3-4f99-9ddf-c775021f3e6e">
<img width="715" alt="Screenshot 2024-04-02 at 11 45 23 PM" src="https://github.com/ONEARMY/community-platform/assets/74334981/06d08983-1c17-434f-9c47-e2f223811d38">

**Additional context**
I am a newbie here and want to try fixing this bug myself first if that is okay!

**Comment by benfurber** [comment]
Thanks @sorikang0806, a really good spot!

Looks like the EditComment component and the CreateComment component should share more code so that the behaviour is consistent.

**Comment by V24039** [comment]
Hi, I would like to work on this. After looking through the code I have made some obs

- For CreateComment the button is disabled if the comment length is 0 i.e. no input is given. As the button is disabled I feel that an error message is not required.
- For EditComment the store procedure function editComment is trimming the comment and checking it hence the original comment is not changed. It will require a validation at EditComment to show an error message to the user.

**Comment by benfurber** [comment]
Thanks for your notes @V24039. I agree there's a challenge with how CreateComment is basically implemented completely differently to EditComment.

I see @npaddle has jumped on this too! :) Will add some feedback there too.
