### ISSUE TITLE
[bug] password validation error message contains some technical terms

### ISSUE THREAD

**Issue by EdwardAndress** [ONEARMY/community-platform#3412]
**Describe the bug**
If you try to sign up with a password that is too short, the error message is `Firebase: Password should be at least 6 characters (auth/weak-password).`. A lot of users won't know what Firebase is so it's just screen clutter. `auth/weak-password` is more self-explanatory but `Password should be at least 6 characters` is probably sufficient.

**To Reproduce**

1. Go to the sign up page
2. Try to sign up using a password that is too short (fewer than 6 chars)
3. See error message `Firebase: Password should be at least 6 characters (auth/weak-password).`

**Expected behaviour**
The error message doesn't contain any technical terms.

**Screenshots**
<img width="633" alt="an image showing the error message generated when signing up with a password that is too short" src="https://github.com/ONEARMY/community-platform/assets/7963978/21e5d42d-18f9-4555-8894-45f6fe2d130d">

**Additional context**
Nope.

**Comment by EdwardAndress** [comment]
Actually, would it be sufficient just to show "Too short" under the password field when it is too short? This already happens when the username is too short (and it's super simple to achieve).

<img width="583" alt="Screenshot 2024-04-03 at 10 38 14" src="https://github.com/ONEARMY/community-platform/assets/7963978/8514abec-ca12-4e30-8d33-9d3ca7df235b">

**Comment by EdwardAndress** [comment]
I'll take this on later this (UK) evening unless someone wants to keep the original error message :)

**Comment by benfurber** [comment]
That's great @EdwardAndress! Thanks for picking this up!

**Comment by EdwardAndress** [comment]
@benfurber - testing this proved tricky and I've found the problem but am retiring for the day... so no PR yet! 😴

**Comment by benfurber** [comment]
@EdwardAndress This might be worth a look/related: https://github.com/ONEARMY/community-platform/pull/3417

Of course I haven't seen your testing approach yet but I imagine that's also the test file that you'll need to update.

**Comment by EdwardAndress** [comment]
Thanks @benfurber! Yes, it's that file which needs updating. The problem I'm encountering relates to how the user inputs are validated using Yup (and how that imacts on the way validation failure is displayed in the cypress tests). I'm not able to do anything on this tonight but will have a go tomorrow.

**Comment by benfurber** [comment]
Closed in 386de2af1ae8c194eb34ba9add6725c54bc56ad4
