### ISSUE TITLE
[bug] How-to page does not load

### ISSUE THREAD

**Issue by m-azoubel** [ONEARMY/community-platform#3419]
**Describe the bug**
How-to page does not load on Chrome Version 123.0.6312.59 (Official Build) (64-bit) , nor in incognito.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to (https://community.preciousplastic.com/how-to)
2. See error

**Expected behaviour**
How-to page opened.

**Screenshots**
![Captura de tela 2024-04-04 142506](https://github.com/ONEARMY/community-platform/assets/90778074/0b4d868e-956f-4079-acf5-0990913496a2)

**Comment by Robert-LC** [comment]
This might be fixed, or specific to your machine, because I clicked the link and it loaded up.
Was this on your local environment or live site?

![image](https://github.com/ONEARMY/community-platform/assets/72999492/5eb8cc90-a91c-477e-b3be-6a571986c400)

**Comment by benfurber** [comment]
@m-azoubel This was an admin bug due to a weird untitled doc in the db. Can close this.
