### ISSUE TITLE
[bug] Same profile has different flags

### ISSUE THREAD

**Issue by m-azoubel** [ONEARMY/community-platform#3420]
**Describe the bug**
When filtering the How-to author to Precious Plastic, it shows some How-to's with the author's flag being Portugal and some with a grayscale flag.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://community.preciousplastic.com/how-to
2. Filter by author "precious-plastic"
3. See error

**Expected behaviour**
Same flag for all How-to's

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/90778074/00065624-86bb-46b7-934d-94fd2f567603)

**Comment by benfurber** [comment]
@m-azoubel I think I'm going to close this issue as I've thought about it a bit more and it's working as expected.

The author details are set on the how-to on save and as there was an issue with the precious-plastic account data at the time (the seperate wipe issue), the user account didn't have the location set as expected. 

Now the data issue with the pp user account has now been fixed, if you update any how-to now the updated author details (with location) will be set correctly.

**Comment by benfurber** [comment]
@m-azoubel I think I'm going to close this issue as I've thought about it a bit more and it's working as expected.

The author details are set on the how-to on save and as there was an issue with the precious-plastic account data at the time (the seperate wipe issue), the user account didn't have the location set as expected.

Now the data issue with the pp user account has now been fixed, if you update any how-to now the updated author details (with location) will be set correctly.
