### ISSUE TITLE
Quick SEO wins

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3424]
There's a few quick wins we can do from a search and social prospective.

1. Use heading tags correctly.
2. Ensure all images have alt tags.
3. Set more/better open graph tags.

### Heading tags
The research, how-to and question titles should definitely be h1s rather than h2s. There might also be more semantic heading considerations.

### Image alt tags
At the moment we don't ask users to provide alt tags for the images that upload. As a short-term fix, we should apply alt tags to research updates, how-to steps and questions which follow some kind of dynamtic structure, e.g. '<research update title> - <image index>'

### Better open graph tags
At a minimum we need 'og:type' set to website in the `postCraBuild.ts` script, but there's probably [more improvements we should make](https://docs.prerender.io/docs/open-graph)

**Comment by benfurber** [comment]
@codisart Good point. Let's not worry about the maps for the moment I think...

**Comment by benfurber** [comment]
Wrong auto action. There's still some to do right, @codisart?

**Comment by codisart** [comment]
Yep at least Howto.

**Comment by benfurber** [comment]
@codisart Questions all good?

**Comment by codisart** [comment]
There is many headings in user and user settings. I have begun working on it.

**Comment by benfurber** [comment]
Also, @codisart - are you on our discord? I wish to send you more praise.
