### ISSUE TITLE
trouble with my own instance

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3479]
Hello,

I am interested in creating my own instance of the community-platform, follow along as I go through the steps of figuring everything out.

Below are some pretty specific steps I did (If I am stuck somewhere, it is noted in the most recent comment.)

Steps:
1. Go to https://console.firebase.google.com/u/0/

2. Create a new project
    -> give it a name and id
    -> disable Google Analytics
Note: my id is `food-better-production`

3. Wait for the project to be ready.

4. Change the billing plan from Spark (free) to Blaze (pay-as-you-go), this is needed because we need access to cloud functions, which are unlocked at Blaze tier.
Note: it is possible to get a big bill for services, so precede with caution.

5. Clone the repo locally
```
cd ./Documents
git clone git@github.com:ONEARMY/community-platform.git
```

6. Follow the getting started instructions. [link](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--getting-started)
```
cd ./community-platform
nvm use 20.12.2
yarn
```

7. Modify the `.firebaserc` file to:
```
{
  "projects": {
    "default": "food-better-production"
  },
  "targets": {}
}
```

8. Try to deploy:
```
npm install -g firebase-tools
firebase deploy
```
Note: you may be asked to authenticate.

9. Get an error:
```
ERROR in unable to locate '/home/david/Documents/community-platform/build/index.html' glob
```
To fix: this error seems to happen because we need to build something, this can be fixed with `yarn build`

During the building, there were some errors, but also a success message, good enough for me.

10. Try to deploy.

11. Get another error:
```
Firebase Storage has not been set up on project 'food-better-production'.
Go to https://console.firebase.google.com/project/food-better-production/storage
and click 'Get Started' to set up Firebase Storage.
```
To fix: click the link, pick "production" and then eur3-west.

12. Try to deploy.

13. Get an error:
```
Errors while reading 'extensions' in 'firebase.json'
- No params file found for firestore-send-email
```

To fix: open `extensions/README.md` and follow the instructions.

After some googling, I ended up with a file like this:
```
DEFAULT_FROM=whatever@food-better.com
MAIL_COLLECTION=emails
SMTP_CONNECTION_URI=mail.smtp2go.com
TTL_EXPIRE_TYPE=never
TTL_EXPIRE_VALUE=1
```
The `SMTP_CONNECTION_URI` probably needs a username and password to really work, but for now I don't care.

14. Try to deploy. If asked, type `y` and press enter to agree to terms of service.

15. Get an error:
```
HTTP Error: 403, Cloud Firestore API has not been used in project food-better-production before or it is disabled.
Enable it by visiting https://console.developers.google.com/apis/api/firestore.googleapis.com/overview?project=food-better-production then retry.
If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

To fix: go to that link and press the enable button. And wait 5 minutes.

16. Try to deploy.

17. Get an error:
```
HTTP Error: 400, ANY_API ApiScope is not supported for Datastore Mode databases.
```
To fix: Go to https://console.firebase.google.com/u/0/project/food-better-production/firestore, click the button to be redirected, click some buttons, and switch to native mode.

18. Try to deploy.

19. Get an error:
```
HTTP Error: 409,
<eye3 title='/FirestoreMetadata.BootstrapDatabase, ABORTED'/> APPLICATION_ERROR;
cloud_datastore.metadata/FirestoreMetadata.BootstrapDatabase;
<eye3 title='/FirestoreMetadataWrite.BootstrapDatabase, ABORTED'/> APPLICATION_ERROR;
cloud_datastore.metadata/FirestoreMetadataWrite.BootstrapDatabase;
Can not write to database. Please retry after 210.754465 seconds.;
AppErrorCode=10;
StartTimeMs=1714060508016;
unknown;
ResFormat=uncompressed;
ServerTimeSec=0.026902425;
LogBytes=256;
Non-FailFast;
EffSecLevel=none;
ReqFormat=uncompressed;
ReqID=26205c979f6c2e5;
GlobalID=0;
Server=[2002:a05:6028:224b:b0:371:253a:2511]:4001;
AppErrorCode=10;
StartTimeMs=1714060507991;
unknown;
Deadline(sec)=30.0;
ResFormat=uncompressed;
ServerTimeSec=0.052764657;
LogBytes=256;
Non-FailFast;
EffSecLevel=none;
ReqFormat=uncompressed;
ReqID=8e793ff7c6db1834;
GlobalID=0;
Server=[2002:a85:3347:0:b0:2fe:e80c:c3d3]:4001;
```

To fix: as indicated in the error message, wait 210.76 seconds.

20. Try to deploy.

21. Get an error:
```
- create firestore-send-email
Request had 1 validation errors: `params.SMTP_CONNECTION_URI`: Invalid SMTP connection URI.
Must be in the form `smtp(s)://username:password@hostname:port` or `smtp(s)://username@hostname:port`
```
Okay, so the URI does matter. Create an account at brevo.com, then go to https://app.brevo.com/settings/keys/smtp

Mine became: `smtp://my_email@gmail.com:my_password@smtp-relay.brevo.com:587`

In retrospect, it may have been enough to add `smtp://`

22. Try to deploy.

23. It works (kinda!) 

24. Going to the signup page (https://food-better-production.web.app/sign-up):

```
@firebase/firestore: Firestore (10.6.0): Uncaught Error in snapshot listener: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.
```

![Screenshot from 2024-04-25 19-25-50](https://github.com/ONEARMY/community-platform/assets/4391884/f53ac356-2511-4501-a7a1-5fd59ec1514c)

Also, filling out the form, and pressing submit results in:
```
TypeError: e.t0.inner is undefined
    e SignUp.tsx:107
    Babel 9
    validate SignUp.tsx:115
    x final-form.es.js:561
    R final-form.es.js:652
    change final-form.es.js:943
    change final-form.es.js:1064
    onChange react-final-form.es.js:592
    onChange FieldInput.js:33
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    i helpers.ts:99
```

I found some results on Google, but I am not familiar with authentication for firebase and such. It seems to be that some database rules might need to be added. https://stackoverflow.com/questions/46590155/firestore-permission-denied-missing-or-insufficient-permissions

**Comment by pizzaisdavid** [comment]
25. I have found some database rules in the repository (https://github.com/ONEARMY/community-platform/blob/master/firestore.rules) and pasted them into the database rules (https://console.firebase.google.com/u/0/project/food-better-production/firestore/databases/-default-/rules) still the same errors.

26. I have noticed some network requests contain the project id "precious-plastics-v4-dev"
![Screenshot from 2024-04-26 10-41-37](https://github.com/ONEARMY/community-platform/assets/4391884/3e279450-b34e-47ff-9f58-2bcc58b97876)

Which let me to `src/config/config.ts`

Which also let me to finding `packages/documentation/docs/Install.md`, whoop! documentation!

27. based on https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env I tried to make a `.env` file but couldn't get it working. So I modified some code directly.

```
const getSiteVariant = (): siteVariants => {
  return 'production' as siteVariants
}

...

const _c = (property: ConfigurationOption, fallbackValue?: string): string => {
  if (property === 'REACT_APP_FIREBASE_API_KEY') {
    return 'abc123'
  }
  if (property === 'REACT_APP_FIREBASE_AUTH_DOMAIN') {
    return 'food-better-production.firebaseapp.com'
  }
  if (property === 'REACT_APP_FIREBASE_DATABASE_URL') {
    return 'https://food-better-production.firebaseio.com'
  }
  if (property === 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID') {
    return '123'
  }
  if (property === 'REACT_APP_FIREBASE_PROJECT_ID') {
    return 'food-better-production'
  }
  if (property === 'REACT_APP_FIREBASE_STORAGE_BUCKET') {
    return 'food-better-production.appspot.com'
  }


  if (property === 'REACT_APP_SUPPORTED_MODULES') {
    return 'howto,map,research,academy,user,question'
  }
 ...
```

Now I was able to create an account, get an email, confirm my account, finish my profile, create a howto. Whoop!

28. Uploaded images are broken; I didn't figure it out yet, but I didn't really try yet either.

From the documentation:
> Configure `cors.json` on the storage bucket](https://cloud.google.com/storage/docs/configuring-cors) to support your deployed origin. See: functions/src/config/cors.md

**Comment by pizzaisdavid** [comment]
My profile image does work (https://food-better-production.web.app/u/pizzaisdavid) so it is probably not related to images generally. I see that it says "Awaiting moderation" maybe the howto must be first approved, maybe only after that the image will appear.

29. Add myself as admin. it seems I need to modify my user entry to have a property called "userRoles" with an array containing the string `super-admin`.

30. There doesn't seem to be a UI for approving howtos, so I assume I just modify the database directly.

`awaiting-moderation` --> `accepted`

That didn't fix it. Seems that I should just configure the CORS.

![Screenshot from 2024-04-26 13-01-35](https://github.com/ONEARMY/community-platform/assets/4391884/5bd3fc05-15bd-454b-9878-977c5353fc56)

**Comment by pizzaisdavid** [comment]
31. Find more documentation: https://github.com/ONEARMY/community-platform/blob/master/functions/src/config/cors.md

32. Install gcloud, whatever that is: https://cloud.google.com/sdk/docs/install

For me, it was:
```
curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-473.0.0-linux-x86_64.tar.gz
tar -xf google-cloud-cli-473.0.0-linux-x86_64.tar.gz
```
(and then following the instructions on the page.)

33. Run `gcloud init` from the docs (browser tab opened up, signed in with the same account I've been using.)
```
You are logged in as: [davidispizza@gmail.com].

Pick cloud project to use: 
...
 [5] food-better-production
...
 [10] Enter a project ID
 [11] Create a new project
Please enter numeric choice or text value (must exactly match list item):  5

Your current project has been set to: [food-better-production].
Do you want to configure a default Compute Region and Zone? (Y/n)?  n
```

34. gsutil cors set ./functions/src/config/cors.json gs://food-better-production.appspot.com
(The relative path in the documentation is slightly out-of-date.)

35. Now there are images, that is cool!
![Screenshot from 2024-04-26 15-22-04](https://github.com/ONEARMY/community-platform/assets/4391884/0751a7ce-80a1-45c5-b5c3-59cbddfd0584)

36. I want to be able to add a research module entry, but there is no button, from looking at the URL patterns, I have guessed it should be: https://food-better-production.web.app/research/create

37. Get error message, need admin role, no problem!
From the firebase user interface, add "admin" to the list on my user.

38. Make a temp research entry --> https://food-better-production.web.app/research/comparing-store-bought-and-homemade-hummus Whoo-who!

39. The research as entry has some placeholder image and no ability to replace via the user interface. I assume the current thing to do is: upload image via firebase user interface, get the URL, and then replace that in the database.

Update: actually, no. The thumbnail is automatically the first image found in an "update" of the module.

40. Custom domain.

https://console.firebase.google.com/project/food-better-production/hosting/sites/food-better-production

community.food-better.com should now work, but it has an unsecure connection, but I think firebase takes care of this itself.

41. Style steps.

41a. Remove academy and map for now.

41b. "Inspire the Precious Plastic world." -> "Inspire the world."
Well, it looks like this opens up some interesting stuff. `packages/themes/dist/precious-plastic/styles.js`

**Comment by pizzaisdavid** [comment]
41c. Replaced the contents of `packages/themes/assets/images/precious-plastic-logo-official.svg` with some basic logo.

41d. Change some stuff of `packages/themes/dist/precious-plastic/styles.js`

41e. Change favicon `src/assets/images/themes/precious-plastic/public/favicon.ico`

41f. Change the text at the bottom, as I am not sure it would be a One Army project.

**Comment by pizzaisdavid** [comment]
42. Going to https://community.food-better.com redirects to https://community.food-better.com/academy which is unavailable.

**Comment by benfurber** [comment]
@pizzaisdavid This is so cool! Thank you for going through the process and documenting everything. 

As I'm sure you appreciate (especially as you haven't been asking for any yet) as a small team it'll be hard for us to provide much support but please shout when you would like a hand.

**Comment by pizzaisdavid** [comment]
@benfurber thanks for the nice words. At first I wasn't sure if this would be an annoying post or good post.

I hope it is at least not annoying. :slightly_smiling_face:  

About help: yeah, I understand, I also don't want to take anyone's time really, as I don't know where my instance will go.

I think I have largest technical things sorted, only some small bits leftover.

I'm very impressed that everything was documented well enough for me to get everything going, especially since making it easy to setup is not a focus of the project yet. Very nice.

Since there a few things I still need to get setup/change, I'd like to keep this ticket open, until then, if possible.

**Comment by benfurber** [comment]
@pizzaisdavid Perfect!

**Comment by thisislawatts** [comment]
Thanks for sharing your process here ✨ PRs are very welcome to the install.md document so we can improve the process for the next person. 🙏🏻

**Comment by pizzaisdavid** [comment]
44. Fork https://github.com/ONEARMY/academy to https://github.com/pizzaisdavid/food-better-academy

45. Make a branch called `gh-pages` (on your local machine do `git checkout -b gh-pages`)

46. Push that branch to Github (on your local machine do `git push origin gh-pages`)

47. Do some stuff in the project settings.
![pages](https://github.com/ONEARMY/community-platform/assets/4391884/8bfb2acc-71b3-411b-bc36-1e3a42c209e3)

48. Make some changes on a non-master branch. (git checkout -b test, edit a file, commit, and push.)

49. Create a merge request into the master of your own fork (and not ONEARMY's repo, [whoops](https://github.com/ONEARMY/academy/pull/212).)

50. Merge the merge request. Merging into master causes a Github action to run, which deploys the latest code (documentation) to https://pizzaisdavid.github.io/food-better-academy/intro.html

51. For some reason, there is no CSS, it seems.

**Comment by pizzaisdavid** [comment]
52. In your community-platform clone, set `academyResource` to `'https://pizzaisdavid.github.io/food-better-academy/'`

53. build and deploy (yarn build && firebase deploy)

54. Going to https://community.food-better.com still redirects to https://community.food-better.com/academy and 404s.

55. include academy in the public modules:
```
  if (property === 'REACT_APP_SUPPORTED_MODULES') {
    return 'academy,howto,research,user,question'
  }
```

56. build and deploy again.

**Comment by pizzaisdavid** [comment]
My deployment is more-or-less setup.

Some things I would want to do in the future, but they are small (catogories/tags/improving academy styling.)

**Comment by pizzaisdavid** [comment]
To avoid some difficulties with filenames, importing, and correct stylings, when you clone the academy, called it academy, not food-better-academy. And then I had to update the academyResource to just academy.

**Comment by pizzaisdavid** [comment]
The whole environment variables trouble probably is because you also have to run yarn run build:post manually!

so:
```
yarn build
// set enviroment variables, like export REACT_APP_PLATFORM_THEME=project-kamp
yarn run build:post
firebase deploy
```
