### ISSUE TITLE
No maintainer docs on how to make a module public

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3490]
Not all modules are publicly available on all instances on the platform. What is/isn't public is configured...somewhere. There's a couple of bits to make public for precious plastic soon so I'll write up the process for the maintainer docs.

**Comment by benfurber** [comment]
In fact... @pizzaisdavid... from your recent setup of a fresh platform, do you know how to do this!?

**Comment by pizzaisdavid** [comment]
@benfurber 

I think I understood you.

I'm in the train at the moment, but the short answer is: configure the REACT_APP_SUPPORTED_MODULES environment variable.

The default is howto,map,research,academy,user,question

Searching for REACT_APP_SUPPORTED_MODULES does show some tiny documentation.

**Comment by pizzaisdavid** [comment]
See the very bottom of this file https://github.com/ONEARMY/community-platform/blob/master/packages%2Fdocumentation%2Fdocs%2FInstall.md
