### ISSUE TITLE
bug: research drafts not being filtered out

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3503]
The drafts of the new topics saved by all the users are visible for all the rest of the users.

![Captura_de_pantalla_2024-05-07_094342](https://github.com/ONEARMY/community-platform/assets/16688508/33f68eb6-9560-4bac-ad79-456080649c00)

My guess is this is because the move over to the research service didn't include adding a filter to remove drafts?

**Comment by benfurber** [comment]
Can you have a look please @mariojsnunes?

**Comment by mariojsnunes** [comment]
1. A quick solution would be to always add the draft filter.
But then how would the user get to the draft to continue his work?

2. A more complex solution would be to display the drafts created by the logged in user.
But this could lead to the user thinking everyone can see it.

Maybe there should be a place where users can see their drafts and we could apply the first one?

**Comment by benfurber** [comment]
2 is how it worked previously.

**Comment by mariojsnunes** [comment]
As an alternative, what do you think about adding this filter?
![image](https://github.com/ONEARMY/community-platform/assets/8073622/7dfd00e0-7cf6-4be3-b407-4ef256e87adc)

**Comment by benfurber** [comment]
Sonuds good as a follow-up addition.

**Comment by mariojsnunes** [comment]
Another option would be to have a "My Drafts" button, would be more intuitive than the filter option.
![image](https://github.com/ONEARMY/community-platform/assets/8073622/8d18f502-a86d-4dd2-805e-3cdb53246132)

I'll work on this today then share a video

**Comment by benfurber** [comment]
The button makes sense.

How-tos and research have drafts (and questions should though the option isn't shown to the user currently), so whatever is implemented should be for all three please. 

Another annoying element is this behaviour is currently not possible to test e2e, can a ticket for that debt please be added.
