### ISSUE TITLE
Add nested comments to the how-to's

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3505]
### Description

We've released nested comments for Research and Question module.

Next we also need this new discussion model in the howto's (and not remove the current comments content)

**Comment by pizzaisdavid** [comment]
It seems that this is already done, I guess?

https://precious-plastics-v4-dev.firebaseapp.com/how-to/new-title-2

![Screenshot from 2024-06-04 22-12-52](https://github.com/ONEARMY/community-platform/assets/4391884/93d75aac-3a8e-44cf-9b5e-a35c564ae23e)

https://github.com/ONEARMY/community-platform/pull/3579 unless, is there something missing?

**Comment by davehakkens** [comment]
yep. thanks for flagging!
