### ISSUE TITLE
Unable to comment on research module

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3508]
**Describe the bug**
As a user, I want to be able to give feedback on someone's research but cannot. Trying to leave a comment doesn't work.

![Screenshot from 2024-05-07 21-42-12](https://github.com/ONEARMY/community-platform/assets/4391884/f6dca22d-bb44-4ff4-98f7-dddbaeeee9a9)

**Steps to reproduce the behaviour**
1. Go to https://community.projectkamp.com/research/can-we-find-alternative-solutions-for-food-storage-
2. Write comment.
3. Press submit
4. Be sad. 

**Expected behaviour**
My comment is published.

**Additional context**
There is some output in the console, this snippet might be of interest:

```
Failed to set comment {
  err: [Error: n is undefined]
}
```

[click here for full console log output](https://github.com/ONEARMY/community-platform/files/15240162/console_log.txt)

Currently, commenting works on the development environment (https://precious-plastics-v4-dev.firebaseapp.com/research/lc-test-240506-0059 I am the account called testtesttest.)

source: https://discord.com/channels/586676777334865928/1237309179937689625/1237415816375435438

**Comment by benfurber** [comment]
Thanks @pizzaisdavid. Starting to look now.

**Comment by benfurber** [comment]
I can still make a comment...

**Comment by benfurber** [comment]
Oh wait, is this because of the updated security roles...?

**Comment by benfurber** [comment]
Did some more prod testing(!)

I was able to add a comment to the last update on this research: https://community.projectkamp.com/research/can-we-renovate-a-granite-ruin
But not this older research...: https://community.projectkamp.com/research/can-we-make-a-roof-from-recycled-plastic

**Comment by benfurber** [comment]
I wonder if it's something about pre-existing but empty discussion documents.

**Comment by benfurber** [comment]
I deleted the discussion for the last update on here: https://community.preciousplastic.com/research/turn-precious-plastic-into-a-dao

I was then able to sucessfully add a comment.

**Comment by benfurber** [comment]
I then added a second comment, deleted both and then sucessfully added a new 'first' comment. So it's not about the comments being empty.

The only difference is the new discussion object had a 'contributorIds' array. So that looks like the issue.

**Comment by benfurber** [comment]
I've updated the prod data so all discussions now has the contributorIds arrray. Now users can add comments again! YAY!

Tomorrow I'll fix the brittle implementation that caused this. And update the contributorIds to have the ids each should.
