### ISSUE TITLE
[bug] Breadcrumbs category doesnt link back to overview

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3520]
**Describe the bug**
We just released breadcrumbs.
But when clicking the category (Machines) it should bring you back to the overview showing only show the "machines"
This doesnt work for any category in any module

<img width="488" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/c17124da-dce1-427e-8c71-a8617235d970">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to community.preciousplastic.com
2. Try it on any How-to, Questions and Research
3. [Example](https://community.preciousplastic.com/how-to/make-hydraulic-plastic-shredder)

**Comment by benfurber** [comment]
This is a duplication of #3514. The problem is more in the filtering than the breadcrumbs.

**Comment by benfurber** [comment]
This is a duplication of #3514. The problem is more in the filtering than the breadcrumbs.
