### ISSUE TITLE
[feature request] Navbar order

### ISSUE THREAD

**Issue by m-azoubel** [ONEARMY/community-platform#3523]
**Is your feature request related to a problem? Please describe.**
The navbar should have an hierarchy to better display information/a minimal suggested order for users to navigate in the platform.

**Describe the solution you'd like**
Reorganise the navbar to the following order, from left to right:
1. Academy
2. Map
3. How-to's
4. Research
5. Questions

**Comment by davehakkens** [comment]
Agree this could be improved. Where is your hierarchy based upon?

**Comment by m-azoubel** [comment]
Well my ideal hierarchy is actually:
1. Academy -> core part of CP, it's where people (should) get started to learn about plastic
2. Questions -> ready to start but still unexperienced, so they'll start asking technical questions
3. Map -> now they got some experience, so they're ready to start their business and put themselves into the map
4. How-to's -> got some expertise, now want to share back
5. Research -> very experienced and comfortable with the tools, and want to expand their knowledge to try out new things

However, Questions is still very new and not populated, which might "scare" people a bit if it only has a couple of questions. So the initial suggestion followed the logic of most populated -> less populated modules

**Comment by davehakkens** [comment]
I see. And just checking your logic here ;)
Wouldn't How-to's than be second? Since thats where you download the items after learning in the Academy

**Comment by codisart** [comment]
It this hierarchy be the same for each site ? Or is it just for precious plastic ?

**Comment by m-azoubel** [comment]
Good point. 
Thinking again, I think that the order between Questions and How-to doesn't really matter, as I'm imagining the following scenarios based on the different cultural approaches to learning and building:

Scenario #1
1. Learn in the Academy
2. Decides to build, let's say, a shredder
3. Is redirected to the shredder How-to to download files
4. Has questions about the building process, then is redirected to Questions

Scenario #2
1. Learn in the Academy
2. Decides to build a shredder
3. Has questions about the building process before starting, then is redirected to Questions
4. Has questions answered, then downloads files and starts building
