### ISSUE TITLE
[feature request] Extend webhooks for notifications in Discord #activitybot

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3533]
### Current setup
We have a few webhooks installed to make a notification in [Discord](https://discord.com/invite/SSBrzeR) to the #activitybot channel.
![afbeelding](https://github.com/ONEARMY/community-platform/assets/13672737/20b48d38-ad02-46ba-ab2e-dab0fc699a15)
<img width="1031" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/a70c0436-e756-41b3-9dbd-63d752b1bcce">

### Current Problems
1.  They are only installed for the `map` and `how-to`module. (not `research` or `questions`)
2. They are triggered on edit (should only be triggered on create/approved)

### Describe the solution you'd like
1. We need webhooks for `questions` and `research` module.
2. Stop to trigger webhooks when content (map-pins + howtos) are edited

   
### Trigger Overview
**Research:**
Trigger: New Update posted inside a Research module
Text: 📝 New update from [username] in their research: **[insert research title]**
Learn about it here: [[url to research update](https://github.com/ONEARMY/community-platform/discussions/url)]

**How-to:**
Trigger: New How-to approved by admin
Text: "🎁 Yeah! New solution made by [username]: **[insert how-to title]** 
Check it out here: [[url to how-to](https://github.com/ONEARMY/community-platform/discussions/url)]"

**Member-map-pin:**
Trigger: Member Map-pin approved by admin
Text:"👋 New pin on the map from [username] that want's to get started
See if they are local to you here: [[url to map](https://github.com/ONEARMY/community-platform/discussions/url)]"

**Space-map-pin:**
Trigger: Space Map-pin approved by admin
Text:"🌏 New space on the map from [username] that grows the global movement!
Find them here: [[url to map](https://github.com/ONEARMY/community-platform/discussions/url)]"

**Question:**
Trigger: Question posted in Question module
Text:"❓ [username] has a new question: [insert question title]
Help them out and answer here: [[url to question](https://github.com/ONEARMY/community-platform/discussions/url)]"

### Things to keep in mind
- Use these`<>` to wrap the <url> so it doesnt show a preview-card in Discord
- It might be more effective to solve the "edit" problem on a higher level. Since currently any edit to a map-pin and how-to needs approval by an admin. This could be removed to only ask for approval when create, not edit. (Bonus: this would also make admins happy)
- It needs to be done for all our 3 live instances

Note: 🔥 #activitybot is our 4th most watched channel in our Discord

**Comment by pizzaisdavid** [comment]
I have addressed the Howto editing triggering a notification (and need re-approval from admins) https://github.com/ONEARMY/community-platform/issues/3613 currently it is still open, but just so anyone else avoids doing that work.

**Comment by davehakkens** [comment]
Thanks for the first part on this @pizzaisdavid !
Are you also up for doing the other bit of this?

**Comment by pizzaisdavid** [comment]
I might try but no promises.

> Stop to trigger webhooks when content (map-pins + howtos) are edited

Moving the location of a pin does not trigger the need for re-approval but changing the "focus" of a profile does. And we want to disable that, correct?

In case anyone else wants to try, here is the related code: https://github.com/ONEARMY/community-platform/blob/master/src/stores/Maps/maps.store.ts#L187

**Comment by pizzaisdavid** [comment]
![best_i_can_do](https://github.com/ONEARMY/community-platform/assets/4391884/3ff5dc2b-9561-4ce5-928c-a05f4d98840e)

current state:
- Pins of type `member` do not need moderation.
- Switching type in anyway requires moderation.

What I can adjust it to:
- NEW: Switching between different `non-member` types do not affect moderation status (accepted entries stay as accepted.)
- SLIGHT CHANGE: Switching from `member` to a `non-member` type requires moderation, already happening indirectly.
- Pins of type `member` do not need moderation (same as before.)

Example: if someone switches from member to collection point, they would need moderation. If they switch back to member, they don't need moderation. But if they switch back again to collection point (or any other non-member type) they need approval again.

Summary: any time switching from member to non-member, it would require moderation.

If the wish is they really only need to be approved once ever, then a new property could be introduced (or a different approach.) But I can't estimate the complexity of that.

Also to reiterate for those reading, whenever the moderation status of a pin is changed to `accepted` it triggers the webhook.

Also, I could be wrong about any of this, anyone feel free to correct me.

**Comment by davehakkens** [comment]
Thanks for the indepth look, very useful!
Your porposal sounds more complete then the original plan of no moderation at all.
To me this seems like a good path to take

**Comment by pizzaisdavid** [comment]
I see we want to push the questions module for precious plastic.. therefore, it would be good if we setup the webhook for that.

**Comment by davehakkens** [comment]
> I see we want to push the questions module for precious plastic.. therefore, it would be good if we setup the webhook for that.

Agree that would be a very nice/useful one

**Comment by mariojsnunes** [comment]
> Kay, here's a pull request that publishes webhooks for new questions: #3619

This has been deployed 🚀

**Comment by pizzaisdavid** [comment]
Research Updates have a collaborators property, which is a list of usernames. I've only ever seen an Update written by one person, so a list of just one username.

But is it planned to support multiple collaborators on a single update?

I could build some more complicated logic in that case:

1 author:
 📝 New update from [username1] in their research: ...

2 authors:
 📝 New update from [username1] and [username2] in their research: ...

3 authors:
 📝 New update from [username1], [username2], and [username3] in their research: ...

And so on..

Thoughts?

**Comment by pizzaisdavid** [comment]
> What does this deployment mean @pizzaisdavid?
> Should notifications come in somewhere now, from dev or live?

It is possible I don't understand you correctly, but the next time a Question is asked on community.preciousplastic.com/questions  there should be a corresponding bot post in the activitybot Discord channel.

Precious plastic is the only one with questions enabled, but in the future, if others have it enabled too, there would be notifications from them as well. 

I thought about posting a test question on Precious Plastic, but I think it isn't possible to delete your own question, so I felt like it would be not nice.

Can I post a test question on production, to verify it works correctly?

**Comment by davehakkens** [comment]
yeh lets give it a try @pizzaisdavid!

**Comment by pizzaisdavid** [comment]
https://discord.com/channels/586676777334865928/599259846767935519/1251985417973006376

**Comment by davehakkens** [comment]
Nice one! 💪
@goratt12 So what is the function of the new Discord Bot we recently setup up? -Since this seems to run on the original one.

For the archive:
<img width="961" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/1edef37f-5aed-43b0-a974-c55d46d847b3">

**Comment by goratt12** [comment]
The function stayed in `firebase-discord.ts` 
https://github.com/ONEARMY/community-platform/blob/7b84b82bc2aaaf20c423df14bc1b2882390c065a/functions/src/Integrations/firebase-discord.ts#L18-L25

The testing function is also in that file
https://github.com/ONEARMY/community-platform/blob/7b84b82bc2aaaf20c423df14bc1b2882390c065a/functions/src/Integrations/firebase-discord.ts#L34-L48

We are having issues with the testing in the CircleCI environment, currently moving the PR to Draft until we will figure out a solution

**Comment by benfurber** [comment]
Is there a way we could check on the cypress tests that a notification has been sent?

**Comment by pizzaisdavid** [comment]
> Is there a way we could check on the cypress tests that a notification has been sent?

The ideal: the cypress tests are ran in Docker, the backend functions are ran in the emulator inside docker, and the simple "simulated-webhook-receiver" is also started-up inside Docker.

https://github.com/ONEARMY/community-platform/tree/master/packages/simulated-webhook-receiver

They are all handled via Docker Compose, then everything is happening locally (either on the devs machine or in the CI.)

There is an endpoint in there to get the requests that have been made.

Pros:
+ doesn't depend on an external service, Discord could have problems, we don't care.
+ devs can run tests without internet access
+ the tests would be more simple (compared to what I will propose next.)

Cons:
- Docker bro.
- Cannot be done until the backend functions for cypress tests are also ran locally.

Would be fine to implement if the tests were already running in docker.

---

Achievable "today"-ish

Follow what @goratt12 has been trying to do. I guess Discord offers an API to check messages for a Discord channel.

Backend functions for cypress are configured to send to test channel.

Cypress test generates uniquely identifiable content (for example, a question with a title has is 24 random characters.)

In the assert section of the test, use their helper function posted above to check that there was a Discord message in that test channel that has the same random characters.

If static test data was used, it would pass even if it broke, due to old messages of the same static content.

Pros:
+ could be done easier than "Dockerize everything"

Cons:
- Relies on an external service
- Devs who want to work on webhooks would then want access to this, another thing to keep in mind.
- A further ingraining less then ideal testing setup, but better than none, I guess?

**Comment by pizzaisdavid** [comment]
I have made an issue for cypress tests (https://github.com/ONEARMY/community-platform/issues/3694) and Guy's pull request should add unit tests https://github.com/ONEARMY/community-platform/pull/3636

**Comment by pizzaisdavid** [comment]
I believe the only remaining part of this task is related to the map pins, and that is under discussion. But I could be wrong of course.

As for example: when an initial Reseach Article is created (but not Updates are made) there is no webhook for that, and that is not covered by the ticket.

**Comment by davehakkens** [comment]
> As for example: when an initial Reseach Article is created (but not Updates are made) there is no webhook for that, and that is not covered by the ticket.

Agree. this could be nice to have, but not essential.

What i think is still missing:
Make the notifications work for Project Kamp (mainly the research)

**Comment by pizzaisdavid** [comment]
>  Make the notifications work for Project Kamp (mainly the research)

:+1: (yes and that is already covered by another ticket: https://github.com/ONEARMY/community-platform/issues/3693)
