### ISSUE TITLE
[bug] "Want to get started" pins reappearing by default again

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3555]
**Describe the bug**
A while back, we set it up on precious plastic to hide the member/"Want to get started" pins by default. But they're back now for some reason. Maybe the recent move to the map pin API?

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [the map on PP](https://community.preciousplastic.com/map)'
2. See all the ~1600 odd member pins  

**Expected behaviour**
Those ~1600 odd member pins to be hidden.

**Screenshots**
<img width="1731" alt="image-map" src="https://github.com/ONEARMY/community-platform/assets/16688508/4ff31892-fba5-4ded-a4bd-d654c4544d70">

**Comment by davehakkens** [comment]
previous PR for reference https://github.com/ONEARMY/community-platform/pull/3000
