### ISSUE TITLE
[bug] Items in the Research module having current date as "Last Updated" date

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3558]
**Describe the bug**
All the items in the research module of Project Kamp have the current date as the date of when they have been last updated. This creates a problem for Project Kamp people contributing to the research module, since they would like the latest research update to be shown on top.

**To Reproduce**
Steps to reproduce the behaviour:

1. Navigate to https://community.projectkamp.com/research (or also Precious Plastic's research module)
2. See that the date next to "Updated" incorrectly shows current date

**Expected behaviour**
The date should accurately indicate the date when the Research item was last edited by the author or the collaborators.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/22c290a8-a15e-4b41-9fe7-5bd39e716240">

**Additional context**
I noticed that in the Precious Plastic's research module, some items have the date of today, the others have the date of the day before yesterday. The bug doesn't seem to be present in the dev version.

**Comment by benfurber** [comment]
I believe this is because it's displaying, filtering and indexing `_modified` when it should be using `_contentModifiedTimestamp`.

What needs fixing:
- Research listing display
- Research filtering
- `firestore.indexes.json`

**Comment by davehakkens** [comment]
@mariojsnunes did this break after the remake you worked on for the research module recently?
Would either way be good to fix this one soon because a lot of interesting new research will be created in Precious Plastic (due to the [PPOSF](https://pposf.preciousplastic.com/)) but now its very hard to see the latest updates
