### ISSUE TITLE
Ensure all images have unique alt tags

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3578]
At the moment we don't ask users to provide alt tags for the images that upload. As a short-term fix, we should apply alt tags to research updates, how-to steps and questions which follow some kind of dynamtic structure, e.g. '<update>-<index>'

This is important from a Search Engine Optimisation prospective.

**Comment by dbernhauser5** [comment]
Is this still a relevant ticket or just wasn`t closed?

**Comment by benfurber** [comment]
Hey @dbernhauser5, welcome! This is absolutely still relevent and no one (I know about(!)) is working on it. Can I assign it to you...?

**Comment by koeppel** [comment]
I'd pick it if @dbernhauser5 isn't responding :)
I'd create a PR for the default alt text and also an extra text field for the image uplade to add a "description" text to the image?

**Comment by dbernhauser5** [comment]
I must have missed an email about a reply to my comment. However go for it and take the ticket I do not have much experience with frontend so it would probably just take a lot of time. I will check out some other tickets.

**Comment by benfurber** [comment]
Thanks for the offer @koeppel! Assigned!

@dbernhauser5 Does anything else take your fancy?
