### ISSUE TITLE
[developer experience] e2e tests are not ran for some users on pull requests

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3584]
As a developer I expect the e2e tests to be ran in the pipeline so we know nothing broke before merging.

Actual (https://github.com/ONEARMY/community-platform/pull/3575)
![e2e_not_ran](https://github.com/ONEARMY/community-platform/assets/4391884/bdf56f48-c473-4731-973e-dce2a23a8b17)

Expectation (https://github.com/ONEARMY/community-platform/pull/3583)
![e2e_expectations](https://github.com/ONEARMY/community-platform/assets/4391884/e1491f18-cd3f-49dd-b252-3937a72ce6d2)

Here you can see the circleci workflow for the ones that don't have the tests: https://app.circleci.com/pipelines/github/ONEARMY/community-platform/9079/workflows/b893849b-2c02-4468-a165-6b5551449020

It could be that they are not ran because a previous job is not ran.

Also, on that page there is the text:

> The user who triggered the build may not have permission to a context being used. Visit our help article, [Troubleshooting Builds "Unauthorized" due to contexts](https://support.circleci.com/hc/en-us/articles/360050273651-Builds-Unauthorized-due-to-contexts).

**Comment by pizzaisdavid** [comment]
To check if this problem started recently, it would be good if someone with a circleci team account could open this link: https://circleci.com/gh/ONEARMY/community-platform/52994 and then look at the workflow for that.

Taken from the my first merge request (made in 2023 October) https://github.com/ONEARMY/community-platform/pull/2898

**Comment by pizzaisdavid** [comment]
https://circleci.com/docs/contexts/

> To use environment variables set within a context, the person running the workflow must be a member of the organization for which the context is set.

But the lines in the circleci config (`context: build-context`) haven't changed in more than a year.

It could be that environment variables are now configured for that context, causing it only now to not run OR maybe this has been not running for a long time?

**Comment by pizzaisdavid** [comment]
My proposed solution would be to check if the `build-context` can be un-restricted so anyone can trigger that context (I'm not sure if that is even a thing, because in the docs it talks about members of an organization).

An admin of the CircleCI would need to check if any of the environment variables defined in the `build-context` context are sensitive/private. And check if there is the ability to make the executable by anyone. Same probably goes for the `e2e-tests` context because I want to be able to see the e2e tests run.

https://circleci.com/docs/contexts/#restrict-a-context

@benfurber @thisislawatts Are either of you administrators on CircleCI? If not, can you tell me who?

**Comment by pizzaisdavid** [comment]
Based on @benfurber recommendation, I logged into circleci (via Github account) and refreshed my permissions: https://app.circleci.com/settings/user

that didn't work.

I have requested to circleci to delete my account. Maybe that will fix something? (I had an account previously for work.)

**Comment by pizzaisdavid** [comment]
Am I the only one with this problem?

(it is still happening)
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/9641/workflows/59d2d020-3cd8-44bd-b72b-4df305a0b3ec

I am not sure if there are people in the circleCI organization. And it would just be fixed by adding to the org?

**Comment by benfurber** [comment]
Is this still happening?
