### ISSUE TITLE
[feature request] There is a "My Drafts" button on the question page, but it isn't possible to save a question as a draft

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3591]
As a person with a question, I don't necessarily need to be able to save a draft, I can edit the content in a text editor until I am ready to post, but it is strange that there is a button that seems like it won't ever do anything.

![image](https://github.com/ONEARMY/community-platform/assets/4391884/1f33d4dd-eff6-4d2c-95e7-40b7dd732756)

![image](https://github.com/ONEARMY/community-platform/assets/4391884/2bc67340-96b7-434f-9481-585dd939a735)

**Describe the solution you'd like**
possible solutions: remove the button or add the ability to save as a draft.

**Comment by mariojsnunes** [comment]
should remove the drafts feature for questions as it doesn't make sense here, at least for now.
