### ISSUE TITLE
[bug] Many network requests made when viewing notifications

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3592]
As a site admin, I wouldn't want unnecessary network calls going, because I imagine they can impact the cost. 

![notifications_many_requests_made](https://github.com/ONEARMY/community-platform/assets/4391884/95c40c6e-9cca-4937-a00c-09247c33e0cb)

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to https://precious-plastics-v4-dev.firebaseapp.com
2. Publish a question.
3. Logout
4. Login with a different account.
5. Publish an answer to your question.
6. Log back in to the original account.
7. Open the notification panel
8. Watch the network requests roll in.

**Expected behaviour**
Not a stream of constant requests.

Maybe a maintainer or someone could weigh-in if this is with worth addressing

**Comment by mariojsnunes** [comment]
Wow this is a great find, thank you!

> Maybe a maintainer or someone could weigh-in if this is with worth addressing

It is definitely! I'm looking into it now
