### ISSUE TITLE
[feature request] RSS or Atom feed for research modules

### ISSUE THREAD

**Issue by lbrocke** [ONEARMY/community-platform#3603]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to follow either all or certain modules on the research page, specifically from Project Kamp, without making an account.

**Describe the solution you'd like**
While arguably becoming less and less common, the standard way of providing this would be an Atom or RSS feed. Lots of news sites and blogs still provide feeds for content that is publicly available anyway.

**Describe alternatives you've considered**
I found that this was briefly mentioned as an implementation option for subscriptions in issue https://github.com/ONEARMY/community-platform/issues/1438, but not discussed further.

**Comment by benfurber** [comment]
I'm afraid this isn't part of our roadmap currently so I'm going to close this issue for the moment.
