### ISSUE TITLE
[feature request] Add mandatory questionmark for Questions module

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3604]
**Is your feature request related to a problem? Please describe.**
The questions module should host "questions" 

**Describe the solution you'd like**
1. Make it mandatory to have a questionmark inside the title.
2. Add an error message the explain to the user
3. ideally it can be combined with the current error message regarding the character length 

**Describe alternatives you've considered**
To avoid complexcity, don't make the validation error. Just mention it in the title of the input field

**Screenshot**

![questionmark](https://github.com/ONEARMY/community-platform/assets/13672737/98135bdd-13c3-40cd-9506-05fba3a4c496)

**Comment by iSCJT** [comment]
@davehakkens how about we just add a question mark on the end if they don't?  No need for any messages then.

**Comment by davehakkens** [comment]
Could be.
If it would be there by default, so the person posting already sees it and can adopt their title. (if not and we add the question mark after publishing it likley result into some weird titles that are not phrased as sentences)

**Comment by pizzaisdavid** [comment]
The image (and description) use "questionmark" but from an English perspective, it would be better to use "question mark"

> Needs to end with a question mark

**Comment by lucaasrojas** [comment]
Hi, I am working on this (no need to block it this is my first time :) ) and have a question, should the question mark count as a character for the counter?
![image](https://github.com/ONEARMY/community-platform/assets/26610409/09853e4b-d782-48ca-bbc3-9a19acb3e5bc)
