### ISSUE TITLE
[bug] Comment count on research item out of sync

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3629]
**Describe the bug**
On the Project Kamp instance, the ruin research post has 0 comments, while in reality it has 2. Related to previous issue #3510 .

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://community.projectkamp.com/research'
2. Find the "Can we renovate a granite ruin almost from scratch?" research
3. See that it shows 0 comments

**Expected behaviour**
To show accurate number of comments - in this case at this point in time 2.

**Screenshots**
<img width="1250" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/ae1123ec-2363-4dbd-a028-3b3313297da7">

**Additional context**
Also, on mobile I saw the count being NaN, but I wasn't able to replicate this behaviour.
![telegram-cloud-photo-size-4-5985369310656316470-x](https://github.com/ONEARMY/community-platform/assets/35503298/0d640ec1-1b6a-4154-81cf-b60393f1d3bd)

**Comment by benfurber** [comment]
I've done a manual sync of the db data again. But to solve this properly #3641 needs doing.
