### ISSUE TITLE
[bug] Profile Tips notice showing on mobile in PK's instance

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3630]
**Describe the bug**
On Project Kamp's instance, in the profile settings, the Profile Tips notice is showing on mobile. The Profile Tips notice was migrated from Precious Plastic instance and is not relevant for Project Kamp. It was deemed not necessary and hidden for desktop, but on mobile viewport it still shows.

**To Reproduce**
Steps to reproduce the behaviour:

1. Log in to 'community.projectkamp.com'
2. Go to 'Profile settings'
3. Change the viewport to mobile, or do this process on your phone

**Expected behaviour**
Removing the content that links to Precious Plastic and hiding or removing the notice.

**Screenshots**
<img width="374" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/bf13fb05-ed5d-43e0-b686-872713acadba">

**Comment by benfurber** [comment]
This won't be needed after the new form is finished.
