### ISSUE TITLE
[feature request] Improve the display of the edit and delete buttons next to user's own comment

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3651]
> This ticket is part of series of 7 tickets concluding a design task focusing on improving design and usability of comments feature. Here you can find the [Figma file](https://www.figma.com/board/GfQPMs7PyC7jbkymDTco2D/CP-%2F-Nested-Comments-Improvements?node-id=0-1&t=7sgMA4ZPYXAMb03A-1) for more context.

### **2/7 - Improve the display of the edit and delete buttons next to user's own comment**
---

**Is your feature request related to a problem? Please describe.**
The problem here is, that the height of the edit and delete buttons is increasing the spacing between the username and the text. This creates an inconsistency of spacing between user's own comments and other comments.

![image](https://github.com/ONEARMY/community-platform/assets/35503298/7d86a6ab-8ffb-416c-8412-423793ca6d1f)

**Describe the solution you'd like**
A solution with consistent height of the wrapping div, that accounts for the size of the buttons regardless if they are there or not. The username should have `justify-content: flex-end;` 

<img width="738" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/056efec1-4691-48bc-bd33-564d4fc8a387">

Additionally, it would be good to have a less dominant version of the buttons as shown here. The issue of creating less dominant variant of the button component is prominent on several places throughout the platform and is discussed in this ticket #3655 . 

![image](https://github.com/ONEARMY/community-platform/assets/35503298/e90ff3ea-1e03-4c7d-b013-94842f5c9357)

**Describe alternatives you've considered**
I first considered, making the buttons the size of the username component which is 25px, but that would be too small for mobile.

A menu with three dots is standard in other platforms, but I am not sure how big and complex of an implementation that would be, so I just propose this quick adjustment for now. However, the three dots menu was a consideration before and could be a good option, since the options will likely grow in the future (adding report function). The three dots would also perform better on mobile, not creating problems with stacking below.

**Additional context**
See the milestone

**Comment by elideg** [comment]
@dalibormrska I can pick this ticket up.

**Comment by pizzaisdavid** [comment]
If other people look at this ticket, I have made a pull request that makes the buttons into the "less dominant version."

**Comment by pizzaisdavid** [comment]
> The issue of creating less dominant variant of the button component is prominent on several places throughout the platform and is discussed in this ticket https://github.com/ONEARMY/community-platform/issues/3655 .

The approach in that linked pull request might not apply to this same situation, based on Mario's feedback.

https://github.com/ONEARMY/community-platform/pull/3700#pullrequestreview-2147310041

**Comment by onim-at** [comment]
Hello! What's the status on this user story? Can I pick it up?
