### ISSUE TITLE
[feature request] ButtonShowReplies minor adjustments

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3652]
> This ticket is part of series of 7 tickets concluding a design task focusing on improving design and usability of comments feature. Here you can find the [Figma file](https://www.figma.com/board/GfQPMs7PyC7jbkymDTco2D/CP-%2F-Nested-Comments-Improvements?node-id=0-1&t=7sgMA4ZPYXAMb03A-1) for more context.

### **3/7 - ButtonShowReplies minor adjustments**
---

**Is your feature request related to a problem? Please describe.**

1. First and major problem is the visual dominance of the button. This is talked about in a separate ticket #3655 and is therefore not in the scope of these adjustments.

2. The second issue is the text that makes the button too long, since it includes the username.

3. The third issue is with the arrow icon not being centred and being too thick

<img width="217" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/292440c7-a48b-4353-a393-eb8a4e6b34e3">

**Describe the solution you'd like**
_Must Have:_ Make it say “Show X replies” and “Hide X replies” if it has replies.
If it doesn’t have replies it can say “Reply” and then “Hide replies”

_Should Have:_ Adjustment to the icon, consider making it into a chevron, making it centered and the stroke thickness balanced.

<img width="463" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/446c6b8e-2039-49d8-8786-8fcaead996ca">

Additionally, there is the proposal to have the button without the border, but it is in the scope of another ticket, mentioned also above #3655 . Below is how it should look after removing the border as well, also with the hover state.

<img width="463" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/afed0d06-3a01-47ca-85b2-6f06e5bff022">

**Describe alternatives you've considered**
The issue of creating less dominant variant of the button component is prominent on several places throughout the platform and is discussed in this ticket #3655 . Could there be a common solution for creating a button variant without border?

**Additional context**
See the milestone

**Comment by y-bhargava** [comment]
I can take this ticket.

**Comment by davehakkens** [comment]
Forgot to assign. Are you still up for this @y-bhargava ?

**Comment by y-bhargava** [comment]
yes @davehakkens

**Comment by davehakkens** [comment]
I dont think this is completed @benfurber

**Comment by benfurber** [comment]
Hey @y-bhargava - how are you getting on with this?

**Comment by onim-at** [comment]
Hello @benfurber, I can help with this if @y-bhargava is not available

**Comment by benfurber** [comment]
That would be great, thank you @onim-at.
