### ISSUE TITLE
[feature request] Improving the display of the date

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3653]
> This ticket is part of series of 7 tickets concluding a design task focusing on improving design and usability of comments feature. Here you can find the [Figma file](https://www.figma.com/board/GfQPMs7PyC7jbkymDTco2D/CP-%2F-Nested-Comments-Improvements?node-id=0-1&t=7sgMA4ZPYXAMb03A-1) for more context.

### **4/7 - Improving the display of the date**
---

**Is your feature request related to a problem? Please describe.**
Currently the date in in a hard-to read format, making it visually cluttered and also it takes time for the user to figure out exactly when was the comment or other content made or edited. Some countries have DD-MM-YYYY and some MM-DD-YYYY formats, so it is not entirely clear which one is month and which one is day.

<img width="321" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/7290c5b6-6dbd-4991-acc8-b8b6e75e40c2">

Additionally the text that says '(Edited)' is in a different font and size. In other parts of the platform the solution is better, where the information about editing is incorporated into the date.

<img width="349" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/28f7655c-2cbe-424e-b80c-b05cd6c2693a">

**Describe the solution you'd like**
Turn date info into what time has passed - 2 hours ago, 5 minutes ago, 1 year ago. Maybe there is some existing library or something that can be implemented, also considering i18n (In english there are only 2 gramatical formulations, such as '1 year ago' and '2 years ago', but in Czech for example you have 'před 1 rokem', 'před 2 roky', 'před 5 lety').

Additionally, it should have a simple [title](https://www.w3schools.com/tags/att_global_title.asp) on hover, like in this example:

<img width="317" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/4e26fd02-2366-47c9-ad7e-1a76dee531de">

> Ticket scope to include (notes from Ben):
> 
> - Create component in the library to cover this
> - At least one example in the end-to-end tests of the 'just now' render of the component displayed.
> - List everywhere it should go:
>   - Comments and nested comments across all modules where there are comments
>   - Research module listing
>   - Single research and research updates
>   - Questions module listing
>   - Single question
>   - Single How-To
>   - In academy pages (I am aware that it is a different system, so it is more of a Could-Have, not a Must-Have)

**Describe alternatives you've considered**
An easier alternative would be to just spell out the month into a format like this: 1-Feb-2023, however still a harder to read format.

**Additional context**
See the milestone

**Comment by prashik0202** [comment]
i know how to format data and display
you can assign this issue to me

**Comment by davehakkens** [comment]
How is this going @prashik0202 ?

**Comment by prashik0202** [comment]
@davehakkens 
![image](https://github.com/ONEARMY/community-platform/assets/88095936/5293b57b-8d43-42bf-94be-b44249807dd0)

**Comment by prashik0202** [comment]
@davehakkens  i want to install a package called "moment" which helps in display like '2 min ago'.
but I'm unable to install it, what command should i use to handle this.

**Comment by mariojsnunes** [comment]
> @davehakkens i want to install a package called "moment" which helps in display like '2 min ago'. but I'm unable to install it, what command should i use to handle this.

Dont install moment, use date-fns

**Comment by mariojsnunes** [comment]
> @davehakkens ![image](https://private-user-images.githubusercontent.com/88095936/345768415-5293b57b-8d43-42bf-94be-b44249807dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ0OTMsIm5iZiI6MTcyMDA4NDE5MywicGF0aCI6Ii84ODA5NTkzNi8zNDU3Njg0MTUtNTI5M2I1N2ItOGQ0My00MmJmLTk0YmUtYjQ0MjQ5ODA3ZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMWFmNzE5YmY2MWViZDEzMTY4ZWM4MTUzMzUxZjNlMzJkYjI0ZDFhNjI3NjVlM2U2YmEzM2UzMDgzZDNmMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5iGLpKK5dRpXBfXbAybkMw29siacAVbiX0UtAZ3e4V0)

Day, month, year. Not month day year, please! I don't think the week day is relevant

**Comment by prashik0202** [comment]
@davehakkens 
![image](https://github.com/ONEARMY/community-platform/assets/88095936/8850a3cf-2752-4808-8074-604b60ddcfdd)

and relative time:
![image](https://github.com/ONEARMY/community-platform/assets/88095936/da8167bb-d858-4dea-8edd-ad2dedf7201e)

**Comment by davehakkens** [comment]
The relative time looks good and what originally intended with the issue. 👆

Is it possible to show the precise date when hovering? AS this example 
![afbeelding](https://github.com/ONEARMY/community-platform/assets/13672737/76ee2f4e-20ff-4d9a-a958-c25182999e3e)

**Comment by dalibormrska** [comment]
> The relative time looks good and what originally intended with the issue. 👆
> 
> Is it possible to show the precise date when hovering? AS this example ![afbeelding](https://private-user-images.githubusercontent.com/13672737/345806000-76ee2f4e-20ff-4d9a-a958-c25182999e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTMzODIsIm5iZiI6MTcyMDA5MzA4MiwicGF0aCI6Ii8xMzY3MjczNy8zNDU4MDYwMDAtNzZlZTJmNGUtMjBmZi00ZDlhLWE5NTgtYzI1MTgyOTk5ZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDExMzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMzU1MTZkZWM0OTdmY2ViMjk2MzM4OWE5YWU5YjhmODU3NTAzZjFhY2U3ZmFlOTMzOGExMzcwMjc4NmU3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iLMrnByre2qfffZWWm-muGvFtxlXWG1eJ6Ldbx1rsuo)

This is usually done with HTML Title attribute, should be very easy to implement. 
https://www.w3schools.com/tags/att_global_title.asp

**Comment by prashik0202** [comment]
@davehakkens 
check out
![image](https://github.com/ONEARMY/community-platform/assets/88095936/9f147d04-98c6-4b8f-8622-13693d971b1b)

**Comment by davehakkens** [comment]
Could you make a Pull Request @prashik0202 so we can have a look?

**Comment by dalibormrska** [comment]
Great job @prashik0202 ! Looks awesome and works really well for the comments, I'm very glad to see the change implemented! Now the task would be to implement this date display consistently throughout the platform, as it is formulated in the scope of the ticket above. Since currently in How-tos, Research or Questions the items still have the old format of the date display. Would you be up for it? :)))

<img width="780" alt="image" src="https://github.com/user-attachments/assets/d7ddeca8-3fdc-454e-a92c-a1121f82646b">

**Comment by onim-at** [comment]
Hello @dalibormrska, I could help with this task if @prashik0202 is not available

**Comment by benfurber** [comment]
Awesome, thanks @onim-at - it's yours.

Would be delighted if you were able to contribute again in the future, @prashik0202. :)
