### ISSUE TITLE
[bug] Adding a default avatar in CommentItem when userAvatar isn't present

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3654]
> This ticket is part of series of 7 tickets concluding a design task focusing on improving design and usability of comments feature. Here you can find the [Figma file](https://www.figma.com/board/GfQPMs7PyC7jbkymDTco2D/CP-%2F-Nested-Comments-Improvements?node-id=0-1&t=7sgMA4ZPYXAMb03A-1) for more context.

### **5/7 - Adding a default avatar in CommentItem when userAvatar isn't present**
---

**Is your feature request related to a problem? Please describe.**
Now with the avatars in place for the comments, a problem arises when an user does not have their avatar set, then the alignment is off.

![image](https://github.com/ONEARMY/community-platform/assets/35503298/538ebc43-0233-4c25-8dad-1d91692153c2)

**Describe the solution you'd like**
Add a default avatar. There is already a default avatar in the profile, when the new user registers. 

<img width="793" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/7df4ccb1-57d7-42f6-8f29-7e814255a6ad">

**Describe alternatives you've considered**
Alternative could be just indenting the comments by default, making space for the avatars if they are there. 
Alternative to the default smiley face avatar could be the icon of a member, or a workspace.

**Additional context**
See the milestone

**Comment by prashik0202** [comment]
by conditional rendering the image tag we can set default avatar on commentitem avatar 
please assign this issue to me

**Comment by kimskovhusandersen** [comment]
I can pick up this ticket [@ONEARMY/maintainers](https://github.com/orgs/ONEARMY/teams/maintainers).
