### ISSUE TITLE
[feature request / bug] when a research module as no updates, it isn't possible to leave a comment.

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3660]
There are two research modules on production that don't have an initial update, making it impossible to leave a comment on.

- https://community.projectkamp.com/research/how-can-we-improve-our-organic-compost
- https://community.projectkamp.com/research/can-we-renovate-granite-walls

Should this behavior change or should an initial update/entry be required?

source: https://discord.com/channels/586676777334865928/745249754597818418/1250893835639455755

**Comment by benfurber** [comment]
Thanks for highlighting but I'm confortable with the current behaviour and ensures a low barrier to creating/adding research. It's a choice of content creators to publish a research topic without an update and thus uncommentable.
