### ISSUE TITLE
[feature] Cypress CircleCI- add cache browser on test_e2e jobs

### ISSUE THREAD

**Issue by tuliobluz** [ONEARMY/community-platform#3683]
**Is your feature request related to a problem? Please describe.**
It is not associated with a problem, however, every time that e2e-chrome-(1,2,3,4) runs it has to download the browser as you can see [here](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/9403/workflows/2fb641be-0e00-462f-94e5-13b5b1dccfa1/jobs/82435). The idea is to cache the browser.

The download will be not necessary anymore as it will be cached. Saving time and resources as you can see down below:

As an example, it can take more or less:
Time total: **168 seconds** (42 seconds to finish the download step and e2e-chrome runs 4 times as it is parallel) 

**Describe the solution you'd like**

I created this https://github.com/ONEARMY/community-platform/pull/3682 to try to solve it.

**Describe alternatives you've considered**
I am not sure it has others.

**Comment by tuliobluz** [comment]
Make sure to be able to update the browser to the new versions when it is cached.

**Comment by benfurber** [comment]
Are you still looking at this @tuliobluz ?

**Comment by tuliobluz** [comment]
@benfurber I am going to look at this now.

**Comment by tuliobluz** [comment]
Every time that `setup_repo` is used on the pipeline, it installs cypress and takes about 40 seconds more to install.

Jobs that run it:

1. lint
2. test_security_rules
3. setup
4. test_functions
5. test_functions_upload_coverage
6. test_unit
7. test_circular_dependency
8. build
9. storybook
10. deploy
11. test_e2e
12. chromatic

I am trying to find a way to cache the cypress. It seems that [orbs](https://docs.cypress.io/guides/continuous-integration/circleci) is the best approach, but we have to find out its impact.
