### ISSUE TITLE
[bug] un-necessary browser pop-up warning about unsaved changes when submiting(?)/saving(?) research article

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3712]
Feel free to enhance this ticket with more details. Approximate recreation steps are given in the Discord discussion.

![Misdirection](https://github.com/ONEARMY/community-platform/assets/4391884/e4151832-3f3f-4551-81c0-d712968f1035)

source: https://discord.com/channels/586676777334865928/1256336177305485412/1256368742481395722

**Comment by kristiyanyanchev** [comment]
I can take this one

**Comment by mariojsnunes** [comment]
Check if this is still happening, the confirmation modal was refactored recently here https://github.com/ONEARMY/community-platform/pull/3761
