### ISSUE TITLE
[feature request] Get more direct user feedback

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3716]
From @davehakkens:

Thinking of changing the current 'chat button' to 'Feedback button' 
* Less traffic going to Discord (good for questions module)
* We can gather more feedback from users (knowing that our tests don't catch everything)
* We have a steady dev and mod team to implement (didn't have this before)
* Still need to figure out how the filtering goes.

From:
![image](https://github.com/ONEARMY/community-platform/assets/16688508/66c27c81-840c-4fa1-88a9-d7769bc543a9)

To:
![image](https://github.com/ONEARMY/community-platform/assets/16688508/afc6a3d9-bef8-4c59-b2c9-39d4167a390e)

**Comment by pizzaisdavid** [comment]
..Where does the button go?

I would prefer the text "Report problem"
