### ISSUE TITLE
Each time I push to my fork (while contributing) get a notificatin that Run Chromatic failed.

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3723]
As a developer, the notifications on GitHub should be actionable.

https://github.com/pizzaisdavid/community-platform/actions/runs/9747558072/job/26900538140

I have a fork in order to contribute to the project, but when I push, the pipeline fails because I have no environment variable. I am probably never gonna set that environment variable.

**Comment by pizzaisdavid** [comment]
I found this https://github.com/ONEARMY/community-platform/blob/master/.github/workflows/chromatic.yml maybe on merge or something would be better?

**Comment by benfurber** [comment]
I think I closed this in #3769
