### ISSUE TITLE
[feature request] Remove beta-wrapper for 'Pay what you can' feature

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3726]
It's time to release the '[Pay what you can](https://github.com/ONEARMY/community-platform/pull/3493)' feature.
Currently its only visible for beta-tester as its behind the auth-wrapper.

This needs to be removed so it's available for everyone.

NOTE: Create the PR but don't merge yet. We will send an email to the creators at the same time
![afbeelding](https://github.com/ONEARMY/community-platform/assets/13672737/aa1cb40f-a5c9-4038-ae60-ea619aa70a20)

**Comment by davehakkens** [comment]
> Hi @davehakkens 
> 
> I'm looking for a good first issue to contribute to, and this one seems available.
> 
> Could you assign it to me?
> 
> 
> 
> Thanks :)

Sounds good! We were planning to release this next week. Are you up for it before that time?

**Comment by leoasimon** [comment]
Hi @davehakkens 
When next week?
I can start working on it now for about 1h and continue on Monday if I'm not done today

**Comment by davehakkens** [comment]
We could aim for mon-tuesday?

**Comment by leoasimon** [comment]
> We could aim for mon-tuesday?

Yes that works!

**Comment by leoasimon** [comment]
Hi @davehakkens 
By "available for everyone," do you mean:
- Available for anyone logged in, whether they are beta testers or not
- Available to anyone, logged in or not

**Comment by davehakkens** [comment]
@leoasimon  It should be easy since all the functionality is already there.

There is a beta-tester 'authwrapper' around this component.
(To make it visible only for people with that role)
Removing this authwrapper makes it visible for everyone in the way we want in.

**Comment by leoasimon** [comment]
> @leoasimon It should be easy since all the functionality is already there.
> 
> There is a beta-tester 'authwrapper' around this component. (To make it visible only for people with that role) Removing this authwrapper makes it visible for everyone in the way we want in.

Yes I see how it works.
Is "everyone" = "Everyone logged in" or "Everyone, even people not logged in"
that's my question

**Comment by davehakkens** [comment]
Everyone should see the button. (with a tooltip login to download)
Everyone logged in is able to click and download

**Comment by davehakkens** [comment]
Also ready to release when its ready to merge! @benfurber 🔥
