### ISSUE TITLE
[bug] Saving a new Research Article Update as Draft triggers the webhook

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3740]
**To Reproduce**
Steps to reproduce the behaviour:

1. Start emulator backend.
2. Start frontend for emulator.
3. Login as precious plastic.
4. Edit the existing Research Article.
5. Create a new Update.
6. Create a title, description, and add a photo.
7. Press save as draft.
8. Check in the command line that the webhook was triggered.

Link to  emulator: https://github.com/ONEARMY/community-platform/blob/master/packages/documentation/docs/Backend%20Development/firebase-emulator.md#commands

**Expected behaviour**
The webhook should not be triggered.

Also, as Ben has pointed out in the comments, that if the article is a draft, it is currently also possible to trigger the webhook, which is bad mm'kay.

**Comment by pizzaisdavid** [comment]
When you fix this, it would be good to add a corresponding unit test, you can use this as a base: https://github.com/ONEARMY/community-platform/blob/0561978461d00b06a6c38f5f6b1983fa4931714f/functions/src/Integrations/firebase-discord.test.ts

**Comment by benfurber** [comment]
I can accidently confirm this problem. This is a draft update on a draft research article!

<img width="717" alt="Screenshot 2024-07-08 at 16 55 45" src="https://github.com/ONEARMY/community-platform/assets/16688508/c5725623-498e-434e-86af-855a1107e0de">

**Comment by pizzaisdavid** [comment]
@benfurber Good catch, I have updated the description.

Someone please consider adding the label Good First Issue. :)

**Comment by onim-at** [comment]
Hello! I'd like to work on this issue
Where should I see whether the webhook was triggered or not?
In my case the backend and frontend emulator don't show any log

<details><summary>Details</summary>
<p>
Backend cmd 

![image](https://github.com/user-attachments/assets/2a74ca80-06dd-4546-90d3-b3819232f9ec)

Frontend cmd

![image](https://github.com/user-attachments/assets/49d128d0-0591-4024-910f-b26d3440010d)


</p>
</details>

**Comment by pizzaisdavid** [comment]
Hello @onim-at, thanks for trying to take a look.

It is slightly hard to answer your question, because it is not 100% clear which commands you used.

But to answer your question. You should see it in the docker-compose terminal (the one you have labeled "Backend cmd")

Here is a video, where I re-create the bug, showing the webhook is triggered, using the latest master code and exactly what commands to run and what to do in the user interface:
https://www.youtube.com/watch?v=IqPDdR0cQjw

The documentation on the onearmy website is out-of-date (unfortunately) so best to look directly at the markdown documentation:
https://github.com/ONEARMY/community-platform/blob/master/packages/documentation/docs/Backend%20Development/firebase-emulator.md

**Comment by pizzaisdavid** [comment]
If anything is still unclear, please let me know. I realize now that the screen recording doesn't include mouse movements, which probably makes it even harder to understand.

**Comment by benfurber** [comment]
Thanks for picking this up @onim-at! Good luck.

**Comment by onim-at** [comment]
Hello @pizzaisdavid, thanks for the video explanation! 
Unfortunately I didn't manage to run correctly the firebase functions as the backend emulator throws a bunch of errors

I've synched my fork to the latest master branch commit and run the following commands

```
# on terminal 1
yarn install
yarn run frontend:for-emulated-backend:watch 
```

```
# on terminal 2
yarn run backend:emulator:watch
```

However the backend raises several error, some of which are `TS2307: Cannot find module 'oa-shared' or its corresponding type declarations` which I guess is the reason why my local environment is not running the firebase functions
I leave attached the backend logs in case someone knows how to fix them

[backend_logs.txt](https://github.com/user-attachments/files/16824048/backend_logs.txt)

On a more positive note, I've created a PR with to fix that should fix the issue but couldn't test it due to the mentioned errors

**Comment by pizzaisdavid** [comment]
About the error, off the top of my head, I'm not sure. Which is annoying, because the Docker/backend emulator is supposed to be something nice that works for everyone.

I have looked at your pr though.
