### ISSUE TITLE
[bug] Possible to upload an invalid image file

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3755]
**Describe the bug**
For research updates (and also certainly for every other instance of file upload), it's possible to upload an invalid image. Neither the field or form highlight that there's a problem and allow the form to be submitted.

By invalid I mean a file type which won't render (e.g. HEIC) or a file with a JPG/PNG extension that (for whatever reason) rendering.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a research topic.
3. Create a research update.
4. Add a 'wrong' image'.
6. See that it shows an empty space where the image should render.
7. Submit the form with the invalid image
8. See that empty space rendering on the research page.

**Expected behaviour**
The file shouldn't upload in the first place!

**Screenshots**
<img width="973" alt="empty-image" src="https://github.com/ONEARMY/community-platform/assets/16688508/1bd84d09-4058-4f69-8a2d-faa75c1dc892">
(At time of writting) [update 8](https://community.preciousplastic.com/research/converting-a-small-milling-machine-to-cnc-for-molds-making)

<img width="1463" alt="empty-2" src="https://github.com/ONEARMY/community-platform/assets/16688508/8e151ad1-7c1c-4f22-ab17-12432e849b3e">

**Additional context**
1. Could be related to the Compressor plugin added to Uppy last month.
2. Unit and feature tests should be updated.

**Comment by benfurber** [comment]
Maybe worth implementing a [package like this one](https://www.npmjs.com/package/image-validator)

**Comment by iSCJT** [comment]
> Maybe worth implementing a [package like this one](https://www.npmjs.com/package/image-validator)

thanks Ben, will take a look.  Seems HEIC file rendering is browser specific, Safari works fine but everything else not.

**Comment by benfurber** [comment]
@iSCJT We contacted the user and asked them to upload the image to https://onlinejpgtools.com/verify-if-image-is-jpg to see what was going on. Maybe worth linking to that in the error message?

**Comment by iSCJT** [comment]
@benfurber not been able to get online as much as I thought but I've worked out all the bits I want to do (and how) offline.  Going to incorporate image compression and cropping etc as well (i'll do them as separate pr's).  Should have pr's up in the next couple of days.
