### ISSUE TITLE
[e2e] Discussion being tested three times

### ISSUE THREAD

**Issue by tuliobluz** [ONEARMY/community-platform#3766]
**Is your feature request related to a problem? Please describe.**

The **discussion** functionality is shared by **HowTo, Question, and Research**, with that, there are e2e to all those 3 features. So, the same functionality is being tested three times. I did not see any big difference among the assertions.

**Describe the solution you'd like**

The solution is the discussion functionality should be covered by only one spec e2e. Then, we avoid duplicated code, reduce the e2e total run time, and it would be easy to maintain. 

You can also check if the discussion is displayed on the other pages.

**Describe alternatives you've considered**

If it is **indispensable** to test discussion for the 3 pages, we can do a refactor creating `commandsUi` to be shared among the 3 specs files. Then, we avoid duplicated code and it would be easy to maintain.

**Comment by benfurber** [comment]
While the user action is currently identical across the three document types, the following is different:
- the templating with business logic
- the side effects through the discussion store
- some outputs have their own independent business logic

(This is especially true of research compared to the other two.) So without the seperate specs, it would be very easy to create regressions.

I agree the code is repeative though, so I like the idea of a command ui or two.

**Comment by mariojsnunes** [comment]
> - the templating with business logic
> - the side effects through the discussion store
> - some outputs have their own independent business logic

Would it be possible to reduce/eliminate those differences?

**Comment by tuliobluz** [comment]
Another alternative to cover the Business is using [API testing](https://learn.cypress.io/advanced-cypress-concepts/integration-and-api-tests) via Cypress. 

Approach:

- One spec covering the UI functionalities of **discussion**
- Two new API specs to cover the business.

**Comment by benfurber** [comment]
Well there isn't currently an API to test. :) 

Start with the `commandsUi` and go from there?

**Comment by tuliobluz** [comment]
That is true, I forgot about the API

What we can also do is remove some step

Example of `Research` and `Questions` to be removed:

- Can create their own comment
- Can edit their own comment
- Can delete their own comment
- Can edit their reply

Then we leave the follow steps 

- Can add reply
- Can delete their reply'
- Comment generated a notification for primary research author
- Comment generated a notification for update collaborators
- Reply generated a notification for comment parent

And for `howTo` we leave all the steps to make the full test of the functionality

**Comment by benfurber** [comment]
Let's go with 1 please.

**Comment by benfurber** [comment]
There's also some missing coverage on research discussions which meant #3778 slipped through. Should hide the comments after deletion and check the button text has the right comment count.

**Comment by tuliobluz** [comment]
@benfurber I created a PR for the first solutions and also added assertions to check the comment count.

**Comment by tuliobluz** [comment]
Closing the issue as it was merged
