### ISSUE TITLE
[bug] Dev sites indexed by search

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3777]
**Describe the bug**
A user has reported that our dev sites are findable on google. I wasn't able to quickly confirm this but I was able to quickly check that `https://dev.community.projectkamp.com/` doesn't have [a meta tag to request that robots don't index](https://developers.google.com/search/docs/crawling-indexing/block-indexing). e.g. `<meta name="robots" content="noindex, nofollow">`

**Expected behaviour**
During build, probably in `postBuild.ts`, a meta tag is added when the build isn't a prod release. The env variable `REACT_APP_BRANCH` can probably be used.

The builds that shouldn't be indexed: 
* dev.onearmy.world
* dev.community.projectkamp.com
* dev.onearmy.world

The builds that should be indexed:
* community.preciousplastic.com
* community.projectkamp.com
* community.fixing.fashion

**Comment by pizzaisdavid** [comment]
If you search google with "site:dev.community.projectkamp.com" it restricts to that site only.

https://www.google.com/search?q=site%3Adev.community.projectkamp.com&sca_esv=cc40cfa443a9a9e9&sxsrf=ADLYWIKI6UCxQLu3dA9-5R9JK-QE4jvpww%3A1721731762791&ei=soqfZv_3L66Wxc8P6q_CwQU&ved=0ahUKEwj_mPrQ_ryHAxUuS_EDHeqXMFgQ4dUDCA8&uact=5&oq=site%3Adev.community.projectkamp.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiInNpdGU6ZGV2LmNvbW11bml0eS5wcm9qZWN0a2FtcC5jb21I-BNQtwlY6w5wAXgAkAEAmAFtoAHXAqoBAzMuMbgBA8gBAPgBAZgCAKACAJgDAIgGAZIHAKAH1wI&sclient=gws-wiz-serp

**Comment by pizzaisdavid** [comment]
There is a good amount of results for site:dev.onearmy.world, though
