### ISSUE TITLE
feat: add map list card view for mobile

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3853]
### Description

Currently, the new map uses the same `CardListItem` for `CardList` across all viewports. These cards are a little too chunky for mobile.

### Mockup

This is how the map pin card is designed for desktop:
![image](https://github.com/user-attachments/assets/cea82f6d-8b8d-4b09-9c4a-8faaeafe1db1)

And this is how we want it to look for mobile:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/060800fe-bd0b-44fb-a520-f00b233e4015">

So we want it to stretch on full width of the screen. Ideally we want a roll up animation so that the card slides from the bottom. As you can see the buttons of the map move up as well. 

### Build suggestion

* The component that needs the extra UI is probably `CardProfile`
* `CardList` is called in `MapWithListHeader`, this component is already given a `viewport` prop. I'd pass this prop down to `CardProfile`.

**Comment by dalibormrska** [comment]
Hey Ben! What do you exactly mean with this issue? Can you specify the problem to me a bit more? I tested it on mobile and the cards look good to me.

**Comment by benfurber** [comment]
@dalibormrska You've sketch file use to have a different display for mobile, no?

**Comment by dalibormrska** [comment]
Ahh I see, you mean the map pin card. Alright, description added.

**Comment by benfurber** [comment]
@dalibormrska I mean this: 
<img width="284" alt="Screenshot 2024-09-24 at 13 11 19" src="https://github.com/user-attachments/assets/a4f775ac-357b-4618-9429-89cf14e97681">

**Comment by benfurber** [comment]
Discussed elsewhere. Happy with the current responsive implementation
