### ISSUE TITLE
[feature request] Add an icon to the search bar component

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3857]
**Is your feature request related to a problem? Please describe.**
The search box currently has no clear indication that it is a search box apart from the placeholder text. It might take more time for users to recognise that it is a search box. It is a standard UI design practice to have the search icon, users are used to that.

**Describe the solution you'd like**

<img width="481" alt="image" src="https://github.com/user-attachments/assets/04a2e559-18ee-4345-8d69-d433e7ac136f">

I would be advocating here for having a search icon on the right side of the input field for easier recognition. Nowadays it is not needed to have a separate button beside, but the icon would be a great help, should be clickable, but not a must (in edge cases for example on mobile after you type and the keyboard gets buggy and does not open, it is good for the user to have the option to run the search with the button).

I don't know if the search icon is present in the codebase, I saw one in the design documentation, but it is too thick. Look at how other icons look and how are they implemented, especially the one for password input (which is quite awfully off-centered). Find a suitable icon, try to keep the size of the icon that you pick consistent with the others, eventually all of them will need a design rework later on.  
<img width="582" alt="image" src="https://github.com/user-attachments/assets/d73e3664-8610-4d6e-86d0-75c3618e4c91">

Then this updated search component should be present in all the places where it is used (How-Tos, Research, Questions, Old map, New map).

Think about edge cases... When the icon touches the text for example...
<img width="506" alt="image" src="https://github.com/user-attachments/assets/8bffa898-7aee-472e-9ec5-741f8cb25418">

**Describe alternatives you've considered**
If you are up for deepdive into the input components and how they are used across, from a design and structure point of view, I really like the [solution such as this](https://mui.com/base-ui/react-input/) of having one input component where you can turn on the prefix or suffix and change them. So that there can be the icon of an eye for password inputs and search icon for search box. I would not touch the textarea though, since there is another feature being worked on involving textarea adjustments. 

**Additional context**
<img width="921" alt="image" src="https://github.com/user-attachments/assets/44774b4c-9724-468b-bfbb-3d8cc2ea682a">

**Comment by kk7188048** [comment]
can you suggest me how to see this issue?

**Comment by benfurber** [comment]
Hi @kk7188048, welcome! Can you say more about the guidance you're looking for?

**Comment by LahuenGR** [comment]
Hello hey hi! First timmer here, working on this issue <3
