### ISSUE TITLE
Drop non-"forDonationRequest" file downloads 

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3858]
### Description

For research articles we setup an experiment asking users to make a small donation when downloading a file. It's gone well. So now we're ready to release the feature for all file downloads. 

### Build suggestion

See `DownloadWithDonationAsk`. Most of that can now be moved to the component library. Every use of `DownloadStaticFile` should now have the same implementation.

**Comment by mchen10** [comment]
Hey! Have a PR on my local for this; would love to get the code on a working branch to get some comments and eyes.

**Comment by benfurber** [comment]
Welcome @mchen10, have you setup a [fork of the repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)? Then you can submit a PR from a branch of your fork to the main repo.
