### ISSUE TITLE
[idea] HacktoberFest - proposal to open issues for contribution

### ISSUE THREAD

**Issue by yodur2potassium** [ONEARMY/community-platform#3864]
Hi there !
I'm following your videos on YT and saw that you were looking for contributors and as HacktoberFest 2024 is starting soon, I thought that you may want to open issues to open source contributions during that time.
If I'm not mistaken you just need to tag issues with ":hacktoberfest:" and you should show up here : https://github.com/topics/hacktoberfest
Don't know if it fits the values of PK but I think it's a good way to get exposition and enrol new people on a project.

I'll look if I can contribute to anything but not too sharp on frontend and Javascript 😄 

Keep up the good work ! 💪 

Jérémy

**Comment by benfurber** [comment]
Thanks @yodur2potassium, will do.
