### ISSUE TITLE
Add donation request to Project Kamp Community

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3870]
## Component infos
We've been testing the "donate what you can" feature on Precious Plastic how-to's and will extend it to research on Project Kamp. (related to this issue https://github.com/ONEARMY/community-platform/issues/3858 )

### What to do

Change the text, image, and embed code so it's ready for Project Kamp.

### Assets

**The text:**

> Support our work
> All of the content here is free. Your donation supports this library of Open Source research and development. Making it possible for everyone in the world to use it.
> Thank you for helping to make this possible

**The embed code for the widget:**
`<script src="https://donorbox.org/widget.js" paypalExpress="false"></script><iframe src="https://donorbox.org/embed/community-platform?language=en" name="donorbox" allowpaymentrequest="allowpaymentrequest" seamless="seamless" frameborder="0" scrolling="no" height="900px" width="100%" style="max-width: 500px; min-width: 250px; max-height:none!important" allow="payment"></iframe>`

**The image:**
![Project-Kamp-Support](https://github.com/user-attachments/assets/56b2e102-5e31-4152-9944-2215f59dd38e)

### Mockup Example

This is the one we currently have for Precious Plastic
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/5101e805-39cf-4326-b05e-7fdd5ad438d6">

**Comment by mchen10** [comment]
Happy to take on this work! Have an open PR for the issue you tagged 🙂

**Comment by davehakkens** [comment]
Great! Go for it :)

**Comment by davehakkens** [comment]
How is this going @mchen10 Would love to have this running for Project Kamp!

**Comment by mchen10** [comment]
> How is this going @mchen10 Would love to have this running for Project Kamp!

Hey sorry for the delay! Will share some updates by EOW

**Comment by benfurber** [comment]
Sorry @mchen10, I didn't really think about it when I assigned this to you. To get this working is just setting some env variables on ci so you can't do this!

**Comment by benfurber** [comment]
@davehakkens FYI this is a preview from my local branch.
<img width="1035" alt="Screenshot 2024-10-22 at 16 47 56" src="https://github.com/user-attachments/assets/2b686669-a529-49f4-9a28-cd0731b7a4c4">

**Comment by davehakkens** [comment]
Niceee

**Comment by benfurber** [comment]
Now that #3869 has been released, I've confirmed this is working on prod.

<img width="1204" alt="Screenshot 2024-10-22 at 17 39 08" src="https://github.com/user-attachments/assets/31e80a81-cf32-4372-bef6-244f85764d50">

**Comment by mchen10** [comment]
Ah, thanks @benfurber ! Yea I took a brief look and was pretty confused.
