### ISSUE TITLE
feat: hide profile contribution and impact tabs when empty

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3871]
<img width="665" alt="Screenshot 2024-09-30 at 13 56 39" src="https://github.com/user-attachments/assets/d592adcb-807b-4a5a-acf2-d7b970d9d051">

`SpaceProfile` should only show the contribution or impact tabs when there's contributions to show!

Please update the feature tests to cover this. For the impact tab, a step can be added to the existing impact feature test. 
For the contributions tab, the research creation spec can be updated.

**Comment by davehakkens** [comment]
yes please. I would suggest the same for 'impact'

**Comment by benfurber** [comment]
Hey @akshay0712-dev, looks like @Shalankwa already dived in with a PR! Did any other issue take your interest? Say hi on discord if not and we can talk.

**Comment by Shalankwa** [comment]
@akshay0712-dev my apologies! I wasn't aware you may have already started this.
