### ISSUE TITLE
feat: update design of zoom controls on new map

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3872]
![PP Map Final](https://github.com/user-attachments/assets/f4adf512-188b-4890-aac3-c62e2d40e753)

The zoom controls for the new map (`<MapWithList />`) are currently the default design. 

Please update them with the design above. (Though leave them on the top left).

We use an old version of leaflet for the map.

**Comment by JoseAConcepcion** [comment]
Hello there! I'm new, I could work on this.

**Comment by benfurber** [comment]
Welcome @JoseAConcepcion! The issue is yours! Please shout if you have any questions.
