### ISSUE TITLE
fix: linter should error if describe.only() or it.only() is present

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3873]
<img width="807" alt="Screenshot 2024-09-30 at 14 46 59" src="https://github.com/user-attachments/assets/3699fe24-cf48-467e-8660-335971a62998">

Multiple times over the last few months I've added describe.only() or it.only() to only run specific tests on a spec. ...And then accidently merged them in!

The linting rules should be updated to ensure that can't happen!

**Comment by mchen10** [comment]
Opened a PR here: https://github.com/ONEARMY/community-platform/pull/3911!
