### ISSUE TITLE
UI update for the Questions Module

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3900]
### Description

We want to change the UI for the questions page to reduce unnecessary space. 
It's part of the overal design goals of trying to have a different visual impact per module
- How-to: Visual space high
- Research: Visual space medium
- Question: Visual space low

### Page related

 [Questions module](https://community.preciousplastic.com/questions)
(Get the module up to a good standard and Project Kamp will use it!)

### Mockup

**What it should look like**
<img width="1726" alt="Screenshot 2024-07-15 at 01 00 41" src="https://github.com/user-attachments/assets/80a5a00d-3d67-4f97-a40f-97f85e076735">

**What it looks like now**
<img width="1664" alt="image" src="https://github.com/user-attachments/assets/0162c0fb-2859-4a8a-85ec-ef4595f8a1af">

**Comment by jaykayudo** [comment]
Hello @davehakkens i will like to handle this if possible. I am new here

**Comment by jaykayudo** [comment]
Thank you :)

**Comment by jaykayudo** [comment]
@benfurber  could you please point me to where i can find the styles for the question list item card
