### ISSUE TITLE
[bug] When editing a howto in draft, button displays wrong text

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3910]
**Describe the bug**
![image](https://github.com/user-attachments/assets/a33aaec8-97f8-435f-8127-17d25361e8ba)
Button shows "Revert to Draft" even though it is already a draft.

**To Reproduce**

1. Save a howto as draft
2. Refresh the edit page

**Expected behaviour**
Should still display "Save as Draft"

**Comment by mchen10** [comment]
Hey! Happy to take this. 

Right now, it seems like we only display "Revert to draft" when the form status is in "draft" mode. Once we fix this bug, then we will never display "Revert to draft". Is that expected? 

We also have the same bug on the Research forms: https://github.com/mchen10/community-platform/blob/master/src/pages/Research/Content/Common/Research.form.tsx#L110. Assuming we want to fix there as well?

**Comment by mchen10** [comment]
Does it make sense to just get rid of "Revert to draft"? It feels it would make sense for us to allow reverting to draft for something that's in AWAITING_MODERATION or IMPROVEMENTS_NEEDED state, but it doesn't read like the BE is hooked up to support that.
