### ISSUE TITLE
[Tech] Create API for questions search

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3917]
**Is your feature request related to a problem? Please describe.**
Move our current questions search capability to an API using Remix routing.
Create a Remix loader in a api.questions.ts route.

**Additional context**
This is part of the effort to decouple the firebase search from the client.
And make it easier for a Supabase migration and improve codebase maintainability.

**Comment by onim-at** [comment]
Hello! I'd like to work on this issue

**Comment by mariojsnunes** [comment]
Awesome! It's yours, if you need any help chat me on discod :)
