### ISSUE TITLE
Document full system architecture

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#393]
As mentioned in #328, it's a bit confusing for seasoned devs and newcomers alike to understand the full platform architecture unless already quite familiar with the stack. Probably a good excuse to play around with cloudcraft. If anyone feels like they have a good understanding of the full platform they are welcome to take this on, otherwise happy to do it myself when I can find the time.

**Comment by tx4x** [comment]
maybe some on-boarding videos would do the job. doing good docs takes an insane amount of time. worsening is that those docs become obsolete  often in no time.

with a onboarding video you just need to show where is what, on case to case base. i think most confusing comes with mobx/firebase and cloud functions (which unnecessary bloat to me but ok), if you can point out how to add new fields, cloud functions, etc.. i think most newbies are good to start :-)

you could even make monthly zoom sessions so people can ask right away :-)

**Comment by chrismclarke** [comment]
Yeah I can imagine things getting quickly obsolete but hopefully if done well we could keep maintenance to a minimum. I'll put this on my personal roadmap for next month. I'm hoping in time we can add better middle-layers to make choice of database, server-functions and auth system a bit more flexible, particularly as I really don't like some of the very custom syntax (like firestore's timestamps). I've been finding myself manually explaining a lot to lots of different people which really isn't very sustainable so hope some improvements can be made.

I hadn't thought about a monthly zoom, interesting idea. Right now best means of communication for quick response from me at least seems to be slack (as git conversations grow it's getting harder to keep track of everything), but I can see why not everyone might want to jump in the main slack channel. Discord could be another option more specifically for platform dev if the number of people keeps growing.

**Comment by chrismclarke** [comment]
Closing as not really doable as a single issue (!) (and slow progress being made on documentation)
