### ISSUE TITLE
Add automatic deployment for design storybook

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#394]
Should add build and deploy scripts to let the design storybook be available. Easiest way is probably to host on github pages:

https://storybook.js.org/docs/basics/exporting-storybook/
https://github.com/storybooks/storybook-deployer
https://docs.travis-ci.com/user/deployment/pages/

Once deployment sorted can add a custom domain to make more easily accessible

Note, this will probably need to be done by a project admin as will need to configure environment variables

**Comment by BenGamma** [comment]
Yes github.io deployments seems a good option, and we will not need a subdomain but a url path in that case.

We could do */ui* or */design-system*

**Comment by chrismclarke** [comment]
I'm not sure how easy it will be to direct a url path to a different domain, if possible to do with a subdomain once deployed onto github pages that would be a lot easier to setup. Personally I like the sound of design.onearmy.world

Do you want to try and handle the github pages deploy? Otherwise add a `help-wanted` label and there might be somebody who has done this before (otherwise I'm happy to look at it when I next have free time, although that's not likely to be until week of March 25th).

**Comment by BenGamma** [comment]
In the first place we need to add more components to the storybook.

Then I'll do it no problem, that's something I wanted to dive in.

**Comment by chrismclarke** [comment]
@caiokf - is this something you would be interested in looking into?

**Comment by thisislawatts** [comment]
@chrismclarke do you think this is still valuable? The storybook system doesn't seem to be very well adopted by the current set of contributors. That could be exactly _because_ we are missing this public site **or** simply because for a project of this size it is not necessary. What do you think?

**Comment by thisislawatts** [comment]
Now deployed as part of the build process:
https://onearmy.github.io/community-platform/storybook-static/index.html
