### ISSUE TITLE
Change favicon.ico

### ISSUE THREAD

**Issue by guilhae** [ONEARMY/community-platform#3980]
Not an expert at this, but i've noticed the favicon for the Project Kamp Community Platform is still precious plastic one:
https://community.projectkamp.com/favicon.ico
![image](https://github.com/user-attachments/assets/653b6793-af02-4f3a-aa71-72f168a83775)

Would be nice to be Project Kamp logo :)

**Comment by mariojsnunes** [comment]
Good catch!

Currently it is being overridden by the actual PK favicon below:
<img width="572" alt="image" src="https://github.com/user-attachments/assets/e7eb3f67-ae14-42ee-854e-776c92f025bf">

So it isn't a big issue. But would be nice to clean it up.

**Comment by mariojsnunes** [comment]
alright, I'll look into it
