### ISSUE TITLE
[feature request] Change name 'how-to' to 'library'

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3989]
**Is your feature request related to a problem? Please describe.**
Throughout the years how-to's have evolved into much more then guides as it also shares 3D models and files to download.
it's finally time for the change

**Describe the solution you'd like**
We want to change the name from 'how-to' 'to Library" so it represents better what it is. 
And we call items inside the library 'projects'

**Describe alternatives you've considered**
More about it in this discussion https://github.com/ONEARMY/community-platform/discussions/3241

# **Changes we need:**
### **Navbar**
<img width="360" alt="Screenshot 2024-08-26 at 09 56 42" src="https://github.com/user-attachments/assets/f8764844-9a5f-463f-8fb7-53088038a225">

### **Create button**
<img width="359" alt="Screenshot 2024-08-26 at 09 56 46" src="https://github.com/user-attachments/assets/f1e4b5c2-269a-4e5e-8b16-a2cd9955d7dd">

### **Search bar**
<img width="345" alt="Screenshot 2024-08-26 at 09 56 48" src="https://github.com/user-attachments/assets/65e439d0-913c-422e-8b1e-466f9b093465">

### **Footer**
Contribute to the Precious Plastic Library, Share your project
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/71c0d169-f6d6-488e-b2be-55c34b208282">

### **Create a howto**
- Add a project
- Title of your project
- 4 . Create your project
https://community.preciousplastic.com/how-to/create
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/d128904c-b9cf-4330-8cb2-e75dc8d93b72">

### **Profiles**
- Projects in Library
- Library
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/a57cb9f9-71cd-4526-a268-4340df49da9d">
<img width="856" alt="image" src="https://github.com/user-attachments/assets/c5e2e874-618a-42cd-994a-3307ca3cba4c">

### ⚠️ Important
Make sure that all existing urls continue to work and are redirected accordingly

**Comment by benfurber** [comment]
I thinking about initially doing just routing and user label changes. Then the DB migration later on can take care of renaming everything in the system. What do you think @mariojsnunes?

**Comment by benfurber** [comment]
@davehakkens The academy guides will need updating too.

**Comment by benfurber** [comment]
There's a bunch of props here and there that probably don't need to be 'howto' or 'project' - 'item' would be fine.

**Comment by mariojsnunes** [comment]
> I thinking about initially doing just routing and user label changes. Then the DB migration later on can take care of renaming everything in the system. What do you think @mariojsnunes?

agreed

**Comment by davehakkens** [comment]
> @davehakkens The academy guides will need updating too.

yes PP team has a list of things to change. We need to sync up to release

**Comment by benfurber** [comment]
@davehakkens Maybe more effective for me to change the guide text as it's all markdown?

**Comment by davehakkens** [comment]
> @davehakkens Maybe more effective for me to change the guide text as it's all markdown?

Yeh could be for some things in the Academy! But still best to align with the PP team.
They made a document mapping out all the areas for change.
