### ISSUE TITLE
[Tech] Create API for fetching comments

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3992]
**Is your feature request related to a problem? Please describe.**
Create an API using Remix routing.
Should be done by creating the **loader** routes:
- api.discussions.$sourceId.ts 

**Additional context**
This is part of the effort to decouple the firebase from the client to make it easier for a Supabase migration.
And also improve codebase maintainability.

**Comment by benfurber** [comment]
@mariojsnunes This still applicable?

**Comment by mariojsnunes** [comment]
forgot to close, thanks
