### ISSUE TITLE
add text & heading component to storybook

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#437]
Write story for text and heading component.

An example can be found in [button component](https://github.com/OneArmyWorld/onearmy/blob/master/src/components/Button/button.stories.tsx)

**Comment by tanvirraj** [comment]
@BenGamma, I want to do this

**Comment by BenGamma** [comment]
Yes just do it ! Again let me know, to avoid two people working on the same thing. Thanks !

**Comment by tanvirraj** [comment]
start working

**Comment by tanvirraj** [comment]
when i run `yarn storybook` i get this error, can't start storybook 
any idea ?
<img width="1427" alt="Screen Shot 2019-05-07 at 7 33 16 PM" src="https://user-images.githubusercontent.com/3768120/57303392-0ab33980-70ff-11e9-950e-085610f9a031.png">

**Comment by BenGamma** [comment]
Looks like there is an issue with storybook 5.0.0 https://github.com/storybooks/storybook/issues/6306

If you can have a look that would be nice :)

**Comment by tanvirraj** [comment]
i will look into it.

**Comment by jparadasb** [comment]
Hello! is someone working on this issue? I took a look at this and was fixed after upgrading storybook to `5.2.1` and changing the webpack.conf as the migration guideline says [https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecate-webpack-extend-mode](url)

> @BenGamma
> when i run `yarn storybook` i get this error, can't start storybook
> any idea ?
> <img alt="Screen Shot 2019-05-07 at 7 33 16 PM" width="1427" src="https://user-images.githubusercontent.com/3768120/57303392-0ab33980-70ff-11e9-950e-085610f9a031.png">

**Comment by BenGamma** [comment]
Oh cool ! No feel free to fix it !

**Comment by chrismclarke** [comment]
closed by #618
