### ISSUE TITLE
[enhancement] - Update user avatar methods

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#448]
**Is your feature request related to a problem? Please describe.**
During user module rewrite most avatar-related methods became deprecated and need to be put back in (to match improved workflows and conventions).  Will try get it done this week.

**Comment by BenGamma** [comment]
@chrismclarke is this issue still to fix ? There was some work done on avatar component in #782, maybe that fixed the issue here ?

**Comment by chrismclarke** [comment]
Given that we're no longer using profile avatars (instead member pins) I'm guessing it's safe to close (can always revisit if we decide to put back in)
