### ISSUE TITLE
add auth to dev.onearmy.world

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#465]
Create an basic htaccess auth with user & psw to access dev.onearmy.world

**Comment by chrismclarke** [comment]
what's the purpose for this?

**Comment by BenGamma** [comment]
To keep the dev site for internal use, and we'll have the alpha.onearmy.world to deploy the release on a public url.

**Comment by chrismclarke** [comment]
That would mean creating another database and auth system which I am not keen to do. We need a site that anybody who wants to contribute to the project can easily use, this is the purpose of the staging site. For each URL we have to essentially define the database, entrypoint and access, we currently have

Staging DB - localhost dev or dev.onearmy.world live, for any developer
Production DB - beta.onearmy.world, to display the latest production (/tagged) release

If you want the dev site not to be exposed publicly we can take down or change the url, but I really don't see the harm in having it open for anyone who wants to use it. If you really wanted I could add a script that deletes content periodically to keep it a bit cleaner, but for now the usage is still really low.
