### ISSUE TITLE
Virtual Scroll Component

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#493]
### Description

When displaying large lists of data it would be more efficient to only render what is in the current viewport. Alternative would be to use infinite scroll to systematically query more data however this takes more of a technical implementation and doesn't hold much benefit (slightly smaller db requests but by no means significant, and could still be implemented on top)

### Page related

Will be used in :

- Events list (possibly also how-to)

### Example(s)

https://bvaughn.github.io/react-virtualized/#/components/List

### Build suggestion

Suggest using the package support by airbnb:
https://github.com/bvaughn/react-virtualized

**Comment by chrismclarke** [comment]
Update - still a good feature to have. Particularly as the current db and service worker strategy loads all  howtos and caches image on render. This means a default user loading the page will be loading all images, where might be more desirable to only cache those that show. Alternative would be pagination.

**Comment by tudi2d** [comment]
Hey. This sounds useful and interesting. I would like to tackle this by using https://github.com/bvaughn/react-window , as the creator mentioned that it is the optimized version of react-virtualized (smaller & faster).

**Comment by chrismclarke** [comment]
That would be awesome! Yeah I remember trying to do some work on it a while back with react virtualized but it had some problems (can't fully remember why, possibly needing exact row item heights and length in advance). But yeah the rewrite sounds like exactly what we need, great if you can test implementing it!

To start with I would suggest just trying to get it working for the list of howtos. Once working we can try to turn it into a more reusable component to use with events etc.

**Comment by chrismclarke** [comment]
Hi @tudi2d , just wondering if you've managed to make any progress on this? Would be great to get into the May release (aiming for Monday 25th May).

**Comment by tudi2d** [comment]
Hey. Thanks for reminding. No progress yet, I will hopefully find time tomorrow. I will keep you updated!
