### ISSUE TITLE
[optimisation] - code bundle sizes

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#504]
**Is your feature request related to a problem? Please describe.**
An npm script has been added to view bundle sizes (`npm run analyze`) using webpack-bundle-analyzer, and whilst still pretty small highlights some of the main offenders

**Describe the solution you'd like**
Find ways to remove, reduce or defer import of

- [ ] Firebase
- [x] Material-UI
- [ ] DevExpress
- [ ] ReactSelect
- [ ] Uppy
- [ ] React-pose

Some can likely be removed entirely if not used much (devexpress?, material-ui), others can hopefully be tree-shaken more (firebase, react-pose?), others can be deferred until actually needed (uppy, react-select)

A couple specific links for firebase (that also include tree-shaking and defer strategies):
https://codeburst.io/firebase-package-names-and-bundle-sizes-ec10cede63f1
https://davidea.st/articles/firebase-bundle-size

![image](https://user-images.githubusercontent.com/10515065/58914879-8cef4780-8717-11e9-8bff-cc24b2b04ec2.png)

**Comment by thisislawatts** [comment]
A PR here, which will remove material-ui
