### ISSUE TITLE
Migrate DB methods to use Dexie instead of firestore for caching

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#522]
Dexie provides a really useful wrapper around local indexeddb, and offers a more versatile solution for offline-first data approaches. The firestore cache can only be used with firestore methods, making it harder to migrate to other dbs in the future and doesn't support use with firebase realtime which is currently required for the map. 

In addition Dexie provides a nice query syntax which could be used throughout the site.

**Comment by BenGamma** [comment]
Is this closed with #540 ? @chrismclarke

**Comment by chrismclarke** [comment]
Ah yeah it does, will add the ref
