### ISSUE TITLE
[feature request] allow user to upload avatar picture

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#525]
**Is your feature request related to a problem? Please describe.**
For now you can only have a profile picture if you import your profile from DH website.

**Describe the solution you'd like**
Need to allow the user to upload his own Profile picture, even if he doesn't have a DH account.

**Comment by Andrux51** [comment]
@BenGamma @pmcp I'd like to take this on and do a bit of refactoring to the `ImageInput` component to make it a more generic uploader, with the idea that pages will implement it and style a button/etc around it.

What I currently see is that the image uploader is so closely tied to its style that trying to reuse it for Avatar uploading (or anywhere else on the site in the future) would be basically impossible without an overhaul.

The overhaul can be ready within a few days, let me know any thoughts you may have for me going in.

**Comment by chrismclarke** [comment]
Sounds great @Andrux51 , yes the original image input was designed only with the how-tos in mind so something more general could be of use. There is a separate `FileInput` component also which is built on top of [uppy](https://uppy.io/), but not sure if that would make things easier or harder - ideally we would want to keep the client-side image compression on upload, however there is an open pr that will remove the buttons seen on the `how-to` and just apply default settings.

The only other consideration I can think of is to ensure it still works within a form field (see https://github.com/OneArmyWorld/onearmy/blob/master/src/components/Form/ImageInput.field.tsx), it's only a single binding to the `onFilesChange` prop so as long as that isn't renamed should be fine.

**Comment by chrismclarke** [comment]
> however there is an open pr that

and.... that was you. So I'm guessing you're more than aware! :S

**Comment by Andrux51** [comment]
Perfect, I'll jump in and get going on my idea

**Comment by BenGamma** [comment]
Hi @Andrux51 👋 
Thanks for helping !
Is this moving forward ? Did you run into a problem that we could help to solve in any ways ?
Let us know, so we can organize the work on our side too 🤓 tks !

**Comment by Andrux51** [comment]
Thanks for checking in! I'm making progress on it, it's a bit more complicated than I thought at first, but I should be able to get a pull request up soon.

Hopefully I'm not blocking anything, but if so, please feel free to not wait on my work.

**Comment by BenGamma** [comment]
Ahah yes I see, we all went throught this path I think 😅 

Nope nothing blocking on our side, I'm planning the next release and wanted to catch up.
Thanks again for helping out !

**Comment by BenGamma** [comment]
Sorry @Andrux51 but we add to move on and we implement this in the [v0.7.0](https://github.com/ONEARMY/community-platform/releases/tag/v0.7.0)
Thanks for the effort putted and hopefully next time we'll manage to make it work for both of us !
