### ISSUE TITLE
[feature request] integrate captcha validation for content (how-to & events)

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#545]
**Is your feature request related to a problem? Please describe.**
To avoid massive spamming when the plateform will be release to a broader audience, we consider using captchas validation before submiting a how-to and an event.

**Describe the solution you'd like**
An easy, not too anoying validation captcha for users.

**Describe alternatives you've considered**
An hidden checkbox that if checked means that it's a robot ?
Or did someone have any recommendations to avoid spamming without captchas ?

**Additional context**
After a quick search, seems like there is two main ways to do this in react :
* Open source and self hosted using [BotDetect](https://github.com/captcha-com/reactjs-captcha) package. Seems a bit young and need to host a dedicated API endpoints BUT we have full control on what datas are going in and out.
* The [google recaptcha](https://developers.google.com/recaptcha/docs/v3) implemented in [react-google-recaptcha module](https://github.com/dozoisch/react-google-recaptcha) and [react-recaptcha module](https://github.com/appleboy/react-recaptcha). They seems way more used, stable and convinient for users BUT it's google 🙈 .

**Comment by chrismclarke** [comment]
Google captchaV3 is invisible at least, and widely used so could be a decent option

**Comment by davehakkens** [comment]
Not needed add this point. No spam yet :)
