### ISSUE TITLE
[feature request] how-to pdf export

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#546]
**Is your feature request related to a problem? Please describe.**
Allow users to access the content of the how-to anytime, even without internet connexion?

**Describe the solution you'd like**
Ability to export the how-to content into pdf files.

**Additional context**
Seems like [react-pdf](https://github.com/diegomura/react-pdf) would be the way to go

**Comment by davehakkens** [comment]
Not needed at this point
