### ISSUE TITLE
Update /u/<username> UI page

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#584]
Integration of the new mockup of the user profile page.

## Page infos
* Url : `/u/<username>`
* Path in codebase : `src/pages/User/Content/UserPage`

### Mockup
https://precious-plastic-community.webflow.io/u/user-profile

Note : use placeholder data for "Extrusion Workspace" eg workspace_type and image of the workspace_type. Also the badges and howto and events count can be placeholders data.

**Comment by drydenwilliams** [comment]
Estimate: 2d

**Comment by BenGamma** [comment]
done with #613
