### ISSUE TITLE
[feature request] - Zapier (or similar integrations)

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#588]
**Is your feature request related to a problem? Please describe.**
Unlikely to have notification/email system in place for launch so could provide a quick, reasonable way to improve knowledge of events on the platform. Zapier in particular already has configurations for firebase: https://zapier.com/app-directory/firebase/integrations/zapier

**Describe the solution you'd like**
Decide what are the main trigger events, and add to integration.

**Describe alternatives you've considered**
Building our own custom system (desirable but less quick), explore other options similar to zapier (e.g. ifttt, automate.io etc.)

**Additional context**
Mentioned by Dave so he's likely to have a good idea of the types of triggers/actions we might want

**Comment by davehakkens** [comment]
Good basic triggers would be
- New user registered 
- New How-to uploaded
- New event created 
- New pin on the map 

Optional triggers
- notification if how-to is edited

**Comment by BenGamma** [comment]
As I understand this in now done using GCloud functions to avoid Zapier limitation.
@davehakkens Do you know where the code of these functions will be ? Would be nice to save them in github. We could create a new repo for them under ONEARMY organization if needed

**Comment by davehakkens** [comment]
Yes currently I have them locally and stored in Firebase Functions. But it seems there are a few other Functions already there.` DHSite_login , DHSite_migrateAvatar , DHSite_getUser `Dont know where they are stored in Github @chrismclarke. But would be good to store them at the same place.

**Comment by BenGamma** [comment]
They are stored in [functions/src/DaveHakkensNL/index.tsx](https://github.com/ONEARMY/community-platform/blob/master/functions/src/DaveHakkensNL/index.ts).
I'll move this discussion to slack for an easier chat.
