### ISSUE TITLE
[feature request] - Add delete option for all user content (how-tos, events etc.)

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#589]
**Is your feature request related to a problem? Please describe.**
Recently added delete functionality to the database and enabled with user profile delete. Would be good to also integrate with the other common user interactions (e.g. how-tos, events etc.).

**Describe the solution you'd like**
Clear buttons and dialogs to allow the right users to be able to delete content.

**Describe alternatives you've considered**
Could possibly just 'archive' instead of delete (mark as deleted and not display, but retain content for future recovery). 

**Additional context**
We currently don't have much in the line of permission hierarchy, so assume same delete permissions as editing (i.e. content creators + admin)

**Comment by iSCJT** [comment]
Being implemented on #2438
