### ISSUE TITLE
How-to step should only allow 3 images to be uploaded [bug]

### ISSUE THREAD

**Issue by drydenwilliams** [ONEARMY/community-platform#593]
**Describe the bug**
When you create a new how-to, you should only be able to upload 3 images max. Currently you can upload as many as you want.

**To Reproduce**
1. Visit the `/how-to/create` route
2. Go to a step
3. Upload lots of images

**Expected behavior**
The upload should only upload the first three images.

**Screenshots**

<img width="788" alt="Screenshot 2019-09-25 at 17 33 31" src="https://user-images.githubusercontent.com/4403089/65616622-a6184e80-dfbb-11e9-804b-b4ee79df1ebb.png">

**Additional context**

**Comment by drydenwilliams** [comment]
Few questions about the UI & UX of this: 
- What should happen if the user uploads more than three images?

**Comment by mattia-io** [comment]
Hey @drydenwilliams 
Thanks for bringing this up. 

So, when the user uploads 3 images the dotted image upload box should disappear. Hence the user is not able to upload more than 3 pics. If he/she needs to replace one he/she would have to:
- delete one of the already uploaded images 
- Dotted image upload box reappears
- Upload a new image.  

Quickly paste together an example, let me know if not clear. 

![65616622-a6184e80-dfbb-11e9-804b-b4ee79df1ebb](https://user-images.githubusercontent.com/17761877/65696554-b68efe80-e079-11e9-8be9-76be143878b5.jpg)
