### ISSUE TITLE
[suggestion] moving from styled-component to emotion

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#596]
After rebass upgrade to v4 (#595), the lib use now by default [emotion](https://emotion.sh/docs/introduction) for styling.
Considering most of our component library is based on rebass, would make sens to align with them to insure the highest compatibility now and in the futur.

Also emotion seems to have a better developer experience and the size of the bundle is more than 10kb smaller, c.f. capture from [npm trends](https://www.npmtrends.com/styled-components-vs-emotion)
<img width="1110" alt="Capture d’écran 2019-09-26 à 15 08 53" src="https://user-images.githubusercontent.com/4993215/65690730-f4872500-e06f-11e9-9c99-baad59ede7ca.png">

**Comment by drydenwilliams** [comment]
Do you have an estimate to do the switch to emotion?

**Comment by BenGamma** [comment]
Still need to investigate a bit on the benefits to switch to emotion and how to integrate it with our codebase (current component library/storybook) but once this is done I would say a day should be enough.

**Comment by chrismclarke** [comment]
Before trying to assess the benefits of a new system, it would be good to identify pain-points/known limitations with the current system and look for solutions (which may/may not be another similar system). There's always going to be something newer and shinier, and easy to get lured into 'pro-information bias'.

**Comment by thisislawatts** [comment]
We've not actively worked towards this goal over the last 2 years and I have raised some a few PRs recently which address our use of rebass to ensure we explicitly load the `rebass/styled-components` variant for consistent styling.

I am going to close this issue out in the meantime. Please feel free to re-open with a comment that addresses @chrismclarke questions around indentifying _pain-points/known limitations with the current system_
