### ISSUE TITLE
Allow admin editing of tags

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#598]
**Describe the bug**
Some tags from the `v2_tags` collection are not displayed anymore in the tags selector in how-to section.
Needs investigate. May be linked to dexie cache db.
**To Reproduce**

* Open the tag selector in how-to list or how-to create/edit page
* check list of tags in firebase (you can order them by category to have a better overview)
* 16 tags are in the firebase, only 8 are shown in the selector

**Expected behavior**
All the tags should display in the selector

Note for later:
In the futur would be nice to have a better system to populate tags in the database (from the `/admin` ?)

**Comment by chrismclarke** [comment]
There's 16 tags in the DB but they are split between how-to and event tags, so only the 8 that are categorised as how-tos are shown.

e.g.:
![image](https://user-images.githubusercontent.com/10515065/67226923-04efad00-f42e-11e9-8545-37fbf2f385ae.png)

Agree it would be better to manage tags from another panel, suggest either renaming this issue or closing here and opening elsewhere
