### ISSUE TITLE
update filters on map

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#607]
Link the existing filters on the map with the profile v2 user models.

There is two filters that doesn't depend on each others :

* Filtering depending on the `profileType` field :
<img width="881" alt="Capture d’écran 2019-10-02 à 14 45 29" src="https://user-images.githubusercontent.com/4993215/66045107-512c8900-e523-11e9-8af2-ab70f9b97fc4.png">

* Filtering depending on the `workspaceType` field :
<img width="896" alt="Capture d’écran 2019-10-02 à 14 43 33" src="https://user-images.githubusercontent.com/4993215/66045016-23474480-e523-11e9-98ad-d7d83107bad4.png">

**Comment by drydenwilliams** [comment]
I think this has been taken over by @chrismclarke. Can you confirm please @chrismclarke?

**Comment by chrismclarke** [comment]
The filters are there and I made a few tweaks to how they work, although I'm not sure if I understand what the issue refers to exactly? Is it old work just to bring the filters in? Or something we need to update for them? Happy to do whatever, or close this issue if already done, so just let me know.

**Comment by BenGamma** [comment]
Yes it was old work. Closing now that map with filtering was release in [v0.8.0](https://github.com/ONEARMY/community-platform/releases/tag/v0.8.0)
