### ISSUE TITLE
Define browser matrix [feature request]

### ISSUE THREAD

**Issue by drydenwilliams** [ONEARMY/community-platform#611]
It would be great to know what browsers we are going to support e.g. 

- Chrome - v-x-x
- Firefox - v-x-x
- Safari
- Internet Explorer

Once we have done this we can explore any polyfills needed and also code for older versions if needed. 

I raise this as we have used `object-fit` which is not supported on IE11 and looking at these stats from Africa (https://gs.statcounter.com/os-market-share/all/africa) Windows the most common OS.

---

From @chrismclarke point: 

> I would suggest opening an issue to include defining the platforms we would like to support, and if possible good ways to help automate testing on them

**Comment by chrismclarke** [comment]
Whilst we're talking about this, it would be good to have some way of automating some of the tests on multiple browsers, even if only in a very basic way (current e2e testing only supports chrome/chromium/electron). I'm sure someone put some links for this somewhere at some point but I can't track them down

**Comment by chrismclarke** [comment]
Somewhat related, in the future we could try doing some additional automated testing with https://github.com/microsoft/playwright

Playwright is similar to google's puppeteer (automated chrome web browser for testing), but supports more browsers. Suggest we want to be testing:
- chrome
- firefox
- safari
- edge (although now just runs chromium)
And if possible variants such as desktop, mobile, and if possible incognito.

Example browser stats: https://browserl.ist/?q=%3E+1%25

**Comment by chrismclarke** [comment]
Update - cypress now also supports firefox and edge, so could be worth adding or including for a small subset of tests.
https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers
https://docs.cypress.io/guides/guides/cross-browser-testing.html#Continuous-Integration-Strategies

**Comment by chrismclarke** [comment]
Update - created PR #950 which adds firefox testing support. 

Going through various docs and forum issues, it does not appear that cypress will ever support incognito mode (it itself is a plugin which would therefore be disabled), so I think this is about as good as we can do.  It also is clear that it would be a huge undertaking to write our own test library to use with playwright on safari (which itself is still not very stable), so I don't think that could be considered reasonable. There is an open issue and discussion for supporting macOS Safari within cypress, so if that ever lands we can include, but for now I consider this issue closed.
