### ISSUE TITLE
[bug] Nothing happens clicking on "More Events"

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#616]
**Describe the bug**
At the end of the events list, there's the button "More Events" that doesn't do anything

**To Reproduce**

1. Go to https://community.preciousplastic.com/events
2. Scroll down to 'More Events' button
3. Click on the button
4. See error (nothing happens)

**Expected behavior**
If there are more events, then show more events at the bottom of the list
If there are no other events, then hide the button
Hide the button if there are no more events with the currently selected tags

**Comment by BenGamma** [comment]
We removed the more button for "create" button. Closing
