### ISSUE TITLE
[bug] "Back" button doesn't work

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#621]
**Describe the bug**
When I get to the end of an How-To article there's a "Back" button to go to the list page, but this button does nothing when I click on it.

**To Reproduce**

1. Go to https://community.preciousplastic.com/how-to/glue-hdpe--pp-with-2component-adhesives
2. Scroll down to the end of the article
4. Click on the "Back" button

**Expected behavior**
The button should bring the user to the list page.
NTH:
- Use browser history (rather than creating a new history entry)
- If user lands on the article page from a not-PP URL then link will direct to the list page creating a new browsing history entry.

**Screenshots**
<img width="396" alt="image" src="https://user-images.githubusercontent.com/940045/66310094-937f0d00-e90b-11e9-8012-5b8f949dcf5d.png">

**Comment by BenGamma** [comment]
Fixed in last release, see [production site](https://community.preciousplastic.com/)
