### ISSUE TITLE
[bug] can't preview image upload on safari

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#630]
**Describe the bug**
On safari, when uploading an image, the preview doesn't show the image the user wants to upload.

**To Reproduce**
using safari, try to upload an image either in youe user `/settings` or in the create how-to page.

**Expected behavior**
User should be able to preview the image your are about to upload.

**Screenshots**
After image selected :
<img width="336" alt="Capture d’écran 2019-10-08 à 16 20 00" src="https://user-images.githubusercontent.com/4993215/66403812-88011400-e9e7-11e9-9335-6777ac9d9889.png">

**Additional context**

**Comment by chrismclarke** [comment]
As a fix can I just give you a better web browser @BenGamma ? :p

I'm guessing this should also link with browser support (#611) and testing strategy.

**Comment by thisislawatts** [comment]
Unable to recreate in the latest version of Safari. 

![Screenshot 2021-11-23 at 15 57 56](https://user-images.githubusercontent.com/472589/143048050-353052fb-7b11-43aa-b40e-bb194015a357.jpg)
