### ISSUE TITLE
[feature request] send verification email to new users

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#632]
**Is your feature request related to a problem? Please describe.**
When user sign-up successfully, we prompt them a message to verify their account by clicking the link they just receive by email. But we don't send any email.

**Describe the solution you'd like**
Send the verification email to new user with unique link. Firebase provide a [custom mail handler](https://firebase.google.com/docs/auth/custom-email-handler)

**Additional context**
Non verified users can't create content.

**Comment by lauvrenn** [comment]
I'll give it a try 👌

**Comment by chrismclarke** [comment]
We don't?? We used to, I wonder what happened/changed. Firebase has it's own built in mail system that should be handling this (and we only need to update the template).

@lauvrenn , I think you might not be able to do this without access to the firebase console so I'd say probably wouldn't be the best use of your time to investigate. There are a number of other issues tagged `Good first issue` and `Help wanted` which may be better starting points

https://github.com/ONEARMY/community-platform/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+first+issue%22
