### ISSUE TITLE
[bug] Profile stats disappears for tablet view

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#633]
**Describe the bug**
The profile statistics box disappears for viewports between 640px-831px

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://dev.onearmy.world/u/davehakkens
2. Set browser width at 700px 

**Expected behaviour**
See expected here: https://one-army-community-platform.webflow.io/u/my-profile

**Screenshots**
<img width="671" alt="image" src="https://user-images.githubusercontent.com/940045/66464239-e7f6c980-ea7e-11e9-8d21-aa1f49eaa74b.png">

**Comment by chrismclarke** [comment]
Appears to be fixed, closing
