### ISSUE TITLE
Tags in /how-to are not shown on load

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#636]
**Describe the bug**
Open /how-to and no tag was shown for any how-to

**To Reproduce**
https://github.com/ONEARMY/community-platform/commit/6faefbcac756ab79a86f5b3abe9ba99bc2806bd4

**Expected behavior**
Tags are shown as the following
![image](https://user-images.githubusercontent.com/2813016/66536430-20fa7100-eb47-11e9-8e93-832492553fa9.png)

**Comment by lauvrenn** [comment]
I'll try to fix this one :hand:
