### ISSUE TITLE
Friendly messages for failed login

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#649]
**Describe the bug**
Error messages at the login screen were very technical and were not helpful.
![image](https://user-images.githubusercontent.com/2813016/66570847-99d5e900-eb98-11e9-8005-e7e76f6e6968.png)

**To Reproduce**
c44fab7268313e6099b4f875d10cee38695f0ba8

**Expected behavior**
There are 2 main scenarios:
- Wrong email + any password: then show **Incorrect email**
- Correct email + wrong password: then show **Incorrect password**

**Comment by chrismclarke** [comment]
If anyone wants to take this on, I don't have the exact text from the design team, but what could be nice is to include some sort of `DISPLAY_MESSAGES` json or ts file that can be used for quick look-up of a specific message and return something nicer (fallback to original message if not available). 

That way we can have all the text in one place and easy to change/adapt in the future.

**Comment by chrismclarke** [comment]
Including friendlier messages with #661. So should be able to use same methods.
see `getFriendlyMessage()` function in `src\components\Notification\messages.tsx`

**Comment by jparadasb** [comment]
Hello @chrismclarke This is great, what do you think about to move this method to utils/helpers? and handle a single file with the `MESSAGES` const, as a translation file?

**Comment by chrismclarke** [comment]
Hey @jparadasb, yep that makes a lot of sense, much easier if people want to make their own changes just to the text.  By translate file are we thinking JSON with a http import mechanism? I had briefly thought about that and should definitely work, was just lazy at the time of writing code. 

In any case feel free to make a PR however you feel best.

**Comment by jxofficial** [comment]
Hi, I would like to take this issue if it's not being worked on!
