### ISSUE TITLE
The sign-in page is accessible to logged-in users

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#651]
**Describe the bug**
Currently logged-in users were able to open the log-in page with its url, /sign-in

**To Reproduce**
23ab619c445e4e1f244a3fd8cbe193754036b1c6

**Expected behavior**
Users should be redirected to the home page instead

**Comment by prolland006** [comment]
hi, i found the solution but we see a little bit the login page before the redirection. I didn't found any solution for this stuff. I'm going to do the pull request.

**Comment by chrismclarke** [comment]
Thanks for this. There would be a workaround using a route-guard (I think there's an admin page that already uses auth-route or similar), but that would require a few more changes higher up so honestly I think this is fine for now. Thanks for taking the time to help us out!
