### ISSUE TITLE
Received a broken How-to page when opening a unknown how-to

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#676]
**Describe the bug**
When visiting /how-to/unknown-anything, the page was as below
![image](https://user-images.githubusercontent.com/2813016/66795052-9c846580-ef2d-11e9-8513-4e0c7752aeec.png)

**To Reproduce**
5a266775073243f6fa702a9e94351a6f727d7c12

**Expected behavior**
Just show the 404 page for any nonexistent resource

![image](https://user-images.githubusercontent.com/2813016/66795072-ac03ae80-ef2d-11e9-972e-fffc14d34fc6.png)

**Comment by prolland006** [comment]
no "404" Page also for [http://localhost:3000/events/unknown-anything]

**Comment by prolland006** [comment]
i found the bug and i am doing a pull request !
