### ISSUE TITLE
CSS is broken for an event card

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#677]
**Describe the bug**
- Tags were overlapped  
- There was too much space between Go to event and its icon

![image](https://user-images.githubusercontent.com/2813016/66795671-82e41d80-ef2f-11e9-9aa8-070a339df24d.png)

**To Reproduce**
Run `cy:open` and select the `event.spec.ts` test file

**Expected behavior**
- Tags should be put in a new line when there are too many
- **Go to event** should be right next to its icon

**Comment by drydenwilliams** [comment]
Fixed the date output and the styling on the tags.

<img width="1238" alt="Screenshot 2019-10-17 at 14 55 06" src="https://user-images.githubusercontent.com/4403089/67010583-398dfc80-f0ee-11e9-9d21-8cc1b0aaca15.png">

**Comment by tmhung88** [comment]
> Fixed the date output and the styling on the tags.
> 
> <img alt="Screenshot 2019-10-17 at 14 55 06" width="1238" src="https://user-images.githubusercontent.com/4403089/67010583-398dfc80-f0ee-11e9-9d21-8cc1b0aaca15.png">

@drydenwilliams Could you also put the text "**Go to Event**" next to its icon

**Comment by drydenwilliams** [comment]
Done ✅
