### ISSUE TITLE
Inconsistent behavior for the anonymous when opening /events/create

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#679]
**Describe the bug**
As an anonymous, visiting /events/create, the user was redirected to /events

**To Reproduce**
1e196543e4c31ee5e1dbca16f4ba8d3454c0df4f

**Expected behavior**
It should be handled as same as #656 that is to ask users to login
![image](https://user-images.githubusercontent.com/2813016/66818913-3ff26c00-ef68-11e9-97a3-31082ee41f9d.png)

**Comment by thisislawatts** [comment]
According the linked PR this issue has been addressed.
