### ISSUE TITLE
Date picker is not shown in the /events/create page

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#680]
**Describe the bug**
Part of the user experience, I expected the date picker should be shown when clicking into  the input box. However it did not. 
We had to click into the small arrow icon. It was only shown when we hovered over the field.
![image](https://user-images.githubusercontent.com/2813016/66824755-1d198500-ef73-11e9-938f-0ad119b5bfc4.png)

**To Reproduce**
- Go to the page that is to create an event
- Click onto the Date field

**Expected behavior**
- When an user clicks onto the Date field, a date picker is shown

**Comment by lauvrenn** [comment]
This should be fixed once #667 is merged

**Comment by tmhung88** [comment]
Fixed by #667
