### ISSUE TITLE
Cannot open /events/create as logged-in users

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#683]
**Describe the bug**
Logged in users were redirected to the /events page when visiting /events/create

**To Reproduce**
- Log in with any user
- Go to /events/create

**Expected behavior**
- Should allow users to see /events/create.
This issue also happened to /how-to/create before (#640). We should have a fix at the authentication layer which decides a page to be seen by an authenticated user.

**Comment by prolland006** [comment]
The method AuthRoute.isUserAuthenticated() is not working. The userStore at this moment is not loading so there is a redirection as the user was not connected.

**Comment by prolland006** [comment]
i did a correction in AuthRoute that wait than user data are ready to use. It has an impact on every AuthRoute uses in the website !

**Comment by thisislawatts** [comment]
It seems that this issue was fixed as with PRs addressing: https://github.com/ONEARMY/community-platform/issues/1124
