### ISSUE TITLE
[feature request] Create a ResetLinkHandler for testing

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#684]
An improvement for this quick fix 4041bf2a34a42a8f27e20ec81b31c2c8bf776560. There is a daily cap, 150  of **reset_auth** requests/day in Firebase. As a result, Lost Password tests fail permanently if we hit this threshold. A solution is to inject corresponding ResetLinkHandler based on the environment
- FirebaseResetLinkHandler - call Firebase SDK to send a reset link
- TestRestLinkHandler - does nothing except console.log('Auth Reset Link sent') as a trace for debugging

**Comment by tmhung88** [comment]
There is a much simpler solution that we just let it hit the limitation and verify if the expected Firebase error is returned. It's enough to say that we've called the correct resend-auth api.

**Comment by thisislawatts** [comment]
Marking this issue as resolved. 
There is a test for this in the current e2e suite and this has not failed at any point over the last 3 months even with an uptick in CircleCI jobs being run. 
https://github.com/ONEARMY/community-platform/blob/master/packages/cypress/src/integration/sign-in.spec.ts#L18-L23
