### ISSUE TITLE
Users stay on the same page after logout

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#685]
**Describe the bug**
For some protected pages (/settings, /create ...), users were asked to login just right after they logged out. The behavior was confusing.
![image](https://user-images.githubusercontent.com/2813016/66847376-79919a00-ef9d-11e9-9272-4e0fea4fd0c6.png)

**To Reproduce**
af8706c2aa93d7e588dbd4d39e94e86190c61e5f

**Expected behavior**
Should redirect users to Home page ('/') after they log out.
@chrismclarke any suggestion.

**Comment by chrismclarke** [comment]
makes sense to me, go for it @drydenwilliams

**Comment by drydenwilliams** [comment]
This one seems to be completed. @chrismclarke please could you confirm and if so we can close this issue.

**Comment by chrismclarke** [comment]
agreed, closing
