### ISSUE TITLE
[feature request] As an user, I want to clear the location box with a single click

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#687]
**Is your feature request related to a problem? Please describe.**
Users manually removed the selected location with backspace. It's unpleasant if a location is too long 

![image](https://user-images.githubusercontent.com/2813016/66848514-6ed80480-ef9f-11e9-92cb-864f0bd5e6d4.png)

**Describe the solution you'd like**
There should be a small icon (X). It should clear texts in the box on click.

**Comment by chrismclarke** [comment]
Anyone looking into this may also want to refer to #678 and #712 because there could be overlap.

**Comment by tmhung88** [comment]
@chrismclarke #678 is a bug and different to this request. It's tiny functionality to clear input whether Aloglia suggestion box is opened or not. In case, Algolia is opened, (X) also closes the box
