### ISSUE TITLE
/how-to/{slug}/edit is not accessible to resource owners

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#688]
**Describe the bug**
As an creator of a how-to, the user was redirected to /how-to instead of seeing the /edit page of the given how-to

**To Reproduce**
0c2e2f90874aedf8a9df7eccd9f4ee19e9806af5

**Expected behavior**
- Should allow resource owners to go to Edit mode of their how-tos with the url
- Please note Anonymous and other logged-in users shouldn't get into the page if they're not resource owners.

**Comment by chrismclarke** [comment]
appears to be working, closing
