### ISSUE TITLE
Edit button is not shown after login with firebase api

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#692]
**Describe the bug**
Most the time, the Edit button was not shown after login done via firebase SDK within Cypress test. However, if we use **cy.wait(1000)**, it'll appear.

**To Reproduce**
Run the Cypress test in this commit f11d33ce9f8a2f084283d8347a08d9ffc6a3a641

**Expected behavior**
 The Edit button should be shown even if it's slow

**Comment by tmhung88** [comment]
Set this one as High because this issue is affecting many test cases that requires login

**Comment by drydenwilliams** [comment]
Could be going to a `404` page instead of the `/how-to/make-glasslike-beams`? I've tried quite a few times and the edit button seems to display find. Only time when it doesn't is when I don't own that how-to (which is great) and then if the how-to isn't there.

**Comment by chrismclarke** [comment]
Will investigate, I imagine it's down to there being two different ways for gatekeeping content, one at the routing level and one at the component level. For now I'd say just workaround however possible for testing how-tos, and will try to have a fix in place by the time it comes to adding tests for editing events.

**Comment by tmhung88** [comment]
I gave it another try and my finding is **userStore.user** does get updated after **cy.login()**. However, **Howto** component isn't notified by **userStore** in order to re-render.

**Comment by tmhung88** [comment]
Fixed by #744
