### ISSUE TITLE
Map - Popup opens when filtering [bug]

### ISSUE THREAD

**Issue by drydenwilliams** [ONEARMY/community-platform#698]
**Describe the bug**
Popup is visible when the map has been filtered. 

**To Reproduce**

1. Go to the map
2. Click on a marker to open the popup
3. Click somewhere else on the map to close the popup
4. Use the filters to filter markers
5. Note that the last popup you clicked on is open without a marker

**Expected behavior**
It should just filter the markers. Not open the popup you last clicked on.

**Screenshots**
<img width="1440" alt="Screenshot 2019-10-17 at 11 48 49" src="https://user-images.githubusercontent.com/4403089/66998347-60d7d000-f0d4-11e9-8c90-a87f7ba2931c.png">

**Additional context**
I quickly tried to investigate this but no luck. Would be helpful to check through the [leaflet docs](https://leafletjs.com/reference-1.5.0.html) for methods like: `closePopup` `popupclose`

**Comment by BenGamma** [comment]
The method `componentDidUpdate` of the Popup component is fired everytime the filter is onChange. That seems to be why.
We need to find a way to not update the component 🤔

**Comment by chrismclarke** [comment]
should be closed with latest map PR
