### ISSUE TITLE
academy routing

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#706]
As it is an iframe now, you can only see the `/academy`.

Allow user to navigate with URLs. Update the routing depending on the iframe using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

**Comment by chrismclarke** [comment]
Just to elaborate a bit more, the academy uses an iframe to show content from a static site generated at: https://onearmy.github.io/academy

We want to be able to directly link to sections in the academy from the main site, i.e.,

https://onearmy.github.io/academy/plastic/basics
should be viewable at
https://dev.onearmy.world/academy/plastic/basics

This can probably be done simply by binding the iframe src url to a variable that also track the current site url. Alternatively (/possibly one for the future), we might want to look at better ways to communicate between both sites using postmessages.

Open for anyone interested
