### ISSUE TITLE
Change asserts of the date that can change with timezone

### ISSUE THREAD

**Issue by porcelani** [ONEARMY/community-platform#710]
**Is your feature request related to a problem? Please describe.**
When I execute the Cypress tests in my timezone the tests fail.

**Describe the solution you'd like**
![Screenshot from 2019-10-20 10-00-06](https://user-images.githubusercontent.com/7378479/67161082-7267e480-f32d-11e9-9aaf-473dc462efdc.png)

**Describe alternatives you've considered*
Change assert of day

**Comment by chrismclarke** [comment]
closed with #714
