### ISSUE TITLE
GDPR regulation

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#722]
Align the platform with GDPR regulation.

**Comment by chrismclarke** [comment]
Might be good if other people weigh in on this, but I'm naively assuming there isn't much we actually need to do at this stage. We're not currently using cookies to track/store any analytics, and the only user information we expose publically is username and profile picture (both of which users can choose to make non-identifiable). 

I can see a similar discussion on discourse here: https://meta.discourse.org/t/gdpr-compliance-when-using-public-user-profiles/95059/10

The only other thing I can think about is the right to remove/delete profile/data. I think there's open issues on this for some specific modules, but assuming it would be good to have a delete profile option somewhere.

I'm wondering if there is anyone we can reach out to in the community who might know more about this?

**Comment by BenGamma** [comment]
I know @pmcp had some contact in that field, maybe you could make the link with us ?

**Comment by chrismclarke** [comment]
merge into #619
