### ISSUE TITLE
[bug] - Settings page resets input fields on map pin location change

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#728]
**Describe the bug**
When filling out the form on the settings page, once I input a location for the map pin there is some sort of form reset and I lose description fields and contact links

**To Reproduce**
Go to settings page, fill out all fields and then change the pin location

**Expected behavior**
Only the pin should be updated

**Screenshots**
Example of description field remove on change (other fields also remove)
![image](https://user-images.githubusercontent.com/10515065/67891805-95a24900-fb10-11e9-860b-6dfe0a4ac91c.png)

![image](https://user-images.githubusercontent.com/10515065/67891840-a5ba2880-fb10-11e9-9d1d-410cee0bf257.png)

**Comment by lauvrenn** [comment]
Does this happen on a specific activity tab ("I run a workspace", "I am a member") or all of them? I can't seem to reproduce the issue

**Comment by BenGamma** [comment]
seems fixed, can't reproduce anymore 🤷‍♂
