### ISSUE TITLE
[bug] - Location input returns non-precise values

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#739]
**Describe the bug**
Pointed out by @NimaBoscarino in PR #738 - When using location input to search for a location on the map (or save a map pin location) algolia seems to cap the gps at 6 significant figures (so varying 2-3 decimal places). This throws off locations by a good few hundred metres. Not the end of the world but would be nicer if there were an easy way to return a more precise value from algolia places.

**To Reproduce**

See output from https://community.algolia.com/places/
Enter given coordinates into https://www.latlong.net/Show-Latitude-Longitude.html

**Expected behavior**
Full gps precision

**Screenshots**
![image](https://user-images.githubusercontent.com/10515065/68051432-9c61c500-fca4-11e9-9c85-c2416abfa60e.png)
_Lat/lon from algolia_
![image](https://user-images.githubusercontent.com/10515065/68051672-3c1f5300-fca5-11e9-83c7-f49c8cf061ee.png)
_Difference between exact (top-left) and rounded (bottom-right) values on a map_

**Comment by positive-impact** [comment]
Unfortunately, this looks like the __intended behavior__ of Algolia: the API is only accurate at a street level.


Algolia's comment about this can be found in this somewhat old issue https://github.com/algolia/places/issues/500 

And in the official documentation:

> Important: Algolia Places relies on OpenStreetMap data. Due to the sparseness of house level data in OSM, Places supports geocoding only up to the street level - house level precision is not guaranteed.

**Comment by chrismclarke** [comment]
Oh, I think I understand. When you use OSM lookup it links directly to saved place names, so in the example above `401 west georgia street` returns the building lighthouse labs whose specific gps has been saved, whilst algolia places doesn't have the same level of place names and so searches at a street level (not points of interest) and provides an approximation for street numbers. 

So for example, if you were to search for a nearby cafe OSM may well know the name and exact location but algolia places would need a road and then would only provide approximation.

So a few options I see are
a) Ignore it - the place name is still retained (e.g. 401 west georgia street) so if a user wants more precision they can use google maps when locating
b) Add functionality so the user make fine-adjustments to their pin
c) Add functionality to cross check finalised locations against OSM service to try and pull more-precise result

Personally I'm leaning towards (a), but guess that's because I'm a dev :D

I would suggest @BenGamma  and @davehakkens  also take a quick look at this thread and see if they have any thoughts.

**Comment by davehakkens** [comment]
weird.. that feels incomplete.
Its not a big deal at all when you search on the map. A rough area is enough to find pins.

It is annoying though if you add a pin, search for address and it puts it somewhere else. This means all the pins will be on inaccurate locations.  What we use in the current map is "drag Pin" so you search and then drag the pin on the exact location. Works good. But seems like option 2.

So.. I guess depends on how much time it will costs to implement this added functionality.
Either way its ok to not have it for the launch. It works but could be better.
But it might be worth having it as an proper issue in case someone wants to implement. So perhaps we can spend some time on defining the behavior and hopefully someone would take it on?

**Comment by BenGamma** [comment]
We seem to have quite some feedbacks from users that can't find their pin on the map, or it is misplaced. As a quick fix we could add a little message on the bottom of the map informing the user that the non accuracy of the pin is a known issue and that he's address is displayed anyway on his profile, so there is not too much to worry about ?
