### ISSUE TITLE
Unable to save Workplace-focused Settings

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#752]
**Describe the bug**
Filled up all fields on the screen and failed to Save because the Focus type was deselected. I couldn't select any focus option. It seems the whole thing was disabled
![workplace-disabled](https://user-images.githubusercontent.com/2813016/68281037-6019d480-00a9-11ea-8be2-30b3a10c531d.png)

**To Reproduce**
Run the test suite **settings.spec.ts**  [Settings] => [Focus Workplace]

**Expected behavior**
Should able to save changes when all of them are valid

**Comment by BenGamma** [comment]
fixed with #751
