### ISSUE TITLE
Upload status isn't reset after editing a how-to

### ISSUE THREAD

**Issue by lauvrenn** [ONEARMY/community-platform#757]
**Describe the bug**
When a how-to is to be re-edited after a short amount of time, the upload status panel remains open on the 'Edit a how-to' page, blocking any user interaction. This is because the visibility of the panel is dependent on the upload status and the status isn't reset after editing a how-to.

**To Reproduce**
1. Edit a how-to
2. Go to the main page
3. Open any how-to and try to edit it

**Expected behavior**
User should be able to re-edit a how-to.

**Comment by BenGamma** [comment]
Sorry I fixed it this morning without any PR in 6a0da09fd8ea0ed7912556854f7b5dcbb5273e4c, I should have done a proper issue and PR 😬 my bad
Good catch though 👀
