### ISSUE TITLE
[bug] - Map member pins should be hidden

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#763]
**Describe the bug**
On the map you can see pins for members, although it was decided not to include this. So ideally these pins should be filtered out somewhere (early) in the general map pin flow.

I think in part this is a legacy bug, as new members aren't given the option to add a map pin point, although it should also be tested whether a user changing type (e.g. from workspace to member) keeps a pin.

**To Reproduce**
- Visit the map page, look for the pink hand icon

and/or

- Create a workspace pin and then try change to a member pin

**Expected behavior**
Member pins never rendered (and possibly never even populated in the database) (tbc?)

**Comment by BenGamma** [comment]
With #767 I introduce the reset of the profile values (including `location`) when user change their profile type.
Shouldn't be an issue any more (but may have some legacy data that we'll get rid of when spotting). Closing.
