### ISSUE TITLE
username with space in url

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#773]
At the moment we use the `userName` field to create the user url `/u/<userName>`.

We observe that some user have a username with space, which creates profile url like this :
https://community.preciousplastic.com/u/Plastiki%20Rafiki
https://community.preciousplastic.com/u/Recycle%20Rebuild

To avoid this behavior we will need to have two separate for the name :
- `userName` to use in the url `/u/<userName>`
- `name` to use in the profile page :
<img width="343" alt="Capture d’écran 2019-11-15 à 14 14 26" src="https://user-images.githubusercontent.com/4993215/68946054-4ca9f000-07b2-11ea-8e07-f5d52580e4dd.png">

This is the beavior used by instagram & twitter :
<img width="549" alt="Capture d’écran 2019-11-15 à 14 06 54" src="https://user-images.githubusercontent.com/4993215/68946543-8b8c7580-07b3-11ea-82ce-2a4cf56f74fa.png">
<img width="593" alt="Capture d’écran 2019-11-15 à 14 10 48" src="https://user-images.githubusercontent.com/4993215/68946552-8fb89300-07b3-11ea-855b-b8ab4c71bf93.png">

To migrate current user we could copy the value of `userName` field in new `name` field, and ask the user with a space to update their `userName` to a value without space. Or change it ourselves.

We probably need to add a field to the sign-up form with the `name` field.

We will have to check the `userName` field doesn't contain the following caracters :
- space
- uppercase
- ... to define with @ONEARMY/design

**Comment by chrismclarke** [comment]
So just to be clear, why is this a problem? I followed the link you gave and the page loaded. I'm not opposed to having strict usernames, but I just want to know what we'd be trying to achieve with them?

**Comment by davehakkens** [comment]
usually the username is different from the profile name.
Now many users insert their profile name.
Which ends up in very long usernames: 
**Plastikowa Rewolucja**
https://community.preciousplastic.com/u/Plastikowa%20Rewolucja
**Javier (Singular MARS Ltd)**
https://community.preciousplastic.com/u/Javier%20(Singular%20MARS%20Ltd)
**Inez UP!cycling**
https://community.preciousplastic.com/u/Inez%20UP!cycling

Which is not nice to share or use, but that's not the main issue.
I've been told this could cause bugs and results into mappins not linking properly. Resulting into "user not found" pages. 

Once usernames are created its harder to go back. Overal it seems more common to seperate them so we keep usernames clean (no characters, spaces, uppercase. Only lowercase letters )

**Comment by mattia-io** [comment]
yep, agree with dave.. is that a big thing to do @chrismclarke ?

**Comment by BenGamma** [comment]
merged with #853
