### ISSUE TITLE
remove data caching

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#778]
Data caching is a great feature to help lower the bandwith impact of the platform. However in the current implementation it seem to lead to a few critical issues :
- Platform crashes when interacting with database on "private browsing" mode. The error is :
![Screenshot from 2019-11-25 17-10-29](https://user-images.githubusercontent.com/4993215/69903970-e8d21a80-13a0-11ea-9789-011b1039c3c6.png)

- When we update the database models, users have to delete the cache themselves, by going to the developers tools.

@tmhung88 already mention me that we should deactivate before V1 launch, maybe he will have more things to add to this list.

**Comment by chrismclarke** [comment]
Personally I'm against this idea, I think caching is hugely important for our sustainability goals and instead we should work to address the issues within the current system. 

I've created pr #806 which should make the process of clearing old caches much easier. 

I just tried accessing the platform in private browsing mode on chrome and it worked fine, so would be good if somebody can give guidance on how to recreate in a separate issue.

**Comment by BenGamma** [comment]
I totally agree that the caching system is hugely important ! I was suggesting to remove it for now because it seemed not stable enough.
With #806 it will helped a lot, and I think we'll move forward fixing issues as we run into.
I created #807 to describe the main problem with have with cache on firefox, it seems to be a legacy bug from mozilla's core that we can't do that much about.
