### ISSUE TITLE
[bug] doubled map pins

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#780]
**Describe the bug**
Some map pins are doubled. (see screenshots)

**To Reproduce**
Seems like when an error occures when user try to save his profile and have to save it twice, the map pin is doubled.

**Expected behavior**  
Should have doubled map pins

**Screenshots**
in eindhoven :
<img width="350" alt="Capture d’écran 2019-11-15 à 16 13 43" src="https://user-images.githubusercontent.com/4993215/68953797-f3968800-07c2-11ea-95b1-07202e67afc2.png">
in albania :
<img width="450" alt="Capture d’écran 2019-11-15 à 16 11 34" src="https://user-images.githubusercontent.com/4993215/68953868-1b85eb80-07c3-11ea-9be7-9a75d7cddb7e.png">

**Additional context**
When I checked the database entry, they add different `about` field. Some maybe it appends on profile edit. May be linked to #700

**Comment by sovesove** [comment]
@BenGamma trying to understand the criterias to set the priority, what makes this one a "high"?

**Comment by BenGamma** [comment]
They are purely objective for now 🤷‍♂ 
It is high because it can cause some heavy misunderstanding to the user, and makes the data on the map irrelevant

**Comment by sovesove** [comment]
Replied to Slack to Cc everyone else:
https://onearmy.slack.com/archives/CHUDUK0UV/p1574656265007800

**Comment by thisislawatts** [comment]
I haven't been able to verify that either of those examples still exist within the database. So I am closing for the time being. Please feel free to re-open if you encounter the issue again.
