### ISSUE TITLE
[bug] mutation error during sign up

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#790]
Description
I get this error: InvalidStateError A mutation operation was attempted on a database that did not allow mutations.

Link
https://community.preciousplastic.com/sign-up

Screenshots
https://wetransfer.com/downloads/a6c08c2c89a4e2ae5558a9b9f4f544a820191116013859/81ed01d39ead38d1a3d558f467d34c6620191116013859/6d4e1b

User contact
flo@precious-plastic-hamburg.de
Sure, I'm happy to help!

**Comment by BenGamma** [comment]
I can't see the screenshot, maybe we shouldn't advise to use wetransfer as it disapear after a week ?

**Comment by BenGamma** [comment]
may be related to #778

**Comment by sovesove** [comment]
ah damn, yeah maybe I'll remove that service then.
The screenshot was just showing the signup modal with that error as described, not much more to be honest

**Comment by BenGamma** [comment]
alright, then yes it can be good to remove the service.
I'm closing this one because it is a duplicate of #778
