### ISSUE TITLE
[bug] Changing focus does not work properly

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#791]
Description
Changing focus does not work properly. I go to settings > change focus > save and when I go back is back to the previous focus. Also, map does not update. Tried this multiple time :(

Link
https://community.preciousplastic.com/u/Vincent%20Vega

Screenshots

User contact
hello@mattia.io
Not this time

**Comment by davehakkens** [comment]
could this be an issue with caching? I had it a few times in the past that things where removed (from database in firebase) but still showing up..

**Comment by BenGamma** [comment]
I can't manage to replicate this one. Can we have more info on how to reproduce the same problem @mattia-io ?

**Comment by drydenwilliams** [comment]
I can't seem to replicate this. What do you mean by "change focus" @sovesove?

**Comment by mattia-io** [comment]
Me neither. I guess you guys already fixed it. 

But as I was trying to replicate the issue I encountered another one. 

I made first a sheetpress account. Then switched to member. Attached you can see what my profile says now. Maybe good to create a separate issue? @sovesove ?

<img width="386" alt="Screenshot 2019-12-07 at 16 38 08" src="https://user-images.githubusercontent.com/17761877/70372968-00188700-1910-11ea-880c-a0b205674814.png">

**Comment by BenGamma** [comment]
yes please create a separated issue @mattia-io , thanks !

**Comment by sovesove** [comment]
Done: https://github.com/ONEARMY/community-platform/issues/818
