### ISSUE TITLE
[bug] Duplicated titles in How-To list page

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#795]
Description
It shows 2 different tiles for "Extrude different textures", and both link to https://community.preciousplastic.com/how-to/extrude-different-textures.
Would be good if one tile can be deleted (the pink/grey one, see image), without deleting the how-to it links to.

Link
https://community.preciousplastic.com/how-to

Screenshots
https://we.tl/t-3Nq1QXWKgu

User contact
katharinaelleke@gmail.com
Sure, I'm happy to help!

**Comment by BenGamma** [comment]
may be linked to #700
