### ISSUE TITLE
[bug] Map profile card issues

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#796]
Description
The map card when user clicks the badge.
Currently online name is a link, the whole card should be a link.

Name of workspace should be reflecting the styling on the webflow prototype

Description should be longer.. not sure how's it cut if is char number or by line.. should be a little longer.. a little frustrating for the user

Last active user should have a capital L at the beginning

Link
https://community.preciousplastic.com/map

Screenshots
https://postimg.cc/bDBZrDPW

User contact
hello@mattia.io
Not this time

**Comment by prolland006** [comment]
For the description we should change the size also in the profile, it is also short there ! So i pull my request it without this.
