### ISSUE TITLE
[bug] Typo in how-to page button

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#799]
**Describe the bug**
Missing a dash.
It says "Create howto" instead of "Create how-to"

**To Reproduce**
https://community.preciousplastic.com/how-to
scroll to the bottom

<img width="673" alt="image" src="https://user-images.githubusercontent.com/940045/69513474-d1e78e80-0f82-11ea-8152-79ab160ab526.png">

**Comment by drydenwilliams** [comment]
Please could you just confirm this is still a problem @sovesove? I think it's been fixed

**Comment by sovesove** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/940045/70300457-8bbbe600-1832-11ea-8d5b-a0aa46b17438.png">

Yep in the button I still see the wrong copy
