### ISSUE TITLE
[bug] How-Tos not loading

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#801]
**Description**
The How-To's are still not loading (I already cleared cache) on Windows 10, on Mozilla

**Link** 
https://community.preciousplastic.com/how-to

**Screenshots**

**User contact**
mariska
Sure, I'm happy to help!

**Comment by sovesove** [comment]
@BenGamma can't replicate on Mac, but seems urgent.

**Comment by BenGamma** [comment]
I got in touch with user and it was linked to the fact that the browser was set to not save any history, which is described in #807 
I'm closing as it's not something we are going to / can fix. See more infos in related issue mentionned above.
