### ISSUE TITLE
[bug] Discord field on user profile

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#802]
**Description**
Discord input field has not been defined. 
If I put my Discord ID (mattia-io#4245) on my profile page the link is leading me to: https://community.preciousplastic.com/u/mattia-io#4245 . 
I think for discord the field should simply show the text so people can copy and search it on Discord. 
On top of this I would add a text placeholder for the input field with an example of what the discord ID looks like. 

**Link** 
https://community.preciousplastic.com/settings

**Screenshots**

**User contact**
https://we.tl/t-AzECLhyoGs
Not this time

**Comment by BenGamma** [comment]
For the fact that the discord ID is redirecting to https://community.preciousplastic.com/u/mattia-io#4245, it will be fixed with #788 
Then the suggestion on the design, will have to go through design team first.
