### ISSUE TITLE
[bug] Unable to signup

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#803]
**Description**
Cannot join the new platform. I have used both Brave and Firefox browsers. 

**Link** 
https://community.preciousplastic.com/sign-up

**Screenshots**
https://we.tl/t-SiLHTro5pM

**User contact**
mettodo
Sure, I'm happy to help!

**Comment by BenGamma** [comment]
First screenshot with mutators error is a known issue #778 
Second screenshot I'm not able to reproduce using Brave version : 0.20.30 
@sovesove can we contact the user mettodo to have more infos on his version of the Brave browser or how to reproduce the error he experienced ?

**Comment by sovesove** [comment]
I don't have the user's contact unfortunately, I think that is their
discord ID.

**Comment by BenGamma** [comment]
I've reached to the user `mettodo` on PP discord, waiting on his answer now. Otherwise will close.
I've changed the priority to `medium` because the bug is not affecting a lot of users.

**Comment by BenGamma** [comment]
User just reach back now, he was browsing in private mode. So this was fixed with #806
