### ISSUE TITLE
[bug] Profile page bus

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#804]
**Description**
First - page keeps adding a new line / option for the links and contacts every time you edit the profile, so that unless you delete the last line, it will appear on the profile as an empty link.
Second (minor) - changing from one header to another, it rolled back the first one and I had to reupload the second one. Happened only once. 

**Link** 
https://community.preciousplastic.com/u/Precious%20Plastic%20Estonia

**Screenshots**

**User contact**

Sure, I'm happy to help!

**Comment by BenGamma** [comment]
If I get it right there is two issues here :
1. We are saving empty contact links in the /settings page.
This one is a known issue and will be fixed with #788 
2. This one I don't really understand what is it about, any more information about it ?

**Comment by sovesove** [comment]
I think 2. refers to the cover photo maybe?

**Comment by catx23** [comment]
there is another bug : links without protocol in the profile will route to local 404s

**Comment by BenGamma** [comment]
> there is another bug : links without protocol in the profile will route to local 404s (https://community.preciousplastic.com/u/preciosplasticvalencia.com)
> **
> ![image](https://user-images.githubusercontent.com/1205100/70095030-0bc03100-1624-11ea-9304-ecb176a77305.png)
> **

This one is fix with [v0.8.3](https://github.com/ONEARMY/community-platform/releases/tag/v0.8.3)
Can't replicate 2. Closing
