### ISSUE TITLE
[bug] Map zoom issue

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#811]
**Description**
Little navbar bug on the map. 
On landing all good. As soon as you click +/- to zoom on a location the navbar shrinks and gets heavily misaligned.   

**Link** 
https://community.preciousplastic.com/map

**Screenshots**
https://we.tl/t-GK21rZAQ3c

**User contact**
hello@mattia.io
Not this time

**Comment by BenGamma** [comment]
This one is because user scrolled on the page 😅 
closing
