### ISSUE TITLE
[bug] Log in issue of user "12much"

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#819]
** Description **
I try to refresh my account as stated in the email ....

**Link**
I cannot log in, but cannot create a new account. Have all our old accounts disappeared?

** Screenshots **

** User contact **
12much - boy@12much.nl
Sure, I'm happy to help!

**Comment by BenGamma** [comment]
Yeah I contacted this user by email the 12 of december, said he will have a look, never heard back 🤷‍♂
