### ISSUE TITLE
[bug] Cover image is replaced when updating an image in how-to

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#822]
**Description**
Critical issue. I changed the image of step 25 and it automatically replaced the cover image. 

**Link** 
https://community.preciousplastic.com/how-to/setup-an-extrusion-workspace

**Screenshots**

**User contact**
hello@mattia.io
Not this time

**Comment by drydenwilliams** [comment]
I can't seem to replicate this one. Please could you give more information.

**Comment by chrismclarke** [comment]
hasn't been seen again so assume working correctly. closing
