### ISSUE TITLE
[bug] Add a 600-char limit to each How-to step

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#824]
Context: The text boxes don't have a limit to 600 characters which means I can put loads of words in and then when uploaded it stretched the step. But after if I want to split the step into 2 steps. But have added additional steps I need to manually move every step down....super tedious process.

**Add a 600-char limit to each How-to step.**

**Comment by davehakkens** [comment]
Yeh I guess this fits in this issue: https://github.com/ONEARMY/community-platform/issues/777
