### ISSUE TITLE
[bug] MOBILE - minor UI issues on How-To detail page

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#840]
**Describe the bug**
Check the mobile design here: https://one-army-community-platform.webflow.io/u/how-to-article

- too much padding in the title and steps card
- step's numbers should not be full width but a smaller (narrower) box
- the main image in each step should have some margin (5px) and round corners (currently there's no margin, which is fine, but then the corners need to be changed dynamically if there's other images)
- the icons and text are not aligned:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/940045/71540711-105cd880-2989-11ea-8afa-81cdb2651b26.png">

**Comment by BenGamma** [comment]
fixed in https://github.com/ONEARMY/community-platform/pull/1001
