### ISSUE TITLE
[bug] Broken page and/or link

### ISSUE THREAD

**Issue by sovesove** [ONEARMY/community-platform#863]
**Describe the bug**
This page is broken:
https://preciousplastic.com/en/videos/build/upgrades/shredder-2-1.html

**To Reproduce**
Open
https://community.preciousplastic.com/academy/build/shredder
click on "Upgrade: Shredder 2.1"
<img width="449" alt="image" src="https://user-images.githubusercontent.com/940045/71958701-e084bf00-322b-11ea-8108-e1068dd742c5.png">

**Comment by davehakkens** [comment]
fixed. thanks for spotting
