### ISSUE TITLE
[feature request] setup analytics

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#864]
_Updated 2020-01-20 CC_ 
Required for analytics:

- [x] Decide on analytics provider (use GA for now, but hopefully matomo in future, as per some discussion on here and on slack)
- [x] Add component binding/hooks (close with pr #869)
- [x] Add privacy policy/terms of use and opt-in/out mechanism (see #619)
- [ ] Add profile/data deletion options (currently on manual request)
- [x] Add data opt-in/out
- [ ] Add explainer to wiki

_End of Update_

**Is your feature request related to a problem? Please describe.**
We are currently not using any analytics solutions for the community-platform. Would be useful to collect some insight numbers.

**Describe the solution you'd like**
Implement a analytics tracking solution. Two options are :
- Google analytics.
Pros : 1. No server required 2. High granulatity level of analytics and data processing 
Cons : 1. make the page more heavy (loading the GA script is ~20kb per page) 2. it add a GA cookie, AND we are trying to avoid google 😈 
- Matomo.
Pros: 1. no script added if we use the [http tracking api](https://developer.matomo.org/api-reference/tracking-api). It makes the tracking very lightweight (only a GET request is made). 2. Total control over data. 
Cons : 1. Need our own server (can be a cheap 2$/month vps) 2.lower granularity of analytic

WIth any of these solutions we'll probably have to add some opt-in opt-out to tracking, to be gdpr compliant. More informations there https://matomo.org/blog/2018/04/how-to-make-matomo-gdpr-compliant-in-12-steps/

**Comment by drydenwilliams** [comment]
Would be great to get some analytics on ASAP. I'm a big fan of GA as it's easy to add and give great granularity and events too. 

Seems there is quite a few different alternatives out there: 
https://www.leadfeeder.com/blog/google-analytics-alternatives/
