### ISSUE TITLE
[docs] - outline current service worker/caching strategies

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#873]
**Is your feature request related to a problem? Please describe.**
Following pr #872 a bunch of changes were made to make the service worker and overall site work more efficiently. Some of the code might not be obvious (particularly custom changes required if considering reverting back to create-react-app), so would be good to add a section to the wiki.

Also worth sharing to consider any additional caching strategies that might be needed in the future (e.g. handling data that updates more regularly, such as workspace photos/avatars)

**Describe the solution you'd like**
Wiki section

**Comment by chrismclarke** [comment]
**To Include**
> I wonder though how do I test this correctly : everything seems to work fine when I have a internet connexion, but as soon as I turn my wifi off and try to reload the page, the app crashes :

Yeah testing is a bit of a pain as by default the service worker isn't installed on localhost (would make developing a pain if changes weren't seen immediately).

The best way to test is create a local build and serve that via a web server (I usually do this on port 5000 as firebase also uses it when serving).

```
npm i -g serve
yarn build
serve -s build -p 5000
```

Now you'll see the full service worker (in debug mode as on localhost)
![image](https://user-images.githubusercontent.com/10515065/72437451-a58a0a80-379a-11ea-899a-171049504c86.png)

You can also check the `Network` panel to see what is being loaded from cache vs server
![image](https://user-images.githubusercontent.com/10515065/72437647-17faea80-379b-11ea-8f80-7299a7cd8ffb.png)


This should probably also be included in the docs todo #873

**Comment by iSCJT** [comment]
@thisislawatts seeing as you were the last to get stuck into the service worker / caching side of things do you mind seeing whether the docs are sufficient please?
