### ISSUE TITLE
[suggestion] - Add context to feedback mechanism

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#882]
**Is your feature request related to a problem? Please describe.**
Suggested by @Lionel Horn on discord. 

> For specific pages, let's take https://community.preciousplastic.com/how-to/set-up-a-shredder-workspace as an example. Have you considered something to be able to get in context feedback. As in, for the visitor to be able to click/tap and select and send some feedback related to some specific highlighted part of the document. Has something like that been considered and discarded or it was never thought of?

**Describe the solution you'd like**
If useful we could easily add a prefilled field to say what page the user has come from. Would require an extra field on the form (either hidden, or with additional mechanism to for user to say whether this is relevant or not). Not sure what else could be done for fine-grained feedback.

**Describe alternatives you've considered**
Leave things as they are, depends on how good people have been at accurately describing issues to date.

**Comment by lionelhorn** [comment]
For additionnal feedback, I've also encountered
- Screenshots (automatically captured) 
- - https://html2canvas.hertzen.com/
- Recordings (but probably too cumbersome to be easy enough to use. May also not be implemented in all browser yet)
- - https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

**Comment by catx23** [comment]
yeah, that would be awesome ! comments or questions per step is a good way to improve the content but also also local infos. 
I guess you guys already checked instructables on this : 

![image](https://user-images.githubusercontent.com/1205100/72992894-c8e53300-3df4-11ea-81f2-aa9a0dcd21e2.png)

I'd also love to see attachments per step :-)
