### ISSUE TITLE
SEO - Low word count on pages [bug]

### ISSUE THREAD

**Issue by drydenwilliams** [ONEARMY/community-platform#887]
**Describe the bug**
After running a SEO check on [here](https://app.neilpatel.com/en/seo_analyzer/site_audit?domain=preciousplastic.com&view=all) it raised we have a low word count on 12 pages.

<img width="1119" alt="Screenshot 2020-02-20 at 09 48 46" src="https://user-images.githubusercontent.com/4403089/74924468-746cad80-53ca-11ea-9699-d44c75c42778.png">

Task: 
To add lots of nice content to the those pages to make Google happy :)

**Comment by davehakkens** [comment]
This is SEO for preciousplastic.com
I guess you need to use community.preciousplastic.com for the platform

**Comment by mattia-io** [comment]
Hey @drydenwilliams thanks for looking into it!
What you mean content? Keywords? 
Any more info on best practices?

**Comment by davehakkens** [comment]
This seems to be posted in the wrong repository? 
It's for preciousplastic.com not community.preciousplastic.com
Cleaning up Github and this should be the the repository below. 
But can't move it so i'm closing. sorry.
https://github.com/ONEARMY/precious-plastic/issues
