### ISSUE TITLE
SEO - Create unique title & meta descriptions [bug]

### ISSUE THREAD

**Issue by drydenwilliams** [ONEARMY/community-platform#888]
**Describe the bug**
We have duplicate `meta` descriptions and `title` tags on `https://preciousplastic.com/` and it's better for SEO if they are unique

<img width="1131" alt="Screenshot 2020-02-20 at 09 49 16" src="https://user-images.githubusercontent.com/4403089/74924533-936b3f80-53ca-11ea-91cd-38efcb909628.png">

**Comment by davehakkens** [comment]
This seems to be posted in the wrong repository? 
It's for preciousplastic.com not community.preciousplastic.com
Cleaning up Github and this should be the the repository below. 
But can't move it so i'm closing. sorry.
https://github.com/ONEARMY/precious-plastic/issues
