### ISSUE TITLE
[bug] - Email validation user issues

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#891]
**Describe the bug**
Various messages coming through on email to say issue with confirming email address. Most saying they did not receive a link but some having issues of 'endless loop', possibly email confirmation link not working. 

Possibly a couple issues, might be as trivial as spam filters for those not seen, but also likely issue with platform as I can't see any users who have their email marked as verified (every user has verified:FALSE)

**To Reproduce**
See messages on slack and email

**Comment by alromh87** [comment]
I look a bit into this an it seems that firebase email is working properly on dev environment, 

@chrismclarke could you point me in the right direction to find more details to reproduce

I could not find a custom implementation of the handdling of password verification, so I guess thas why verified is never changed, probably should need something like:

https://firebase.google.com/docs/auth/custom-email-handler

**Comment by chrismclarke** [comment]
Honestly I don't really know what the issues are or how to reproduce - I think Kat would put messages in slack from time to time having received requests from community members but I don't know if they were down to platform error or user error.

I would suggest using a service like https://temp-mail.org to create a new account on the live site and just confirm the workflow is correct, as well as resetting a password. You could also look at what happens when the email confirmation link is used and see if there is any code in place to update a user profile to show email verified (I know firebase auth retains this information, I'm just not sure if we ever populate it to the profile)...

**Comment by thisislawatts** [comment]
👋🏻 Hey @alromh87, you're assigned to this issue. Is it still something you'd be available to help out on? No worries not, life gets busy! If we've not heard back from you in a month we'll remove your assignment from this issue.

✨

**Comment by iSCJT** [comment]
@ONEARMY/maintainers anyone seeing this as an issue currently or should I close?

**Comment by davehakkens** [comment]
close it. we will see if it pops up again
