### ISSUE TITLE
[discussion] - Browserstack

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#892]
**Is your feature request related to a problem? Please describe.**
We previously signed up for a non-profit account with browserstack and were given a year's access, however I'm not sure if it's been used. Is it possible to automate anything with browserstack? Is there more we could or should be doing?

To make matters a little bit more difficult, the email first used to register the nonprofit (hello@onearmy.world) has now been replaced by platform@onearmy.world so I'm not sure even how to access (google sign-on won't work).

I think @BenGamma handled the first sign-up, any thoughts on this?

**Comment by BenGamma** [comment]
I send you the login details on slack.
I haven't setup any automated testing with it yet but that was the idea at the time, I just got lost into thousand of other things 🌪

**Comment by chrismclarke** [comment]
Yeah I'm the same, I just noticed a bunch of marketing emails from them and that reminded me. I don't expect to have much time/use myself, but thought be good to open an issue in case anyone else suggests it in the future. Now it's been flagged I think I'll just close here and can always re-open in the future if someone has more interest on working with it.
