### ISSUE TITLE
Add Publication Date

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#894]
Description: Add the date when the how-to was published. In dd-mm-yyyy format.
Location: Single how-to Page 

<img width="760" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/75415147-ba88ba80-5950-11ea-93d0-eccc96c01828.png">

**Comment by tudi2d** [comment]
I would like to add this. Is this additional to the "| xxx days ago" or can I remove that?

**Comment by davehakkens** [comment]
cool! The "days ago" should be removed..

**Comment by tudi2d** [comment]
I saw that #895 & #896 are related to this. I would like to work on them as well and would suggest to bundle the fixes in the pull request #906 with separate commits.

**Comment by BenGamma** [comment]
Yep that's good, see my comment in #906

**Comment by BenGamma** [comment]
FYI there is already a PR (#905 ) that fix #895

**Comment by BenGamma** [comment]
merge with #908
