### ISSUE TITLE
Add latest edit date

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#896]
Description: Add "last edit" date. This shows the latest date the how-to was editted. In dd-mm-yyyy format
Location: Single how-to Page

<img width="523" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/75415247-13f0e980-5951-11ea-8b2c-347bd5d3b146.png">

**Comment by tudi2d** [comment]
![image](https://user-images.githubusercontent.com/8904624/76161266-0b0ecd80-6132-11ea-8d58-a00515b65da1.png)
 I pushed the changes to the PR as mentioned. This is what it looks like.

**Comment by davehakkens** [comment]
sweet!

**Comment by BenGamma** [comment]
merge with #909
