### ISSUE TITLE
Remove Image captions

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#898]
Description: Image captions are shown when images are uploaded for a how-to. However they are not used in the front end and make the backend more messy. So remove.
Location: Edit and Create How-to

<img width="712" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/75415536-f1130500-5951-11ea-90ab-11ce7efe2b7b.png">
<img width="730" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/75415592-0d16a680-5952-11ea-8a97-db10d6d36736.png">

**Comment by tudi2d** [comment]
I would like to work on this :+1:

**Comment by davehakkens** [comment]
yeah!
