### ISSUE TITLE
Align the description length on map-thumbnail.

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#900]
Description :
The description text is currently cut of on map-thumbnails. 2 changes need to happen

**1. Map thumbnail.**
- Should show max 70 characters. if there are more charachters add dots...
- Height of the thumbnail will change accordingly
- [Example](https://precious-plastic-community.webflow.io/u/map)

**2. Edit/Create Profile page**
- The input text should be limited to 70 characters
- Box should be reduced in size. 2 lines height should be enough

<img width="1008" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/75416170-97abd580-5953-11ea-8e6d-0e22b89ae022.png">
<img width="821" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/75416417-3f290800-5954-11ea-8191-aa1c64c177f8.png">

**Comment by tudi2d** [comment]
I would like to work on this! :)

**Comment by davehakkens** [comment]
yeah!

**Comment by BenGamma** [comment]
> I would like to work on this! :)

Cool tks @tudi2d, let us know here if you have any questions

**Comment by davehakkens** [comment]
Not sure how this is going. But this issue https://github.com/ONEARMY/community-platform/issues/925  could be a good followup

**Comment by tudi2d** [comment]
Sounds good. I will continue with #925 :)
