### ISSUE TITLE
[bug] Multiple scroll bars

### ISSUE THREAD

**Issue by mojoaxel** [ONEARMY/community-platform#904]
**Describe the bug**
In the academy menu the scrolling is broken, so that two scroll bars are displayed.

**To Reproduce**

1. Go to https://community.preciousplastic.com/academy
2. Scroll down and up

**Expected behavior**
Only the main scroll-bar should be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/600565/75629977-27b57d80-5be7-11ea-8633-fb4a32c29680.png)

**Comment by BenGamma** [comment]
Thanks for pointing out !
It's because we embed the academy from an other domain, I needed to update the size of the container only in the academy section.
Fixed with #907
