### ISSUE TITLE
Set Character limites

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#925]
## Component infos
We need to set character limits for some input fields.
And mention this limit in the placeholder text for the fields

### Input fields & limits

|  Place                                 | character limit   | Place holder text |
|---------------------------|-------|-------|
| Create how-to (intro title)  |  50      | Make a chair from.. (max 50 characters)  |
| Create how-to (intro description)  |  700    | Introduction to your How-To (max 700 characters) |
| Create how-to (step title)  |  30      |  Title of this step (max 30 characters)   |
| Create how-to (step description)         | 400     |  Explain what you are doing in this step. if it gets to long break it into 2 steps (max 400 characters)  |
|  Event (title)                       | 140      |  Title of your event (max 140 characters) |

**Example of placeholder text**
![github_placeholder](https://user-images.githubusercontent.com/13672737/77843310-205ca200-719c-11ea-9a42-83aa359b96cf.jpg)

**Comment by tudi2d** [comment]
![image](https://user-images.githubusercontent.com/8904624/77934704-c26dae80-72b0-11ea-8592-061e7cb39396.png)

I changed the placeholders and also adjusted the other placeholders so it looks the same (no '*' in the placeholder e.g.)
