### ISSUE TITLE
[bug] - How-to failed uploads get stuck

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#932]
**Describe the bug**
When uploading a new how-to there can be an error with one of the steps (e.g. step images upload). when this happens the modal stays displayed (with no way to close) and spinner keeps spinning. The only way to close it is refreshing the page which loses all the how-to data.

**To Reproduce**
1. Create new how-to, filling required fields
2. Disconnect internet
3. Click publish

Note, this isn't only when internet issues but also seen with unknown file upload error (possibly related to permissions)

**Expected behaviour**
An error message should appear, allowing the user to close modal and either try again or at least save draft. This will likely involve refactoring the current system for tracking upload progress to also note the error and give the option to manually close on error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10515065/78183871-7429ee00-741d-11ea-868a-a15ae1d47b37.png)
Will stay like this indefinitely on upload fail

**Comment by chrismclarke** [comment]
duplicate of #781

**Comment by BenGamma** [comment]
Couldn't it be linked to the upload image problem kat was mentioning ? I also experienced strange behaviors with image upload while working on #899

**Comment by chrismclarke** [comment]
Yes I think it is (the reason I came across it). I think there might be a couple issues if for example a user is trying to simultaneously upload images with the same filename, and also linked to however the save draft system works and subsequently replacing/updating images. But I haven't figured out good ways to reproduce the other issues yet and so only posted this one.

**Comment by chrismclarke** [comment]
But we should probably either move this discussion over to the other thread or create a new issue so it doesn't get lost
