### ISSUE TITLE
[bug] - PNG images lose transparency (background turns black)

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#933]
**Describe the bug**
Uploaded pngs seem to have a black background instead of transparent.

**To Reproduce**
Add a png with transparency to any how-to upload

**Expected behavior**
Keep transparency. If converting to JPG (which I don't think happens) then probably default to white background.

**Screenshots**
![image](https://user-images.githubusercontent.com/10515065/78194860-156f6f00-7433-11ea-9e22-1098aa2d73e7.png)

![iconfinder_wuhan-coronavirus-virus-outbreak-02_5730675](https://user-images.githubusercontent.com/10515065/78194909-3637c480-7433-11ea-81e4-76eb36281346.png)
Original

**Comment by alromh87** [comment]
Look into this and images are compressed with [client compress](https://www.npmjs.com/package/client-compress)  with current limitations:

- When working with image/gif, the compressed image will no longer animate.
- When working with image/png with transparent background, the compressed image will lose transparency and result in black background

Thats why images end as black background png, if we are to look for an alternative library it would be important to understand the compression required.

**Comment by alromh87** [comment]
@chrismclarke can you assign this one to me and Backend tag label should be changed to Frontend since this compreesion is executed on the browser before upload

**Comment by nshevcun** [comment]
Experiencing a similar issue, except the uploaded PNG image backgrounds show up as white on Github Pages.

**Comment by chrismclarke** [comment]
Yeah, there is an outstanding issue on compressjs (`https://github.com/alextanhongpin/compress.js/issues/3`), which client-compress is forked from (and another issue there: `https://github.com/davejm/client-compress/issues/7`)

I think unlikely this will be fixed in either repo so we should look to make a change. Browser-image-compression seems like a solid option, a few other alternative 
 
 ![image](https://user-images.githubusercontent.com/10515065/126002671-ef74078b-6770-4932-a53c-60a514712916.png)
https://www.npmtrends.com/browser-image-compression-vs-client-compress-vs-compressorjs-vs-pica

Open if anyone wants to take it on
