### ISSUE TITLE
Mandatory contact details

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#934]
## Component infos
Make it mandatory to fill in at least 1 contact detail in profile details under "contact & links"

Pages:
https://community.preciousplastic.com/u/precious-plastic
https://community.preciousplastic.com/settings

<img width="994" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/78386590-27414580-75de-11ea-98f0-a7749ea6fd61.png">

**Comment by tudi2d** [comment]
I would like to work on this 👍

**Comment by davehakkens** [comment]
yeah!

**Comment by chrismclarke** [comment]
closed with #942
