### ISSUE TITLE
Add guideliness to cover images

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#935]
### Description

Currently there are no guidelines for uploading a cover image in profile, resulting in a lot of moderating and unnecessary mails. A few simple lines will avoid many issues.

### Page related
**Live**: https://community.preciousplastic.com/settings
**Example**: https://community-platform.webflow.io/u/edit/edit-user-profile

### Text needed

> Images are shown in your profile and helps us evaluate your account.
> Make sure the first image shows your Space. Best size is 1920x1080. 

### Example(s)
<img width="763" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/78387289-5dcb9000-75df-11ea-8988-10066109da6c.png">

**Comment by BenGamma** [comment]
merged with #941
