### ISSUE TITLE
[bug] delete map pin when profileType is change to member

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#946]
**Describe the bug**
When user is changing his profile back to member, his pin still appear on the map as member.

**To Reproduce**

1. Go to your user settings
2. Change your profile type back to user
3. check the map

**Expected behavior**
Member pin shouldn't be displayed on the map.
A quick fix could be to only display the pins that have a different profileType than `member`.

**Comment by chrismclarke** [comment]
Different ways we could go about this:
1. Just code in an extra side-effect function into the profile save/update method (simplest, but not super clean to have something so custom in the middle of things more general code-wise. Perhaps it could be moved to a separate folder and called from there? 
2. Add a cloud function trigger to automatically handle from the backend on user update (possibly more reliable, still not super clean so would suggest put in a dedicated custom PP updates folder)
3. Do nothing and filter on the map view (slightly less efficient in terms of db calls (although I don't think this is a very common case), but at least the map is already set out to run a custom filter)

As a bonus we could try link whatever option to also handle cases where user accounts are deleted and therefore map pins also

**Comment by BenGamma** [comment]
3 sounds like the best option to me.
That could allow us to do 2 shots in a row : filtering the member pins and the deleted pins

We already have some deleted pins here and there on the map (I have 2 in mind), but these may be worth removing by hand.

**Comment by prolland006** [comment]
i'm working on it ! I did the 3rd point and looking for the "bonus" !

**Comment by prolland006** [comment]
i can't do the bonus because i don't know how to remove a pin and when i tried to create/remove a user no deletion is coming from firebase. So i put my pull request.

**Comment by alromh87** [comment]
I would suggest setting a different bug for handling user deletion and channing deletion of related data.

Trigger would be best suited for this

I should define beforehand whan datashould be preserved and what should be removed automatically
