### ISSUE TITLE
[suggestion] - SEO Optimisations

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#961]
## Update 2021-07-14
Still a nice to have moving forward. One other suggestion which might be simpler short term:

- Add a backend function to intercept page requests from common bots (e.g. google, facebook, twitter bots etc.), and populate with metadata tags taken from the db entry (e.g. howto main image) 

Here's an [example file](https://github.com/supportingami/sami-maths-club/blob/master/maths-club-app/functions/src/seoHost.ts) I added to another project to update SEO meta tags on request (could be further improved on by making specific reads to DB)

E.g. If we were to use current howto main image, title, description we would have something like:
![image](https://user-images.githubusercontent.com/10515065/125678048-a820092d-e40b-4ac7-b111-283aa7864d6a.png)

## Original Issue
Currently the site isn't highly optimised for SEO. A few possible ways to improve this could be:

[ ] - Generate sitemaps from db for use by search index (#886)
[ ] - Review current visibility (robots.txt etc.)
[ ] - Register and review with google search console
[ ] - Generate dynamic page meta via react-helmet (or similar)
[ ] - Possibly explore SSR options
[ ] - Consider ways to let users personalised SEO tags etc.

(any other suggestions/comments more than welcome)

**Comment by chrismclarke** [comment]
@davehakkens If design team are interested in exploring a couple options for how things like howtos might look you can use the site https://metatags.io/ to design/preview

**Comment by davehakkens** [comment]
cool tool! Something like that would be really nice. 
It would be great if we could use the how-to information:
1. Header title
2. Header image 
3. Intro description

They are generally well-curated with the best images.

**Comment by chrismclarke** [comment]
Yeah I think howtos should be fairly straight-forward if we do things that way. Then we need to decide what to do about other pages (events, research, user profile etc.), E.g.

**Events**
Title - event title
Description - event location name or just some standard text (e.g. 'check out this event')
Image - some standard svg or maybe country flag(?)

Each module will want some sort of similar mapping, even if just fairly basic.

**Comment by chrismclarke** [comment]
Haha, took a while but we got there in the end! Thanks for all the help @thisislawatts
