### ISSUE TITLE
Tag Dropdown Styling

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#963]
Hello hello, 

The tag dropdown seems to have been left to its default styling. 
Originally it was designed as the screenshot below:
![Screenshot_2020-05-18_at_15_06_24](https://user-images.githubusercontent.com/17761877/82198414-e7c68280-9919-11ea-87d4-744e35c55f0d.jpg)

Any chances we could achieve that look 👆👆👆

Mainly would be a matter of:
1. Font-family: Varela
2. Color: black
3. Add the appropriate arrow, svg attached below 
[arrow_svg.zip](https://github.com/ONEARMY/community-platform/files/4643282/arrow_svg.zip)

Thanks!

**Comment by mattia-io** [comment]
Also valid for Map and Events page

**Comment by tudi2d** [comment]
Hey. I would like to improve this 👍

**Comment by mattia-io** [comment]
hey @tudi2d all yours 🥳

**Comment by tudi2d** [comment]
Ok cool, thanks! I added a pull request. It looks like this:

**HowTo´s**
![image](https://user-images.githubusercontent.com/8904624/85346880-2215d780-b4f7-11ea-83ee-815d643bb647.png)

**Events**
![image](https://user-images.githubusercontent.com/8904624/85346918-4376c380-b4f7-11ea-8b4d-668ca67e9238.png)

I did not changed the look of the tag select when creating/editing HowTo´s/Events as there are more default styled selects/inputs and it looked weird when there is only one select with a different indicator icon and another text color.

![image](https://user-images.githubusercontent.com/8904624/85348155-03b1db00-b4fb-11ea-9c59-5fbf9710618e.png)

I hope this is more accurate to your inital design! :)

**Comment by mattia-io** [comment]
Fantastic. Thanks!
@chrismclarke or @BenGamma will review and merge asap. 

Indeed all the other down arrows should be aligned. 
If you have the time here is the grey down-arrow.
💪

[grey-down-arrow.svg.zip](https://github.com/ONEARMY/community-platform/files/4818911/grey-down-arrow.svg.zip)

**Comment by tudi2d** [comment]
Sure! The change would be a different then, so it might make sense to wait with merging. Will probably get to this in the next few days 🙂

**Comment by tudi2d** [comment]
Looks like this now & the pull request will implemented it for HowTo´s & Events: 

![aCkC35rP6p](https://user-images.githubusercontent.com/8904624/85543721-9b5a1b00-b61a-11ea-8f9b-813875421612.gif) 

In a future issue it might be interesting to change the map selects to look like the other selects: 

![image](https://user-images.githubusercontent.com/8904624/85544212-17ecf980-b61b-11ea-985c-aa489fcceeca.png)
