### ISSUE TITLE
Map dropdowns improvements

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#965]
Hello, 

Few minor changes on the map that would do a whole lot to the user experience and overall UI. 
Would be great if:
1. We could replace the existing arrow with the one mariska originally designed for it. Attached below
[arrow_svg.zip](https://github.com/ONEARMY/community-platform/files/4643361/arrow_svg.zip)
2. All text placeholders are black
3. Text placeholder says "All workspaces"
4. Checkmark is a bit smaller. Currently it is 30px by 30px. I think 20 by 20 would do just fine. 
![Screenshot_2020-05-18_at_15_25_10](https://user-images.githubusercontent.com/17761877/82200455-a71c3880-991c-11ea-97b4-419c72c99d49.jpg)
5. Dropdown consistency. In the how-to the dropdown is styled properly with a few pixels margin and a black border. In the map was maybe forgotten. Would be great to achieve the same look (the how-to one) across the website. 
![Screenshot_2020-05-18_at_15_32_46](https://user-images.githubusercontent.com/17761877/82200930-40e3e580-991d-11ea-861c-8cc19adb3af7.jpg)
![Screenshot_2020-05-18_at_15_32_53](https://user-images.githubusercontent.com/17761877/82200943-45100300-991d-11ea-8a0f-d9465eacac26.jpg)

Hope is clear.. can clarify if any doubts!

**Comment by Daniel-Davies** [comment]
Hello, I'd be happy to look into some of the issues here if nobody else is looking into this.

**Comment by mattia-io** [comment]
hey @Daniel-Davies by all means, go ahead. 
Also, as you're at it, could you also change the cursor css styling on hover to pointer?

Let me know if you need any further assistance. 
Mattia
