### ISSUE TITLE
How-to cover fine-tuning

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#966]
Hey devs 🤙

The how-to cover is slightly different from the original design (which can be found [here](https://community-platform.webflow.io/u/how-to-article)). Small things but I think that’s where we can excel. 
![Screenshot_2020-05-19_at_09_13_50](https://user-images.githubusercontent.com/17761877/82288440-231b8c80-99c0-11ea-9f01-b1de63500e0f.png)
![fixes](https://user-images.githubusercontent.com/17761877/82287907-ea2ee800-99be-11ea-8bc9-178af59dfa83.png)
A few things that need changes:
1. The back button should be more subtle. No stroke, grey text and smaller size. Plus back arrow next to the text. (nice to have) 
2. Published on. Would be great to have the text following this template “By {author} | Published on {date}”
2a. Edit on. Would be nice to align and say "Last edit on {date}"
3. Title should be font-family: Varela Round,  font-size: 20px and font-Colour: black
4. The cover image should always fill 100% of the height. In the original sketch was built using a bg image covering a div. There are probably better ways to build it but would be nice to achieve that result.
5. Add the download icon Mariska designed. Attached below. 
[5e57208e3dcd887e95da312e_icon download.svg.zip](https://github.com/ONEARMY/community-platform/files/4648262/5e57208e3dcd887e95da312e_icon.download.svg.zip)

Hope this clear, if any doubt just comment below and I’ll try to make myself more clear. 
Big up!

**Comment by tudi2d** [comment]
Hey. I would like to work on this. Just gonna drop this old ticket here (#894 (Publication Date)) as it will reverse the changes implemented back then. This is intended, right? @mattia-io 👍

**Comment by mattia-io** [comment]
hello @tudi2d that would be sweet. Yes, you can drop #894. 
One more thing to add to the above changes would be to replace the arrow to the back button with the grey one you already replaced on the other issue. 

Thank you Philip 🤘

**Comment by mattia-io** [comment]
Hey @tudi2d just noticed a little conflict of versions. 
The date should remain in dd-mm-yyyy format. The rest should be like in the sketch above.
Sorry for the confusion.

**Comment by tudi2d** [comment]
No worries! Will fix this issue in the next few days. I will upload a screenshot for you to verify 👍

**Comment by tudi2d** [comment]
Looks like this now:

![image](https://user-images.githubusercontent.com/8904624/86021971-06945a80-ba2a-11ea-8be8-f51df293ce60.png)

And the "last edit": 
![image](https://user-images.githubusercontent.com/8904624/86022130-393e5300-ba2a-11ea-819f-4029975aef0f.png)

**Comment by mattia-io** [comment]
Super! Looks neat. Thanks @tudi2d great job. 
One last thing if you find the time would be to make the button subtler (point 1 above). Not sure if you need more info to make this change. 
Big up!

**Comment by tudi2d** [comment]
Thanks for the feedback! I did not change the the "Back" button yet, as there does not exists a general style for buttons, that looks like this (and you wrote it would be a nice to have). I will add this - probably in the next days or so. 

At the moment I only replaced the general download icon and kept the PDF icon for PDF´s - I will change this as well.

**Comment by mattia-io** [comment]
Yhe, I thought there wasn't a style set yet. 
Whenever you got some time. Nice one!

**Comment by tudi2d** [comment]
I pushed my changes to the PR. Looks like this now:

![m6gjMmpfxd](https://user-images.githubusercontent.com/8904624/86458514-a2bdaa80-bd25-11ea-99b1-0215f94e3f19.gif)

**Comment by mattia-io** [comment]
Looks great to me. 
One last thing only, if you could change the "back" button arrow to the hand-drawn one previously shared above.
And lastly, I just noticed issue #967 is very closely related to what you're working on. Maybe you want to take care of that too? So this page is cleaned up properly. 

Much appreciated :)

**Comment by tudi2d** [comment]
@mattia-io Cool. Not sure which arrow icon you mean. I used the [hand drawn one which was already in the assets](https://github.com/ONEARMY/community-platform/blob/master/src/assets/icons/icon-arrow.svg).

Sure. #967 looks good - you can assignee me there :)

**Comment by mattia-io** [comment]
I meant the arrow used for the dropdowns. The one you changed last week. 
Not a big deal but would be great to align. 

This one
[arrow_svg.zip](https://github.com/ONEARMY/community-platform/files/4878133/arrow_svg.zip)

**Comment by tudi2d** [comment]
Sure. Update the PR. Looks like this now :) 

![image](https://user-images.githubusercontent.com/8904624/86825257-6ffe1400-c08f-11ea-9b1d-9e46937d26e1.png)

**Comment by BenGamma** [comment]
merged with #993. CUrrently on dev site and will be live with the next release :rocket:
