### ISSUE TITLE
Mobile - How-to icons

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#967]
On mobile the icon blocks for steps, time and difficulty are aligned horizontally. 
Would be great if they are aligned vertically and centred 👀
 
![Screenshot_20200525-185806](https://user-images.githubusercontent.com/17761877/83100522-c742b900-a0cd-11ea-8405-8e91985ba3f3.jpg)

**Comment by tudi2d** [comment]
I implemented this (as discussed in #966). Below a screenshot of what it looks like. The display will not change on orientation change/ resizing. It will only change on load.

![image](https://user-images.githubusercontent.com/8904624/87875885-9c415b00-c9d4-11ea-9d71-85a981f16d16.png)

**Comment by mattia-io** [comment]
Brilliant, thanks!
