### ISSUE TITLE
[bug] - Profile links without full url (e.g. https://) don't link correctly

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#968]
**Describe the bug**
When a profile enters a link (e.g. instagram.com/user) in their profile the link will only be appended to the current website (e.g. https://community.preciousplastic.com/u/instagram.com/user). This is the default behaviour of `<a href` tags (https://www.w3schools.com/html/html_links.asp), but ideally should be handled by the platform better.

**To Reproduce**
1. Go to your profile
2. Add a link without http:// or https:// at start
3. Save profile and try to follow link

**Expected behavior**
Urls should be re-written to link to correct external website, or correct format enforced when creating anywhere on site - preference for first option so that we don't have to rewrite existing links in the database

**Screenshots**
![image](https://user-images.githubusercontent.com/10515065/83295704-44406200-a1a4-11ea-902a-c9f8d03d8bb6.png)

**Comment by BenGamma** [comment]
That's weird, we had a mutator to add the http:// if missing, I will investigate.

**Comment by chrismclarke** [comment]
I'm doing some other work on profiles for #818 and am planning to add a small workaround to update URL, but if you also figure out at the point of user entering info that would be handy
