### ISSUE TITLE
Add country flags at username

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#972]
### Description
Show the diversity of the worldwide community more, by adding locations flags to usernames. Based on the location selected by the user.

### Page related
Will be used in :
[How-to overview](https://community.preciousplastic.com/how-to) 
[Single How to](https://community.preciousplastic.com/how-to/add-interchangable-patterns-to-injection-moulds)

### Mockup
![profile-flag](https://user-images.githubusercontent.com/13672737/83517869-ef6d5600-a4d9-11ea-90d5-940574d67d2c.png)
![flag_howto](https://user-images.githubusercontent.com/13672737/83517876-f3997380-a4d9-11ea-8233-d52ac13d4048.jpg)

**Comment by BenGamma** [comment]
This one is a bit in the same veine as #974. We'll probably have to add a field on the how-to model `creatorCountry` when howto is created, to be able to easily get this info.

**Comment by Daniel-Davies** [comment]
Hello- I'd love to help out your platform and contribute to this issue, if possible. Could I take this issue? (Or would you recommend another?)

**Comment by davehakkens** [comment]
Thanks for wanting to help @Daniel-Davies, however @alromh87 is currently working on this one. 
What do you like to work on/ what are your skills? We have quite some SEO improvement we need to make, optimise backend, and bugfixes.

We are working on some new features but are currently still in design stage.

**Comment by Daniel-Davies** [comment]
Hello- I've had a look at other issues. Is #989 available?

**Comment by alromh87** [comment]
@BenGamma @chrismclarke  I have some doubts about the cache for howto list:

Flag  **in howto list** gets updated if I edit the howto from the browser but not when i trigger from DB

Flag in Detail its updated every time (from browser or DB)

**Comment by BenGamma** [comment]
@alromh87 yes it would be preferable to update from the browser. Otherwise we have to update the cache of all the user and that's a lot of data 😬 
Can you describe the procedure to update from the browser ? I'm not sure to understand

**Comment by alromh87** [comment]
When a user is updates a howto, the fag gets correctly updated in the HowToList.

But if a user changes his location all of his how-tos should reflect the change, that its achived with a firestore function.
After change the new flag will display in how-to detail(edit, view) but not on how to list.

Im unsure if this has to do with my dev environment or some web cache

**Comment by BenGamma** [comment]
> When a user is updates a howto, the fag gets correctly updated in the HowToList.

Ok and #1033 is updating the flag in the howto list but it doesn't update the location of the how-to if the user changes it.

> But if a user changes his location all of his how-tos should reflect the change, that its achived with a firestore function.
After change the new flag will display in how-to detail(edit, view) but not on how to list.

Is it something you are planning to had to #1033 before merge ?

> Im unsure if this has to do with my dev environment or some web cache

It's hard to tell for your problem since I don't see the code

**Comment by alromh87** [comment]
> > When a user  updates a howto, the fag gets correctly updated in the HowToList.
> 
> Ok and #1033 is updating the flag in the howto list but it doesn't update the location of the how-to if the user changes it.
> 

Not sure I understod this, If a user changes his location his howTo don't reflect the change, will fix that with next commit

> > But if a user changes his location all of his how-tos should reflect the change, that its achived with a firestore function.
> > After change the new flag will display in how-to detail(edit, view) but not on how to list.
> 
> Is it something you are planning to had to #1033 before merge ?

Yes I will update the PR

> 
> > Im unsure if this has to do with my dev environment or some web cache
> 
> It's hard to tell for your problem since I don't see the code

The database is updated correctly its just the howTo list that doesn't reflect the change

**Comment by alromh87** [comment]
Firestore Trigger added 
https://github.com/ONEARMY/community-platform/pull/1033/commits/b287bcceea9cc2671734a1bb503ac746302c49fe

**Comment by BenGamma** [comment]
Reopen because we need to add `creatorCountry` field to existing how-tos before it's fully completed

**Comment by alromh87** [comment]
Following script will populate the fields as needed, has been run on dev environment already showing all available flags

![Captura de pantalla de 2020-10-14 10-08-56](https://user-images.githubusercontent.com/7505980/95977901-1e012300-0e22-11eb-8c66-c60dc7f20319.png)

```
const functions = require('firebase-functions')
const request = require('request')

const admin = require('firebase-admin');
admin.initializeApp();
const db = admin.firestore();

// Change for prod:
// import { db } from '../Firebase/firestoreDB'

// Set all user flags
async function updateAllFlags() {

  console.log('Updating all flags ...')

  try {
    const querySnapshot = await db.collection('v3_users').get();

    if(querySnapshot  && !querySnapshot.empty){
      querySnapshot.forEach(async user => {
        const country = (user.data().location && user.data().location.countryCode) ? user.data().location.countryCode : (user.data().country ? user.data().country.toLowerCase() : '')
        if(country !== ''){

          console.log('Procesing', user.data()._id, 'flags');

          const querySnapshotHowTo = await db.collection('v3_howtos').where("_createdBy", "==", user.data()._id).get()
          if(querySnapshotHowTo){
            querySnapshotHowTo.forEach(doc => {
              console.log('updating', user.data()._id, 'doc', doc.data()._id, 'to', country);
              doc.ref.update({
                'creatorCountry': country,
                '_modified': new Date().toISOString()
              })
              .then( () => {
                console.log("Document successfully updated!");
                return null
              }).catch( error => {
                console.error("Error updating HowToCountry: ", error);
                return null
              });
            });
          } else {
            console.error('Error getting user howTos');
          }
        }else{
          console.log('No info for ', user.data()._id, 'flags');
        }
      })
    }
  }catch(e) {
    console.log('Error updating flags:', e)
  }
}

// Cant trigger from url, fix permissions or use google cloud console  https://console.cloud.google.com/functions/list?project=precious-plastics-v4-dev&folder=&organizationId=

exports.migrationFeat972Flags = functions.https.onRequest(async (req, res) => {
  await updateAllFlags();
  res.status(200).send('Finished');
});
```

**Comment by BenGamma** [comment]
Ok cool, @chrismclarke since it's a one shoot script, do you prefer we run it from the console or like the userStats, create a dedicated folder/migration file for it ?

**Comment by davehakkens** [comment]
> Following script will populate the fields as needed, has been run on dev environment already showing all available flags
> 
> ![Captura de pantalla de 2020-10-14 10-08-56](https://user-images.githubusercontent.com/7505980/95977901-1e012300-0e22-11eb-8c66-c60dc7f20319.png)

What is up with your tag selection box @alromh87, you always see it like that?

**Comment by alromh87** [comment]
Haha yep, when I use one version of chrome, I'm not on my computer now but will tell you specific version when I'm back

**Comment by alromh87** [comment]
@davehakkens I see it like that with chrome Versión 69.0.3497.81 (Build oficial) (64 bits) on Debian Jessie

If I use Versión 80.0.3987.16 (Build oficial) beta (64 bits) int he same computer tag selection is smaller
![Captura de pantalla de 2020-10-16 23-37-21](https://user-images.githubusercontent.com/7505980/96306564-8f022f80-1008-11eb-9d07-96eba989bda9.png)

**Comment by chrismclarke** [comment]
I think this discussion moved over to slack, but if there's still anything missing from my side feel free to reach out to me over on slack (I don't check github as regularly)
