### ISSUE TITLE
Swap flag + username

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#973]
### Description

Swap the flag in the userprofile. Instead of being at the end of the username, it should be in the beginning. So it aligns with the other flags (https://github.com/ONEARMY/community-platform/issues/972) in the platform. Seems pretty straightforward, but below a mockup.

### Page related

Will be used in :
[Profile](https://community.preciousplastic.com/u/precious-plastic)

### Mockup

![swap-flag](https://user-images.githubusercontent.com/13672737/83519914-1a0cde00-a4dd-11ea-88ab-9cca1ae697eb.jpg)

**Comment by jxofficial** [comment]
Hi, can I take this issue?

**Comment by davehakkens** [comment]
yes! :)
