### ISSUE TITLE
Extra information on Profile

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#974]
### Description
In the profiles we need some additional information in a sidebar
**Map pin:** Show if profile has map pin (and [link to pin](https://community.preciousplastic.com/map#username). )
**How-to:** Show amount of how-to's created by this profile (all approved ones)
**Events:** Show amount of events created by this profile (all approved ones)

### Page related

Will be used in :
[Profiles](https://community.preciousplastic.com/u/precious-plastic)

### Mockup
![profile-items-nopatreon_01](https://user-images.githubusercontent.com/13672737/83521802-04e57e80-a4e0-11ea-9c63-584131a23f29.jpg)
![profile-items_explained_01](https://user-images.githubusercontent.com/13672737/83521801-03b45180-a4e0-11ea-9542-e902605070ff.jpg)

**Comment by BenGamma** [comment]
For this one IMO we should add new fields in the user model : `howtoCount` & `eventCount` to avoid having to do heavy reading on the DB (that filters from all how-to's the ones from the author) each time a user profile is displayed. Instead Increment the counters `howtoCount` & `eventCount` values that are directly on the user's data, along with his basic informations (name- profile pic, etc). They wil be incremented each time a how-to or event is approved.
What do you think @chrismclarke ?

**Comment by chrismclarke** [comment]
Yep definitely agree with you that we need to keep specific counters for these things rather than calculating each time. I would suggest however instead of adding a lot more to the user profile we store the info either in a single `userStats` variable, or possibly use a subcollection so all the info sits at `users/chrismclarke/stats` or similar in the db.

I also think we should move the logic away from individual pages/stores (e.g. update when a user clicks to create a howto), to the database itself via triggers (i.e. when new entry is detected under howtos, read the `_createdBy` field and update that users stats). Actually, a good way to go about this would be to write a single trigger for all db updates (create or delete events), that keeps a single list of every entry created by that user, so all howtos, events, mappins in the same place - we can then just pull that list and filter to present any stats we want?

**Comment by BenGamma** [comment]
Agree with the `userStats` variable.
> I also think we should move the logic away from individual pages/stores
You mean we will then create a firebase function that will update `userStats` when a db entry is created or updated ?

**Comment by chrismclarke** [comment]
Exactly, so nothing needed to be called manually from the user on the webpage (which  is much more prone to error), and nothing required in main platform code (all be within the functions instead)

**Comment by alromh87** [comment]
Hello DB trigers for updating count when new howto/event are ready, now I will go for the display. What are your tougths on data for the frontend:

Extend user model
Create new model just for this

Note: I remember that last time I added fields to a model It caused trouble with the caching system and it would trigger big dta updates

**Comment by alromh87** [comment]
In case of the first is possible I have PR ready

**Comment by davehakkens** [comment]
Neat
Could you make sure it also says `How-to `and `Events`?
<img width="174" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/92324332-0e333980-f041-11ea-8070-ce0e1bc4b3ae.png">
Now it only shows the icon..

**Comment by alromh87** [comment]
Thanks updated

**Comment by davehakkens** [comment]
<img width="181" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/92326819-36c52e80-f055-11ea-8ff7-4cd6fbd2f50f.png">
Howto is called event? Also should be on one line

**Comment by alromh87** [comment]
Should be fixed now
![Captura de pantalla de 2020-09-06 18-58-55](https://user-images.githubusercontent.com/7505980/92329861-0c826980-f073-11ea-8c9b-19304fb8c1a9.png)

**Comment by chrismclarke** [comment]
I've made a few changes to the code to also keep track of draft/pending as well as specific ids of events/howtos in the stats as it's cleaner from a dev perspective and figure could be useful in the future. @davehakkens - by default this shows the counts for both approved and pending howtos or events, is there a strong preference to have the number only indicate approved (one line of code to filter if that's the case), or ok to include both?

**Comment by davehakkens** [comment]
no strong preference. Including draft/pending count for how-to's is also good. (there are very little of those anyway)
