### ISSUE TITLE
Admin panel - moderation overview components

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#980]
### Description
To make it easier for moderators to quickly get overview of outstanding issues/tasks. For backend keep simple and just do on-demand db requests, frontend can hopefully reuse existing components + simple HTML table. Doesn't need to be too fancy as won't be seen by many people.

### Page related
Will be used in :
- Admin page

### Mockup
![image](https://user-images.githubusercontent.com/10515065/84185088-555e5e00-aa43-11ea-96f3-504700935242.png)

**Comment by iSCJT** [comment]
Closing due to other options being explored for admin interface.
