### ISSUE TITLE
[bug] - User last active does not automatically update

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#984]
**Describe the bug**
I think we created the field with the intention of updating it on login, but guessing forgot.

**To Reproduce**
Logout
Go to own map pin and see last active
Login
View map pin again (last active will not have changed)

**Expected behavior**
Likely will want a server-side or user store trigger that populates lastActive and modified on successful login. Server-side likely more reliable, but client side easier (could just add to existing `userSignedIn` field.

**Comment by nahos** [comment]
Hey, Can you assign it to me. I will try fixing it.

**Comment by nahos** [comment]
Btw I am not able to see my pin, it just shows my location but it doesn't show a  pin.

**Comment by chrismclarke** [comment]
Sure thing, happy to have you work on this. 

Pins aren't enabled on all profile types so depending what you have selected in settings you may not have one (we don't have pins for members because there's just too many of them and don't represent physical locations as well as things like workspaces). If there seems to be some other problem then feel free to open another issue here with your username to help debug.

**Comment by danitrod** [comment]
Hi @nahos, are you working on this? Looks like it's been a while, I'd like to work on it if you're not.

**Comment by chrismclarke** [comment]
Reassigned. Thanks @danitrod!

This should hopefully be fairly straight-forward, the userstore has a `userSignedIn` method which can be used to also update the last active once the user profile has been successfully loaded. 

The only complication would be with the `functions/src/userUpdates/backupUser.ts` function, which by default creates a backup of the user whenever the profile is updated - which we probably don't want to do if the only thing that is changing is the last active time. But it seems that function is not currently active (not sure why, but it would otherwise be called in the `handleUserUpdates`), so probably would be good enough to just add a note to update it in the future if it becomes enabled again.
