### ISSUE TITLE
[bug] dissalow capitalized letter in userprofile links

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#986]
**Describe the bug**
If a user saved his link with a capitalized H like Http://link.com, it will make the link fail on the user profile page.

**Expected behavior**
We shouldn't allow capitalize letter when submitting a link.

**Comment by tudi2d** [comment]
Hey. I would like to add this. My solution would be to simply convert any input to lower case when saving. This should fix unintentional upper case letters in the future and also does not require any more user interaction.

**Comment by BenGamma** [comment]
Yep seems good to me, thanks for picking it up :)
