### ISSUE TITLE
[bug] Error message for password reset renders multiple times

### ISSUE THREAD

**Issue by jxofficial** [ONEARMY/community-platform#989]
**Describe the bug**
Reset password error message flickers upon input change.

**To Reproduce**

1. Go to the login page.
2. Click on 'Lost password'
3. Type anything into the input fields
4. Error message flickers erratically.

**Expected behavior**
Error message should only render once and disappear upon timeout.

**Screenshots**
![animation flicker](https://user-images.githubusercontent.com/49927092/85322487-01e71800-b4f9-11ea-89da-2ac0a21d4592.gif)

**Comment by Daniel-Davies** [comment]
Hello- I'm happy to take this one if you'd like!

**Comment by davehakkens** [comment]
yes! :)
